#!/usr/bin/env python3
# Module BONUS : « Le guide de survie Keto-Essenciel » (12 chapitres + quiz final 20 q)
import io, sys
PATH = '/app/keto.html'
src = io.open(PATH, encoding='utf-8').read()

# Ancre : fin du dernier module « Le suivi » puis fermeture du tableau PC
i = src.find('{t:"Le suivi"')
if i < 0: print('ERREUR: module Le suivi introuvable'); sys.exit(1)
ANCHOR = '\n]}\n];'
j = src.find(ANCHOR, i)
if j < 0: print('ERREUR: ancre fin de PC introuvable'); sys.exit(1)
if src.find('Le guide de survie Keto-Essenciel') >= 0:
    print('DÉJÀ APPLIQUÉ'); sys.exit(0)

NEW = r'''{t:"Le guide de survie Keto-Essenciel",e:"🎁",bonus:true,d:"Module bonus : gérer sereinement toutes les situations du quotidien — restaurant, fêtes, voyages, sport — sans renoncer à vos objectifs.",ch:[
 {t:"Manger au restaurant sans culpabiliser",mi:"Au prochain restaurant (ou dès ce soir sur un menu en ligne) : 🍽️ repérez en 2 minutes le plat le plus adapté — une protéine + des légumes — et une adaptation simple à demander (« des légumes à la place des frites, s'il vous plaît »). Notez comme c'est facile !",p:[
  ["👋 Introduction","Le restaurant fait partie des plaisirs de la vie — et il n'y a aucune raison d'y renoncer !\nAvec quelques réflexes simples, vous pouvez profiter d'un excellent repas au restaurant tout en respectant vos objectifs. Sans stress, sans culpabilité, et sans passer pour « la personne compliquée » de la table.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ lire une carte rapidement et efficacement ;\n✅ faire les meilleurs choix selon le type de restaurant ;\n✅ repérer les pièges (sauces, accompagnements) ;\n✅ demander une adaptation sans gêne."],
  ["📋 Lire une carte en 2 minutes","La méthode simple pour scanner n'importe quelle carte :\n1️⃣ CHERCHEZ LA PROTÉINE — viande grillée, poisson, fruits de mer, œufs : c'est la base de votre assiette ;\n2️⃣ REGARDEZ L'ACCOMPAGNEMENT — remplacez mentalement frites, riz, pâtes par légumes ou salade ;\n3️⃣ MÉFIEZ-VOUS DES MOTS-PIÈGES — « pané », « en croûte », « caramélisé », « laqué », « sauce aigre-douce » cachent farine et sucre ;\n4️⃣ LES VALEURS SÛRES — entrecôte-salade, poisson grillé-légumes, salade composée (sans croûtons), plateau de fruits de mer, poulet rôti.\nSelon le type de restaurant :\n🥩 grill/brasserie : le plus simple — viande + légumes ;\n🍣 japonais : sashimis, brochettes yakitori (attention au riz et à la sauce sucrée) ;\n🇮🇹 italien : carpaccio, burrata, escalope + légumes (évitez pâtes/pizza ou partagez-en peu) ;\n🇬🇷 grec/libanais : grillades, salades, tzatziki — un régal keto !","m12c0b"],
  ["🥗 Accompagnements et sauces : les bons choix","LES ACCOMPAGNEMENTS À PRIVILÉGIER :\n✔ légumes verts sautés ou vapeur ;\n✔ salade verte (vinaigrette huile-vinaigre) ;\n✔ poêlée de champignons ;\n✔ ratatouille, épinards à la crème.\nPresque tous les restaurants acceptent de remplacer les frites par une salade ou des légumes — il suffit de demander !\n\nLES SAUCES : LE VRAI PIÈGE CACHÉ\n⚠️ à limiter : sauces sucrées (barbecue, aigre-douce, miel-moutarde), sauces liées à la farine, ketchup ;\n✔ à privilégier : beurre maître d'hôtel, sauce au poivre ou roquefort (à la crème), béarnaise, huile d'olive, citron, moutarde nature.\nAstuce : demandez la sauce « à part » — vous en mettez la quantité que VOUS décidez.","m12c0c"],
  ["🗣️ Demander une adaptation sans gêne","Beaucoup n'osent pas demander de modification. Pourtant :\n💬 les restaurateurs ont l'habitude — allergies, régimes, préférences : votre demande est banale pour eux ;\n💬 formulez positivement et simplement : « Est-ce possible d'avoir des légumes à la place des frites ? » — pas besoin de justifier ni d'expliquer votre alimentation ;\n💬 pour les sauces : « la sauce à part, s'il vous plaît » ;\n💬 au dessert : un café, une infusion, ou un plateau de fromages sont d'excellentes fins de repas.\nEt si le repas n'est pas parfait ? Ce n'est PAS grave. Un repas ne détruit jamais des semaines d'efforts — c'est la régularité globale qui compte, pas la perfection ponctuelle.\n\n💡 Astuce Keto-Essenciel : regardez le menu en ligne AVANT d'y aller. Choisir son plat à l'avance évite de se décider sous la pression, l'estomac vide et le panier de pain sous le nez !","m12c0d"],
  ["📝 À retenir","📝 À retenir :\n✔ la formule gagnante : une protéine + des légumes ;\n✔ méfiez-vous des mots-pièges : pané, en croûte, caramélisé, laqué ;\n✔ demandez les légumes à la place des frites — c'est banal et presque toujours accepté ;\n✔ sauce à part = vous gardez le contrôle ;\n✔ un repas imparfait n'efface jamais vos efforts : zéro culpabilité.\n\n🏅 Badge à débloquer en validant le quiz : « Je maîtrise le restaurant »"]],
  q:[["Quelle est la formule gagnante au restaurant ?",["Une protéine + des légumes","Entrée + plat + dessert obligatoirement","Uniquement de la salade"],0,"Viande ou poisson grillé + légumes : simple, savoureux et adapté partout."],
     ["Quels mots sur une carte doivent vous alerter ?",["Pané, en croûte, caramélisé, laqué","Grillé, rôti, vapeur","Frais, maison"],0,"Ils signalent farine et sucre cachés dans la préparation."],
     ["Que demander à la place des frites ?",["Rien, c'est impossible","Des légumes ou une salade — demande banale et presque toujours acceptée"],1,"Les restaurateurs ont l'habitude : formulez simplement, sans vous justifier."],
     ["Pourquoi demander la sauce « à part » ?",["Pour contrôler soi-même la quantité","C'est plus joli","Pour payer moins cher"],0,"Vous décidez de la dose — les sauces sucrées ou farinées sont le piège n°1."],
     ["Un repas de restaurant imparfait…",["Détruit des semaines d'efforts","Ne change rien à la tendance globale : c'est la régularité qui compte"],1,"Zéro culpabilité : reprenez simplement vos habitudes au repas suivant."]]},
 {t:"Vacances : profiter sans perdre tous ses progrès",mi:"Pour vos prochaines vacances (ou fictivement dès aujourd'hui) : 🏖️ listez 3 stratégies que vous utiliserez — ex. petit-déjeuner protéiné au buffet, une marche par jour, reprise des habitudes dès le retour. Gardez cette liste dans votre téléphone.",p:[
  ["👋 Introduction","Les vacances riment souvent avec « lâcher prise »… et parfois avec 3 kilos au retour et une glycémie déréglée.\nBonne nouvelle : il est tout à fait possible de PROFITER pleinement de ses vacances — apéros, découvertes culinaires, restaurants — tout en préservant l'essentiel de ses progrès.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ préparer vos vacances sereinement ;\n✅ gérer les repas d'hôtel et les buffets ;\n✅ rester actif avec plaisir ;\n✅ reprendre vos habitudes au retour sans drame."],
  ["🧳 Préparer ses vacances — et gérer l'hôtel","AVANT DE PARTIR :\n📋 repérez les restaurants et supermarchés autour de votre lieu de séjour ;\n🥜 glissez des collations sûres dans la valise : amandes, noix ;\n💊 si vous êtes sous traitement : emportez le double de vos médicaments (répartis dans 2 bagages) et votre matériel de mesure ;\n🎯 fixez-vous une règle simple et réaliste, par exemple : « un vrai écart par jour maximum, et je choisis lequel ».\n\nÀ L'HÔTEL :\n🍳 le petit-déjeuner est votre meilleur allié : œufs, omelette, fromage, jambon, yaourt nature — presque tous les hôtels en proposent ;\n🥐 les viennoiseries et jus de fruits sont là chaque matin… mais VOUS choisissez : un croissant dégusté le jour de votre choix vaut mieux que trois avalés par automatisme ;\n🧊 un mini-frigo dans la chambre ? Parfait pour du fromage, des yaourts nature et de l'eau gazeuse.","m12c1b"],
  ["🍽️ Les buffets : la stratégie du tour de repérage","Le buffet est un défi classique… avec une parade simple :\n1️⃣ FAITES D'ABORD UN TOUR COMPLET sans assiette — repérez tout ce qui existe ;\n2️⃣ COMPOSEZ ensuite UNE assiette réfléchie : protéines (viandes, poissons, œufs, fruits de mer) + légumes + fromages ;\n3️⃣ asseyez-vous LOIN du buffet — chaque resservage doit être une vraie décision, pas un réflexe ;\n4️⃣ pour le dessert : choisissez-en UN qui vous fait vraiment envie et savourez-le lentement… ou optez pour un café gourmand de fromages !\n\n🏃 BOUGER EN VACANCES — SANS CORVÉE :\nmarche exploration de la ville, baignade, randonnée, vélo, pétanque, jeux de plage… Les vacances sont souvent le moment où l'on bouge LE PLUS naturellement. 8 000 pas de visite touristique = une vraie séance d'activité !","m12c1c"],
  ["🔄 Le retour : reprendre sans drame","Le vrai danger des vacances n'est pas l'écart… c'est de ne jamais reprendre.\nVotre plan de retour :\n📅 J1 : refaites des courses « saines » dès le premier jour (frigo vide = tentations de livraison) ;\n🍳 reprenez immédiatement vos petits-déjeuners habituels — c'est le repas le plus facile à re-cadrer ;\n💧 hydratez-vous davantage les 3 premiers jours ;\n⚖️ pesez-vous à J+4 ou J+5, pas le jour du retour : une partie de la prise est de l'eau (sel, glucides) qui repart seule en quelques jours ;\n😌 zéro culpabilité : 2 semaines de vacances sur 52 semaines, c'est moins de 4 % de votre année.\n\n💡 Astuce Keto-Essenciel : programmez AVANT de partir un rappel « courses + menu de la semaine » pour le lendemain du retour. La reprise devient automatique au lieu de dépendre de votre volonté un jour de fatigue.","m12c1d"],
  ["📝 À retenir","📝 À retenir :\n✔ préparez : collations, double des traitements, règle simple « un écart choisi par jour » ;\n✔ le petit-déjeuner d'hôtel est votre allié : œufs, fromage, yaourt nature ;\n✔ au buffet : tour de repérage d'abord, UNE assiette réfléchie ensuite ;\n✔ les vacances font naturellement bouger : profitez-en ;\n✔ au retour : courses J1, pesée à J+4, zéro culpabilité.\n\n🏅 Badge à débloquer en validant le quiz : « Je profite de mes vacances »"]],
  q:[["Que mettre dans sa valise si l'on est sous traitement ?",["Le double de ses médicaments, répartis dans deux bagages","Rien, on verra sur place","Uniquement une ordonnance"],0,"Perte de bagage ou retard : le double réparti vous protège."],
     ["Quelle est la meilleure stratégie face à un buffet ?",["Se servir immédiatement de tout","Faire d'abord un tour complet de repérage, puis composer UNE assiette réfléchie"],1,"Repérer avant de se servir évite l'accumulation automatique."],
     ["Le petit-déjeuner d'hôtel idéal ?",["Viennoiseries et jus d'orange","Œufs, omelette, fromage, jambon, yaourt nature"],1,"Presque tous les hôtels proposent ces options protéinées rassasiantes."],
     ["Quand se peser au retour de vacances ?",["Le jour même du retour","Vers J+4 : une partie de la prise est de l'eau qui repart seule"],1,"Sel et glucides retiennent l'eau : attendez quelques jours pour un chiffre honnête."],
     ["Quel est le vrai danger des vacances ?",["Faire un écart","Ne jamais reprendre ses habitudes au retour"],1,"2 semaines sur 52 ne pèsent rien SI la reprise est immédiate : courses dès J1."]]},
 {t:"Les invitations chez des proches",mi:"À votre prochaine invitation : 🎉 appliquez la stratégie complète — collation avant de partir si besoin, proposition d'apporter un plat ou le dessert, service raisonnable au moment du repas. Racontez-vous ensuite ce qui a le mieux fonctionné.",p:[
  ["👋 Introduction","Un dîner chez des amis, un déjeuner de famille… Ces moments précieux peuvent devenir source de stress : « Comment refuser le gratin de tata sans la vexer ? »\nCe chapitre vous donne les stratégies concrètes pour profiter des invitations en toute sérénité — pour vous ET pour vos hôtes.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ accepter une invitation sans appréhension ;\n✅ ménager la susceptibilité de vos hôtes ;\n✅ appliquer les bonnes stratégies avant et pendant le repas ;\n✅ gérer le moment délicat du dessert."],
  ["🤝 Accepter sereinement — sans vexer personne","D'abord, un principe : une invitation est un moment de LIEN, pas un examen nutritionnel. Dites OUI et réjouissez-vous !\n\nPour éviter tout malaise :\n💬 PRÉVENIR EN AMONT (optionnel mais efficace) : un simple « je fais attention à mon alimentation en ce moment, ne prépare rien de spécial pour moi, je me régalerai de ce qu'il y a ! » désamorce tout ;\n🍰 PROPOSER D'APPORTER quelque chose : une salade composée, un plateau de fromages, ou LE dessert — vous garantissez ainsi au moins un plat adapté sur la table (et vos hôtes adorent) ;\n🙏 ne JAMAIS faire la leçon à table : votre assiette parle pour vous, pas besoin de commenter celles des autres ;\n😋 goûtez ce qui vous est offert avec plaisir : une petite portion du plat mijoté avec amour vaut tous les discours.","m12c2b"],
  ["🍽️ Avant et pendant le repas : les stratégies","AVANT DE PARTIR :\n🥚 si l'apéritif s'annonce long : une petite collation protéinée (œuf dur, fromage, poignée d'amandes) évite d'arriver affamé et de dévaster les chips ;\n💧 buvez un grand verre d'eau avant de partir.\n\nÀ L'APÉRITIF :\n✔ vos alliés : olives, fromage, charcuterie, crudités, fruits à coque ;\n⚠️ à doser : chips, biscuits apéro, feuilletés ;\n🥂 un verre à la main (eau gazeuse-citron par exemple) évite les resservages automatiques.\n\nÀ TABLE :\n✔ servez-vous raisonnablement de tout — ou laissez l'hôte vous servir « une petite portion » ;\n✔ mangez lentement, participez à la conversation : on mange moins quand on parle plus ;\n✔ resservez-vous de légumes et de salade sans hésiter ;\n✔ le pain : laissez-le hors de portée de main, tout simplement.","m12c2c"],
  ["🍮 Le moment du dessert — et l'après","Le dessert est souvent le passage le plus délicat :\n🎂 OPTION 1 — la petite part : « une toute petite part, il a l'air délicieux ! » Vous honorez le dessert ET gardez le contrôle ;\n☕ OPTION 2 — le café d'abord : « je vais d'abord prendre un café, je suis très bien là » — souvent, l'envie passe ;\n🧀 OPTION 3 — le fromage : s'il y a un plateau, prolongez-le pendant que les autres passent au sucré ;\n💬 face à l'insistance (« allez, une part, ça ne va pas te tuer ! ») : souriez et tenez bon gentiment — « c'était délicieux, je n'ai vraiment plus faim » répété calmement fonctionne toujours.\n\nET APRÈS ? Si vous avez fait un vrai écart : c'est un repas de PLAISIR partagé, pas une faute. Reprenez vos habitudes dès le repas suivant — rappelez-vous la règle « jamais deux fois de suite ».\n\n💡 Astuce Keto-Essenciel : proposer d'apporter le dessert est LA stratégie royale : un fondant au chocolat noir amande (recette dans l'app !) régale tout le monde… et vous savez exactement ce qu'il contient.","m12c2d"],
  ["📝 À retenir","📝 À retenir :\n✔ une invitation est un moment de lien : dites oui avec joie ;\n✔ proposer d'apporter un plat ou le dessert garantit une option adaptée ;\n✔ collation avant de partir = pas de fringale à l'apéro ;\n✔ au dessert : petite part, café ou fromage — avec le sourire ;\n✔ un écart de convivialité se rattrape au repas suivant, jamais de culpabilité.\n\n🏅 Badge à débloquer en validant le quiz : « Invité serein »"]],
  q:[["Quelle est la stratégie royale pour une invitation ?",["Refuser l'invitation","Proposer d'apporter un plat ou le dessert","Ne rien manger de la journée avant"],1,"Vous garantissez une option adaptée sur la table — et vos hôtes apprécient."],
     ["Pourquoi prendre une collation avant de partir ?",["Pour ne pas arriver affamé et dévaliser l'apéritif","Pour pouvoir sauter le repas","C'est inutile"],0,"Un œuf dur ou une poignée d'amandes évite les excès d'apéro."],
     ["Face à l'insistance pour le dessert, que faire ?",["Céder systématiquement","Se fâcher","Sourire et répéter calmement « c'était délicieux, je n'ai plus faim » — ou accepter une toute petite part"],2,"La gentillesse ferme fonctionne toujours ; la petite part choisie aussi."],
     ["Faut-il commenter les assiettes des autres à table ?",["Oui, pour les éduquer","Non, jamais : votre assiette parle pour vous"],1,"Une invitation n'est pas une tribune nutritionnelle — le lien d'abord."],
     ["Un écart lors d'un repas de famille…",["Se rattrape dès le repas suivant, sans culpabilité","Oblige à jeûner 3 jours","Annule tous les progrès"],0,"Règle d'or : jamais deux fois de suite — et on repart."]]},
 {t:"Alcool et alimentation cétogène",mi:"Faites le point sur votre consommation : 🍷 notez ce que vous buvez lors d'une semaine type. Si vous prenez un traitement hypoglycémiant, vérifiez ce soir dans ce chapitre les précautions qui vous concernent — et parlez-en à votre médecin au prochain rendez-vous.",p:[
  ["👋 Introduction","Un verre de vin entre amis, une bière en terrasse… L'alcool fait partie de la vie sociale. Mais quand on surveille sa glycémie ou son poids, quelques connaissances s'imposent.\nCe chapitre fait le tri — sans moralisme — entre ce qui est compatible, ce qui l'est moins, et les VRAIES précautions à connaître, notamment avec certains traitements.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre les effets de l'alcool sur la glycémie ;\n✅ choisir les boissons les plus adaptées ;\n✅ connaître le risque d'hypoglycémie avec certains traitements ;\n✅ consommer avec modération et bonnes pratiques."],
  ["🩸 L'alcool et la glycémie : un effet en deux temps","L'alcool a un effet PARADOXAL sur la glycémie :\n📈 dans un premier temps, les boissons SUCRÉES (cocktails, bières, vins doux, sodas ajoutés) font MONTER la glycémie ;\n📉 mais ensuite, l'alcool BLOQUE la production de glucose par le foie — occupé à éliminer l'alcool, il ne peut plus libérer de sucre dans le sang. Résultat : la glycémie peut CHUTER plusieurs heures après, parfois pendant la nuit.\n\n⚠️ RISQUE MAJEUR À CONNAÎTRE : si vous prenez de l'INSULINE ou des SULFAMIDES hypoglycémiants (gliclazide, glimépiride…), l'alcool augmente fortement le risque d'HYPOGLYCÉMIE — y compris tardive et nocturne. De plus, les signes d'hypo (tremblements, confusion, sueurs) ressemblent à l'ivresse : l'entourage peut ne pas réagir.\nRègles de sécurité : ne JAMAIS boire à jeun, toujours manger en buvant, contrôler sa glycémie avant le coucher, et informer ses proches. Parlez-en à votre médecin.","m12c3b"],
  ["🥂 Boissons : le classement pratique","✅ LES PLUS COMPATIBLES (avec modération) :\n🍷 vin rouge ou blanc SEC : ~1-2 g de glucides/verre ;\n🥂 champagne brut : ~1-2 g ;\n🥃 spiritueux purs (whisky, vodka, gin, rhum) : 0 g de glucides — MAIS jamais avec des sodas sucrés : optez pour eau gazeuse + citron.\n\n⚠️ À LIMITER FORTEMENT :\n🍺 bière : 10-15 g de glucides par pinte (le « pain liquide ») ;\n🍹 cocktails sucrés (mojito, piña colada…) : 20-40 g par verre ! ;\n🍷 vins doux, moelleux, portos, cidres doux : très sucrés ;\n🥤 tout alcool mélangé à un soda ou jus.\n\n📌 Et n'oubliez pas : même « zéro glucide », l'alcool apporte 7 kcal/g, freine la combustion des graisses tant qu'il est métabolisé, désinhibe (bonjour les grignotages !) et dégrade le sommeil. Le mieux reste toujours d'en boire peu.","m12c3c"],
  ["🧭 Les bonnes pratiques de modération","Pour profiter d'un verre sans conséquences :\n1️⃣ JAMAIS à jeun — toujours en mangeant ;\n2️⃣ UN verre d'eau entre chaque verre d'alcool (hydratation + rythme ralenti) ;\n3️⃣ fixez votre limite AVANT la soirée (ex. : 2 verres max) — décider à froid est plus facile qu'à chaud ;\n4️⃣ méfiez-vous des resservages : gardez votre verre en main, même à moitié plein ;\n5️⃣ sous insuline ou sulfamides : glycémie avant le coucher + collation si besoin + entourage informé ;\n6️⃣ repères officiels : maximum 2 verres/jour, pas tous les jours, et jamais plus de 10 verres/semaine.\n\n🚫 Et bien sûr : jamais d'alcool au volant, et abstinence totale en cas de grossesse ou de maladie du foie.\n\n💡 Astuce Keto-Essenciel : l'eau gazeuse + citron vert + glaçons dans un beau verre à cocktail « fait le job » socialement — personne ne vous demandera pourquoi vous ne buvez pas.","m12c3d"],
  ["📝 À retenir","📝 À retenir :\n✔ l'alcool fait d'abord monter (boissons sucrées) puis CHUTER la glycémie (foie occupé) ;\n✔ sous insuline ou sulfamides : risque d'hypoglycémie tardive — jamais à jeun, glycémie au coucher ;\n✔ vins secs, champagne brut, spiritueux purs = les moins glucidiques ;\n✔ bière et cocktails sucrés = les pièges principaux ;\n✔ modération : limite fixée à l'avance, eau entre les verres, max 2/jour et pas tous les jours.\n\n🏅 Badge à débloquer en validant le quiz : « Je gère l'alcool avec sagesse »"]],
  q:[["Quel est l'effet de l'alcool sur la glycémie plusieurs heures après ?",["Elle peut chuter : le foie occupé par l'alcool ne libère plus de glucose","Elle monte indéfiniment","Aucun effet"],0,"Risque d'hypoglycémie tardive, parfois nocturne — surtout sous certains traitements."],
     ["Avec quels traitements l'alcool augmente-t-il fortement le risque d'hypoglycémie ?",["Insuline et sulfamides hypoglycémiants","Vitamine D","Paracétamol"],0,"Jamais à jeun, glycémie au coucher, entourage informé — et avis médical."],
     ["Quelles boissons sont les moins glucidiques ?",["Bière et mojito","Vin sec, champagne brut, spiritueux purs (sans soda)","Cidre doux et porto"],1,"1-2 g par verre de vin sec contre 20-40 g pour un cocktail sucré."],
     ["Pourquoi la bière est-elle surnommée « pain liquide » ?",["Elle contient 10-15 g de glucides par pinte","Elle est fabriquée en boulangerie","Elle ne contient rien"],0,"C'est l'une des boissons alcoolisées les plus riches en glucides."],
     ["Quelle bonne pratique adopter en soirée ?",["Fixer sa limite avant la soirée et boire un verre d'eau entre chaque verre","Boire à jeun pour moins manger","Enchaîner les cocktails"],0,"Décider à froid + hydratation = la modération sans effort."]]},
 {t:"Le jeûne intermittent : pour qui et dans quelles conditions ?",mi:"Observez votre rythme naturel : ⏳ notez à quelle heure vous avez VRAIMENT faim le matin. Si vous êtes tenté par le jeûne intermittent et que vous prenez un traitement, notez la question à poser à votre médecin — ne commencez rien sans son avis.",p:[
  ["👋 Introduction","Le jeûne intermittent est partout : magazines, réseaux sociaux, discussions entre amis. Effet de mode ou véritable outil ?\nLa réponse est nuancée : c'est un outil INTÉRESSANT pour certaines personnes, dans certaines conditions — et DÉCONSEILLÉ pour d'autres. Ce chapitre vous aide à savoir où vous vous situez.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer les différents types de jeûne intermittent ;\n✅ connaître ses bénéfices potentiels ;\n✅ identifier les situations où il est déconseillé ;\n✅ comprendre les précautions indispensables en cas de diabète."],
  ["⏰ Les différents types de jeûne intermittent","Le principe : alterner des périodes où l'on mange et des périodes où l'on ne consomme que des boissons non caloriques (eau, café ou thé non sucrés).\n\nLes formules les plus courantes :\n🕛 LE 16/8 — le plus populaire : on mange sur une fenêtre de 8 h (ex. : 12 h-20 h) et on jeûne 16 h (dont la nuit). Concrètement : on saute le petit-déjeuner ou le dîner ;\n🕐 LE 14/10 — version douce : 14 h de jeûne, fenêtre de 10 h. Excellent point de départ ;\n📅 LE 5:2 — 5 jours normaux + 2 jours très légers (~500-600 kcal). Plus contraignant ;\n🌙 et rappelons-le : TOUT LE MONDE jeûne déjà chaque nuit ! Passer de 10 h à 14 h de jeûne nocturne, c'est parfois juste… avancer l'heure du dîner.\nBonne nouvelle : l'alimentation keto facilite naturellement le jeûne — les graisses rassasient longtemps et la faim se fait discrète.","m12c4b"],
  ["🌟 Bénéfices potentiels — et contre-indications","CE QUE SUGGÈRENT LES ÉTUDES (bénéfices potentiels, variables selon les personnes) :\n📉 aide à réduire l'apport calorique global sans compter ;\n🔑 amélioration possible de la sensibilité à l'insuline ;\n🩸 baisse possible de la glycémie et de l'insuline à jeun ;\n🧘 simplicité : moins de repas à préparer, digestion allégée.\n⚠️ Mais le jeûne n'est PAS magique : c'est un OUTIL d'organisation des repas, pas une baguette. La qualité de l'alimentation reste la base.\n\n🚫 DÉCONSEILLÉ (sans encadrement médical strict) :\n• grossesse et allaitement ;\n• antécédents de troubles du comportement alimentaire ;\n• insuffisance pondérale, grande fatigue, dénutrition ;\n• diabète de type 1 ;\n• personnes âgées fragiles ;\n• enfants et adolescents.","m12c4c"],
  ["🩺 Diabète de type 2 : les précautions indispensables","Si vous vivez avec un diabète de type 2, le jeûne intermittent PEUT être envisagé — mais JAMAIS à la légère :\n1️⃣ AVIS MÉDICAL D'ABORD — indispensable si vous prenez de l'insuline ou des sulfamides : jeûner sans adapter ces traitements expose à des HYPOGLYCÉMIES potentiellement graves. Seul votre médecin peut ajuster les doses ;\n2️⃣ COMMENCEZ EN DOUCEUR : 12 h de jeûne nocturne, puis 14 h si tout va bien — inutile de viser 16/8 d'emblée ;\n3️⃣ SURVEILLEZ votre glycémie plus souvent au début, notamment en fin de période de jeûne ;\n4️⃣ HYDRATEZ-VOUS abondamment (eau, tisanes, bouillon) ;\n5️⃣ ARRÊTEZ en cas de malaise, vertiges, sueurs : un jeûne ne doit jamais faire souffrir ;\n6️⃣ pendant la fenêtre de repas : mangez VRAIMENT et équilibré — le jeûne ne doit pas devenir une restriction déguisée.\n\n💡 Astuce Keto-Essenciel : le jeûne le plus naturel ? Dîner tôt (19 h) et petit-déjeuner tardif (9 h) = 14 h de jeûne sans même y penser, dont l'essentiel en dormant.","m12c4d"],
  ["📝 À retenir","📝 À retenir :\n✔ 16/8, 14/10, 5:2 : le principe = alterner repas et périodes sans calories ;\n✔ bénéfices potentiels : moins de calories, meilleure sensibilité à l'insuline — mais ce n'est pas magique ;\n✔ déconseillé : grossesse, TCA, diabète de type 1, personnes fragiles ;\n✔ diabète de type 2 sous insuline/sulfamides : AVIS MÉDICAL OBLIGATOIRE avant de commencer ;\n✔ commencez doux (12-14 h), surveillez, hydratez-vous, arrêtez si malaise.\n\n🏅 Badge à débloquer en validant le quiz : « Je comprends le jeûne intermittent »"]],
  q:[["Que signifie le jeûne 16/8 ?",["16 h sans calories, fenêtre de repas de 8 h","16 repas en 8 jours","8 h de sommeil et 16 h de sport"],0,"Exemple : manger entre 12 h et 20 h — le jeûne inclut la nuit."],
     ["Le jeûne intermittent est-il magique ?",["Oui, il remplace tout","Non : c'est un outil d'organisation, la qualité de l'alimentation reste la base"],1,"Il peut aider (calories, insuline) mais ne dispense pas de bien manger."],
     ["Dans quel cas le jeûne est-il déconseillé ?",["Grossesse, troubles du comportement alimentaire, diabète de type 1, personnes fragiles","Après 40 ans","Quand on mange keto"],0,"Dans ces situations, ne jeûnez pas sans encadrement médical strict."],
     ["Pourquoi l'avis médical est-il OBLIGATOIRE sous insuline ou sulfamides ?",["Jeûner sans adapter ces traitements expose à des hypoglycémies graves","Pour la paperasse","Ce n'est pas obligatoire"],0,"Seul le médecin peut ajuster les doses en fonction du jeûne."],
     ["Comment débuter le jeûne intermittent en douceur ?",["Directement 48 h de jeûne","12 h de jeûne nocturne, puis 14 h si tout va bien","Sauter tous les repas du week-end"],1,"Dîner tôt + petit-déjeuner tardif = 14 h sans effort, l'essentiel en dormant."]]},
 {t:"Les édulcorants : lesquels choisir ?",mi:"Inspectez vos placards : 🍰 identifiez les édulcorants que vous possédez (ou ceux des produits « sans sucre » que vous achetez). Repérez-les dans la liste de ce chapitre — et testez cette semaine l'érythritol ou la stévia dans une recette de l'app.",p:[
  ["👋 Introduction","Envie de sucré sans le sucre ? Les édulcorants promettent le goût sans les glucides… mais entre stévia, aspartame, érythritol et sirops divers, difficile de s'y retrouver.\nCe chapitre trie le vrai du faux, sans diaboliser ni idéaliser.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer les grandes familles d'édulcorants ;\n✅ connaître leurs avantages et leurs limites ;\n✅ démonter quelques idées reçues ;\n✅ les utiliser avec discernement et modération."],
  ["🌿 Les grandes familles","1️⃣ LES POLYOLS (naturels) :\n✔ ÉRYTHRITOL — le chouchou keto : ~0 kcal, quasi aucun effet sur la glycémie, très bien toléré, se comporte comme le sucre en pâtisserie ;\n⚠️ XYLITOL — pouvoir sucrant proche du sucre, mais effet laxatif à forte dose et TOXIQUE POUR LES CHIENS ;\n⚠️ MALTITOL — attention ! très utilisé dans les produits « sans sucre » du commerce, mais il élève BEL ET BIEN la glycémie (index glycémique ~35) et provoque souvent des troubles digestifs.\n\n2️⃣ LES ÉDULCORANTS INTENSES NATURELS :\n✔ STÉVIA — extraite d'une plante, 0 kcal, 0 effet glycémique ; léger arrière-goût de réglisse ;\n✔ FRUIT DU MOINE (monk fruit) — 0 kcal, goût propre, encore peu répandu en France.\n\n3️⃣ LES ÉDULCORANTS INTENSES DE SYNTHÈSE : aspartame, sucralose, acésulfame K — 0 kcal, autorisés avec des doses journalières admissibles, mais débats scientifiques en cours (microbiote…). Ni poison, ni aliment santé.","m12c5b"],
  ["🧐 Idées reçues — et vraies limites","❌ « Les édulcorants font maigrir » — FAUX : ils réduisent les calories du sucré, mais ne font pas maigrir par eux-mêmes. Certaines études suggèrent même qu'ils ENTRETIENNENT l'attirance pour le goût sucré ;\n❌ « Naturel = sans effet » — FAUX : le maltitol est « naturel » et élève la glycémie ; le xylitol donne des troubles digestifs ;\n❌ « Le miel et le sucre de coco sont de bonnes alternatives » — FAUX pour la glycémie : ce sont des SUCRES (le miel = ~80 % de sucres), avec un habillage marketing ;\n❌ « Sans sucre = keto » — FAUX : vérifiez toujours le maltitol et les glucides totaux sur l'étiquette ;\n✔ VRAI : les produits sucrés — même édulcorés — entretiennent l'habitude du goût sucré. L'objectif à long terme est que votre palais se RÉÉDUQUE : les fraises redeviennent des bonbons !","m12c5c"],
  ["🥄 En pratique : les utiliser intelligemment","Notre hiérarchie pratique :\n🥇 ÉRYTHRITOL — pour la pâtisserie keto (gâteaux, mousses) : fiable, neutre, glycémie stable ;\n🥈 STÉVIA — pour sucrer une boisson ou un yaourt (quelques gouttes suffisent) ;\n🥉 mélanges érythritol-stévia — bon compromis goût/comportement en cuisine ;\n⚠️ à éviter au maximum : MALTITOL (chocolats et bonbons « sans sucre » du commerce !) et sirops de glucose-fructose déguisés.\n\nLes bons réflexes :\n1️⃣ voyez les édulcorants comme une TRANSITION ou un plaisir occasionnel, pas un pilier ;\n2️⃣ dosez léger : mieux vaut « peu sucré » que « très édulcoré » ;\n3️⃣ écoutez votre digestion : les polyols à forte dose ballonnent ;\n4️⃣ desserts édulcorés = plaisirs de week-end, pas automatisme quotidien.\n\n💡 Astuce Keto-Essenciel : dans les recettes de desserts de l'app, l'érythritol se remplace poids pour poids par du sucre classique… dans l'autre sens aussi : divisez par deux la quantité au fil des mois, votre palais suivra !","m12c5d"],
  ["📝 À retenir","📝 À retenir :\n✔ érythritol et stévia : les deux meilleurs choix keto (0 impact glycémique) ;\n✔ MALTITOL = le piège des produits « sans sucre » : il élève la glycémie ;\n✔ miel et sucre de coco restent des sucres, quel que soit le marketing ;\n✔ les édulcorants n'apprennent pas au palais à aimer moins sucré : dosez léger ;\n✔ objectif long terme : rééduquer son goût, desserts édulcorés en plaisir occasionnel.\n\n🏅 Badge à débloquer en validant le quiz : « Je choisis mes édulcorants »"]],
  q:[["Quels sont les deux édulcorants les plus adaptés au mode keto ?",["Érythritol et stévia","Maltitol et miel","Sucre de coco et sirop d'agave"],0,"0 calorie, quasi 0 impact glycémique, bonne tolérance."],
     ["Pourquoi se méfier du maltitol ?",["Il élève réellement la glycémie et provoque des troubles digestifs","Il est trop cher","Il n'a aucun goût"],0,"C'est le piège n°1 des chocolats et bonbons « sans sucre » du commerce."],
     ["Le miel est-il une bonne alternative au sucre pour la glycémie ?",["Oui, il est naturel","Non : il contient ~80 % de sucres"],1,"« Naturel » ne veut pas dire sans effet sur la glycémie."],
     ["Les édulcorants font-ils maigrir ?",["Oui, automatiquement","Non : ils réduisent les calories du sucré mais entretiennent le goût sucré"],1,"L'objectif long terme reste de rééduquer son palais."],
     ["Quelle est la bonne place des desserts édulcorés ?",["À chaque repas","Un plaisir occasionnel, en dosant léger","Interdits à vie"],1,"Transition et plaisir de week-end — pas un pilier quotidien."]]},
 {t:"Adapter son alimentation autour du sport",mi:"Avant votre prochaine séance d'activité : 🏃 préparez votre « kit sécurité » — bouteille d'eau, et si vous êtes sous insuline ou sulfamides, de quoi vous resucrer (3 morceaux de sucre). Notez votre énergie pendant l'effort pour ajuster la prochaine fois.",p:[
  ["👋 Introduction","Faut-il manger avant le sport ? Et après ? Que faire si la glycémie chute pendant l'effort ?\nBien s'alimenter autour de l'activité physique permet d'avoir de l'énergie, de bien récupérer… et de bouger en toute sécurité quand on vit avec un diabète.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ savoir quoi manger avant et après une séance ;\n✅ bien vous hydrater ;\n✅ reconnaître les signes d'hypoglycémie pendant l'effort ;\n✅ adapter votre alimentation à l'intensité de l'activité."],
  ["🍽️ Avant et après la séance","AVANT LA SÉANCE :\n🚶 activité douce à modérée (marche, vélo tranquille, renforcement léger) : pas besoin de manger spécialement — votre corps adapté au keto puise très bien dans ses graisses. Évitez juste de partir affamé ou juste après un repas copieux ;\n⏰ le bon timing : 2-3 h après un repas, ou une petite collation 30-60 min avant si besoin (poignée d'amandes, œuf dur, fromage) ;\n💪 séance intense : une collation protéinée-grasse en amont aide (yaourt grec + noix).\n\nAPRÈS LA SÉANCE :\n🥩 l'important = les PROTÉINES pour réparer les muscles : œufs, poulet, poisson, fromage blanc — dans les 2 h qui suivent, idéalement lors d'un vrai repas ;\n💧 re-hydratez-vous bien ;\n❌ pas besoin de « boisson de récupération » sucrée ni de barre énergétique pour une activité de loisir : c'est du marketing pour la plupart des pratiquants.","m12c6b"],
  ["💧 Hydratation — et signes d'hypoglycémie","HYDRATATION :\n💧 buvez AVANT d'avoir soif : un grand verre avant la séance, quelques gorgées toutes les 15-20 min pendant, et généreusement après ;\n🧂 en keto, on élimine plus d'eau et de sels : pour les longues séances ou par forte chaleur, une pincée de sel dans l'eau ou un bouillon après l'effort évite fatigue et crampes ;\n⚠️ évitez les boissons « sport » classiques : ce sont des sodas déguisés (6-8 g de sucre/100 ml).\n\n🚨 HYPOGLYCÉMIE PENDANT L'EFFORT — LES SIGNES À CONNAÎTRE :\ntremblements, sueurs froides, fringale brutale, palpitations, vertiges, vision trouble, confusion, jambes coupées.\nQUE FAIRE ? ARRÊTEZ-VOUS immédiatement, asseyez-vous, resucrez-vous (3 morceaux de sucre ou équivalent), attendez 15 min, contrôlez si vous avez un lecteur. Ne reprenez que si tout est rentré dans l'ordre.\n⚠️ Ce risque concerne SURTOUT les personnes sous insuline ou sulfamides — si c'est votre cas, ayez TOUJOURS de quoi vous resucrer sur vous pendant l'effort.","m12c6c"],
  ["📊 Adapter selon l'intensité","🚶 ACTIVITÉ DOUCE (marche, jardinage, yoga) : aucune adaptation nécessaire — hydratez-vous, c'est tout ;\n🚴 ACTIVITÉ MODÉRÉE 30-60 min (vélo, natation tranquille, renforcement) : collation protéinée avant si le dernier repas est loin ; protéines au repas suivant ;\n🏃 ACTIVITÉ INTENSE OU LONGUE (>1 h, randonnée sportive, course) : collation avant + hydratation salée + éventuellement une collation pendant (noix, fromage) ; sous traitement hypoglycémiant : contrôle de glycémie avant/pendant/après et avis médical pour adapter les doses ;\n📉 bon à savoir : une séance intense peut faire baisser la glycémie jusqu'à 24-48 h après (les muscles refont leurs réserves) — d'où l'intérêt du contrôle au coucher les jours de grosse activité ;\n📈 à l'inverse, un effort très intense et bref peut faire MONTER temporairement la glycémie (adrénaline) : pas de panique, elle redescend.\n\n💡 Astuce Keto-Essenciel : la marche de 15 min APRÈS le repas reste l'outil le plus efficace et le plus sûr du quotidien — aucune adaptation alimentaire nécessaire, que des bénéfices glycémiques !","m12c6d"],
  ["📝 À retenir","📝 À retenir :\n✔ activité douce : pas d'adaptation, juste de l'eau ;\n✔ après l'effort : des protéines dans les 2 h pour les muscles ;\n✔ hydratation avant-pendant-après ; pensez au sel pour les longues séances ;\n✔ signes d'hypo à l'effort : tremblements, sueurs, vertiges → arrêt + resucrage immédiat ;\n✔ sous insuline/sulfamides : toujours du sucre sur soi + avis médical pour adapter les doses.\n\n🏅 Badge à débloquer en validant le quiz : « Je m'alimente autour du sport »"]],
  q:[["Faut-il manger avant une marche de 30 minutes ?",["Oui, un gros plat de pâtes","Non : le corps adapté au keto puise dans ses graisses — évitez juste de partir affamé"],1,"Pour une activité douce, aucune adaptation n'est nécessaire."],
     ["Quel est le nutriment clé après une séance ?",["Les protéines, pour réparer les muscles","Le sucre rapide","Rien"],0,"Œufs, poulet, poisson ou fromage blanc dans les 2 h — un vrai repas suffit."],
     ["Quels sont les signes d'une hypoglycémie pendant l'effort ?",["Tremblements, sueurs froides, vertiges, fringale brutale","Grande forme et euphorie","Mal aux cheveux"],0,"Arrêt immédiat + resucrage (3 morceaux de sucre) + 15 min de pause."],
     ["Qui doit toujours emporter de quoi se resucrer pendant le sport ?",["Tout le monde sans exception","Surtout les personnes sous insuline ou sulfamides hypoglycémiants"],1,"Ces traitements exposent à l'hypoglycémie d'effort — avis médical pour adapter les doses."],
     ["Que penser des boissons « sport » classiques ?",["Indispensables","Ce sont des sodas déguisés (6-8 g de sucre/100 ml) : eau + pincée de sel suffit"],1,"Pour une activité de loisir, l'eau (éventuellement salée) fait parfaitement le travail."]]},
 {t:"Voyager sans perdre ses habitudes",mi:"Préparez votre « trousse de voyage keto » type : ✈️ notez 5 collations transportables (amandes, fromage à pâte dure, boîte de sardines, œufs durs pour les trajets courts, carrés de chocolat noir 85 %). Ajoutez-y vos médicaments en double si vous êtes traité.",p:[
  ["👋 Introduction","Aéroports, gares, aires d'autoroute : le voyage est le royaume des sandwichs tristes et des viennoiseries industrielles.\nAvec un minimum de préparation, vous pouvez voyager l'esprit léger — sans dépendre des distributeurs automatiques ni arriver affamé à destination.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ préparer intelligemment un voyage ;\n✅ gérer les longs trajets et les repas d'avion ou de train ;\n✅ composer votre trousse de collations ;\n✅ gérer le décalage horaire si nécessaire."],
  ["🧳 Préparer le voyage — la checklist","📋 LA CHECKLIST AVANT DE PARTIR :\n1️⃣ MANGEZ UN VRAI REPAS avant le départ : partir rassasié = 4-5 h de tranquillité ;\n2️⃣ PRÉPAREZ VOS COLLATIONS (voir page suivante) — ne comptez JAMAIS sur l'offre sur place ;\n3️⃣ si vous êtes sous traitement : médicaments EN CABINE (jamais en soute !), en double quantité, avec l'ordonnance (idéalement en dénomination internationale pour l'étranger) ;\n4️⃣ pour l'insuline : elle se conserve à température ambiante plusieurs semaines, mais évitez chaleur extrême — pochette isotherme si destination chaude ;\n5️⃣ repérez à l'avance un supermarché près de votre hébergement : votre premier réflexe à l'arrivée ;\n6️⃣ location avec cuisine ou hôtel ? Une kitchenette simplifie tout (petits-déjeuners maîtrisés).","m12c7b"],
  ["🚄 Trajets, avion, train : en pratique","🥜 LA TROUSSE DE COLLATIONS IDÉALE (voyage en cabine OK) :\namandes/noix, fromage à pâte dure (comté, mimolette — supportent bien quelques heures), chocolat noir 85 %, sachets de jambon sec ou viande séchée nature, olives en sachet. Pour les trajets courts : œufs durs, bâtonnets de crudités.\n\n✈️ EN AVION :\nles plateaux-repas sont très riches en glucides (pain, pâtes, dessert) — mangez la protéine et les légumes, laissez le reste et complétez avec vos collations ;\nbuvez BEAUCOUP d'eau (l'air pressurisé déshydrate énormément) et limitez l'alcool à bord ;\n\n🚄 EN TRAIN / VOITURE :\nle wagon-bar et les stations-service = sandwichs et viennoiseries. Vos alternatives : votre trousse + dans les boutiques relais, cherchez œufs durs, fromage portion et fruits à coque (souvent disponibles !) ;\nen voiture : pique-nique maison — la meilleure option de toutes, et la plus économique.","m12c7c"],
  ["🌍 Le décalage horaire — et l'arrivée","😴 GÉRER LE DÉCALAGE HORAIRE (si voyage lointain) :\n🕐 calez vos repas sur l'heure LOCALE dès l'arrivée (voire dès l'avion) : les repas sont un puissant synchroniseur de l'horloge interne ;\n☀️ exposez-vous à la lumière du jour dès le matin sur place ;\n💊 si vous prenez des traitements à heure fixe (notamment insuline ou sulfamides) : demandez à votre médecin AVANT le départ comment décaler les prises — ne bricolez pas seul ;\n😴 acceptez 2-3 jours d'adaptation : hydratation, repas légers le soir, pas d'alcool.\n\n🛬 À L'ARRIVÉE :\n1️⃣ premier réflexe : petites courses (œufs, fromage, légumes, eau, fruits à coque) ;\n2️⃣ repérez 2-3 restaurants adaptés autour de l'hébergement ;\n3️⃣ et surtout : PROFITEZ ! Découvrir la cuisine locale fait partie du voyage — les grillades, poissons, fromages et légumes existent dans toutes les cultures.\n\n💡 Astuce Keto-Essenciel : dans le monde entier, la formule magique au restaurant reste la même : « une viande ou un poisson grillé + des légumes » — apprenez à la dire dans la langue locale, elle passe partout !","m12c7d"],
  ["📝 À retenir","📝 À retenir :\n✔ vrai repas avant le départ + trousse de collations = voyage serein ;\n✔ médicaments : en cabine, en double, avec ordonnance ;\n✔ en avion : mangez protéine + légumes du plateau, hydratez-vous beaucoup ;\n✔ décalage horaire : repas à l'heure locale, lumière du matin, traitements décalés AVEC le médecin ;\n✔ à l'arrivée : petites courses d'abord, découvertes ensuite — et plaisir toujours.\n\n🏅 Badge à débloquer en validant le quiz : « Je voyage keto »"]],
  q:[["Où placer ses médicaments en avion ?",["En soute","En cabine, en double quantité, avec l'ordonnance"],1,"Bagage perdu = traitement perdu : la cabine est la règle d'or."],
     ["Que faire du plateau-repas d'avion ?",["Tout manger sans réfléchir","Manger la protéine et les légumes, compléter avec ses collations"],1,"Pain, féculent et dessert peuvent rester sur le plateau."],
     ["Quelles collations voyagent bien ?",["Glaces et yaourts à boire","Amandes, fromage à pâte dure, chocolat noir 85 %, viande séchée, olives"],1,"Elles tiennent des heures sans frigo et passent en cabine."],
     ["Comment aider son corps face au décalage horaire ?",["Manger à l'heure locale dès l'arrivée et s'exposer à la lumière du matin","Rester enfermé","Sauter tous les repas"],0,"Repas et lumière sont les meilleurs synchroniseurs de l'horloge interne."],
     ["Sous traitement à heure fixe, comment gérer le décalage horaire ?",["On bricole tout seul","On demande au médecin AVANT le départ comment décaler les prises"],1,"Insuline et sulfamides ne se décalent jamais à l'improvisation."]]},
 {t:"Faire ses courses comme un expert",mi:"Pour vos prochaines courses : 🛒 préparez votre liste par rayons AVANT de partir, mangez quelque chose avant d'y aller, et chronométrez-vous. Objectif : un caddie 100 % assumé et pas un produit imprévu !",p:[
  ["👋 Introduction","Tout se joue au supermarché : ce qui n'entre pas dans le caddie n'entrera jamais dans vos placards… ni dans votre assiette à 22 h.\nFaire ses courses « comme un expert », c'est gagner du temps, de l'argent, et s'épargner des semaines de tentations à domicile.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ préparer une liste efficace ;\n✅ naviguer dans les bons rayons ;\n✅ lire une étiquette en 10 secondes ;\n✅ déjouer les achats impulsifs et organiser votre semaine."],
  ["📋 La liste — et le parcours du magasin","LA LISTE EFFICACE se prépare en 5 minutes :\n1️⃣ partez de vos MENUS de la semaine (l'app les génère pour vous !) ;\n2️⃣ classez la liste PAR RAYONS : fruits & légumes → boucherie/poissonnerie → crèmerie → épicerie → surgelés. Vous suivez le magasin dans l'ordre, sans allers-retours ;\n3️⃣ ajoutez vos « basiques de sécurité » : œufs, beurre, huile d'olive, amandes, conserves de poisson.\n\n🗺️ LE PARCOURS DE L'EXPERT : faites le TOUR EXTÉRIEUR du magasin ! Les produits frais (légumes, viande, poisson, fromage, œufs) sont presque toujours en périphérie. Les allées centrales concentrent l'ultra-transformé : biscuits, sodas, céréales, plats préparés. Moins vous y entrez, mieux vous mangez.\nVos rayons de prédilection : 🥬 fruits & légumes, 🥩 boucherie, 🐟 poissonnerie, 🥚 œufs/crèmerie, 🧀 fromages, 🥫 conserves de poisson, ❄️ légumes surgelés nature (excellent rapport qualité-prix !), 🥜 fruits à coque.","m12c8b"],
  ["🏷️ Lire une étiquette en 10 secondes","La méthode express, dans l'ordre :\n1️⃣ LES GLUCIDES pour 100 g — le chiffre clé : visez < 5-10 g/100 g pour les produits du quotidien ;\n2️⃣ LA LISTE D'INGRÉDIENTS — courte = bon signe. Les ingrédients sont classés par ordre décroissant : si le sucre est dans les 3 premiers, reposez ;\n3️⃣ LES SUCRES DÉGUISÉS — plus de 50 noms : sirop de glucose-fructose, dextrose, maltodextrine, sucre inverti, jus de fruits concentré… ;\n4️⃣ IGNOREZ le marketing du recto : « allégé », « fitness », « riche en céréales », « sans sucres ajoutés » (≠ sans sucres !) — seul le VERSO dit la vérité.\n📌 Le meilleur produit ? Celui qui n'a PAS d'étiquette : un brocoli, une entrecôte, un maquereau n'ont pas de liste d'ingrédients !","m12c8c"],
  ["🛡️ Déjouer les pièges — et organiser sa semaine","LES ACHATS IMPULSIFS ONT 3 DÉCLENCHEURS CONNUS :\n😋 LA FAIM — ne faites JAMAIS les courses le ventre vide (les études le confirment : caddie plus rempli et plus sucré). Une poignée d'amandes avant d'entrer change tout ;\n👀 L'EMPLACEMENT — les produits en tête de gondole, à hauteur des yeux et près des caisses sont placés là pour être pris sans réfléchir. Fixez votre liste, pas les rayonnages ;\n⏰ LA FATIGUE — évitez les courses après une grosse journée : la volonté est une ressource qui s'épuise.\n\n📅 ORGANISER SA SEMAINE :\n✔ UNE grosse course hebdomadaire (avec liste) plutôt que 4 petites improvisées ;\n✔ le drive est votre allié anti-impulsion : on n'achète que ce qu'on a tapé, sans odeur de viennoiserie ;\n✔ en rentrant : lavez et rangez les légumes en évidence dans le frigo — ce qui se voit se mange.\n\n💡 Astuce Keto-Essenciel : générez votre menu de la semaine dans l'app → la liste de courses se crée automatiquement, classée par rayons. Courses expertes en un clic !","m12c8d"],
  ["📝 À retenir","📝 À retenir :\n✔ liste par rayons construite à partir des menus de la semaine ;\n✔ faites le tour extérieur du magasin : le frais est en périphérie, les pièges au centre ;\n✔ étiquette express : glucides/100 g d'abord, puis liste d'ingrédients courte ;\n✔ jamais de courses le ventre vide — le drive est un excellent anti-impulsion ;\n✔ le meilleur produit n'a pas d'étiquette du tout.\n\n🏅 Badge à débloquer en validant le quiz : « Expert des courses »"]],
  q:[["Où se trouvent les produits frais dans un supermarché ?",["Au centre, avec les biscuits","En périphérie : faites le tour extérieur du magasin"],1,"Les allées centrales concentrent l'ultra-transformé."],
     ["Quel chiffre regarder en premier sur une étiquette ?",["Les glucides pour 100 g","Le prix au kilo","La couleur du logo"],0,"Visez moins de 5-10 g/100 g pour les produits du quotidien."],
     ["Pourquoi ne jamais faire les courses le ventre vide ?",["On marche moins vite","La faim pousse aux achats impulsifs et sucrés — c'est prouvé","C'est interdit"],1,"Une poignée d'amandes avant d'entrer protège votre caddie."],
     ["« Sans sucres ajoutés » signifie…",["Sans aucun sucre","Qu'il peut quand même contenir beaucoup de sucres naturellement présents"],1,"Seul le tableau nutritionnel au verso dit la vérité."],
     ["Quel est le meilleur produit du supermarché ?",["Celui qui n'a pas d'étiquette : brocoli, viande, poisson","Celui en tête de gondole","Le plus « allégé »"],0,"Pas de liste d'ingrédients = pas de mauvaise surprise."]]},
 {t:"Fast-food : est-ce compatible ?",mi:"Exercice sans pression : 🍔 sur le site ou l'appli de votre enseigne de fast-food habituelle, composez virtuellement votre commande « keto-compatible » (burger sans pain + salade + eau). Vous saurez exactement quoi demander le jour venu !",p:[
  ["👋 Introduction","Un déjeuner d'équipe au fast-food, des enfants qui réclament leur enseigne préférée, une aire d'autoroute sans alternative… Le fast-food fait partie de la vraie vie.\nAlors, compatible ou pas ? Réponse honnête : ce n'est jamais l'option idéale, MAIS il est tout à fait possible d'y faire des choix corrects. Voici comment.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ identifier les meilleurs choix selon les enseignes ;\n✅ demander les bonnes adaptations ;\n✅ éviter les pièges (sauces, boissons, desserts) ;\n✅ limiter l'impact d'un repas occasionnel."],
  ["🍔 Les meilleurs choix selon les enseignes","LA RÈGLE UNIVERSELLE : la protéine du fast-food (steak, poulet grillé) est correcte — le problème, c'est TOUT AUTOUR : pain, frites, sauce sucrée, soda, dessert.\n\n🍔 BURGERS (McDonald's, Burger King, Five Guys…) :\n✔ demandez votre burger SANS PAIN (en France : possible dans la plupart des enseignes, parfois servi en salade — chez Five Guys, le « bowl » est officiel) ;\n✔ doublez le steak plutôt que prendre des frites ;\n✔ les salades « poulet grillé » (PAS pané) sont souvent la meilleure option du menu ;\n🥗 KEBAB : l'assiette kebab SANS frites ni pain (viande + salade + sauce blanche à dose raisonnable) est étonnamment correcte ;\n🌮 TEX-MEX : bowl sans riz ni haricots — viande, fromage, guacamole, salade ;\n🍕 PIZZERIA RAPIDE : le point difficile — la pâte EST le problème. Optez pour une salade complète si disponible ;\n🍗 POULET : préférez TOUJOURS le grillé au pané/frit (la panure = farine + friture).","m12c9b"],
  ["⚠️ Les pièges à déjouer","1️⃣ LES SAUCES — le piège invisible : ketchup (~25 % de sucre !), barbecue, aigre-douce, curry-mangue sont très sucrées.\n✔ vos alliées : mayonnaise, moutarde, sauce blanche nature (avec modération) ;\n2️⃣ LES BOISSONS — un soda moyen = 35-45 g de sucre, et les recharges gratuites aggravent tout.\n✔ eau, eau gazeuse, café, thé glacé maison non sucré ou soda zéro à défaut ;\n3️⃣ LES DESSERTS — sundae, muffin, cookie : 30-60 g de sucre chacun. Le café en fin de repas fait très bien le travail ;\n4️⃣ LES MENUS « MAXI » — le piège économique : « pour 1 € de plus »… non merci. Le petit format d'aujourd'hui est le bon format ;\n5️⃣ LES NUGGETS ET PANÉS — panure = farine frite : préférez les morceaux grillés quand ils existent.","m12c9c"],
  ["🧭 Limiter l'impact d'un repas occasionnel","Soyons réalistes : parfois, vous mangerez un « vrai » fast-food complet — et c'est OK. Voici comment en limiter l'impact :\n1️⃣ AVANT : ne sautez pas les repas précédents « pour compenser à l'avance » — vous arriveriez affamé et commanderiez le double ;\n2️⃣ PENDANT : mangez LENTEMENT (le fast-food se dévore en 8 minutes — prenez-en 20), buvez de l'eau, savourez vraiment ;\n3️⃣ APRÈS : une MARCHE de 15-20 minutes après le repas atténue significativement le pic de glycémie — c'est le moment parfait pour l'appliquer ;\n4️⃣ LE REPAS SUIVANT : retour direct aux habitudes — léger le soir (légumes + protéine), hydratation ;\n5️⃣ MENTALEMENT : c'était un repas, pas une rechute. La règle « jamais deux fois de suite » s'applique, la culpabilité non.\n\n💡 Astuce Keto-Essenciel : commandez sur borne ou appli plutôt qu'au comptoir — vous personnalisez tranquillement (sans pain, sans sauce sucrée) sans pression sociale ni file d'attente derrière vous.","m12c9d"],
  ["📝 À retenir","📝 À retenir :\n✔ la protéine est correcte, les pièges sont autour : pain, frites, sauces, sodas, desserts ;\n✔ burger sans pain, salade poulet grillé, bowl sans riz = les meilleures options ;\n✔ ketchup et sauces sucrées : préférez mayonnaise ou moutarde ;\n✔ eau ou soda zéro plutôt que soda sucré (35-45 g de sucre !) ;\n✔ repas complet occasionnel : marche de 15-20 min après + retour aux habitudes dès le repas suivant.\n\n🏅 Badge à débloquer en validant le quiz : « Je gère le fast-food »"]],
  q:[["Quel est le vrai problème d'un burger de fast-food ?",["Le steak","Tout ce qu'il y a autour : pain, frites, sauce sucrée, soda, dessert"],1,"Demandez-le sans pain, doublez le steak, prenez une salade à la place des frites."],
     ["Quelle sauce contient environ 25 % de sucre ?",["La mayonnaise","Le ketchup","La moutarde"],1,"Mayonnaise et moutarde sont vos alliées ; ketchup, barbecue et aigre-douce vos pièges."],
     ["Quelle boisson choisir au fast-food ?",["Un soda moyen (35-45 g de sucre)","Eau, café ou soda zéro à défaut"],1,"Les recharges gratuites de soda aggravent encore l'addition glycémique."],
     ["Que faire juste après un repas de fast-food complet ?",["Une sieste immédiate","Une marche de 15-20 minutes pour atténuer le pic de glycémie"],1,"C'est le moment parfait pour appliquer le réflexe marche post-repas."],
     ["Un fast-food occasionnel est…",["Une rechute catastrophique","Un repas comme un autre : jamais deux fois de suite, et on reprend ses habitudes"],1,"Zéro culpabilité — la tendance globale compte plus qu'un repas isolé."]]},
 {t:"Anniversaires, fêtes et repas de famille",mi:"Avant votre prochaine fête : 🎂 choisissez À L'AVANCE votre « écart plaisir » du jour (une part de gâteau ? une coupe de champagne ?). Un écart CHOISI est un plaisir ; dix écarts subis sont un regret. Notez votre choix !",p:[
  ["👋 Introduction","Anniversaires, baptêmes, retrouvailles de famille… Ces journées joyeuses concentrent tous les défis : buffet à volonté, gâteau cérémonial, boissons qui coulent, proches insistants !\nCe chapitre rassemble vos meilleures stratégies pour profiter PLEINEMENT de la fête — car c'est bien le but — sans le regretter le lendemain.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ naviguer dans un buffet de fête ;\n✅ gérer le gâteau et les desserts ;\n✅ choisir vos boissons ;\n✅ transformer l'écart en simple parenthèse."],
  ["🥳 Le buffet de fête — et les boissons","LE BUFFET DE FÊTE, votre plan en 4 temps :\n1️⃣ NE PAS ARRIVER AFFAMÉ — une collation protéinée avant de partir (vous connaissez la chanson !) ;\n2️⃣ TOUR DE REPÉRAGE complet avant de se servir ;\n3️⃣ remplissez VOTRE assiette une bonne fois : crevettes, saumon fumé, viandes froides, fromages, crudités, olives, œufs mimosa — les fêtes regorgent d'excellentes options ! ;\n4️⃣ éloignez-vous ensuite de la table — discutez, dansez, occupez vos mains avec un verre d'eau gazeuse.\n\n🥂 LES BOISSONS DE FÊTE :\n✔ champagne brut ou vin sec si vous buvez (cf. chapitre alcool) — UN à DEUX verres savourés ;\n✔ entre les verres d'alcool : eau gazeuse-citron dans une flûte, personne n'y verra que du feu ;\n⚠️ attention au punch, à la sangria et aux cocktails maison : très sucrés, et on perd vite le compte des verres.","m12c10b"],
  ["🎂 Le gâteau — et les proches insistants","LE GÂTEAU D'ANNIVERSAIRE est un moment SYMBOLIQUE — le refuser peut froisser. Vos options gagnantes :\n🍰 LA PETITE PART ASSUMÉE : acceptez une part fine, mangez-la LENTEMENT en la savourant vraiment. Un écart choisi et apprécié > une frustration ou une culpabilité ;\n🎂 le chant, la bougie, la photo : participez à fond — la convivialité ne se mesure pas en grammes de gâteau ;\n👵 face à l'insistance affectueuse (« j'ai fait ton dessert préféré ! ») : la petite part est la réponse diplomatique parfaite ;\n🧁 vous recevez ? Proposez AUSSI un dessert keto (fondant chocolat-amande, mousse chocolat de l'app) — souvent, tout le monde préfère celui-là !\n\n📌 LES ÉCARTS OCCASIONNELS, parlons-en franchement : 5-6 grandes fêtes par an, même avec de vrais écarts, ne représentent RIEN face à 1 000 repas annuels. Le problème n'est jamais la fête — c'est quand « l'exception » devient hebdomadaire.","m12c10c"],
  ["🔄 Reprendre dès le repas suivant","La compétence qui change tout : LA REPRISE IMMÉDIATE.\n📅 LE REPAS SUIVANT (pas lundi, pas le 1er du mois : le repas SUIVANT) : léger et classique — légumes + protéine + bonnes graisses. Exemple après un déjeuner de fête : soupe de légumes + omelette le soir ;\n💧 hydratez-vous davantage pendant 24-48 h (le sel et les glucides de fête retiennent l'eau) ;\n🚶 une belle marche digestive le jour même ou le lendemain matin ;\n⚖️ ne montez PAS sur la balance pendant 3-4 jours : le chiffre (eau !) serait faussement décourageant ;\n🧠 et mentalement ? La fête était une PARENTHÈSE joyeuse, pas une faute. Elle est fermée, la vie normale reprend — c'est exactement ainsi que fonctionnent les personnes qui maintiennent leurs résultats à vie.\n\n💡 Astuce Keto-Essenciel : le lendemain de fête, votre petit-déjeuner habituel (œufs, avocat…) est votre meilleur « bouton reset » — il re-signale à votre corps ET à votre cerveau que la routine bienveillante a repris.","m12c10d"],
  ["📝 À retenir","📝 À retenir :\n✔ buffet : collation avant, tour de repérage, UNE assiette, puis on s'éloigne de la table ;\n✔ gâteau : la petite part assumée et savourée est la meilleure option — symbole et plaisir ;\n✔ punch et cocktails maison = pièges sucrés ; champagne brut ou eau gazeuse en flûte ;\n✔ 5-6 fêtes par an ne pèsent rien face à 1 000 repas ;\n✔ reprise au repas SUIVANT + pas de balance pendant 3-4 jours.\n\n🏅 Badge à débloquer en validant le quiz : « Je profite des fêtes »"]],
  q:[["Quelle attitude adopter face au gâteau d'anniversaire ?",["Le refuser ostensiblement","Une petite part assumée, savourée lentement","En reprendre trois fois par politesse"],1,"Un écart choisi et apprécié vaut mieux qu'une frustration — ou qu'une culpabilité."],
     ["Quelles boissons de fête sont les plus piégeuses ?",["L'eau gazeuse","Punch, sangria et cocktails maison : très sucrés et on perd le compte"],1,"Préférez champagne brut, vin sec — ou eau gazeuse-citron en flûte."],
     ["Quand reprendre ses habitudes après une fête ?",["Lundi prochain","Le 1er du mois","Dès le repas suivant"],2,"C'est LA compétence des gens qui maintiennent leurs résultats à vie."],
     ["Pourquoi éviter la balance 3-4 jours après une fête ?",["Elle serait cassée","Le sel et les glucides retiennent de l'eau : le chiffre serait faussement décourageant"],1,"Cette eau repart seule en quelques jours."],
     ["5-6 grandes fêtes par an…",["Ruinent toute une année d'efforts","Ne représentent rien face à 1 000 repas annuels"],1,"Le problème n'est jamais la fête, c'est l'exception qui devient hebdomadaire."]]},
 {t:"Noël, Nouvel An et les grandes fêtes",mi:"Préparez vos fêtes de fin d'année : 🎄 notez les 3 plats de fête que vous adorez et qui sont naturellement adaptés (huîtres ? saumon ? dinde ? foie gras ?). Vous verrez : le réveillon keto-compatible est un festin, pas une privation !",p:[
  ["👋 Introduction","Les fêtes de fin d'année : une à deux semaines de repas somptueux, de chocolats en libre-service et de « c'est les fêtes, profite ! ».\nVoici LE grand secret : le repas de réveillon traditionnel français est étonnamment adapté ! Huîtres, saumon fumé, foie gras, dinde, fromages… Ce ne sont pas les plats de fête le problème — ce sont les grignotages sucrés qui les entourent pendant deux semaines.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ profiter des repas de fête intelligemment ;\n✅ appliquer les bonnes stratégies avant, pendant, après ;\n✅ gérer desserts et chocolats ;\n✅ démarrer la nouvelle année sereinement, sans culpabilité ni « régime du 1er janvier »."],
  ["🦪 Le réveillon : un festin naturellement adapté","Regardez la table de fête française avec vos yeux d'expert :\n✅ LES STARS NATURELLEMENT KETO :\n🦪 huîtres et fruits de mer — parfaits ;\n🐟 saumon fumé — parfait ;\n🥂 foie gras — riche mais adapté (sans le pain d'épices : préférez quelques feuilles de salade ou tel quel) ;\n🦃 dinde, chapon, gibier — parfaits ;\n🧀 le plateau de fromages — royal ;\n🥬 haricots verts, champignons, purée de céleri en accompagnement.\n⚠️ LES POINTS DE VIGILANCE : les marrons (très glucidiques — quelques-uns pour le goût), les toasts et pains briochés (le foie gras s'en passe très bien), les farces sucrées, et bien sûr la bûche.\n\n🗓️ LA VRAIE STRATÉGIE DES FÊTES : distinguez les 3-4 VRAIS repas de fête (24, 25, 31, 1er) — profitez-en pleinement ! — des 10 jours « entre les fêtes » : ceux-là sont des jours NORMAUX. Le piège n'est pas le réveillon, c'est le chocolat en continu du 20 décembre au 5 janvier.","m12c11b"],
  ["🍫 Avant, pendant — desserts et chocolats","AVANT LE GRAND REPAS :\n🍳 journée normale et légère (mais ne JEÛNEZ pas « pour compenser » : vous arriveriez affamé) ;\n🚶 une marche dans l'après-midi ;\n\nPENDANT :\n🦪 régalez-vous des entrées de la mer et du plat principal — ce sont les meilleures parts du repas ;\n⏳ mangez LENTEMENT : un réveillon dure des heures, rien ne presse ;\n🥂 alcool : champagne brut de préférence, eau entre les verres (chapitre 4 !) ;\n\n🍰 LA BÛCHE ET LES DESSERTS :\nla petite part assumée reste la reine des stratégies. Ou apportez VOTRE bûche keto (chocolat-mascarpone — recette dans l'app) : succès garanti à table ;\n🍫 LES CHOCOLATS — le vrai adversaire des fêtes : la boîte ouverte sur la table basse pendant 2 semaines. Stratégies : gardez-les HORS DE VUE (dans un placard haut), sortez-en 2 par jour choisis et savourés, et privilégiez le noir 70 %+. Offrez ou remportez les boîtes excédentaires !","m12c11c"],
  ["🎊 Bien démarrer la nouvelle année — sans excès inverse","Le 1er janvier arrive… et avec lui la tentation du « régime drastique de janvier ». NE TOMBEZ PAS dans le piège inverse !\n❌ le cycle « excès de décembre → restriction extrême de janvier → craquage de février » est exactement l'effet yo-yo décrit au Module 7 ;\n✔ à la place : reprenez simplement VOS habitudes normales dès le 2 janvier — petits-déjeuners protéinés, menus de l'app, marches quotidiennes. Sans punition, sans détox marketing, sans jus de céleri ;\n⚖️ pesez-vous vers le 7-10 janvier, pas le 2 (l'eau des fêtes, toujours elle) ;\n💭 et la culpabilité ? Remplacez « j'ai tout gâché pendant les fêtes » par « j'ai profité de ma famille, et je sais exactement comment reprendre ». C'est la mentalité des gens qui réussissent durablement ;\n🎯 janvier est aussi le bon moment pour vous fixer UN objectif simple et mesurable pour le trimestre (ex. : marcher 15 min après chaque déjeuner) — pas quinze résolutions intenables.\n\n💡 Astuce Keto-Essenciel : le 2 janvier, générez votre menu de la semaine dans l'app AVANT d'aller faire les courses. La nouvelle année commence par une liste de courses, pas par une privation !","m12c11d"],
  ["📝 À retenir — et bravo pour ce module !","📝 À retenir :\n✔ le réveillon français est naturellement adapté : huîtres, saumon, foie gras, volaille, fromages ;\n✔ le vrai piège = les grignotages sucrés PENDANT 2 semaines, pas les 3-4 repas de fête ;\n✔ chocolats : hors de vue, 2 par jour choisis, noir 70 %+ ;\n✔ pas de « régime punitif de janvier » : reprise simple des habitudes dès le 2 ;\n✔ pesée vers le 7-10 janvier, un seul objectif trimestriel simple.\n\n🎓 Dans ce Module Bonus, vous avez appris à gérer : le restaurant, les vacances, les invitations, l'alcool, le jeûne intermittent, les édulcorants, le sport, les voyages, les courses, le fast-food, les fêtes de famille et les fêtes de fin d'année.\n\n🏅 Après ce chapitre, le Quiz final du module (20 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge 🌟 « Expert Keto-Essenciel » — et votre certificat de fin de parcours si vous avez terminé tous les modules !"]],
  q:[["Le repas de réveillon traditionnel français est-il adapté ?",["Non, tout est à proscrire","Oui, étonnamment : huîtres, saumon, foie gras, volaille, fromages"],1,"Le problème n'est pas le réveillon — ce sont les grignotages sucrés des 2 semaines autour."],
     ["Quel est le vrai adversaire des fêtes de fin d'année ?",["La dinde","La boîte de chocolats ouverte en continu pendant 2 semaines","Les haricots verts"],1,"Hors de vue, 2 par jour choisis, noir 70 %+ : le trio gagnant."],
     ["Faut-il jeûner avant le grand repas « pour compenser » ?",["Oui, toute la journée","Non : journée normale et légère, sinon on arrive affamé"],1,"Arriver affamé à un réveillon = dégâts garantis dès l'apéritif."],
     ["Que penser du « régime drastique de janvier » ?",["C'est indispensable","C'est le piège inverse : il alimente l'effet yo-yo — reprenez simplement vos habitudes"],1,"Excès → restriction extrême → craquage : le cycle à éviter absolument."],
     ["Quand se peser après les fêtes ?",["Le 1er janvier au matin","Vers le 7-10 janvier, une fois l'eau des fêtes éliminée"],1,"Le chiffre du 2 janvier serait faussement décourageant."]]}
],fq:[
 ["Quelle est la formule gagnante au restaurant ?",["Une protéine + des légumes","Le menu complet avec dessert","Uniquement du pain","Rien du tout"],0,"Viande ou poisson grillé + légumes : la valeur sûre de toutes les cartes."],
 ["Quels mots d'une carte de restaurant cachent farine et sucre ?",["Pané, en croûte, caramélisé, laqué","Grillé, vapeur, rôti","Frais, maison","Bio, local"],0,"Ces préparations enrobent la protéine de glucides cachés."],
 ["Quelle est la meilleure stratégie face à un buffet ?",["Tour de repérage complet, puis UNE assiette réfléchie","Se servir de tout immédiatement","Ne rien manger","Rester debout à côté du buffet"],0,"Et asseyez-vous loin du buffet : chaque resservage doit être une décision."],
 ["Que faire dès le premier jour du retour de vacances ?",["Refaire des courses saines","Se peser immédiatement","Jeûner 3 jours","Rien"],0,"Frigo plein d'options saines = reprise automatique ; la pesée attendra J+4."],
 ["Quelle est la stratégie royale pour une invitation chez des proches ?",["Proposer d'apporter un plat ou le dessert","Refuser l'invitation","Faire la leçon à table","Arriver affamé"],0,"Vous garantissez une option adaptée — et vos hôtes apprécient le geste."],
 ["Pourquoi l'alcool peut-il provoquer une hypoglycémie tardive ?",["Le foie occupé à éliminer l'alcool ne libère plus de glucose","L'alcool contient trop de vitamines","Il ne le peut pas","Par magie"],0,"Risque accru sous insuline ou sulfamides : jamais à jeun, glycémie au coucher."],
 ["Quelles boissons alcoolisées sont les moins glucidiques ?",["Vin sec, champagne brut, spiritueux purs","Bière et cidre doux","Cocktails sucrés","Punch maison"],0,"1-2 g par verre — contre 20-40 g pour un cocktail sucré."],
 ["Sous insuline ou sulfamides, avant de commencer un jeûne intermittent, il faut…",["Un avis médical obligatoire pour adapter les traitements","Rien de spécial","Arrêter ses médicaments soi-même","Le cacher à son médecin"],0,"Jeûner sans adapter ces traitements expose à des hypoglycémies graves."],
 ["Comment débuter le jeûne intermittent en douceur ?",["12 h de jeûne nocturne, puis 14 h si tout va bien","48 h de jeûne direct","Sauter tous les repas","Ne boire que du café"],0,"Dîner tôt + petit-déjeuner tardif : l'essentiel du jeûne se fait en dormant."],
 ["Quels sont les deux meilleurs édulcorants en mode keto ?",["Érythritol et stévia","Maltitol et miel","Sirop d'agave et sucre de coco","Aspartame et sucre roux"],0,"0 impact glycémique et bonne tolérance — méfiez-vous du maltitol !"],
 ["Pourquoi le maltitol est-il un piège ?",["Il élève réellement la glycémie malgré l'étiquette « sans sucre »","Il est introuvable","Il est trop salé","Il n'existe pas"],0,"Très utilisé dans les chocolats « sans sucre » du commerce : lisez les étiquettes."],
 ["Que manger après une séance de sport ?",["Des protéines dans les 2 h pour réparer les muscles","Une barre chocolatée obligatoire","Rien pendant 24 h","Uniquement du jus de fruits"],0,"Œufs, poulet, poisson ou fromage blanc — un vrai repas suffit."],
 ["Quels sont les signes d'hypoglycémie pendant l'effort ?",["Tremblements, sueurs froides, vertiges, fringale brutale","Une grande forme","Des courbatures le lendemain","L'envie de chanter"],0,"Arrêt immédiat + resucrage + 15 min de pause — surtout sous traitement hypoglycémiant."],
 ["Où placer ses médicaments lors d'un voyage en avion ?",["En cabine, en double, avec l'ordonnance","En soute","Dans la poche d'un inconnu","On les laisse à la maison"],0,"Bagage perdu = traitement perdu : la cabine est non négociable."],
 ["Comment aider son horloge interne en cas de décalage horaire ?",["Repas à l'heure locale + lumière du matin","Rester dans le noir","Manger toutes les heures","Ne plus dormir"],0,"Les repas et la lumière sont les synchroniseurs les plus puissants."],
 ["Pourquoi ne jamais faire ses courses le ventre vide ?",["La faim pousse aux achats impulsifs et sucrés","C'est plus long","Le magasin est fermé","Ça porte malheur"],0,"Étudié et prouvé : une collation avant les courses protège le caddie."],
 ["Quel chiffre regarder en premier sur une étiquette ?",["Les glucides pour 100 g","La taille du logo","Le slogan du recto","La couleur de l'emballage"],0,"Visez < 5-10 g/100 g — et une liste d'ingrédients courte."],
 ["Quelle est la meilleure adaptation au fast-food ?",["Burger sans pain ou salade au poulet grillé, avec de l'eau","Menu maxi avec soda","Double dessert","Nuggets et sauce barbecue"],0,"La protéine est correcte — les pièges sont le pain, les frites, les sauces et le soda."],
 ["Après un repas de fête, quand reprendre ses habitudes ?",["Dès le repas suivant","Le mois prochain","Après le 31 décembre","Jamais"],0,"La reprise immédiate est LA compétence du maintien à vie — sans culpabilité."],
 ["Que penser du « régime drastique de janvier » après les fêtes ?",["C'est le piège de l'effet yo-yo : mieux vaut reprendre simplement ses habitudes","C'est obligatoire","C'est la seule solution","Il faut jeûner tout janvier"],0,"Excès → restriction extrême → craquage : brisez le cycle en reprenant votre routine normale."]
],bd:"🌟 Expert Keto-Essenciel",sk:["Manger au restaurant sans culpabiliser","Profiter des vacances et des buffets","Gérer les invitations avec diplomatie","Consommer l'alcool avec discernement","Comprendre le jeûne intermittent et ses limites","Choisir et doser les édulcorants","M'alimenter autour du sport en sécurité","Voyager sans perdre mes habitudes","Faire mes courses comme un expert","Gérer fast-food, fêtes et fin d'année sereinement"]}'''

src = src[:j] + '\n]},\n' + NEW + '\n];' + src[j+len(ANCHOR):]
io.open(PATH, 'w', encoding='utf-8').write(src)
print('OK: Module BONUS = 12 chapitres + quiz final 20 q')
