#!/usr/bin/env python3
# Module 0 « Bienvenue dans Keto-Essenciel » : insertion en tête du Parcours
# + ajout d'un préfixe image stable (ip) sur chaque module existant.
import io, sys
PATH = '/app/keto.html'
src = io.open(PATH, encoding='utf-8').read()
if 'Bienvenue dans Keto-Essenciel",e:"🌿"' in src:
    print('DÉJÀ APPLIQUÉ'); sys.exit(0)

# 1) Préfixes image stables sur les 13 modules existants (ordre actuel = m0..m12)
HEADS = [
 ('{t:"Comprendre son diabète",e:"🧠",', 'm0'),
 ('{t:"Pourquoi le Keto ?",e:"🥑",', 'm1'),
 ('{t:"Bien manger",e:"🥦",', 'm2'),
 ('{t:"Les menus personnalisés",e:"🥑",', 'm3'),
 ('{t:"Cuisiner Keto au quotidien",e:"🍳",', 'm4'),
 ('{t:"Bouger, récupérer et retrouver son énergie",e:"🏃",', 'm5'),
 ('{t:"Comprendre et réussir sa perte de poids durable",e:"⚖️",', 'm6'),
 ('{t:"Comprendre ses analyses biologiques",e:"🧪",', 'm7'),
 ('{t:"Stress, sommeil et équilibre glycémique",e:"😌",', 'm8'),
 ('{t:"Les compléments alimentaires : lesquels, pourquoi, dans quelles situations ?",e:"💊",', 'm9'),
 ('{t:"Les traitements",e:"🩺",', 'm10'),
 ('{t:"Le suivi",e:"📈",', 'm11'),
 ('{t:"Le guide de survie Keto-Essenciel",e:"🎁",', 'm12'),
]
for head, pref in HEADS:
    if src.count(head) != 1:
        print('ERREUR head introuvable/multiple:', head[:50], src.count(head)); sys.exit(1)
    src = src.replace(head, head + 'ip:"' + pref + '",')

# 2) Insertion du Module 0 en tête du tableau PC
ANCHOR = '{t:"Comprendre son diabète",e:"🧠",ip:"m0",'
i = src.find(ANCHOR)
if i < 0: print('ERREUR ancre module 1'); sys.exit(1)

NEW = r'''{t:"Bienvenue dans Keto-Essenciel",e:"🌿",intro:true,ip:"mw",d:"Découvrez l'application, réalisez votre premier bilan et construisez un parcours personnalisé adapté à vos objectifs.",ch:[
 {t:"Bienvenue dans Keto-Essenciel",mi:"Prenez quelques instants. 🌱 Demandez-vous : pourquoi ai-je téléchargé Keto-Essenciel ? Écrivez une ou deux raisons qui vous motivent aujourd'hui. Ces motivations vous aideront dans les moments plus difficiles.",p:[
  ["👋 Bienvenue !","Bienvenue dans Keto-Essenciel.\nJe suis Patrice Raganelli, naturopathe spécialisé dans la perte de poids, la santé métabolique et l'accompagnement des personnes vivant avec un diabète.\nJe suis heureux de vous accueillir dans cette application.\n\nAvant de commencer, j'aimerais vous dire une chose essentielle.\nCette application n'a pas été créée pour vous imposer un régime de plus.\nElle a été conçue pour vous aider à comprendre votre corps, reprendre confiance en vous et construire des habitudes durables, à votre rythme.\nIci, il n'y a ni jugement, ni culpabilité.\nSeulement des outils concrets, des conseils pratiques et un accompagnement progressif.\nChaque petit pas compte.\nEt aujourd'hui, vous venez de faire le premier.\n\n⏱ Temps de lecture : 5 minutes."],
  ["🌱 Ce que vous allez découvrir","Au fil des modules, vous apprendrez à :\n✅ comprendre le diabète de type 2 et la santé métabolique ;\n✅ découvrir l'alimentation cétogène et l'alimentation pauvre en glucides ;\n✅ stabiliser votre glycémie ;\n✅ favoriser une perte de poids durable ;\n✅ comprendre vos analyses biologiques ;\n✅ mieux dormir ;\n✅ gérer votre stress ;\n✅ bouger davantage ;\n✅ choisir les compléments alimentaires avec discernement ;\n✅ construire un mode de vie durable.\nEt en module bonus : gérer sereinement le restaurant, les voyages, les fêtes et toutes les situations de la vraie vie !","mwc0b"],
  ["❤️ Mon engagement","Je souhaite vous accompagner avec bienveillance.\nChaque conseil proposé dans cette application repose sur les connaissances scientifiques disponibles et sur mon expérience en accompagnement.\n\n⚠️ Toutefois, cette application ne remplace pas le suivi par votre médecin ou votre équipe soignante.\nEn cas de traitement contre le diabète ou d'autres maladies, n'arrêtez JAMAIS un traitement sans avis médical.\nVotre médecin reste votre référent : cette application vous aide à mieux comprendre, mieux dialoguer avec lui et devenir acteur de votre santé.","mwc0c"],
  ["💡 Comment profiter pleinement de Keto-Essenciel ?","Je vous conseille de :\n✔ avancer dans les modules DANS L'ORDRE — chaque module s'appuie sur les précédents ;\n✔ réaliser les MISSIONS proposées à la fin de chaque chapitre — c'est là que les connaissances deviennent des habitudes ;\n✔ répondre aux QUIZ — ils valident vos acquis et débloquent vos badges ;\n✔ utiliser régulièrement les OUTILS DE SUIVI de l'application ;\n✔ revenir consulter les chapitres lorsque vous en ressentez le besoin.\nIl n'est pas nécessaire d'aller vite.\nL'important est de progresser.","mwc0d"],
  ["📝 À retenir","📝 À retenir :\n✔ vous n'êtes pas seul ;\n✔ cette application est un accompagnement progressif ;\n✔ chaque module vous permettra de développer une nouvelle compétence ;\n✔ les petits changements répétés sont souvent plus efficaces que les changements brutaux.\n\n🏅 Badge à débloquer en validant le quiz : « Bienvenue dans Keto-Essenciel »"]],
  q:[["Quel est l'objectif principal de Keto-Essenciel ?",["Vous imposer un régime strict","Vous accompagner vers une meilleure santé grâce à des habitudes durables"],1,"Ni jugement, ni culpabilité : des outils concrets et un accompagnement progressif."],
     ["Dans quel ordre est-il conseillé de suivre les modules ?",["Dans l'ordre proposé","Au hasard"],0,"Chaque module s'appuie sur les précédents."],
     ["L'application remplace-t-elle votre médecin ?",["Oui","Non"],1,"Elle complète le suivi médical — ne modifiez jamais un traitement sans avis médical."],
     ["Quel est le meilleur rythme ?",["Aller le plus vite possible","Avancer progressivement"],1,"Il n'est pas nécessaire d'aller vite : l'important est de progresser."],
     ["Pourquoi noter vos motivations ?",["Pour rester engagé dans votre démarche","Ça ne sert à rien"],0,"Elles vous aideront dans les moments plus difficiles."]]},
 {t:"Comment fonctionne l'application ?",mi:"Explorez l'application : 📱 ouvrez chacun des onglets (Plan, Recettes, Suivi, Profil…) pendant 2 minutes. Puis générez votre premier menu de la semaine — vous verrez, tout est automatique !",p:[
  ["👋 Introduction","Keto-Essenciel regroupe tous les outils dont vous avez besoin au même endroit : des menus, des recettes, un suivi, une formation complète… et moi, en filigrane, pour vous guider.\nDans ce chapitre, faisons ensemble le tour du propriétaire — pour que dès demain, l'application devienne votre alliée du quotidien.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ naviguer dans les principaux onglets ;\n✅ générer votre menu de la semaine ;\n✅ utiliser la liste de courses automatique ;\n✅ savoir où trouver chaque outil."],
  ["🍽️ Le Plan : vos menus de la semaine","L'onglet PLAN est le cœur de l'application :\n✨ GÉNÉRER MA SEMAINE — en un clic, l'application compose 7 jours de menus keto adaptés à VOTRE profil (objectifs, mode alimentaire, calories personnalisées) ;\n🔄 un plat ne vous plaît pas ? Échangez-le contre un autre en un geste ;\n🛒 LA LISTE DE COURSES se crée automatiquement à partir de vos menus, classée par rayons — vos courses d'expert en un clic (vous verrez au Module bonus à quel point c'est précieux !) ;\n📄 vous pouvez aussi exporter vos menus en PDF pour les imprimer ou les partager.\nChaque plat affiche ses valeurs : calories, glucides, protéines, lipides — de quoi apprendre en mangeant.","mwc1b"],
  ["📚 Recettes, Suivi et Parcours","🍳 LES RECETTES : des centaines de recettes keto détaillées pas à pas (petits-déjeuners, plats, desserts, collations), adaptées à votre mode alimentaire — standard, végétarien, diabète… Marquez vos favorites !\n\n📊 LE SUIVI : enregistrez votre poids, votre tour de taille, votre glycémie et vos habitudes. Les courbes vous montrent la TENDANCE — bien plus parlante que le chiffre du jour (vous l'apprendrez au fil du parcours !).\n\n🎓 LE PARCOURS : la formation complète que vous êtes en train de suivre — des modules progressifs, des chapitres courts, des missions concrètes, des quiz et des badges. Votre université de la santé métabolique, dans votre poche.","mwc1c"],
  ["👤 Le Profil — et les bons réflexes","⚙️ LE PROFIL : c'est ici que tout se personnalise — vos mensurations, votre objectif (perte de poids, stabilisation), votre mode alimentaire, vos préférences. Un profil bien renseigné = des menus vraiment adaptés ;\n☁️ vos données peuvent être synchronisées dans le cloud pour ne rien perdre en changeant de téléphone ;\n\n💡 LES BONS RÉFLEXES DU QUOTIDIEN :\n1️⃣ le dimanche : générez votre semaine + liste de courses ;\n2️⃣ chaque matin : un œil sur le menu du jour ;\n3️⃣ une fois par semaine : votre pesée et vos mesures dans le Suivi ;\n4️⃣ chaque jour : un chapitre du Parcours (5 minutes suffisent !).\n\n💡 Astuce Keto-Essenciel : ajoutez l'application à l'écran d'accueil de votre téléphone et faites-en votre réflexe du matin, comme la météo !","mwc1d"],
  ["📝 À retenir","📝 À retenir :\n✔ le Plan génère vos menus ET votre liste de courses automatiquement ;\n✔ les Recettes s'adaptent à votre mode alimentaire ;\n✔ le Suivi révèle vos tendances — le Parcours développe vos compétences ;\n✔ un Profil bien renseigné = des menus vraiment personnalisés ;\n✔ la routine gagnante : menus le dimanche, un chapitre par jour, une pesée par semaine.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais mon application »"]],
  q:[["Que fait le bouton « Générer ma semaine » ?",["Il compose 7 jours de menus keto adaptés à votre profil","Il efface tout","Il envoie un email"],0,"Menus personnalisés + liste de courses automatique en un clic."],
     ["Comment se crée la liste de courses ?",["Automatiquement à partir de vos menus, classée par rayons","Il faut tout taper à la main","Elle n'existe pas"],0,"Vos courses d'expert en un clic."],
     ["À quoi sert l'onglet Suivi ?",["À enregistrer poids, mesures et glycémie pour voir les TENDANCES","À jouer","À rien"],0,"La tendance sur plusieurs semaines est plus parlante que le chiffre du jour."],
     ["Pourquoi bien renseigner son Profil ?",["Pour des menus vraiment adaptés à vos objectifs","Pour faire joli","C'est inutile"],0,"Mensurations, objectif, mode alimentaire : tout se personnalise ici."],
     ["Quelle est la routine gagnante ?",["Menus le dimanche, un chapitre par jour, une pesée par semaine","Tout faire une fois par an","Ne jamais ouvrir l'application"],0,"Des petits rendez-vous réguliers valent mieux qu'un marathon ponctuel."]]},
 {t:"Réaliser votre premier bilan",mi:"C'est le moment ! 📏 Prenez vos mesures de départ : poids (le matin, à jeun), tour de taille (au nombril), et si vous en avez, votre dernière glycémie et HbA1c. Enregistrez tout dans l'onglet Suivi — c'est votre photo de départ.",p:[
  ["👋 Introduction","Avant de commencer un voyage, il faut savoir d'où l'on part.\nVotre premier bilan n'est PAS un examen — personne ne vous jugera. C'est simplement votre photo de départ : dans quelques semaines, c'est elle qui vous montrera, chiffres à l'appui, tout le chemin parcouru.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ prendre vos mesures de départ correctement ;\n✅ rassembler vos données de santé utiles ;\n✅ faire un état des lieux honnête de vos habitudes ;\n✅ comprendre pourquoi ce bilan est votre meilleur allié."],
  ["📏 Les mesures de départ","Les 3 mesures essentielles :\n⚖️ LE POIDS — le matin, à jeun, après être passé aux toilettes, sans vêtements lourds. Notez-le, puis oubliez la balance jusqu'à la semaine prochaine (le poids fluctue de ±1-2 kg naturellement) ;\n📏 LE TOUR DE TAILLE — au niveau du nombril, ventre relâché, mètre-ruban horizontal. C'est souvent LUI qui bougera en premier — et c'est le meilleur reflet de la graisse viscérale (vous comprendrez pourquoi au Module 7) ;\n📸 LA PHOTO — optionnelle mais précieuse : une photo de face et de profil, même vêtements, même endroit. Dans 3 mois, elle vous parlera plus que tous les chiffres.\n\nSi vous vivez avec un diabète, ajoutez :\n🩸 votre dernière GLYCÉMIE à jeun et votre dernière HbA1c (sur votre dernière prise de sang) — ce sont vos repères métaboliques de départ.","mwc2b"],
  ["📋 L'état des lieux de vos habitudes","Prenez 5 minutes pour répondre honnêtement — sans vous juger — à ces questions :\n🍽️ ALIMENTATION : combien de repas par jour ? Des grignotages ? Des boissons sucrées ? Des plats préparés ?\n🚶 MOUVEMENT : combien de temps de marche par jour ? Des escaliers ou l'ascenseur ?\n😴 SOMMEIL : à quelle heure vous couchez-vous ? Vous réveillez-vous reposé ?\n😌 STRESS : votre niveau de stress sur 10 ? Vos moments de détente ?\n💊 SANTÉ : vos traitements en cours ? Votre dernier bilan sanguin date de quand ?\nCes réponses ne servent qu'à VOUS. Il n'y a pas de bonne ou de mauvaise réponse — seulement un point de départ. Ce qui se mesure s'améliore ; ce qu'on ignore stagne.","mwc2c"],
  ["🧭 Pourquoi ce bilan va vous porter","Votre bilan de départ est un cadeau que vous vous faites :\n📈 IL RENDRA VOS PROGRÈS VISIBLES — dans quelques semaines, quand la motivation fera une pause (c'est normal !), relire ses chiffres de départ est le meilleur des carburants : « −4 cm de tour de taille, −0,4 point d'HbA1c… ça marche ! » ;\n🎯 IL PERMET DES OBJECTIFS RÉALISTES — on ne fixe pas le même cap selon d'où l'on part (chapitre suivant !) ;\n🩺 IL ENRICHIT LE DIALOGUE AVEC VOTRE MÉDECIN — arriver en consultation avec ses mesures et ses questions change la qualité de l'échange ;\n⚠️ et rappelez-vous : on ne compare JAMAIS son point de départ à celui d'un autre. Votre seul concurrent, c'est vous-même d'il y a un mois.\n\n💡 Astuce Keto-Essenciel : enregistrez toutes vos mesures dans l'onglet Suivi dès aujourd'hui — les courbes se construiront automatiquement au fil des semaines.","mwc2d"],
  ["📝 À retenir","📝 À retenir :\n✔ le premier bilan est une photo de départ, pas un examen ;\n✔ poids (1×/semaine, à jeun), tour de taille au nombril, photo optionnelle ;\n✔ si diabète : notez votre glycémie à jeun et votre dernière HbA1c ;\n✔ l'état des lieux des habitudes se fait sans jugement ;\n✔ ce bilan rendra vos progrès visibles — votre meilleur carburant pour durer.\n\n🏅 Badge à débloquer en validant le quiz : « Mon bilan de départ est fait »"]],
  q:[["Comment bien se peser pour le bilan de départ ?",["Le matin, à jeun, dans les mêmes conditions — puis 1 fois par semaine","10 fois par jour","Après un grand repas"],0,"Le poids fluctue naturellement de ±1-2 kg : c'est la tendance qui compte."],
     ["Où se mesure le tour de taille ?",["Au niveau du nombril, ventre relâché","Au cou","À la cheville"],0,"C'est le meilleur reflet de la graisse viscérale — souvent le premier à bouger."],
     ["Le bilan de départ est-il un examen ?",["Oui, avec une note","Non : une photo de départ sans aucun jugement"],1,"Il ne sert qu'à vous — pour rendre vos futurs progrès visibles."],
     ["À quoi servira votre bilan dans quelques semaines ?",["À rien","À mesurer objectivement vos progrès et nourrir votre motivation"],1,"Relire ses chiffres de départ est le meilleur carburant des moments creux."],
     ["À qui faut-il comparer votre point de départ ?",["Aux autres","À personne : votre seul concurrent est vous-même d'il y a un mois"],1,"Chaque parcours est unique — le vôtre commence aujourd'hui."]]},
 {t:"Définir vos objectifs personnalisés",mi:"Écrivez votre objectif principal selon la méthode du chapitre : 🎯 « Dans 3 mois, je veux [objectif mesurable], parce que [votre vraie motivation] ». Affichez-le quelque part où vous le verrez chaque jour.",p:[
  ["👋 Introduction","« Je veux maigrir » ou « je veux être en meilleure santé » sont de beaux souhaits… mais de mauvais objectifs : impossibles à mesurer, sans échéance, sans plan.\nDans ce chapitre, transformons vos souhaits en objectifs MOTIVANTS et ATTEIGNABLES — la différence entre espérer et réussir.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ formuler un objectif clair et mesurable ;\n✅ distinguer objectifs de résultat et objectifs d'action ;\n✅ fixer des échéances réalistes ;\n✅ relier vos objectifs à vos vraies motivations."],
  ["🎯 Un bon objectif : précis, mesurable, daté","La différence est énorme :\n❌ « je veux perdre du poids » → 🎯 « je veux perdre 5 kg en 3 mois » ;\n❌ « je veux être moins fatigué » → 🎯 « je veux me coucher avant 23 h tous les soirs de semaine pendant 1 mois » ;\n❌ « je veux améliorer ma glycémie » → 🎯 « je veux faire baisser mon HbA1c de 0,5 point d'ici ma prochaine prise de sang ».\n\nLes 3 ingrédients d'un bon objectif :\n1️⃣ PRÉCIS — un chiffre, pas une intention ;\n2️⃣ MESURABLE — avec l'outil pour le vérifier (balance, mètre, prise de sang) ;\n3️⃣ DATÉ — une échéance raisonnable.\nEt surtout : RÉALISTE. Perdre 0,5 à 1 kg par semaine est durable ; viser 10 kg en 1 mois est le meilleur moyen d'abandonner (l'effet yo-yo vous attend au Module 7 !).","mwc3b"],
  ["⚙️ Objectifs de résultat vs objectifs d'ACTION","Voici le secret des gens qui réussissent :\n📊 L'OBJECTIF DE RÉSULTAT (« perdre 5 kg », « HbA1c à 6,8 % ») donne le CAP — mais vous ne le contrôlez pas directement au quotidien ;\n✅ L'OBJECTIF D'ACTION (« marcher 15 min après le déjeuner », « cuisiner mes menus 5 jours sur 7 », « me coucher à 22h30 ») est 100 % ENTRE VOS MAINS — et c'est lui qui produit le résultat.\nLa formule gagnante : UN cap de résultat + DEUX ou TROIS actions quotidiennes simples.\nExemple complet :\n🎯 Cap : perdre 5 kg en 3 mois ;\n✅ Action 1 : générer et suivre mes menus de la semaine ;\n✅ Action 2 : marcher 15 min après le déjeuner ;\n✅ Action 3 : arrêter les boissons sucrées.\nChaque soir, vous pouvez cocher vos actions — ET c'est ça, le vrai succès quotidien.","mwc3c"],
  ["❤️ Le POURQUOI : votre carburant","Un objectif sans motivation profonde ne survit pas au premier coup de mou.\nDerrière « perdre 5 kg », quel est votre VRAI pourquoi ?\n💭 « pouvoir jouer par terre avec mes petits-enfants sans souffrir » ;\n💭 « ne pas augmenter mon traitement à la prochaine consultation » ;\n💭 « me sentir bien dans mes vêtements au mariage de ma fille » ;\n💭 « être encore là, en forme, dans 20 ans ».\nVotre pourquoi est personnel, parfois intime — et c'est LUI qui vous relèvera les jours difficiles.\nÉcrivez votre objectif complet : « Dans 3 mois, je veux [résultat mesurable], parce que [votre pourquoi]. Pour y arriver, chaque jour je [vos 2-3 actions]. »\n\n💡 Astuce Keto-Essenciel : relisez vos motivations notées au chapitre 1 — votre pourquoi s'y cache sûrement déjà. Affichez votre phrase-objectif sur le frigo ou en fond d'écran !","mwc3d"],
  ["📝 À retenir","📝 À retenir :\n✔ un bon objectif est précis, mesurable, daté — et réaliste ;\n✔ 0,5 à 1 kg par semaine = durable ; les objectifs extrêmes mènent à l'abandon ;\n✔ le cap de résultat guide, les objectifs d'ACTION quotidiens produisent ;\n✔ votre POURQUOI profond est le carburant des jours difficiles ;\n✔ écrivez votre phrase-objectif et affichez-la.\n\n🏅 Badge à débloquer en validant le quiz : « Mes objectifs sont clairs »"]],
  q:[["Quel est le meilleur objectif ?",["« Je veux maigrir »","« Je veux perdre 5 kg en 3 mois »","« Je veux être mieux »"],1,"Précis, mesurable, daté : les 3 ingrédients d'un objectif efficace."],
     ["Quel rythme de perte de poids est durable ?",["0,5 à 1 kg par semaine","5 kg par semaine","10 kg en 2 semaines"],0,"Les objectifs extrêmes mènent à l'abandon et à l'effet yo-yo."],
     ["Qu'est-ce qu'un objectif d'ACTION ?",["Un objectif 100 % entre vos mains, comme « marcher 15 min après le déjeuner »","Un rêve lointain","Un chiffre sur la balance"],0,"C'est lui qui produit le résultat — et que vous pouvez cocher chaque soir."],
     ["Quelle est la formule gagnante ?",["Un cap de résultat + 2-3 actions quotidiennes simples","15 résolutions en même temps","Aucun objectif"],0,"Le cap guide, les actions produisent."],
     ["À quoi sert votre « pourquoi » profond ?",["À rien","C'est le carburant qui vous relèvera les jours difficiles"],1,"Un objectif sans motivation profonde ne survit pas au premier coup de mou."]]},
 {t:"Construire votre parcours et vos premières habitudes",mi:"Lancez-vous : 🚀 choisissez UNE première habitude simple à démarrer dès aujourd'hui (un chapitre du Parcours par jour ? une marche après le déjeuner ?), accrochez-la à une habitude existante, et faites-la aujourd'hui même. Le Module 1 vous attend !",p:[
  ["👋 Introduction","Vous connaissez l'application, votre bilan est fait, vos objectifs sont clairs.\nDernière étape avant le grand départ : construire VOTRE parcours et poser vos premières habitudes — les fondations sur lesquelles tout le reste tiendra.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ organiser votre progression dans les modules ;\n✅ démarrer par des habitudes minuscules qui tiennent ;\n✅ utiliser missions et badges comme moteur ;\n✅ savoir quoi faire en cas de baisse de motivation."],
  ["🗺️ Votre feuille de route dans les modules","Le Parcours est conçu comme un escalier — chaque marche s'appuie sur la précédente :\n📗 MODULES 1-2 : comprendre le diabète et pourquoi le keto fonctionne — vos fondations ;\n🥦 MODULES 3-5 : bien manger, vos menus, cuisiner au quotidien — la pratique ;\n🏃 MODULE 6 : bouger, dormir, récupérer — le mode de vie ;\n⚖️ MODULES 7-8 : perte de poids durable et analyses biologiques — l'expertise ;\n😌 MODULES 9-10 : stress, sommeil, compléments — l'équilibre ;\n🩺 MODULES 11-12 : traitements et suivi — l'autonomie ;\n🎁 MODULE BONUS : restaurant, fêtes, voyages — la vraie vie !\nLe rythme idéal ? UN CHAPITRE PAR JOUR (5 minutes) = le parcours complet en environ 3 mois. Mais c'est VOTRE rythme qui compte : deux chapitres par semaine mènent au même endroit.","mwc4b"],
  ["🌱 L'art des habitudes minuscules","Le secret des habitudes qui TIENNENT : commencer RIDICULEMENT petit.\n❌ « à partir de demain, sport tous les jours + zéro sucre + coucher à 22 h » → épuisement garanti en 10 jours ;\n✅ « cette semaine, je marche 10 minutes après le déjeuner » → tenable, puis extensible.\n\nLa méthode en 3 règles :\n1️⃣ UNE SEULE nouvelle habitude à la fois — quand elle devient automatique (2-3 semaines), ajoutez la suivante ;\n2️⃣ ACCROCHEZ-LA à une habitude existante : « après mon café du matin, je lis mon chapitre du jour » — l'ancienne habitude déclenche la nouvelle ;\n3️⃣ RENDEZ-LA VISIBLE : baskets devant la porte, application sur l'écran d'accueil, légumes en évidence dans le frigo.\nChaque petite victoire répétée construit l'identité : vous devenez quelqu'un qui prend soin de lui.","mwc4c"],
  ["🏅 Missions, badges — et les jours sans","VOS MOTEURS DANS L'APPLICATION :\n🎯 les MISSIONS de fin de chapitre transforment la lecture en action — faites-les vraiment, c'est là que tout se joue ;\n🏅 les BADGES et les points marquent chaque étape franchie — collectionnez-les ! ;\n🎓 les QUIZ FINAUX de module valident vos compétences ;\n🌟 et au bout du chemin : votre CERTIFICAT de fin de parcours.\n\nET LES JOURS SANS MOTIVATION ? Ils viendront — c'est normal et prévu :\n✔ réduisez la voilure au lieu d'arrêter : pas envie de cuisiner ? Une omelette suffit. Pas envie de lire ? Une seule page ;\n✔ relisez vos motivations du chapitre 1 et votre phrase-objectif ;\n✔ regardez vos courbes de Suivi : le chemin déjà parcouru remotive ;\n✔ appliquez la règle d'or : JAMAIS DEUX JOURS DE SUITE sans rien — une mini-action relance toujours la machine.\n\n💡 Astuce Keto-Essenciel : votre prochaine action est toute simple — terminez ce chapitre, validez le quiz… et ouvrez le Module 1. Votre parcours commence maintenant !","mwc4d"],
  ["📝 À retenir — et en route !","📝 À retenir :\n✔ les modules forment un escalier : suivez-les dans l'ordre, à votre rythme ;\n✔ un chapitre par jour = parcours complet en ~3 mois ;\n✔ une seule habitude nouvelle à la fois, accrochée à une habitude existante ;\n✔ missions et badges transforment les connaissances en actions ;\n✔ jours sans : réduisez la voilure, jamais deux jours de suite sans rien.\n\n🎓 Vous avez terminé le Module 0 ! Le Quiz final du module (10 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge 🌿 « Prêt pour le parcours » — puis direction le Module 1 : Comprendre son diabète !"]],
  q:[["Quel est le rythme idéal dans le Parcours ?",["Un chapitre par jour (5 minutes) — ou VOTRE rythme","Tout lire en une nuit","Un chapitre par an"],0,"L'important n'est pas la vitesse, c'est la régularité."],
     ["Comment démarrer une habitude qui tient ?",["Ridiculement petit, une seule à la fois","Tout changer d'un coup","Attendre la motivation parfaite"],0,"Une habitude minuscule tenue 3 semaines devient automatique — puis extensible."],
     ["Comment « accrocher » une nouvelle habitude ?",["À une habitude existante : « après mon café, je lis mon chapitre »","Au hasard","En espérant y penser"],0,"L'ancienne habitude déclenche la nouvelle : c'est l'ancrage."],
     ["Que faire un jour sans motivation ?",["Tout arrêter","Réduire la voilure : une mini-action suffit — jamais deux jours de suite sans rien"],1,"Une seule page lue ou 5 minutes de marche relancent la machine."],
     ["Quelle est votre prochaine étape ?",["Valider le quiz final du Module 0 puis ouvrir le Module 1","Attendre lundi","Recommencer à zéro"],0,"Votre parcours commence maintenant — en route !"]]}
],fq:[
 ["Quel est l'objectif principal de Keto-Essenciel ?",["Vous accompagner vers une meilleure santé grâce à des habitudes durables","Vous imposer un régime strict","Remplacer votre médecin","Vous faire culpabiliser"],0,"Des outils concrets, des conseils pratiques et un accompagnement progressif."],
 ["L'application remplace-t-elle le suivi médical ?",["Non : ne modifiez jamais un traitement sans avis médical","Oui, totalement"],0,"Votre médecin reste votre référent — l'application vous aide à mieux dialoguer avec lui."],
 ["Comment se crée la liste de courses dans l'application ?",["Automatiquement à partir de vos menus, classée par rayons","À la main uniquement","Elle n'existe pas","Par courrier"],0,"Générez votre semaine : les courses suivent en un clic."],
 ["À quoi sert l'onglet Suivi ?",["À voir les TENDANCES de votre poids, tour de taille et glycémie","À regarder des vidéos","À rien","À commander des repas"],0,"La tendance sur plusieurs semaines est plus parlante que le chiffre du jour."],
 ["Comment se pèse-t-on correctement ?",["Le matin à jeun, une fois par semaine, dans les mêmes conditions","Dix fois par jour","Après un repas copieux","Jamais"],0,"Le poids fluctue de ±1-2 kg naturellement : regardez la tendance."],
 ["Où se mesure le tour de taille ?",["Au niveau du nombril, ventre relâché","Au poignet","À la cuisse","Au cou"],0,"C'est le meilleur reflet de la graisse viscérale — souvent le premier à bouger."],
 ["Qu'est-ce qu'un bon objectif ?",["Précis, mesurable, daté et réaliste","Vague et lointain","Impossible à atteindre","Sans échéance"],0,"« Perdre 5 kg en 3 mois » plutôt que « je veux maigrir »."],
 ["Quel rythme de perte de poids est durable ?",["0,5 à 1 kg par semaine","5 kg par semaine","Le plus vite possible","1 kg par heure"],0,"Les objectifs extrêmes mènent à l'abandon et à l'effet yo-yo."],
 ["Qu'est-ce qu'un objectif d'ACTION ?",["Un objectif 100 % entre vos mains, comme marcher 15 min après le déjeuner","Un chiffre sur la balance","Un rêve","Une punition"],0,"Le cap de résultat guide, les actions quotidiennes produisent."],
 ["Comment construire une habitude qui tient ?",["Commencer ridiculement petit, une seule à la fois, accrochée à une habitude existante","Tout changer d'un coup","Attendre la motivation","Se forcer brutalement"],0,"Petite victoire répétée = habitude automatique en 2-3 semaines — jamais deux jours de suite sans rien."]
],bd:"🌿 Prêt pour le parcours",sk:["Connaître les outils de l'application","Réaliser mon bilan de départ","Formuler des objectifs précis et réalistes","Distinguer cap de résultat et actions quotidiennes","Construire des habitudes minuscules qui durent","Utiliser missions, quiz et badges comme moteur"]}'''

src = src[:i] + NEW + ',\n' + src[i:]
io.open(PATH, 'w', encoding='utf-8').write(src)
print('OK: Module 0 inséré en tête (5 chapitres + quiz final 10 q) + préfixes ip sur 13 modules')
