#!/usr/bin/env python3
# Module 8 : refonte complète "Comprendre ses analyses biologiques" (10 chapitres + quiz final)
import io, sys

PATH = '/app/keto.html'
src = io.open(PATH, encoding='utf-8').read()

START = '{t:"Comprendre ses analyses",e:"🔬",d:"Lisez vos prises de sang comme un pro.",ch:['
END = ']},\n{t:"Stress et sommeil"'
i = src.find(START)
j = src.find(END, i)
if i < 0 or j < 0:
    print('ERREUR: bornes module 8 introuvables', i, j); sys.exit(1)

NEW = r'''{t:"Comprendre ses analyses biologiques",e:"🧪",d:"Comprendre les examens biologiques du diabète et de la santé métabolique pour mieux suivre son évolution et dialoguer avec les soignants.",ch:[
 {t:"Comprendre une prise de sang",mi:"Retrouvez votre dernière prise de sang : 📄 repérez 3 analyses que vous connaissez maintenant (glycémie, HbA1c, cholestérol…) et notez leurs valeurs. Conservez ce document : il servira de point de comparaison pour toute la suite du module.",p:[
  ["👋 Introduction","Une feuille pleine de sigles, de chiffres et d'étoiles : la prise de sang peut sembler indéchiffrable.\nPourtant, votre bilan biologique est l'un de vos meilleurs alliés : il raconte, noir sur blanc, ce qui se passe dans votre corps — et il mesure objectivement vos progrès.\nCe module va vous apprendre à le lire… sans jamais remplacer l'interprétation de votre médecin.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi réaliser un bilan biologique ;\n✅ identifier les principales analyses ;\n✅ comprendre les valeurs de référence et leurs limites ;\n✅ interpréter un résultat dans son contexte."],
  ["🩸 Pourquoi faire un bilan biologique ?","Le bilan sanguin sert à :\n🔍 DÉPISTER — détecter tôt un déséquilibre silencieux (prédiabète, foie gras, inflammation…) avant les symptômes ;\n📊 SUIVRE — mesurer l'évolution d'une situation connue (diabète, lipides…) et l'effet de vos changements de mode de vie ;\n💊 ADAPTER — aider votre médecin à ajuster un traitement ;\n🎯 MOTIVER — rien n'encourage plus que de voir ses chiffres s'améliorer noir sur blanc au fil des mois.\nPour les personnes diabétiques, un suivi biologique régulier (souvent tous les 3 à 6 mois pour l'HbA1c, une fois par an pour le bilan complet) fait partie intégrante de la prise en charge.","m7c0b"],
  ["📋 Les principales analyses","Votre bilan métabolique type comprend :\n🩸 la GLYCÉMIE à jeun — le sucre dans le sang à l'instant T ;\n📆 l'HbA1c — la moyenne glycémique des 3 derniers mois ;\n🧈 le BILAN LIPIDIQUE — triglycérides, HDL, LDL, cholestérol total ;\n🫁 les ENZYMES HÉPATIQUES — ALAT, ASAT, GGT (le foie) ;\n💧 la CRÉATININE et le DFGe (les reins) ;\n🔥 la CRP (l'inflammation) ;\n➕ selon les cas : insulinémie, acide urique, vitamine D, B12, ferritine, TSH…\nChaque chapitre de ce module vous les explique une par une.","m7c0c"],
  ["📐 Valeurs de référence : à manier avec précaution","À côté de chaque résultat figure une « fourchette de référence ». Trois choses à savoir :\n1️⃣ elle varie D'UN LABORATOIRE À L'AUTRE (méthodes de mesure différentes) — comparez toujours vos résultats aux références DU laboratoire, et faites idéalement vos suivis dans le même labo ;\n2️⃣ être « dans la norme » ne veut pas toujours dire « optimal » — et être légèrement hors norme n'est pas toujours inquiétant ;\n3️⃣ un chiffre isolé ne dit RIEN : ce qui compte, c'est le contexte (âge, traitements, jeûne respecté ou non, maladie récente, activité de la veille…) et surtout l'ÉVOLUTION dans le temps.\n⚠️ Règle d'or : ne tirez JAMAIS de conclusion seul et ne modifiez jamais un traitement sur la base d'une analyse — c'est le rôle de votre médecin.\n\n💡 Astuce Keto-Essenciel : demandez systématiquement une copie de vos résultats (c'est votre droit) et rangez-les dans un même dossier. Votre historique personnel vaut de l'or pour suivre vos progrès.","m7c0d"],
  ["📝 À retenir","📝 À retenir :\n✔ le bilan biologique dépiste, suit, aide à adapter — et motive ;\n✔ les valeurs de référence varient selon les laboratoires ;\n✔ un chiffre isolé ne dit rien : contexte + évolution dans le temps ;\n✔ gardez toujours une copie de vos analyses ;\n✔ l'interprétation finale appartient à votre médecin.\n\n🏅 Badge à débloquer en validant le quiz : « Je comprends ma prise de sang »"]],
  q:[["À quoi sert un bilan biologique ?",["À dépister, suivre l'évolution et aider à adapter la prise en charge","À remplacer le médecin","À rien"],0,"Il détecte tôt les déséquilibres silencieux et mesure objectivement vos progrès."],
     ["Les valeurs de référence sont-elles identiques partout ?",["Oui, universelles","Non, elles varient selon les laboratoires"],1,"Comparez vos résultats aux références DU laboratoire — et gardez le même labo si possible."],
     ["Un résultat légèrement hors norme signifie-t-il forcément un problème ?",["Oui, toujours","Non : il doit être interprété dans son contexte par le médecin"],1,"Contexte (jeûne, traitement, maladie récente…) et évolution comptent plus qu'un chiffre isolé."],
     ["Qu'est-ce qui est plus parlant qu'un chiffre isolé ?",["L'évolution des résultats dans le temps","La couleur de la feuille","Le nom du laboratoire"],0,"C'est la tendance au fil des bilans qui raconte votre histoire métabolique."],
     ["Peut-on modifier un traitement soi-même suite à une analyse ?",["Oui","Non, jamais : c'est le rôle du médecin"],1,"Règle d'or absolue — l'auto-ajustement peut être dangereux."]]},
 {t:"L'HbA1c : le reflet de votre glycémie sur plusieurs mois",mi:"Retrouvez votre dernière HbA1c : 📆 notez sa valeur et sa date. Au prochain rendez-vous, demandez à votre médecin quel est VOTRE objectif personnalisé — et notez-le à côté. C'est votre boussole des 3 prochains mois.",p:[
  ["👋 Introduction","S'il ne fallait retenir qu'une seule analyse pour le suivi du diabète, ce serait elle : l'HbA1c, ou hémoglobine glyquée.\nContrairement à la glycémie qui change d'heure en heure, l'HbA1c raconte votre histoire glycémique des 2-3 derniers mois. C'est le « film » là où la glycémie n'est qu'une « photo ».\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre ce qu'est l'hémoglobine glyquée ;\n✅ savoir ce que mesure l'HbA1c et les objectifs usuels ;\n✅ connaître les facteurs qui influencent le résultat ;\n✅ savoir comment l'améliorer progressivement."],
  ["🔬 Qu'est-ce que l'hémoglobine glyquée ?","L'hémoglobine est la protéine des globules rouges qui transporte l'oxygène. Quand le glucose circule en excès dans le sang, il se FIXE sur elle — on dit qu'elle est « glyquée ».\nPlus la glycémie a été élevée souvent, plus la proportion d'hémoglobine glyquée est grande.\nComme un globule rouge vit environ 120 jours, l'HbA1c reflète la glycémie MOYENNE des 2 à 3 derniers mois.\nExemples de correspondance approximative : 6 % ≈ 1,26 g/L de moyenne ; 7 % ≈ 1,54 g/L ; 8 % ≈ 1,83 g/L. Chaque point d'HbA1c en moins représente une vraie différence pour vos vaisseaux.","m7c1b"],
  ["🎯 Les objectifs — selon VOTRE situation","Repères généraux (à personnaliser IMPÉRATIVEMENT avec votre médecin) :\n🟢 < 5,7 % : zone habituelle sans diabète ;\n🟡 5,7 - 6,4 % : zone du prédiabète ;\n🔴 ≥ 6,5 % : zone du diabète (critère diagnostique) ;\n🎯 personne diabétique : l'objectif usuel est souvent ≤ 7 %, mais il varie selon l'âge, l'ancienneté du diabète, les traitements (risque d'hypoglycémie) et l'état de santé global — parfois 6,5 %, parfois 8 %.\nIl n'existe PAS d'objectif universel : le bon objectif est celui défini AVEC votre équipe soignante.","m7c1c"],
  ["⚙️ Ce qui influence le résultat — et comment l'améliorer","Facteurs pouvant fausser ou influencer l'HbA1c : anémie, carence en fer, certaines maladies du sang ou du rein, grossesse, transfusion récente… Votre médecin en tient compte.\n\nComment l'améliorer progressivement :\n🥗 réduire les glucides rapides et les produits ultra-transformés — moins de pics = moins de glucose fixé ;\n🚶 bouger chaque jour, notamment après les repas ;\n💪 renforcer ses muscles (grands consommateurs de glucose) ;\n😴 dormir 7-9 h et gérer le stress (cortisol = glycémie) ;\n💊 suivre son traitement tel que prescrit.\n⏳ PATIENCE : l'HbA1c réagit en MOIS, pas en jours. Vos efforts d'aujourd'hui se liront sur la prise de sang dans 3 mois — c'est normal, et c'est même la meilleure preuve que les changements sont durables.\n\n💡 Astuce Keto-Essenciel : notez chaque HbA1c dans un tableau avec sa date. Une baisse de 8 % à 7 % = une glycémie moyenne réduite d'environ 0,3 g/L : chaque dixième compte, célébrez-le !","m7c1d"],
  ["📝 À retenir","📝 À retenir :\n✔ l'HbA1c reflète la glycémie moyenne des 2-3 derniers mois ;\n✔ ≥ 6,5 % = zone du diabète ; l'objectif se personnalise avec le médecin ;\n✔ certains facteurs (anémie, grossesse…) peuvent influencer le résultat ;\n✔ alimentation, mouvement, sommeil et traitement l'améliorent — en quelques MOIS ;\n✔ chaque dixième de point gagné protège vos vaisseaux.\n\n🏅 Badge à débloquer en validant le quiz : « Je maîtrise mon HbA1c »"]],
  q:[["Que reflète l'HbA1c ?",["La glycémie moyenne des 2-3 derniers mois","La glycémie de l'instant","Le taux de fer"],0,"Le glucose se fixe sur l'hémoglobine des globules rouges, qui vivent ~120 jours."],
     ["À partir de quelle HbA1c parle-t-on de diabète ?",["≥ 6,5 %","≥ 4 %","≥ 15 %"],0,"5,7-6,4 % = prédiabète ; ≥ 6,5 % = zone du diabète."],
     ["L'objectif d'HbA1c est-il le même pour tous ?",["Oui, 7 % pour tout le monde","Non : il se personnalise selon l'âge, les traitements et la situation"],1,"Parfois 6,5 %, parfois 8 % : c'est une décision partagée avec l'équipe soignante."],
     ["En combien de temps l'HbA1c réagit-elle aux changements ?",["Quelques heures","Quelques mois","10 ans"],1,"Elle reflète 3 mois de glycémies : soyez patient, elle suivra vos efforts."],
     ["Qu'est-ce qui peut influencer le résultat de l'HbA1c ?",["Une anémie ou certaines maladies du sang","La couleur des yeux","Le jour de la semaine"],0,"Votre médecin tient compte de ces situations particulières pour interpréter."]]},
 {t:"La glycémie et l'insuline",mi:"Notez la glycémie à jeun de votre dernier bilan. 🩸 Si votre insulinémie n'a jamais été mesurée, parlez-en à votre médecin au prochain rendez-vous : elle peut révéler une résistance à l'insuline invisible sur la glycémie seule.",p:[
  ["👋 Introduction","La glycémie et l'insuline sont les deux faces d'une même pièce : la première mesure le sucre dans le sang, la seconde l'hormone chargée de le faire entrer dans les cellules.\nLire les deux ENSEMBLE en dit bien plus que chacune séparément — et permet parfois de détecter un problème des années avant qu'il ne se voie sur la glycémie.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ interpréter la glycémie à jeun et après les repas ;\n✅ comprendre le rôle de l'insuline ;\n✅ comprendre l'hyperinsulinémie ;\n✅ saisir pourquoi ces deux analyses sont complémentaires."],
  ["🩸 La glycémie : à jeun et après les repas","📌 GLYCÉMIE À JEUN (au moins 8 h sans manger) — repères usuels :\n🟢 < 1,00 g/L : normale ;\n🟡 1,00 - 1,25 g/L : prédiabète (hyperglycémie modérée à jeun) ;\n🔴 ≥ 1,26 g/L à DEUX reprises : diabète.\n📌 GLYCÉMIE POST-PRANDIALE (≈ 2 h après le début du repas) : elle révèle comment votre corps gère la « vague » de glucose. On vise généralement < 1,40 g/L ; entre 1,40 et 1,99 g/L on parle d'intolérance au glucose.\nElle est précieuse car certaines personnes ont une glycémie à jeun normale… mais des pics importants après les repas.","m7c2b"],
  ["🔑 L'insuline : la clé des cellules","L'insuline, produite par le pancréas, permet au glucose d'entrer dans les cellules (muscles, foie…) pour y être utilisé ou stocké.\nQuand les cellules deviennent RÉSISTANTES à son message (excès de sucre chronique, graisse viscérale, sédentarité), le pancréas compense en produisant PLUS d'insuline : c'est l'HYPERINSULINÉMIE.\nPendant des années, cette surproduction maintient la glycémie normale — tout semble aller bien. Mais en coulisses :\n📈 le stockage des graisses est favorisé (l'insuline stocke, souvenez-vous du Module 7) ;\n😋 les fringales s'installent ;\n😮‍💨 le pancréas s'épuise progressivement… jusqu'au jour où la glycémie monte : le prédiabète, puis le diabète, apparaissent.","m7c2c"],
  ["🧩 Pourquoi les deux analyses sont complémentaires","La glycémie seule peut être trompeuse :\n✔ glycémie normale + insuline NORMALE = métabolisme serein ;\n⚠️ glycémie normale + insuline ÉLEVÉE = résistance à l'insuline déjà installée — le stade silencieux, des années avant le diabète. C'est LE signal précoce que la glycémie ne montre pas ;\n🔴 glycémie élevée + insuline élevée = résistance avancée ;\n🔴 glycémie élevée + insuline basse = pancréas fatigué (diabète avancé).\nValeur souhaitable d'insulinémie à jeun : généralement < 10 µUI/mL (repères variables selon les laboratoires).\nBonne nouvelle : la résistance à l'insuline RÉPOND très bien au mode de vie — alimentation pauvre en sucres, mouvement, muscle, sommeil.\n\n💡 Astuce Keto-Essenciel : l'insulinémie à jeun n'est pas toujours prescrite en routine. Si vous êtes en prédiabète ou en surpoids abdominal, demandez à votre médecin si elle serait utile dans votre cas — couplée à la glycémie, elle permet de calculer le HOMA (chapitre suivant).","m7c2d"],
  ["📝 À retenir","📝 À retenir :\n✔ diabète = glycémie à jeun ≥ 1,26 g/L à deux reprises ;\n✔ la glycémie post-repas révèle les pics que le jeûne ne montre pas ;\n✔ l'insuline fait entrer le glucose dans les cellules — et stocke les surplus ;\n✔ une insuline élevée avec une glycémie normale = résistance silencieuse déjà installée ;\n✔ glycémie + insuline lues ensemble = un diagnostic bien plus précoce.\n\n🏅 Badge à débloquer en validant le quiz : « Je comprends glycémie et insuline »"]],
  q:[["Un diabète est défini par une glycémie à jeun ≥…",["0,80 g/L","1,26 g/L à deux reprises","3 g/L"],1,"≥ 1,26 g/L confirmée à deux reprises : c'est le seuil diagnostique."],
     ["Que révèle la glycémie post-prandiale (2 h après le repas) ?",["La façon dont le corps gère la vague de glucose du repas","Le taux de fer","Rien d'utile"],0,"Certaines personnes ont un jeûne normal… mais de gros pics après les repas."],
     ["Quel est le rôle de l'insuline ?",["Faire entrer le glucose dans les cellules","Colorer le sang","Faire dormir"],0,"C'est la clé qui ouvre les cellules au glucose — et l'hormone du stockage."],
     ["Une insuline à jeun élevée avec une glycémie normale signifie…",["Tout va bien","Une résistance à l'insuline déjà installée, stade silencieux avant le diabète"],1,"Le pancréas surcompense en coulisses : c'est le signal précoce à ne pas rater."],
     ["La résistance à l'insuline peut-elle s'améliorer ?",["Non, jamais","Oui : alimentation, mouvement, muscle et sommeil sont très efficaces"],1,"C'est l'un des déséquilibres qui répond le mieux au mode de vie."]]},
 {t:"L'indice HOMA : comprendre l'insulinorésistance",mi:"Si votre dernier bilan comporte glycémie ET insuline à jeun, calculez votre HOMA-IR : 🧮 (glycémie en mmol/L × insuline en µUI/mL) ÷ 22,5. (Pour convertir : g/L × 5,55 = mmol/L.) Notez le résultat et sa date — puis discutez-en avec votre médecin.",p:[
  ["👋 Introduction","Comment savoir si vos cellules écoutent encore l'insuline ? Il existe un indice simple, calculé à partir de deux analyses de routine : le HOMA-IR.\nC'est l'un des meilleurs marqueurs de suivi de la santé métabolique — et l'un des plus motivants, car il s'améliore souvent en quelques mois de bonnes habitudes.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre ce qu'est le HOMA-IR et comment il se calcule ;\n✅ interpréter votre résultat ;\n✅ connaître les limites de cet indice ;\n✅ améliorer votre sensibilité à l'insuline."],
  ["🧮 Le calcul — et l'interprétation","Le HOMA-IR (Homeostasis Model Assessment of Insulin Resistance) combine glycémie et insuline À JEUN :\n📐 HOMA-IR = (glycémie [mmol/L] × insuline [µUI/mL]) ÷ 22,5\n(rappel : glycémie en g/L × 5,55 = mmol/L)\n\nRepères d'interprétation usuels :\n🟢 < 2 : sensibilité à l'insuline correcte ;\n🟡 2 à 3 : résistance débutante — le moment idéal pour agir ;\n🔴 > 3 : résistance installée — franche, mais réversible avec le mode de vie.\nExemple : glycémie 1,00 g/L (5,55 mmol/L) et insuline 12 µUI/mL → HOMA = (5,55 × 12) ÷ 22,5 ≈ 2,96 : résistance débutante malgré une glycémie « parfaite ».","m7c3b"],
  ["⚠️ Ce qu'il indique — et ses limites","Ce que le HOMA raconte : le niveau d'EFFORT que fournit votre pancréas pour maintenir votre glycémie normale. Un HOMA qui monte = un pancréas qui compense de plus en plus.\nC'est un excellent marqueur PRÉCOCE (des années avant le diabète) et un formidable outil de SUIVI de vos progrès.\n\nSes limites, à connaître :\n1️⃣ il repose sur une seule mesure à jeun — or l'insuline fluctue : une valeur isolée peut être trompeuse ;\n2️⃣ les repères varient selon les laboratoires et les populations ;\n3️⃣ il est moins fiable chez les personnes traitées par insuline ou dont le pancréas est très fatigué ;\n4️⃣ ce n'est PAS un outil de diagnostic officiel, mais un indicateur d'orientation et de suivi.\nComme toujours : interprétation AVEC votre médecin.","m7c3c"],
  ["🌱 Améliorer sa sensibilité à l'insuline","La résistance à l'insuline est l'un des déséquilibres qui répond le MIEUX aux habitudes de vie :\n🥗 réduire sucres, féculents raffinés et produits ultra-transformés — moins de sollicitation = pancréas soulagé ;\n🚶 marcher après les repas — les muscles captent le glucose SANS insuline pendant l'effort ;\n💪 renforcer ses muscles — plus de masse musculaire = plus de « portes d'entrée » pour le glucose ;\n📉 perdre de la graisse viscérale — elle entretient la résistance (Module 7) ;\n😴 dormir 7-9 h — une seule nuit courte dégrade déjà la sensibilité ;\n🌬️ gérer le stress — le cortisol travaille contre vous.\nRésultats souvent mesurables sur le HOMA en 3 à 6 mois.\n\n💡 Astuce Keto-Essenciel : suivez votre HOMA une à deux fois par an, toujours dans le même laboratoire. Le voir passer de 3,5 à 2,2 est l'une des récompenses les plus concrètes de vos efforts — bien avant la balance parfois.","m7c3d"],
  ["📝 À retenir","📝 À retenir :\n✔ HOMA-IR = (glycémie mmol/L × insuline µUI/mL) ÷ 22,5 ;\n✔ < 2 correct · 2-3 résistance débutante · > 3 résistance installée ;\n✔ il détecte la résistance des années avant le diabète ;\n✔ ses limites : mesure unique, repères variables, non valable sous insuline ;\n✔ mode de vie = amélioration souvent visible en 3-6 mois.\n\n🏅 Badge à débloquer en validant le quiz : « Je décode mon HOMA »"]],
  q:[["Comment se calcule le HOMA-IR ?",["(Glycémie mmol/L × insuline µUI/mL) ÷ 22,5","Poids ÷ taille","Glycémie × âge"],0,"Deux analyses à jeun suffisent : glycémie et insulinémie."],
     ["Un HOMA-IR > 3 indique…",["Une résistance à l'insuline installée","Une hydratation parfaite","Un manque de sel"],0,"Franche, mais réversible avec le mode de vie."],
     ["Quel est l'intérêt majeur du HOMA ?",["Détecter la résistance à l'insuline des années avant le diabète","Mesurer la vitamine C","Remplacer l'HbA1c"],0,"C'est un marqueur précoce et un excellent outil de suivi des progrès."],
     ["Quelle est une limite du HOMA-IR ?",["Il repose sur une mesure unique et est moins fiable sous traitement par insuline","Il est trop précis","Il n'a aucune limite"],0,"Indicateur d'orientation, pas de diagnostic : interprétation avec le médecin."],
     ["Qu'est-ce qui améliore la sensibilité à l'insuline ?",["Moins de sucres, marche après les repas, muscle, sommeil","Plus de sodas","Rester assis"],0,"Résultats souvent mesurables sur le HOMA en 3 à 6 mois."]]},
 {t:"Les triglycérides, le HDL et le LDL",mi:"Sur votre dernier bilan, calculez votre rapport triglycérides ÷ HDL (dans la même unité) : 🎯 en dessous de 2, votre profil métabolique est rassurant. Notez ce chiffre et suivez-le à chaque bilan — puis commentez-le avec votre médecin.",p:[
  ["👋 Introduction","« Vous avez du cholestérol. » Cette phrase inquiète des millions de personnes… souvent à tort, parfois à raison.\nLe bilan lipidique est plus subtil qu'un seul chiffre : triglycérides, HDL, LDL racontent ensemble une histoire — celle de votre métabolisme.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle des triglycérides ;\n✅ distinguer les types de cholestérol (HDL, LDL) ;\n✅ comprendre pourquoi le LDL seul ne suffit pas ;\n✅ lire votre profil lipidique global dans son contexte."],
  ["🧈 Les triglycérides : le marqueur du sucre","Les triglycérides sont la forme de transport et de stockage des graisses. Surprise : ils sont surtout fabriqués par le foie… à partir des SUCRES en excès (fructose en tête).\nObjectif usuel : < 1,50 g/L.\nDes triglycérides élevés signalent souvent : excès de sucres et d'alcool, résistance à l'insuline, foie qui transforme à plein régime.\nC'est l'un des marqueurs qui s'améliore le PLUS vite avec une alimentation pauvre en glucides — souvent en quelques semaines.","m7c4b"],
  ["🚛 HDL et LDL : les transporteurs","Le cholestérol lui-même est indispensable (membranes, hormones, vitamine D). Ce que le bilan mesure, ce sont ses TRANSPORTEURS :\n🟢 le HDL — « l'éboueur » : il ramène le cholestérol excédentaire vers le foie. Plus il est haut, mieux c'est (> 0,40 g/L homme, > 0,50 g/L femme). Il monte avec l'activité physique, les bonnes graisses et la baisse des sucres ;\n🟠 le LDL — « le livreur » : il distribue le cholestérol aux cellules. C'est lui qu'on surnomme « mauvais cholestérol », mais la réalité est plus nuancée : il existe des LDL grosses et légères (peu préoccupantes) et des LDL petites et denses (plus athérogènes). Un profil triglycérides bas + HDL haut oriente vers des LDL de bonne qualité.","m7c4c"],
  ["🧩 Lire le profil GLOBAL — pas un chiffre isolé","Pourquoi ne pas se focaliser sur le LDL seul :\n1️⃣ le LDL peut augmenter légèrement chez certaines personnes en alimentation cétogène, alors même que triglycérides, HDL, glycémie et tour de taille s'améliorent — le tableau GLOBAL compte ;\n2️⃣ le rapport TRIGLYCÉRIDES ÷ HDL est un excellent reflet de la résistance à l'insuline et de la qualité des particules : visez < 2 ;\n3️⃣ le contexte clinique est déterminant : âge, tension, tabac, diabète, antécédents familiaux… C'est ce RISQUE GLOBAL que votre médecin évalue, pas un chiffre isolé.\n⚠️ Si vous prenez un traitement hypolipémiant (statine…), ne le modifiez JAMAIS seul : toute décision se prend avec votre médecin.\n\n💡 Astuce Keto-Essenciel : à chaque bilan, notez 3 chiffres : triglycérides, HDL, et leur rapport. Leur évolution raconte votre santé métabolique mieux que le cholestérol total.","m7c4d"],
  ["📝 À retenir","📝 À retenir :\n✔ triglycérides élevés = souvent trop de sucres (objectif < 1,50 g/L) ;\n✔ HDL haut = protecteur ; il monte avec l'exercice et la baisse des sucres ;\n✔ le LDL seul ne suffit pas : qualité des particules et contexte comptent ;\n✔ rapport triglycérides/HDL < 2 = excellent signe métabolique ;\n✔ jamais de modification de traitement sans le médecin.\n\n🏅 Badge à débloquer en validant le quiz : « Je lis mon bilan lipidique »"]],
  q:[["Les triglycérides sont surtout fabriqués à partir…",["Des sucres en excès (fructose en tête)","Du gras de l'avocat","De l'eau"],0,"C'est pourquoi ils chutent souvent vite en alimentation pauvre en glucides."],
     ["Quel est le rôle du HDL ?",["Ramener le cholestérol excédentaire vers le foie (protecteur)","Boucher les artères","Transporter l'oxygène"],0,"« L'éboueur » : plus il est haut, mieux c'est."],
     ["Pourquoi ne pas se focaliser sur le LDL seul ?",["La qualité des particules et le profil global comptent davantage","Le LDL n'existe pas","Il est toujours parfait"],0,"Triglycérides bas + HDL haut orientent vers des LDL de bonne qualité."],
     ["Quel rapport reflète bien la résistance à l'insuline ?",["Triglycérides ÷ HDL (viser < 2)","Poids ÷ pointure","LDL ÷ âge"],0,"Un rapport < 2 est un excellent signe métabolique."],
     ["Que faire si vous prenez une statine et que vos analyses s'améliorent ?",["Arrêter le traitement seul","En discuter avec votre médecin, sans jamais modifier seul"],1,"Toute décision sur un traitement se prend avec le médecin."]]},
 {t:"La CRP et l'inflammation",mi:"Repérez votre CRP (ou CRP-us) sur votre dernier bilan. 🔥 Choisissez ensuite UNE habitude anti-inflammatoire à renforcer cette semaine : 🐟 poisson gras 2 fois, 😴 coucher à heure fixe, ou 🚶 30 minutes de marche quotidienne.",p:[
  ["👋 Introduction","L'inflammation est la réponse normale du corps à une agression : utile et brève quand vous vous blessez… problématique quand elle devient PERMANENTE et silencieuse.\nCette inflammation chronique « de bas grade » accompagne le surpoids, le diabète et le risque cardiovasculaire. Et il existe une analyse pour la mesurer : la CRP.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre ce qu'est la protéine C-réactive (CRP) ;\n✅ connaître les causes possibles d'une élévation ;\n✅ comprendre le lien inflammation chronique ↔ santé métabolique ;\n✅ adopter les habitudes qui la réduisent."],
  ["🔬 La CRP : le thermomètre de l'inflammation","La CRP (protéine C-réactive) est fabriquée par le foie en réponse à une inflammation. Deux versions au laboratoire :\n📌 la CRP STANDARD — détecte les inflammations franches : infection, blessure, poussée inflammatoire. Elle peut monter très haut (dizaines ou centaines de mg/L) puis redescendre ;\n📌 la CRP ULTRASENSIBLE (CRP-us) — détecte l'inflammation CHRONIQUE de bas grade, invisible autrement. Repères usuels :\n🟢 < 1 mg/L : excellent ;\n🟡 1 à 3 mg/L : moyen ;\n🔴 > 3 mg/L : inflammation chronique probable (si pas d'infection en cours).\n⚠️ Un rhume, une blessure ou une infection dentaire suffisent à fausser la mesure : une CRP élevée se recontrôle à distance de tout épisode aigu.","m7c5b"],
  ["🔗 Inflammation et santé métabolique : le cercle vicieux","Pourquoi la CRP intéresse tant la santé métabolique :\n🍩 la graisse viscérale LIBÈRE en continu des substances inflammatoires — plus elle est présente, plus l'inflammation monte ;\n📉 l'inflammation AGGRAVE la résistance à l'insuline — qui favorise à son tour le stockage abdominal : le cercle vicieux est bouclé ;\n❤️ l'inflammation chronique participe à l'athérosclérose et au risque cardiovasculaire ;\n🫁 elle accompagne souvent le foie gras.\nBonne nouvelle : ce cercle tourne aussi DANS L'AUTRE SENS — perdre de la graisse viscérale fait baisser l'inflammation, qui améliore la sensibilité à l'insuline, qui facilite le déstockage…","m7c5c"],
  ["🌿 Réduire l'inflammation par le mode de vie","Les habitudes anti-inflammatoires les mieux établies :\n🍬 réduire sucres et produits ultra-transformés — première source d'inflammation alimentaire ;\n🐟 des oméga-3 régulièrement : poissons gras (sardines, maquereaux, saumon) 2-3 fois par semaine ;\n🫒 des graisses de qualité : huile d'olive, avocat, oléagineux ;\n🥦 des légumes variés et colorés (polyphénols, fibres) ;\n📉 perdre de la graisse viscérale — l'action la plus puissante ;\n😴 dormir 7-9 h — le manque de sommeil est inflammatoire ;\n🚶 bouger régulièrement, en modéré (le surentraînement, lui, enflamme) ;\n🚭 et bien sûr : pas de tabac, alcool très modéré.\nEn clair : tout ce parcours Keto-Essenciel travaille déjà pour votre CRP.\n\n💡 Astuce Keto-Essenciel : si votre CRP-us est élevée sans cause évidente, pensez aussi aux « inflammations oubliées » : dents et gencives (une gingivite chronique suffit !), sinusite… Parlez-en à votre médecin et à votre dentiste.","m7c5d"],
  ["📝 À retenir","📝 À retenir :\n✔ la CRP-us mesure l'inflammation chronique silencieuse (< 1 mg/L = excellent) ;\n✔ une infection passagère fausse la mesure : recontrôler à distance ;\n✔ graisse viscérale ↔ inflammation ↔ résistance à l'insuline : un cercle qui tourne dans les deux sens ;\n✔ alimentation, sommeil, mouvement et perte de graisse viscérale la font baisser ;\n✔ pensez aux inflammations cachées (dents, sinus…).\n\n🏅 Badge à débloquer en validant le quiz : « Je surveille mon inflammation »"]],
  q:[["Que mesure la CRP ultrasensible ?",["L'inflammation chronique de bas grade","La quantité de fer","Le taux de vitamine C"],0,"Elle révèle l'inflammation silencieuse liée au surpoids et au diabète."],
     ["Quel est le repère d'une CRP-us excellente ?",["< 1 mg/L","> 50 mg/L","Exactement 10 mg/L"],0,"1-3 = moyen ; > 3 = inflammation chronique probable (hors infection)."],
     ["Un rhume peut-il fausser la CRP ?",["Oui : toute infection aiguë l'élève temporairement","Non, jamais"],0,"Une CRP élevée se recontrôle à distance de tout épisode aigu."],
     ["Quel lien existe entre graisse viscérale et inflammation ?",["La graisse viscérale libère des substances inflammatoires en continu","Aucun lien","La graisse viscérale est anti-inflammatoire"],0,"C'est un cercle vicieux… qui tourne aussi dans le bon sens quand elle fond."],
     ["Qu'est-ce qui fait baisser l'inflammation chronique ?",["Moins de sucre, oméga-3, sommeil, activité modérée et perte de graisse viscérale","Plus de sodas","Veiller toute la nuit"],0,"Tout le parcours Keto-Essenciel travaille déjà pour votre CRP."]]},
 {t:"Le foie : un acteur majeur du métabolisme",mi:"Repérez ALAT, ASAT et GGT sur votre dernier bilan. 🫁 Puis offrez un geste à votre foie cette semaine : remplacez les jus de fruits et sodas par de l'eau ou une infusion — le fructose liquide est son premier ennemi.",p:[
  ["👋 Introduction","On parle beaucoup du pancréas dans le diabète… et pas assez du FOIE. Pourtant, cet organe discret est au cœur de votre métabolisme : il stocke, transforme, fabrique, détoxifie — plus de 500 fonctions !\nEt chez la majorité des personnes diabétiques de type 2, il souffre en silence d'un excès de graisse : la stéatose.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle métabolique du foie ;\n✅ lire les enzymes hépatiques (ALAT, ASAT, GGT) ;\n✅ comprendre la stéatose hépatique (foie gras non alcoolique) ;\n✅ adopter les habitudes qui soutiennent votre foie."],
  ["🫁 Le foie, chef d'orchestre métabolique","Parmi ses rôles clés :\n🍬 il STOCKE le glucose (glycogène) et le relâche entre les repas — c'est lui qui fait monter la glycémie à jeun quand il est déréglé ;\n🧈 il FABRIQUE les triglycérides (à partir des sucres en excès !) et le cholestérol ;\n🧹 il DÉTOXIFIE : médicaments, alcool, déchets ;\n🧪 il produit des protéines essentielles (dont la CRP du chapitre précédent).\nQuand le foie s'engorge de graisse, TOUTES ces fonctions se dérèglent — à commencer par la régulation de la glycémie.","m7c6b"],
  ["🔬 ALAT, ASAT, GGT : les enzymes qui parlent","Ces enzymes vivent normalement DANS les cellules du foie. Quand celles-ci souffrent, elles fuient dans le sang :\n📌 ALAT — la plus spécifique du foie ; élevée, elle évoque souvent une stéatose ;\n📌 ASAT — présente aussi dans les muscles et le cœur (un gros effort sportif peut l'élever !) ;\n📌 GGT — sensible à l'alcool, à certains médicaments et à la surcharge graisseuse du foie.\nDes valeurs modérément élevées chez une personne en surpoids abdominal orientent souvent vers la STÉATOSE : un foie qui stocke trop de graisse. La cause n°1 n'est pas le gras alimentaire… mais le SUCRE, et surtout le FRUCTOSE (sodas, jus de fruits), que le foie transforme directement en graisse.\nLa stéatose est très fréquente, silencieuse, et LONGTEMPS RÉVERSIBLE.","m7c6c"],
  ["🌿 Prendre soin de son foie","Le foie est l'organe de la seconde chance : il se régénère remarquablement quand on le soulage.\n🥤 supprimer les sucres LIQUIDES en priorité : sodas, jus (même « pur jus »), sirops — le fructose liquide va droit au foie ;\n🍬 réduire sucres et produits ultra-transformés ;\n🍷 alcool : modération stricte, voire pause de quelques semaines (le foie vous dira merci sur la GGT) ;\n📉 perdre de la graisse viscérale — perdre 5 à 10 % de son poids peut faire fondre visiblement la graisse du foie ;\n🚶 bouger régulièrement — l'activité physique dégraisse le foie même sans perte de poids ;\n☕ bonne nouvelle : le café (non sucré !) est associé à un effet plutôt protecteur.\nEn alimentation pauvre en sucres, les enzymes hépatiques s'améliorent souvent en 2 à 6 mois.\n\n💡 Astuce Keto-Essenciel : si vos enzymes sont élevées, votre médecin peut proposer une échographie ou un score de fibrose (FIB-4) pour préciser l'état du foie. La stéatose détectée tôt se corrige — c'est un rendez-vous à ne pas manquer.","m7c6d"],
  ["📝 À retenir","📝 À retenir :\n✔ le foie régule glycémie, lipides et détoxification ;\n✔ ALAT, ASAT, GGT élevées = un foie qui souffre, souvent de stéatose ;\n✔ cause n°1 du foie gras : le sucre, surtout le fructose liquide ;\n✔ la stéatose est fréquente, silencieuse… et longtemps réversible ;\n✔ moins de sucres + mouvement + perte de graisse viscérale = un foie qui se régénère en quelques mois.\n\n🏅 Badge à débloquer en validant le quiz : « Je prends soin de mon foie »"]],
  q:[["Quelle est la cause n°1 du foie gras non alcoolique ?",["Le sucre et surtout le fructose (sodas, jus)","Les épinards","L'eau minérale"],0,"Le foie transforme l'excès de fructose directement en graisse."],
     ["Que signalent des ALAT/ASAT/GGT élevées ?",["Des cellules du foie qui souffrent","Un excès de vitamine C","Une bonne santé du foie"],0,"Ces enzymes fuient dans le sang quand le foie est agressé."],
     ["La stéatose hépatique est-elle réversible ?",["Non, jamais","Oui, longtemps réversible avec le mode de vie"],1,"Le foie se régénère remarquablement quand on le soulage."],
     ["Quelle boisson supprimer en priorité pour le foie ?",["Les sodas et jus de fruits (fructose liquide)","L'eau","Les infusions"],0,"Le fructose liquide va droit au foie, sans aucun frein."],
     ["Une ASAT isolément élevée peut-elle venir d'autre chose que le foie ?",["Oui : muscles et cœur en contiennent aussi (gros effort sportif…)","Non, impossible"],0,"D'où l'importance du contexte — et de l'interprétation médicale."]]},
 {t:"Les reins : créatinine et fonction rénale",mi:"Repérez votre créatinine et votre DFGe sur votre dernier bilan. 💧 Cette semaine, prenez soin de vos reins simplement : hydratez-vous régulièrement et vérifiez avec votre médecin que votre albuminurie a bien été contrôlée cette année.",p:[
  ["👋 Introduction","Vos reins filtrent environ 180 litres de sang par jour — silencieusement, sans jamais se plaindre. C'est leur force… et leur faiblesse : quand ils souffrent, ils ne préviennent pas.\nLe diabète mal équilibré est la PREMIÈRE cause d'insuffisance rénale : le suivi biologique des reins est donc un pilier de votre bilan.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle des reins ;\n✅ lire la créatinine et le DFGe ;\n✅ comprendre l'albuminurie ;\n✅ savoir pourquoi ce suivi est crucial en cas de diabète."],
  ["💧 Le rôle des reins — et la créatinine","Les reins filtrent le sang en continu : ils éliminent les déchets, régulent l'eau, les minéraux (sodium, potassium…) et la tension artérielle, et participent à la fabrication des globules rouges.\n📌 LA CRÉATININE est un déchet musculaire éliminé par les reins. Si les reins filtrent moins bien, elle s'accumule dans le sang : c'est le marqueur de base.\nMais attention : elle dépend aussi de la masse musculaire (une personne très musclée a une créatinine naturellement plus haute ; une personne âgée menue, plus basse). D'où l'intérêt d'un indicateur plus fin…","m7c7b"],
  ["📐 Le DFGe : le vrai chiffre à suivre","Le DFGe (Débit de Filtration Glomérulaire estimé) traduit la créatinine en capacité réelle de filtration, en tenant compte de l'âge et du sexe. Il s'exprime en mL/min/1,73 m² :\n🟢 ≥ 90 : fonction rénale normale ;\n🟡 60 à 89 : légèrement diminuée (fréquent avec l'âge, à surveiller) ;\n🟠 30 à 59 : insuffisance rénale modérée — suivi rapproché, adaptation éventuelle des traitements ;\n🔴 < 30 : insuffisance sévère — prise en charge spécialisée.\n📌 L'ALBUMINURIE (recherche d'albumine dans les urines, souvent en rapport albumine/créatinine) est le radar PRÉCOCE : elle détecte une souffrance des filtres rénaux des ANNÉES avant que le DFGe ne baisse. Chez les personnes diabétiques, elle se contrôle en général UNE FOIS PAR AN.","m7c7c"],
  ["🛡️ Protéger ses reins au quotidien","Pourquoi ce suivi est vital en cas de diabète : l'excès chronique de glucose abîme les minuscules vaisseaux des filtres rénaux — silencieusement. Détectée tôt (albuminurie), cette souffrance peut être freinée, voire stabilisée.\nLes bons réflexes :\n🩸 garder une glycémie et une HbA1c bien équilibrées — la protection n°1 ;\n💓 surveiller la tension artérielle (l'hypertension abîme aussi les reins) ;\n💧 s'hydrater régulièrement ;\n💊 prudence avec les anti-inflammatoires (ibuprofène & co) en automédication répétée — toxiques pour des reins fragiles ; demandez toujours conseil ;\n🚭 pas de tabac.\n📌 Et les protéines ? Une alimentation riche en protéines n'abîme PAS des reins SAINS. En revanche, en cas de maladie rénale existante, l'apport en protéines doit être ajusté AVEC le médecin ou le néphrologue.\n\n💡 Astuce Keto-Essenciel : notez chaque année vos trois chiffres rénaux — créatinine, DFGe, albuminurie. Trois valeurs stables = des reins qui vont bien ; une dérive = un signal précoce que votre médecin saura exploiter.","m7c7d"],
  ["📝 À retenir","📝 À retenir :\n✔ la créatinine dépend des reins… et de la masse musculaire ;\n✔ le DFGe est le vrai indicateur de la filtration (≥ 90 = normal) ;\n✔ l'albuminurie détecte la souffrance rénale des années à l'avance — contrôle annuel en cas de diabète ;\n✔ glycémie équilibrée + tension surveillée = la meilleure protection ;\n✔ prudence avec les anti-inflammatoires en automédication ; protéines à ajuster seulement si maladie rénale existante.\n\n🏅 Badge à débloquer en validant le quiz : « Je protège mes reins »"]],
  q:[["Qu'est-ce que la créatinine ?",["Un déchet musculaire éliminé par les reins","Une vitamine","Un sucre"],0,"Si les reins filtrent moins, elle s'accumule — mais elle dépend aussi de la masse musculaire."],
     ["Que mesure le DFGe ?",["La capacité réelle de filtration des reins","Le taux de fer","La tension"],0,"≥ 90 = normal ; c'est le vrai chiffre à suivre, plus fin que la créatinine seule."],
     ["Quel est l'intérêt de l'albuminurie ?",["Détecter une souffrance rénale des années avant la baisse du DFGe","Mesurer l'hydratation","Aucun"],0,"C'est le radar précoce — contrôle annuel recommandé en cas de diabète."],
     ["Pourquoi le suivi rénal est-il crucial en cas de diabète ?",["Le diabète mal équilibré est la 1ère cause d'insuffisance rénale","Par simple curiosité","Les reins ne risquent rien"],0,"L'excès de glucose abîme silencieusement les filtres rénaux."],
     ["Une alimentation riche en protéines abîme-t-elle des reins sains ?",["Oui, toujours","Non — mais en cas de maladie rénale existante, l'apport se règle avec le médecin"],1,"La nuance est essentielle : reins sains ≠ reins malades."]]},
 {t:"Les autres analyses utiles à connaître",mi:"Au prochain bilan, demandez à votre médecin si un dosage de la vitamine D — et de la vitamine B12 si vous prenez de la metformine — serait utile dans votre situation. 📄 Notez les valeurs si vous les avez déjà.",p:[
  ["👋 Introduction","Au-delà du trio glycémie-lipides-foie, quelques analyses complémentaires méritent d'être connues : elles éclairent l'énergie, l'humeur, les crampes, la fatigue… et certaines concernent particulièrement les personnes sous metformine.\nToutes ne sont pas systématiques : votre médecin les prescrit SELON votre situation.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre l'acide urique, la vitamine D et le magnésium ;\n✅ comprendre la ferritine et la vitamine B12 ;\n✅ savoir quelles analyses peuvent être proposées selon les cas."],
  ["🧪 Acide urique et vitamine D","📌 L'ACIDE URIQUE — déchet issu de la dégradation des purines, éliminé par les reins. Élevé, il peut provoquer la goutte et accompagne souvent le syndrome métabolique (il monte avec… le fructose, encore lui !). À savoir : il peut s'élever TRANSITOIREMENT dans les premières semaines d'une alimentation cétogène, avant de revenir à la normale — buvez suffisamment et signalez tout antécédent de goutte à votre médecin.\n📌 LA VITAMINE D — essentielle aux os, aux muscles et à l'immunité ; un statut bas est très fréquent, surtout l'hiver, et souvent associé aux troubles métaboliques. Le dosage n'est remboursé que dans certaines situations ; la supplémentation éventuelle se décide avec le médecin. Le soleil (15-20 min/jour) et les poissons gras restent vos meilleures sources.","m7c8b"],
  ["⚡ Magnésium et ferritine","📌 LE MAGNÉSIUM — impliqué dans plus de 300 réactions, dont la régulation de la glycémie et de la tension. Signes évocateurs d'un manque : crampes, paupière qui saute, fatigue, irritabilité. Subtilité : le magnésium SANGUIN reflète mal les réserves (il est surtout dans les cellules et les os) — un dosage normal n'exclut pas un déficit. Sources : oléagineux, chocolat noir, légumes verts, eaux riches en magnésium.\n📌 LA FERRITINE — le stock de fer. Basse = réserves épuisées (fatigue, essoufflement, cheveux qui tombent) ; élevée = attention, elle monte AUSSI avec l'inflammation et la surcharge du foie — une ferritine haute avec une CRP haute est souvent un signe d'inflammation, pas d'excès de fer. Interprétation : toujours avec le médecin.","m7c8c"],
  ["💊 La vitamine B12 — cruciale sous metformine","La vitamine B12 est indispensable aux nerfs et aux globules rouges. Or, la METFORMINE — le traitement le plus prescrit du diabète de type 2 — peut RÉDUIRE son absorption au fil des années.\nUn déficit en B12 peut provoquer : fatigue, fourmillements dans les pieds et les mains, troubles de la mémoire, anémie… des symptômes parfois confondus avec une neuropathie diabétique !\n➡️ Si vous prenez de la metformine depuis plusieurs années, un dosage régulier de la B12 est recommandé — parlez-en à votre médecin.\n\n📋 Selon les situations, votre médecin peut aussi proposer : TSH (thyroïde — elle influence poids et énergie), ionogramme (sodium, potassium), NFS (numération sanguine), bilan hormonal… Chaque analyse a son indication : inutile de tout doser « pour voir ».\n\n💡 Astuce Keto-Essenciel : plutôt que de multiplier les compléments à l'aveugle, appuyez-vous sur des DOSAGES et l'avis de votre médecin : supplémenter un vrai déficit change la vie, supplémenter à l'aveugle enrichit surtout les fabricants.","m7c8d"],
  ["📝 À retenir","📝 À retenir :\n✔ acide urique : marqueur du syndrome métabolique, sensible au fructose (hausse transitoire possible en début de keto) ;\n✔ vitamine D : statut bas très fréquent — soleil, poissons gras, supplémentation sur avis médical ;\n✔ magnésium : le dosage sanguin reflète mal les réserves ;\n✔ ferritine haute ≠ toujours excès de fer : penser à l'inflammation ;\n✔ metformine au long cours → faire surveiller la vitamine B12.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais les analyses utiles »"]],
  q:[["Avec quoi l'acide urique a-t-il tendance à monter ?",["Le fructose et le syndrome métabolique","L'eau plate","La marche"],0,"Encore le fructose ! Une hausse transitoire est aussi possible en début de keto."],
     ["Pourquoi surveiller la vitamine B12 sous metformine ?",["La metformine peut réduire son absorption au fil des années","La B12 fait monter la glycémie","Aucun rapport"],0,"Un déficit peut mimer une neuropathie diabétique : dosage régulier recommandé."],
     ["Le magnésium sanguin reflète-t-il bien les réserves ?",["Oui parfaitement","Non : il est surtout stocké dans les cellules et les os"],1,"Un dosage normal n'exclut pas un déficit — les signes cliniques comptent."],
     ["Une ferritine élevée signifie-t-elle toujours un excès de fer ?",["Oui","Non : elle monte aussi avec l'inflammation et la surcharge du foie"],1,"Ferritine haute + CRP haute = souvent de l'inflammation, pas du fer."],
     ["Faut-il se supplémenter « à l'aveugle » ?",["Oui, au cas où","Non : dosages + avis médical d'abord"],1,"Corriger un vrai déficit change la vie ; supplémenter au hasard, rarement."]]},
 {t:"Lire son bilan biologique comme un tableau de bord",mi:"Préparez votre prochaine consultation : 📋 créez votre tableau de suivi (HbA1c, glycémie, triglycérides/HDL, ALAT, DFGe, CRP) avec vos 2-3 derniers bilans, et notez 3 questions à poser à votre médecin. Vous verrez : la consultation change de dimension.",p:[
  ["👋 Introduction","Vous savez maintenant lire chaque analyse séparément. Dernière étape — la plus puissante : les lire ENSEMBLE, comme les cadrans d'un même tableau de bord.\nCar votre corps est un système : glycémie, insuline, lipides, foie, inflammation et reins se répondent en permanence. Et leur évolution AU FIL DU TEMPS raconte votre santé mieux que n'importe quel chiffre isolé.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ relier les analyses entre elles ;\n✅ suivre leurs évolutions dans le temps ;\n✅ préparer efficacement vos consultations ;\n✅ transformer vos résultats en moteur de motivation."],
  ["🔗 Tout est lié : lire les connexions","Quelques « constellations » typiques que vous savez maintenant décoder :\n📌 triglycérides élevés + HDL bas + tour de taille large + glycémie limite = le tableau classique de la RÉSISTANCE À L'INSULINE — souvent avec ALAT un peu hautes (stéatose) et CRP-us moyenne ;\n📌 HbA1c qui baisse + triglycérides qui chutent + GGT qui se normalise = votre foie se dégraisse et votre métabolisme guérit — même si le LDL bouge peu ;\n📌 ferritine haute + CRP haute = piste inflammatoire ;\n📌 fatigue + metformine ancienne = penser B12.\nUn seul chiffre inquiète ; un ENSEMBLE cohérent éclaire. C'est exactement ainsi que raisonne votre médecin.","m7c9b"],
  ["📈 Le suivi dans le temps — votre vraie richesse","Votre bilan d'aujourd'hui n'a de sens que comparé à ceux d'hier :\n📅 rassemblez vos analyses des dernières années (les laboratoires peuvent réimprimer l'historique) ;\n📊 construisez votre tableau de suivi : une ligne par date, une colonne par marqueur clé — HbA1c, glycémie à jeun, triglycérides, HDL, rapport TG/HDL, ALAT, GGT, DFGe, CRP-us ;\n🔍 regardez les TENDANCES : une HbA1c qui passe de 7,8 → 7,2 → 6,8 raconte une victoire que la valeur isolée « 6,8 » ne montre pas ;\n⚠️ même laboratoire si possible, mêmes conditions (à jeun), et à distance de toute infection.\nCe tableau, c'est le tableau de bord de votre santé — au même titre que votre poids ou votre tour de taille.","m7c9c"],
  ["🩺 Préparer ses consultations — et transformer l'essai","Une consultation se prépare comme un rendez-vous important :\n✔ apportez votre tableau de suivi (ou vos derniers bilans) ;\n✔ notez À L'AVANCE vos 3 questions prioritaires (« Mon objectif d'HbA1c est-il toujours adapté ? », « Faut-il doser la B12 ? », « Mon albuminurie a-t-elle été contrôlée cette année ? ») ;\n✔ signalez vos changements de mode de vie — ils peuvent justifier d'adapter un traitement (uniquement par le médecin !) ;\n✔ repartez avec des OBJECTIFS clairs et réalistes, fixés ensemble, pour le prochain bilan.\nEt surtout : utilisez vos résultats comme un moteur. Chaque marqueur qui s'améliore est la preuve BIOLOGIQUE que vos habitudes fonctionnent — la motivation la plus objective qui soit.\n\n💡 Astuce Keto-Essenciel : la veille de la consultation, surlignez sur votre bilan ce qui a monté, baissé, ou vous questionne. Cinq minutes de préparation = une consultation deux fois plus utile.","m7c9d"],
  ["📝 À retenir — et bravo pour ce module !","📝 À retenir :\n✔ les analyses se lisent ENSEMBLE : les constellations éclairent plus que les chiffres isolés ;\n✔ l'évolution dans le temps est votre vraie richesse — construisez votre tableau de suivi ;\n✔ une consultation préparée (tableau + 3 questions) vaut double ;\n✔ les objectifs se fixent AVEC l'équipe soignante ;\n✔ chaque marqueur amélioré est la preuve objective que vos habitudes fonctionnent.\n\n🎓 Dans ce Module 8, vous avez appris à : comprendre une prise de sang, maîtriser l'HbA1c, lire glycémie et insuline, décoder le HOMA, interpréter votre bilan lipidique, surveiller l'inflammation, prendre soin de votre foie et de vos reins, connaître les analyses complémentaires et lire votre bilan comme un tableau de bord.\n\n🏅 Après ce chapitre, le Quiz final du module (20 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge 🧪 « Je comprends mes analyses » et la compétence : « Je sais lire mon bilan biologique et en discuter avec mon équipe soignante »."]],
  q:[["Comment lire au mieux un bilan biologique ?",["Chaque chiffre isolément","Les analyses ensemble, en constellations, et leur évolution dans le temps"],1,"Un ensemble cohérent éclaire ; un chiffre isolé inquiète inutilement."],
     ["Que suggère le trio triglycérides hauts + HDL bas + tour de taille large ?",["Une résistance à l'insuline","Une carence en vitamine C","Rien"],0,"Le tableau classique du syndrome métabolique — souvent avec ALAT un peu hautes."],
     ["Quel est l'outil le plus précieux pour suivre sa santé métabolique ?",["Un tableau de suivi de ses marqueurs clés au fil des bilans","Une seule prise de sang tous les 10 ans","La mémoire"],0,"Les tendances racontent vos victoires mieux que les valeurs isolées."],
     ["Comment bien préparer une consultation médicale ?",["Arriver sans rien","Apporter son tableau de suivi et 3 questions notées à l'avance"],1,"Cinq minutes de préparation = une consultation deux fois plus utile."],
     ["Avec qui fixer ses objectifs biologiques ?",["Seul, d'après internet","Avec son équipe soignante"],1,"Des objectifs réalistes et personnalisés se décident ensemble."]]}
],fq:[
 ["À quoi sert un bilan biologique ?",["Dépister, suivre l'évolution et aider à adapter la prise en charge","Remplacer le médecin","À rien","À faire peur"],0,"Il détecte tôt les déséquilibres silencieux et mesure objectivement vos progrès."],
 ["Les valeurs de référence sont-elles identiques dans tous les laboratoires ?",["Oui","Non, elles varient selon les laboratoires et leurs méthodes"],1,"Comparez vos résultats aux références DU laboratoire — idéalement toujours le même."],
 ["Que reflète l'HbA1c ?",["La glycémie moyenne des 2-3 derniers mois","La glycémie de l'instant","Le taux de fer","L'hydratation"],0,"Le glucose se fixe sur l'hémoglobine des globules rouges (durée de vie ~120 jours)."],
 ["À partir de quelle HbA1c parle-t-on de diabète ?",["≥ 6,5 %","≥ 4 %","≥ 15 %","≥ 2 %"],0,"5,7-6,4 % = prédiabète ; ≥ 6,5 % = zone du diabète."],
 ["Un diabète est défini par une glycémie à jeun ≥…",["1,26 g/L à deux reprises","0,80 g/L","3 g/L","0,50 g/L"],0,"Le seuil diagnostique, confirmé sur deux prélèvements."],
 ["Une insuline à jeun élevée avec une glycémie normale signifie…",["Une résistance à l'insuline déjà installée","Que tout va bien","Un excès de sport","Une carence en fer"],0,"Le pancréas surcompense en silence : c'est le stade précoce à ne pas rater."],
 ["Comment se calcule le HOMA-IR ?",["(Glycémie mmol/L × insuline µUI/mL) ÷ 22,5","Poids ÷ taille","Glycémie × âge","HDL + LDL"],0,"Deux analyses à jeun suffisent."],
 ["Un HOMA-IR > 3 indique…",["Une résistance à l'insuline installée — réversible avec le mode de vie","Une hydratation parfaite","Un manque de sel","Une allergie"],0,"Franche, mais elle répond très bien aux habitudes de vie."],
 ["Les triglycérides sont surtout fabriqués à partir…",["Des sucres en excès (fructose en tête)","Du gras de l'avocat","De l'eau","Des protéines"],0,"C'est pourquoi ils chutent souvent vite en alimentation pauvre en glucides."],
 ["Quel rapport reflète bien la résistance à l'insuline ?",["Triglycérides ÷ HDL (viser < 2)","LDL ÷ âge","Poids ÷ pointure","CRP × 2"],0,"Un rapport < 2 est un excellent signe métabolique."],
 ["Pourquoi ne pas se focaliser sur le LDL seul ?",["La qualité des particules et le profil global comptent davantage","Le LDL n'existe pas","Il est toujours parfait","C'est le seul chiffre utile"],0,"Triglycérides bas + HDL haut orientent vers des particules peu préoccupantes."],
 ["Que mesure la CRP ultrasensible ?",["L'inflammation chronique de bas grade","Le fer","La vitamine C","Le calcium"],0,"< 1 mg/L = excellent ; > 3 = inflammation chronique probable (hors infection)."],
 ["Un rhume peut-il fausser la CRP ?",["Oui, toute infection aiguë l'élève temporairement","Non, jamais"],0,"Une CRP élevée se recontrôle à distance de tout épisode aigu."],
 ["Quelle est la cause n°1 du foie gras non alcoolique ?",["Le sucre et surtout le fructose (sodas, jus)","Les épinards","L'eau","Le poisson"],0,"Le foie transforme l'excès de fructose directement en graisse."],
 ["La stéatose hépatique est-elle réversible ?",["Oui, longtemps réversible avec le mode de vie","Non, jamais"],0,"Le foie se régénère remarquablement quand on le soulage — souvent en 2 à 6 mois."],
 ["Que mesure le DFGe ?",["La capacité de filtration des reins","La tension","Le fer","Le sommeil"],0,"≥ 90 = normal ; c'est le chiffre rénal à suivre, plus fin que la créatinine seule."],
 ["Pourquoi contrôler l'albuminurie chaque année en cas de diabète ?",["Elle détecte une souffrance rénale des années avant la baisse du DFGe","Pour mesurer l'hydratation","C'est inutile","Pour le plaisir"],0,"C'est le radar précoce des reins — le diabète est la 1ère cause d'insuffisance rénale."],
 ["Pourquoi surveiller la vitamine B12 sous metformine au long cours ?",["La metformine peut réduire son absorption","La B12 fait monter la glycémie","Aucun rapport","La B12 est dangereuse"],0,"Un déficit peut mimer une neuropathie diabétique : dosage régulier recommandé."],
 ["Une ferritine élevée signifie-t-elle toujours un excès de fer ?",["Non : elle monte aussi avec l'inflammation","Oui, toujours"],0,"Ferritine haute + CRP haute = souvent de l'inflammation, pas du fer."],
 ["Quelle est la meilleure façon d'utiliser ses analyses ?",["Les suivre dans le temps et préparer ses consultations avec son équipe soignante","Les interpréter seul et adapter ses traitements","Les jeter","Les ignorer"],0,"Tableau de suivi + 3 questions préparées = des consultations deux fois plus utiles."]
],bd:"🧪 Je comprends mes analyses",sk:["Lire une prise de sang dans son contexte","Suivre mon HbA1c et mes objectifs personnalisés","Comprendre glycémie, insuline et HOMA","Interpréter mon profil lipidique global","Surveiller mon inflammation (CRP)","Protéger mon foie et mes reins","Connaître les analyses complémentaires utiles","Préparer mes consultations comme un tableau de bord"]}'''

src = src[:i] + NEW + ',\n' + src[j+len(']},\n'):]
io.open(PATH, 'w', encoding='utf-8').write(src)
print('OK: Module 8 = 10 chapitres + quiz final')
