#!/usr/bin/env python3
# Module 10 : refonte "Les compléments alimentaires" (10 chapitres + quiz final)
import io, sys
PATH='/app/keto.html'; src=io.open(PATH,encoding='utf-8').read()
START='{t:"Les compléments alimentaires",e:"💊",d:"Ce qui peut aider — et ce qu\'il faut savoir avant.",ch:['
END=']},\n{t:"Les traitements"'
i=src.find(START); j=src.find(END,i)
if i<0 or j<0: print('ERREUR bornes M10',i,j); sys.exit(1)

DISC = "⚠️ Rappel : les compléments alimentaires ne remplacent jamais une alimentation équilibrée, un traitement médical ni le suivi par un professionnel de santé."

NEW = r'''{t:"Les compléments alimentaires : lesquels, pourquoi, dans quelles situations ?",e:"💊",d:"Comprendre le rôle, les indications potentielles, les limites et les précautions des principaux compléments — sans jamais remplacer alimentation, traitement ou suivi médical.",ch:[
 {t:"Les compléments alimentaires : utiles ou inutiles ?",mi:"Faites l'inventaire : 📦 listez les compléments que vous prenez (ou avez pris), et pour chacun notez : pourquoi ? conseillé par qui ? effet constaté ? Apportez cette liste à votre prochain rendez-vous médical.",p:[
  ["👋 Introduction","Rayons entiers, publicités prometteuses, conseils contradictoires… difficile d'y voir clair dans le monde des compléments alimentaires.\nCe module va vous donner une grille de lecture RAISONNÉE : ce qui peut aider, dans quelles situations, avec quelles limites et quelles précautions.\n⚠️ Règle fondatrice, valable pour tout le module : les compléments ne remplacent JAMAIS une alimentation équilibrée, un traitement médical ni le suivi par un professionnel de santé.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer médicament et complément alimentaire ;\n✅ savoir quand un complément peut être envisagé ;\n✅ éviter les erreurs fréquentes ;\n✅ prendre les bonnes précautions avant de commencer."],
  ["⚖️ Médicament vs complément : une différence majeure","💊 UN MÉDICAMENT : efficacité et sécurité démontrées par des essais cliniques, autorisation de mise sur le marché, dosage contrôlé, indications précises, pharmacovigilance.\n🌿 UN COMPLÉMENT ALIMENTAIRE : réglementé comme un ALIMENT — le fabricant n'a pas à prouver l'efficacité avant la vente. Qualité, dosage réel et pureté peuvent varier considérablement d'une marque à l'autre.\nConséquence : « naturel » ne veut dire ni « efficace » ni « sans danger ». Certaines plantes interagissent avec des traitements, certains dosages sont toxiques. Un complément se choisit donc avec la même prudence qu'un médicament… mais avec moins de garanties.","m9c0b"],
  ["🎯 Quand un complément peut-il être envisagé ?","Les situations LÉGITIMES :\n🩸 un DÉFICIT DOCUMENTÉ par une analyse (vitamine D basse, B12 basse sous metformine, ferritine effondrée…) : corriger un vrai manque change réellement les choses ;\n🥗 un apport alimentaire durablement insuffisant malgré les efforts (ex. : jamais de poisson gras → oméga-3 à discuter) ;\n💊 une situation particulière : traitement qui interfère avec un nutriment, grossesse, âge, régime très restrictif ;\n🩺 et TOUJOURS : après échange avec médecin ou pharmacien.\n\nLes ERREURS fréquentes :\n❌ supplémenter « au cas où », sans dosage ni avis ;\n❌ empiler 8 produits aux effets inconnus ensemble ;\n❌ remplacer l'assiette par des gélules ;\n❌ croire qu'« il n'y a rien à perdre » — interactions et surdosages existent ;\n❌ acheter au marketing plutôt qu'à la composition.","m9c0c"],
  ["🛡️ Qualité plutôt que quantité — et précautions de départ","Mieux vaut UN complément justifié, bien choisi et bien dosé que cinq produits « au hasard » :\n✔ un besoin identifié (symptômes + dosage sanguin quand c'est possible) ;\n✔ une forme bien assimilée et un dosage adapté (chapitre 9) ;\n✔ une durée définie, puis une RÉÉVALUATION : est-ce que ça change quelque chose de mesurable ?\n\nAvant de commencer, TOUJOURS :\n1️⃣ en parler à votre médecin ou pharmacien — indispensable si vous prenez des traitements (antidiabétiques, anticoagulants…), en cas d'insuffisance rénale ou hépatique, de grossesse ;\n2️⃣ signaler TOUS vos compléments aux soignants (beaucoup l'oublient en consultation !) ;\n3️⃣ introduire UN produit à la fois, pour identifier effets et éventuels troubles digestifs.\n\n💡 Astuce Keto-Essenciel : posez-vous toujours la question dans cet ordre : puis-je couvrir ce besoin par l'ASSIETTE ? Si oui, c'est presque toujours la meilleure option — plus complète, plus sûre, souvent moins chère.","m9c0d"],
  ["📝 À retenir","📝 À retenir :\n✔ un complément n'est pas un médicament : moins de preuves, moins de garanties ;\n✔ « naturel » ne veut dire ni efficace ni sans danger ;\n✔ un complément se justifie par un besoin identifié — idéalement documenté par un dosage ;\n✔ qualité, un produit à la fois, durée définie, réévaluation ;\n✔ toujours en parler à son médecin ou pharmacien.\n\n🏅 Badge à débloquer en validant le quiz : « J'ai les bons réflexes compléments »"]],
  q:[["Quelle est la grande différence entre médicament et complément ?",["Le médicament doit prouver efficacité et sécurité avant la vente, pas le complément","Aucune","Le complément est plus contrôlé"],0,"Le complément est réglementé comme un aliment — d'où l'importance de la prudence."],
     ["« Naturel » signifie-t-il « sans danger » ?",["Oui, toujours","Non : interactions et surdosages existent"],1,"Certaines plantes interagissent avec des traitements courants."],
     ["Quand un complément est-il le plus légitime ?",["Pour un déficit documenté par une analyse","Au cas où","Parce que la pub est belle"],0,"Corriger un vrai manque change les choses ; supplémenter à l'aveugle, rarement."],
     ["Vaut-il mieux…",["Un complément justifié et bien choisi","Huit produits empilés au hasard"],0,"Qualité plutôt que quantité — avec durée définie et réévaluation."],
     ["Que faire avant de commencer une supplémentation ?",["En parler à son médecin ou pharmacien et signaler tous ses compléments","Rien","La garder secrète"],0,"Indispensable en cas de traitements, d'insuffisance rénale ou de grossesse."]]},
 {t:"Le magnésium : le minéral de l'équilibre",mi:"Cette semaine, misez d'abord sur l'assiette : 🥦 ajoutez chaque jour une source de magnésium — amandes (30 g), épinards, chocolat noir 85 %, ou une eau riche en magnésium. Si crampes et fatigue persistent, parlez-en à votre médecin.",p:[
  ["👋 Introduction","Impliqué dans plus de 300 réactions de l'organisme — dont la régulation de la glycémie, de la tension et du système nerveux — le magnésium est probablement le minéral le plus pertinent à connaître en santé métabolique.\nEt les apports insuffisants sont fréquents, surtout en cas de diabète.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle du magnésium ;\n✅ repérer les signes d'un apport insuffisant ;\n✅ connaître les aliments riches en magnésium ;\n✅ savoir quand une supplémentation se discute, et avec quelles précautions."],
  ["⚡ Son rôle — et pourquoi il concerne le diabète","Le magnésium participe à : la production d'énergie, la contraction musculaire et nerveuse, la régulation du rythme cardiaque, de la tension… et à l'ACTION DE L'INSULINE : il est nécessaire au bon fonctionnement de ses récepteurs.\nParticularité du diabète : une glycémie élevée augmente l'élimination URINAIRE du magnésium — les personnes diabétiques ont donc souvent des réserves plus basses, ce qui peut à son tour peser sur la sensibilité à l'insuline. Un cercle discret mais réel.\nSignes évocateurs d'un manque : crampes, paupière qui saute (fasciculations), fatigue, irritabilité, sommeil léger, sensibilité au stress. ⚠️ Rappel du Module 8 : le magnésium SANGUIN reflète mal les réserves — les signes cliniques comptent autant que le dosage.","m9c1b"],
  ["🥦 L'assiette d'abord","Les meilleures sources alimentaires — parfaitement compatibles keto pour la plupart :\n🌰 oléagineux : amandes, noix du Brésil, noix de cajou (une poignée = un vrai apport) ;\n🍫 chocolat noir ≥ 85 % ;\n🥬 légumes verts feuillus : épinards, blettes (le magnésium est au cœur de la chlorophylle) ;\n🐟 poissons gras, fruits de mer ;\n🎃 graines de courge, de tournesol ;\n💧 eaux minérales riches en magnésium (lisez l'étiquette : certaines dépassent 100 mg/L).\nUne alimentation keto bien construite — légumes verts + oléagineux + poisson — couvre déjà une bonne partie des besoins.","m9c1c"],
  ["💊 Quand supplémenter — et les précautions","La supplémentation PEUT se discuter (avec médecin ou pharmacien) si : signes persistants malgré une alimentation riche en magnésium, diabète mal équilibré, crampes récurrentes, stress important, certains traitements (diurétiques, IPP au long cours…).\nÀ savoir :\n✔ les formes dites mieux tolérées (citrate, bisglycinate…) provoquent moins de troubles digestifs que l'oxyde ;\n✔ des doses trop élevées donnent surtout… de la diarrhée ;\n⚠️ PRÉCAUTION MAJEURE : en cas d'INSUFFISANCE RÉNALE, le magnésium s'accumule et peut devenir dangereux — supplémentation UNIQUEMENT sur avis médical ;\n⚠️ espacer la prise de certains médicaments (antibiotiques de type cyclines/quinolones, hormones thyroïdiennes…) : demandez au pharmacien.\n\n💡 Astuce Keto-Essenciel : commencez par 2 semaines « assiette + eau magnésienne » avant d'envisager une gélule. Beaucoup de signes s'améliorent déjà — et c'est la base la plus sûre.","m9c1d"],
  ["📝 À retenir","📝 À retenir :\n✔ le magnésium participe à l'action de l'insuline — et le diabète augmente ses pertes urinaires ;\n✔ crampes, fatigue, irritabilité, sommeil léger : des signes évocateurs ;\n✔ l'assiette d'abord : oléagineux, légumes verts, chocolat noir, eaux magnésiennes ;\n✔ supplémentation à discuter avec un professionnel — formes bien tolérées, doses raisonnables ;\n✔ insuffisance rénale = avis médical OBLIGATOIRE.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais le magnésium »"]],
  q:[["Pourquoi le magnésium intéresse-t-il particulièrement les personnes diabétiques ?",["Il participe à l'action de l'insuline et ses pertes urinaires augmentent avec la glycémie","Il fait monter la glycémie","Aucun rapport"],0,"Réserves plus basses → sensibilité à l'insuline qui peut en pâtir : un cercle discret."],
     ["Quels signes peuvent évoquer un manque de magnésium ?",["Crampes, paupière qui saute, fatigue, irritabilité","Cheveux qui poussent vite","Excellente humeur"],0,"Et rappel : le dosage sanguin reflète mal les réserves."],
     ["Quelles sont de bonnes sources alimentaires ?",["Amandes, épinards, chocolat noir, eaux riches en magnésium","Sodas","Bonbons"],0,"Une alimentation keto bien construite couvre déjà une bonne partie des besoins."],
     ["Quelle est la précaution majeure avec le magnésium ?",["En cas d'insuffisance rénale : avis médical obligatoire","Aucune","Ne pas en manger dans les aliments"],0,"Des reins qui filtrent mal peuvent laisser le magnésium s'accumuler dangereusement."],
     ["Que provoque surtout un excès de magnésium en gélules ?",["De la diarrhée","Des super-pouvoirs","Rien"],0,"Les formes citrate/bisglycinate sont généralement mieux tolérées que l'oxyde."]]},
 {t:"Les oméga-3 : des alliés pour le cœur et l'inflammation",mi:"Objectif de la semaine : 🐟 2 repas de poisson gras (sardines, maquereau, saumon) — les conserves comptent ! Si vous n'aimez vraiment pas le poisson, notez-le : c'est LA situation où une supplémentation se discute avec votre médecin.",p:[
  ["👋 Introduction","Parmi tous les nutriments étudiés en santé cardiovasculaire, les oméga-3 tiennent une place de choix — particulièrement pertinente en cas de diabète, où le risque cardiaque est augmenté.\nEncore faut-il savoir lesquels, d'où, et pour qui.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer ALA, EPA et DHA ;\n✅ comprendre leur rôle cardiovasculaire et anti-inflammatoire ;\n✅ connaître les sources alimentaires ;\n✅ savoir quand une supplémentation se discute, et les précautions."],
  ["🐟 ALA, EPA, DHA : trois lettres à connaître","Les oméga-3 sont des graisses polyinsaturées « essentielles » (le corps ne sait pas les fabriquer) :\n🌱 ALA — d'origine VÉGÉTALE (noix, graines de lin et de chia, colza). Utile, mais le corps ne le convertit qu'à HAUTEUR DE QUELQUES % en EPA/DHA : il ne remplace pas le poisson ;\n🐟 EPA — surtout MARIN : le plus étudié pour l'inflammation et les triglycérides ;\n🐟 DHA — surtout MARIN : structure du cerveau et de la rétine, santé cardiovasculaire.\nRôles étudiés : baisse des TRIGLYCÉRIDES (effet le mieux démontré), fluidité membranaire, modulation de l'inflammation, soutien du rythme cardiaque. En clair : un profil particulièrement intéressant pour le terrain métabolique.","m9c2b"],
  ["🍽️ Les sources — l'assiette encore d'abord","🎯 L'objectif simple : POISSON GRAS 2 à 3 FOIS PAR SEMAINE :\n🐟 sardines, maquereaux, harengs, anchois — petits poissons = moins de métaux lourds, prix mini, conserves pratiques ;\n🐟 saumon, truite ;\n🌱 en complément végétal : noix, graines de lin moulues, huile de colza (assaisonnement).\nCe rythme couvre les besoins de la plupart des gens — et il est déjà inscrit dans le cadre alimentaire Keto-Essenciel.\nBon à savoir : les oméga-3 s'oxydent à la chaleur — privilégiez cuissons douces, et conservez huiles de lin/colza au réfrigérateur.","m9c2c"],
  ["💊 La supplémentation : pour qui, avec quelles précautions ?","Elle PEUT se discuter si :\n🚫 vous ne mangez jamais (ou presque) de poisson gras ;\n🧈 triglycérides élevés persistants (des formes concentrées existent, parfois sur prescription) ;\n🩺 situations particulières évaluées par le médecin.\nBien choisir : teneur réelle en EPA+DHA (pas juste « huile de poisson »), fraîcheur (odeur rance = oxydé), qualité certifiée.\n\n⚠️ PRÉCAUTIONS :\n💉 à FORTES doses, les oméga-3 fluidifient le sang : prudence avec les ANTICOAGULANTS et antiagrégants — avis médical indispensable ;\n🩺 signaler la prise avant toute chirurgie ;\n🐟 allergie au poisson : formes à base d'algues (DHA/EPA végétal) en alternative.\n\n💡 Astuce Keto-Essenciel : la boîte de sardines est le « complément » d'oméga-3 le plus efficace du marché : EPA+DHA + protéines + calcium (avec les arêtes) + vitamine D, pour environ 2 €.","m9c2d"],
  ["📝 À retenir","📝 À retenir :\n✔ ALA (végétal) ne remplace pas EPA/DHA (marins) — conversion très faible ;\n✔ effet le mieux démontré : la baisse des triglycérides ;\n✔ objectif assiette : poisson gras 2-3 fois/semaine (les petits poissons en conserve sont parfaits) ;\n✔ supplémentation à discuter si zéro poisson ou triglycérides élevés persistants ;\n✔ prudence avec les anticoagulants — avis médical.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais les oméga-3 »"]],
  q:[["L'ALA végétal remplace-t-il les oméga-3 marins ?",["Non : sa conversion en EPA/DHA est de quelques % seulement","Oui, totalement"],0,"Noix et lin sont utiles, mais ne remplacent pas le poisson gras."],
     ["Quel est l'effet le mieux démontré des oméga-3 ?",["La baisse des triglycérides","La pousse des cheveux","La vision nocturne"],0,"Un effet particulièrement intéressant sur le terrain métabolique."],
     ["Quelle est la meilleure source pratique ?",["Poissons gras 2-3 fois/semaine (sardines, maquereaux…)","Les bonbons aux fruits","Les chips"],0,"Petits poissons = moins de métaux lourds, prix mini, conserves pratiques."],
     ["Quelle précaution majeure avec les oméga-3 en gélules ?",["À fortes doses, prudence avec anticoagulants et avant chirurgie","Aucune","Ne pas les prendre avec de l'eau"],0,"Ils fluidifient le sang à doses élevées : avis médical indispensable."],
     ["Quand une supplémentation se discute-t-elle ?",["Si l'on ne mange jamais de poisson gras ou en cas de triglycérides élevés persistants","Systématiquement pour tous","Jamais"],0,"L'assiette d'abord ; la gélule pour les situations où elle ne suffit pas."]]},
 {t:"La vitamine D : bien plus qu'une vitamine",mi:"Cette semaine : ☀️ 15-20 minutes de lumière du jour, bras découverts si possible, et 🐟 un poisson gras au menu. Au prochain rendez-vous, demandez à votre médecin si un dosage de la vitamine D est pertinent dans votre situation.",p:[
  ["👋 Introduction","La vitamine D est à part : fabriquée par la PEAU sous l'action du soleil, elle agit comme une véritable hormone, avec des récepteurs dans presque tous les tissus… y compris le pancréas.\nEt son insuffisance est extrêmement répandue, surtout d'octobre à avril.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ connaître les rôles de la vitamine D ;\n✅ identifier les facteurs de carence ;\n✅ savoir quand un dosage et une supplémentation se discutent ;\n✅ comprendre pourquoi éviter l'automédication à fortes doses."],
  ["☀️ Ses rôles — au-delà des os","La vitamine D est connue pour les OS (absorption du calcium), mais elle fait bien plus :\n💪 fonction MUSCULAIRE (force, équilibre — prévention des chutes chez les seniors) ;\n🛡️ modulation de l'IMMUNITÉ ;\n🧠 humeur et énergie ;\n🩸 et un lien étudié avec le MÉTABOLISME : des récepteurs existent sur les cellules du pancréas, et un statut bas est fréquemment associé à la résistance à l'insuline et au diabète de type 2. Prudence toutefois : association ne prouve pas causalité — la supplémentation n'est pas un « traitement du diabète », mais corriger une vraie carence reste pertinent pour la santé globale.","m9c3b"],
  ["🌥️ Pourquoi la carence est si fréquente","Les facteurs qui y contribuent :\n🌍 la LATITUDE : en France, d'octobre à avril, le soleil est trop bas pour une synthèse efficace ;\n🏢 la vie en intérieur, la crème solaire permanente, les vêtements couvrants ;\n👴 l'ÂGE : la peau synthétise moins bien ;\n🎨 une peau foncée (synthèse plus lente sous nos latitudes) ;\n⚖️ le SURPOIDS : la vitamine D, liposoluble, se « piège » dans le tissu adipeux — les besoins sont souvent plus élevés ;\n🥗 et une alimentation pauvre en poissons gras.\nSources alimentaires (modestes mais réelles) : poissons gras, jaune d'œuf, foie, produits laitiers entiers — l'alimentation seule couvre rarement tout : le SOLEIL raisonnable reste la source n°1.","m9c3c"],
  ["🩺 Dosage, supplémentation… et les excès à éviter","📋 LE DOSAGE sanguin (25-OH-vitamine D) n'est pas systématique : il se justifie dans certaines situations (ostéoporose, chutes, malabsorption, insuffisance rénale…) — votre médecin jugera. Repère souvent utilisé : ≥ 30 ng/mL considéré comme satisfaisant.\n💊 LA SUPPLÉMENTATION se discute quand l'exposition et l'alimentation ne suffisent pas (hiver, âge, surpoids, carence documentée). Doses quotidiennes ou espacées : c'est le médecin ou le pharmacien qui adapte.\n\n⚠️ POURQUOI ÉVITER L'AUTOMÉDICATION À FORTES DOSES : la vitamine D est LIPOSOLUBLE — elle s'ACCUMULE. Des mégadoses prolongées peuvent provoquer une hypercalcémie (nausées, soif intense, calculs rénaux, atteinte rénale). Les cas d'intoxication existent, souvent via des produits surdosés achetés en ligne. Plus n'est PAS mieux.\n\n💡 Astuce Keto-Essenciel : la « dose » la plus sûre reste la marche quotidienne à la lumière du jour — vitamine D + activité physique + régulation du cortisol et du sommeil en un seul geste.","m9c3d"],
  ["📝 À retenir","📝 À retenir :\n✔ la vitamine D agit comme une hormone : os, muscles, immunité, humeur ;\n✔ statut bas très fréquent d'octobre à avril, avec l'âge et le surpoids ;\n✔ dosage et supplémentation : à discuter avec le médecin selon votre situation ;\n✔ liposoluble = elle s'accumule : jamais de mégadoses en automédication ;\n✔ soleil raisonnable + poissons gras = la base.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais la vitamine D »"]],
  q:[["Quelle est la source principale de vitamine D ?",["La synthèse par la peau sous l'action du soleil","Les bonbons","Le café"],0,"L'alimentation (poissons gras, jaune d'œuf) complète, mais couvre rarement tout."],
     ["Pourquoi la carence est-elle si fréquente en hiver ?",["Le soleil est trop bas d'octobre à avril pour une synthèse efficace","Il fait froid","Les jours sont trop longs"],0,"S'ajoutent : vie en intérieur, âge, surpoids (elle se piège dans le tissu adipeux)."],
     ["La vitamine D est-elle un traitement du diabète ?",["Non — mais corriger une vraie carence reste pertinent pour la santé globale","Oui, elle remplace les médicaments"],0,"Association ne prouve pas causalité : prudence avec les promesses."],
     ["Pourquoi éviter les mégadoses en automédication ?",["Liposoluble, elle s'accumule : risque d'hypercalcémie et d'atteinte rénale","Elle ne sert à rien","Elle coûte cher"],0,"Plus n'est pas mieux — les intoxications existent réellement."],
     ["Quel est le geste le plus sûr pour son statut en vitamine D ?",["La lumière du jour quotidienne + poissons gras","Rester enfermé","Tripler les gélules"],0,"La marche à la lumière cumule vitamine D, activité et régulation du sommeil."]]},
 {t:"Le chrome : quel intérêt pour la glycémie ?",mi:"Réflexe esprit critique : 🔍 cherchez un produit « chrome » en ligne et lisez ses promesses. Comparez-les avec ce chapitre : que promettent-ils que la science ne garantit pas ? Cet exercice vaut pour tous les compléments.",p:[
  ["👋 Introduction","« Le chrome régule la glycémie » : l'allégation est partout. Qu'en dit vraiment la science ? Réponse honnête : c'est nuancé — et c'est justement un excellent cas d'école pour apprendre à évaluer un complément.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle du chrome dans le métabolisme du glucose ;\n✅ savoir ce que montrent (et ne montrent pas) les études ;\n✅ identifier les situations où il peut se discuter ;\n✅ connaître ses limites et précautions."],
  ["🔬 Son rôle — et ce que disent les études","Le chrome est un OLIGO-ÉLÉMENT (besoins minuscules) qui participe à l'action de l'insuline : il entre dans un complexe qui facilite la liaison de l'insuline à son récepteur. D'où l'hypothèse : plus de chrome = meilleure sensibilité ?\nCe que montrent les études :\n📊 chez les personnes CARENCÉES, corriger le manque améliore la tolérance au glucose — logique ;\n📊 chez les personnes diabétiques NON carencées, les résultats sont CONTRADICTOIRES : certaines études montrent une petite amélioration (HbA1c, glycémie), beaucoup ne montrent RIEN de significatif ;\n📊 les méta-analyses concluent au mieux à un effet MODESTE et inconstant.\nEn clair : le chrome n'est ni un mythe total, ni un traitement — c'est un « peut-être, petit, chez certains ».","m9c4b"],
  ["🍽️ Sources et situations où il se discute","La carence franche est RARE avec une alimentation variée. Sources : viandes, abats, œufs, brocoli, noix, levure de bière.\nSituations où une insuffisance est possible : alimentation très ultra-transformée prolongée, âge avancé, certaines situations de malabsorption.\nOù il PEUT se discuter (avec un professionnel) : en complément d'une démarche globale déjà en place (alimentation, activité, sommeil), jamais à la place. Attendre d'un comprimé de chrome qu'il compense une alimentation sucrée est le contresens classique.","m9c4c"],
  ["⚠️ Limites et précautions","Les limites à garder en tête :\n1️⃣ preuves FAIBLES et inconstantes — ne remplacent ni traitement ni hygiène de vie ;\n2️⃣ dosages des produits très variables ; formes multiples (picolinate le plus étudié) ;\n3️⃣ effet, s'il existe, MODESTE — indétectable sans suivi objectif (glycémies, HbA1c).\nPrécautions :\n🩺 si vous prenez des ANTIDIABÉTIQUES : tout produit susceptible de modifier la glycémie doit être signalé au médecin (risque théorique d'hypoglycémie en addition) ;\n🚫 respecter les doses des étiquettes — les mégadoses n'apportent rien de plus ;\n🫁 prudence en cas de maladie rénale ou hépatique.\n\n💡 Astuce Keto-Essenciel : si vous testez (avec accord médical), faites-le PROPREMENT : 2-3 mois, glycémies notées avant/pendant, et arrêt si rien ne change. Un complément qui ne montre rien de mesurable ne mérite pas sa place.","m9c4d"],
  ["📝 À retenir","📝 À retenir :\n✔ le chrome participe à l'action de l'insuline — mais la carence franche est rare ;\n✔ études contradictoires : effet au mieux modeste chez les non-carencés ;\n✔ jamais à la place de l'alimentation, de l'activité ou d'un traitement ;\n✔ sous antidiabétiques : signaler au médecin ;\n✔ tester = mesurer (2-3 mois, glycémies/HbA1c), sinon s'abstenir.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais le chrome »"]],
  q:[["Quel est le rôle du chrome ?",["Faciliter l'action de l'insuline sur son récepteur","Remplacer l'insuline","Colorer les aliments"],0,"Un oligo-élément aux besoins minuscules — la carence franche est rare."],
     ["Que montrent les études chez les personnes diabétiques non carencées ?",["Des résultats contradictoires, un effet au mieux modeste","Une guérison systématique","Un doublement de la glycémie"],0,"Ni mythe total, ni traitement : un « peut-être, petit, chez certains »."],
     ["Le chrome peut-il compenser une alimentation sucrée ?",["Non, c'est le contresens classique","Oui, totalement"],0,"Aucun complément ne rattrape l'assiette."],
     ["Quelle précaution si vous prenez des antidiabétiques ?",["Signaler tout complément susceptible de modifier la glycémie au médecin","Aucune","Doubler les doses"],0,"Risque théorique d'addition d'effets — le médecin doit savoir."],
     ["Comment tester un complément intelligemment ?",["2-3 mois avec mesures (glycémies/HbA1c), arrêt si rien ne change","À vie sans mesurer","Au feeling"],0,"Un complément sans effet mesurable ne mérite pas sa place."]]},
 {t:"La berbérine : un complément très étudié",mi:"Si la berbérine vous intéresse, préparez le terrain : 📋 listez TOUS vos traitements actuels et prenez rendez-vous (médecin ou pharmacien) pour vérifier les interactions AVANT tout achat. C'est la seule bonne façon de commencer.",p:[
  ["👋 Introduction","La berbérine est probablement le complément le plus discuté en santé métabolique — avec de vraies études à l'appui et de vrais effets… ce qui implique aussi de VRAIES précautions.\nCar un produit qui agit réellement sur la glycémie n'est jamais anodin.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ savoir ce qu'est la berbérine ;\n✅ comprendre ses mécanismes proposés ;\n✅ connaître les bénéfices potentiels ET les effets indésirables ;\n✅ identifier les interactions et les situations exigeant un avis médical."],
  ["🌿 Ce que c'est — et comment elle agirait","La berbérine est un alcaloïde extrait de plantes comme l'épine-vinette (Berberis), utilisées de longue date en médecine traditionnelle.\nMécanismes proposés dans les études :\n⚙️ activation de l'AMPK — un « interrupteur énergétique » cellulaire (mécanisme proche de celui décrit pour la metformine) ;\n🍬 diminution de la production hépatique de glucose ;\n📈 amélioration de la sensibilité à l'insuline ;\n🦠 effets sur le microbiote intestinal ;\n🧈 baisse des lipides sanguins (LDL, triglycérides) rapportée dans plusieurs travaux.\nC'est ce faisceau de mécanismes qui la rend si étudiée — plusieurs essais cliniques ont observé des baisses de glycémie et d'HbA1c comparables, dans certaines études, à celles de traitements de référence. Les études restent toutefois souvent petites et de qualité variable : l'enthousiasme doit rester prudent.","m9c5b"],
  ["⚠️ Effets indésirables — et vraies précautions","Effets indésirables possibles (surtout digestifs) : constipation, diarrhée, crampes abdominales, nausées — fréquents aux doses étudiées, souvent atténués en commençant bas et en prenant pendant les repas.\n\n🚨 LES INTERACTIONS — le point CRUCIAL :\n💊 avec les ANTIDIABÉTIQUES (metformine, sulfamides, insuline…) : risque d'HYPOGLYCÉMIE par addition d'effets — ne JAMAIS l'ajouter sans avis médical, et ne JAMAIS remplacer un traitement par la berbérine ;\n💊 elle inhibe des enzymes du foie (cytochromes) qui métabolisent de NOMBREUX médicaments (anticoagulants, statines, immunosuppresseurs, certains antihypertenseurs…) : leurs concentrations peuvent augmenter ;\n🤰 CONTRE-INDIQUÉE pendant la grossesse et l'allaitement ;\n🫁 prudence en cas de maladie hépatique ou rénale.\nAvis médical INDISPENSABLE si : vous prenez un traitement quel qu'il soit, vous êtes diabétique traité, ou votre situation est complexe.","m9c5c"],
  ["🧭 En pratique : la démarche raisonnée","Si, APRÈS validation médicale, un essai est décidé :\n✔ produit de qualité, dosage vérifié (les études utilisent souvent ~500 mg × 2-3/jour — mais suivez l'avis du professionnel) ;\n✔ commencer BAS, pendant les repas, augmenter progressivement ;\n✔ SURVEILLER la glycémie de près, surtout les premières semaines (risque d'hypo si traitement associé) ;\n✔ évaluer à 3 mois sur des critères objectifs (glycémies, HbA1c, lipides) — poursuivre seulement si bénéfice mesurable ;\n✔ pauses et durée : à définir avec le professionnel, le recul au très long cours restant limité.\n\n💡 Astuce Keto-Essenciel : la berbérine illustre la règle d'or du module — « ça marche » implique « ça interagit ». Plus un complément est actif, plus l'encadrement médical est indispensable.","m9c5d"],
  ["📝 À retenir","📝 À retenir :\n✔ la berbérine est un complément réellement actif (AMPK, production hépatique de glucose) ;\n✔ des études montrent des baisses de glycémie/HbA1c — mais souvent de petite taille et de qualité variable ;\n✔ effets digestifs fréquents ; contre-indiquée grossesse/allaitement ;\n✔ interactions nombreuses (antidiabétiques, anticoagulants, statines…) : avis médical INDISPENSABLE ;\n✔ jamais en remplacement d'un traitement — et toujours avec suivi mesuré.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais la berbérine »"]],
  q:[["Quel est le mécanisme phare proposé pour la berbérine ?",["L'activation de l'AMPK, un interrupteur énergétique cellulaire","Le blocage de la respiration","Aucun mécanisme"],0,"Un mécanisme proche de celui décrit pour la metformine."],
     ["Quels sont ses effets indésirables les plus fréquents ?",["Troubles digestifs (diarrhée, constipation, crampes)","Perte de cheveux","Insomnie systématique"],0,"Souvent atténués en commençant bas et en la prenant pendant les repas."],
     ["Pourquoi l'avis médical est-il indispensable avec la berbérine ?",["Risque d'hypoglycémie avec les antidiabétiques et interactions avec de nombreux médicaments","Par simple formalité","Il ne l'est pas"],0,"Elle inhibe des enzymes du foie qui métabolisent anticoagulants, statines…"],
     ["Peut-on remplacer son traitement antidiabétique par la berbérine ?",["Non, jamais","Oui, librement"],0,"Un complément ne remplace jamais un traitement — au mieux il s'y ajoute, sous contrôle."],
     ["La berbérine est-elle adaptée pendant la grossesse ?",["Non, contre-indiquée","Oui, recommandée"],0,"Contre-indication grossesse et allaitement."]]},
 {t:"La cannelle : mythe ou véritable intérêt ?",mi:"Test gourmand de la semaine : 🍂 ajoutez ½ à 1 cuillère à café de cannelle de CEYLAN (vérifiez l'étiquette !) dans votre yaourt grec, votre café ou un dessert keto. Plaisir garanti — effet glycémique en bonus éventuel.",p:[
  ["👋 Introduction","Épice star des allégations « anti-diabète », la cannelle mérite un examen honnête : il y a un fond de vrai, beaucoup de variabilité… et une vraie précaution que peu de gens connaissent (la coumarine).\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer les variétés de cannelle ;\n✅ connaître les effets étudiés sur la glycémie ;\n✅ comprendre pourquoi les résultats varient ;\n✅ l'utiliser raisonnablement et sans risque."],
  ["🍂 Deux cannelles très différentes","🌟 LA CANNELLE DE CEYLAN (Cinnamomum verum, « vraie cannelle ») — arôme fin, et surtout TRÈS PEU de coumarine ;\n⚠️ LA CANNELLE DE CASSIA (de Chine) — la plus courante en supermarché (moins chère), plus corsée… et RICHE EN COUMARINE, un composé potentiellement toxique pour le FOIE à doses répétées.\nRepère de sécurité : la dose journalière tolérable de coumarine peut être atteinte avec seulement ~1 cuillère à café de cassia par jour chez un adulte de corpulence moyenne — moins chez l'enfant. En usage QUOTIDIEN, choisissez donc la CEYLAN (l'étiquette doit préciser la variété ; en cas de doute, c'est probablement de la cassia).","m9c6b"],
  ["📊 Ce que disent les études — et pourquoi ça varie","Les effets étudiés : certains essais montrent une baisse MODESTE de la glycémie à jeun (souvent de l'ordre de quelques %) et une amélioration de la sensibilité à l'insuline ; d'autres ne montrent rien. Les méta-analyses concluent à un effet possible mais PETIT et INCONSTANT, avec un impact incertain sur l'HbA1c.\nPourquoi tant de variabilité ?\n🌿 des variétés et préparations différentes selon les études (cassia, ceylan, extraits…) ;\n💊 des doses très variables (de 0,5 à 6 g/jour) ;\n👥 des profils de participants différents (plus d'effet apparent quand la glycémie de départ est élevée) ;\n⏳ des durées courtes.\nConclusion honnête : la cannelle est un PLUS gustatif avec un éventuel petit bonus métabolique — pas un traitement.","m9c6c"],
  ["🥄 L'intégrer raisonnablement","La bonne approche est ALIMENTAIRE, pas « gélule » :\n☕ ½ à 1 cuillère à café de CEYLAN par jour dans le café, le yaourt grec, le skyr, les desserts keto, un curry ;\n🍎 bonus pratique : elle donne un goût « sucré-chaud » qui aide à réduire le vrai sucre dans les préparations ;\n💊 les extraits concentrés en gélules : intérêt non démontré au-delà de l'épice, et doses de coumarine parfois problématiques selon les produits — si vous y tenez, avis du pharmacien ;\n🩺 comme toujours : sous antidiabétiques, signaler toute prise régulière et significative ; et en cas de maladie du foie, prudence avec la cassia.\n\n💡 Astuce Keto-Essenciel : la cannelle est l'exemple parfait du complément « au bon endroit » : dans l'assiette, pour le plaisir, avec un éventuel bonus — et zéro attente miracle.","m9c6d"],
  ["📝 À retenir","📝 À retenir :\n✔ deux variétés : Ceylan (peu de coumarine) vs Cassia (riche en coumarine, prudence foie) ;\n✔ effets sur la glycémie : possibles mais petits et inconstants selon les études ;\n✔ usage quotidien = choisir la Ceylan ;\n✔ l'approche alimentaire (½-1 c. à café/j) prime sur les gélules ;\n✔ un plaisir gustatif avec bonus éventuel — pas un traitement.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais la cannelle »"]],
  q:[["Quelle est la différence clé entre cannelle de Ceylan et de Cassia ?",["La Cassia est riche en coumarine, potentiellement toxique pour le foie à doses répétées","Aucune","La Ceylan est dangereuse"],0,"Pour un usage quotidien, choisissez la Ceylan (vérifiez l'étiquette)."],
     ["Que montrent les études sur cannelle et glycémie ?",["Un effet possible mais petit et inconstant","Une guérison du diabète","Une hausse de la glycémie"],0,"Variétés, doses et durées très différentes : résultats variables."],
     ["Quelle est la meilleure façon d'utiliser la cannelle ?",["Dans l'assiette : ½ à 1 c. à café de Ceylan par jour","En mégadoses de gélules","En bâtons entiers avalés"],0,"Bonus : son goût « sucré-chaud » aide à réduire le vrai sucre."],
     ["Environ quelle dose de cassia peut atteindre la limite de coumarine ?",["~1 cuillère à café par jour chez l'adulte moyen","1 kg par jour","Aucune limite n'existe"],0,"Moins encore chez l'enfant — d'où la préférence pour la Ceylan au quotidien."],
     ["La cannelle est-elle un traitement du diabète ?",["Non : un plaisir gustatif avec un éventuel petit bonus","Oui, elle remplace la metformine"],0,"Zéro attente miracle — et signaler tout usage régulier important au médecin."]]},
 {t:"L'acide alpha-lipoïque : un antioxydant intéressant",mi:"Si vous ressentez fourmillements ou brûlures dans les pieds, ne vous auto-traitez pas : 🩺 parlez-en d'abord à votre médecin. Deux raisons : confirmer la cause (neuropathie ? carence B12 ?) et discuter des options — dont l'acide alpha-lipoïque.",p:[
  ["👋 Introduction","Moins connu du grand public, l'acide alpha-lipoïque (ALA — à ne pas confondre avec l'oméga-3 ALA !) est pourtant l'un des compléments les plus étudiés dans un domaine précis : la NEUROPATHIE diabétique.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle de l'acide alpha-lipoïque ;\n✅ connaître les données sur la neuropathie diabétique ;\n✅ connaître les autres pistes étudiées ;\n✅ maîtriser précautions, contre-indications et interactions."],
  ["🛡️ Un antioxydant « universel »","L'acide alpha-lipoïque est un antioxydant particulier :\n⚙️ le corps en FABRIQUE (en petite quantité) — il participe à la production d'énergie dans les mitochondries ;\n💧 il est actif en milieu aqueux ET graisseux (rare), ce qui lui permet d'agir partout, y compris dans les nerfs ;\n♻️ il « recycle » d'autres antioxydants (vitamines C et E, glutathion).\nPourquoi le diabète l'intéresse : l'excès chronique de glucose génère un STRESS OXYDATIF qui abîme notamment les petits nerfs (neuropathie : fourmillements, brûlures, perte de sensibilité des pieds). D'où l'idée d'un antioxydant puissant capable d'atteindre les nerfs.","m9c7b"],
  ["📊 Neuropathie diabétique : les données — et les autres pistes","🦶 LA NEUROPATHIE, le domaine le plus solide : plusieurs essais cliniques (notamment à 600 mg/jour) ont montré une amélioration des SYMPTÔMES — douleurs, brûlures, fourmillements — chez une partie des patients. Dans certains pays, il est d'ailleurs utilisé comme médicament dans cette indication. Les preuves sont plus fortes pour la voie intraveineuse (hospitalière) que pour la voie orale, mais l'orale a aussi des données positives.\n⚠️ Il SOULAGE des symptômes ; il ne « répare » pas un nerf détruit ni ne remplace l'équilibre glycémique — qui reste LE traitement de fond de la neuropathie.\n\n🔬 Les autres pistes étudiées (preuves plus légères) : sensibilité à l'insuline, marqueurs du stress oxydatif, santé du foie… intéressantes mais insuffisantes pour une recommandation.","m9c7c"],
  ["⚠️ Précautions, contre-indications, interactions","💊 GLYCÉMIE : l'acide alpha-lipoïque peut ABAISSER la glycémie — sous antidiabétiques (insuline, sulfamides…), risque d'HYPOGLYCÉMIE par addition : avis médical et surveillance rapprochée indispensables ;\n🦋 THYROÏDE : prudence en cas de traitement thyroïdien (interactions possibles) — espacer les prises et en parler au médecin ;\n🍽️ à prendre À JEUN (l'absorption chute avec les repas) ; effets indésirables possibles : troubles digestifs, éruptions cutanées ;\n🤰 grossesse/allaitement : éviter par manque de données ;\n🧪 il peut chélater certains minéraux (fer, zinc) : espacer les prises ;\n⚕️ cas particulier rare mais documenté : de fortes doses ont été associées à des hypoglycémies auto-immunes chez certaines personnes prédisposées — un signe de plus que « actif » = « à encadrer ».\n\n💡 Astuce Keto-Essenciel : si une neuropathie vous gêne, la démarche gagnante est : équilibre glycémique (le fond) + avis médical sur les options (dont l'ALA) + vérification de la B12 (souvenez-vous : metformine !). Trois leviers valent mieux qu'une gélule seule.","m9c7d"],
  ["📝 À retenir","📝 À retenir :\n✔ antioxydant actif en milieux aqueux et graisseux, jusque dans les nerfs ;\n✔ meilleur dossier : les symptômes de la neuropathie diabétique (600 mg/j dans les études) ;\n✔ il soulage des symptômes — l'équilibre glycémique reste le traitement de fond ;\n✔ peut abaisser la glycémie : prudence sous antidiabétiques ;\n✔ à jeun, hors grossesse, avec avis médical — comme toujours.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais l'acide alpha-lipoïque »"]],
  q:[["Dans quel domaine l'acide alpha-lipoïque a-t-il les meilleures données ?",["Les symptômes de la neuropathie diabétique","La pousse des ongles","La vision nocturne"],0,"Plusieurs essais (600 mg/j) montrent une amélioration des douleurs et fourmillements."],
     ["L'acide alpha-lipoïque répare-t-il les nerfs détruits ?",["Non : il soulage des symptômes ; l'équilibre glycémique reste le traitement de fond","Oui, totalement"],0,"Le fond de la neuropathie se traite par la glycémie — l'ALA peut aider sur les symptômes."],
     ["Quelle précaution majeure sous antidiabétiques ?",["Risque d'hypoglycémie par addition d'effets : avis médical et surveillance","Aucune","Il faut doubler l'insuline"],0,"Un complément qui abaisse la glycémie n'est jamais anodin."],
     ["Comment le prendre pour une bonne absorption ?",["À jeun","Au milieu d'un repas gras","Avec un soda"],0,"L'absorption chute nettement avec les repas."],
     ["Est-il conseillé pendant la grossesse ?",["Non, à éviter par manque de données","Oui, fortement"],0,"Principe de précaution classique pour les compléments actifs."]]},
 {t:"Comment choisir un complément alimentaire de qualité ?",mi:"Exercez votre œil : 🔍 prenez un complément que vous avez (ou en magasin) et passez son étiquette au crible — forme du nutriment, dose par prise, additifs, label, allégations. Verdict : le garderiez-vous après ce chapitre ?",p:[
  ["👋 Introduction","Deux flacons de « magnésium » peuvent contenir des produits radicalement différents : forme mal absorbée bourrée d'additifs pour l'un, forme efficace et propre pour l'autre — parfois au même prix.\nApprendre à lire une étiquette, c'est ne plus jamais acheter à l'aveugle.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ reconnaître les critères de qualité d'un produit ;\n✅ identifier les formes les mieux assimilées ;\n✅ lire une étiquette et repérer labels et certifications ;\n✅ déjouer les pièges du marketing."],
  ["🏷️ Lire l'étiquette comme un pro","Les points à vérifier :\n1️⃣ LA FORME du nutriment — c'est elle qui fait l'assimilation : magnésium bisglycinate/citrate > oxyde ; oméga-3 en triglycérides > esters éthyliques ; vitamine D3 > D2 ; B12 méthylcobalamine ou cyanocobalamine correctement dosée…\n2️⃣ LA DOSE PAR PRISE réelle du nutriment actif (pas du composé total) — comparez aux références journalières ;\n3️⃣ LA LISTE DES EXCIPIENTS : plus elle est courte, mieux c'est (méfiance envers les colorants et édulcorants inutiles… et le sucre dans les gummies !) ;\n4️⃣ le NOMBRE DE PRISES par jour et le coût par mois RÉEL ;\n5️⃣ l'origine et le sérieux du fabricant (site transparent, analyses disponibles).","m9c8b"],
  ["✅ Labels, certifications — et gages de sérieux","Ce qui rassure :\n🏅 les CERTIFICATIONS QUALITÉ de fabrication (normes type bonnes pratiques, contrôles par lots) ;\n🔬 les analyses par LABORATOIRE INDÉPENDANT (métaux lourds, pureté, dosage réel) — les bonnes marques les publient ou les fournissent sur demande ;\n🐟 pour les oméga-3 : des labels de pureté/fraîcheur et de pêche durable existent ;\n🌿 bio : pertinent pour les plantes ; ne dit rien de l'assimilation d'un minéral ;\n🇪🇺 une fabrication européenne facilite la traçabilité — les achats en ligne hors UE échappent souvent aux contrôles (dosages parfois fantaisistes, jusqu'aux contaminations).\nUn produit sans AUCUNE de ces garanties, vendu uniquement sur les réseaux sociaux ? Passez votre chemin.","m9c8c"],
  ["🎭 Les pièges du marketing","Le bingo des signaux d'alarme :\n❌ promesses MIRACLES (« inverse le diabète en 30 jours », « fait fondre la graisse ») — plus la promesse est grosse, plus le produit est douteux ;\n❌ « formule exclusive » aux 25 ingrédients sous-dosés (le « fairy dusting » : un soupçon de tout, une dose efficace de rien) ;\n❌ « approuvé par les médecins », témoignages spectaculaires avant/après, comptes à rebours d'achat ;\n❌ prix exorbitant justifié par un « secret » ;\n❌ absence de dose précise ou de composition complète.\nRappel légal utile : un complément n'a pas le droit de prétendre GUÉRIR ou traiter une maladie. Toute promesse de ce type est déjà, en soi, un signal de fuite.\n\n💡 Astuce Keto-Essenciel : votre PHARMACIEN est votre meilleur allié gratuit : il connaît les interactions avec VOS traitements et peut évaluer un produit en 2 minutes. Utilisez-le !","m9c8d"],
  ["📝 À retenir","📝 À retenir :\n✔ la FORME du nutriment fait l'assimilation — vérifiez-la en premier ;\n✔ dose réelle par prise, excipients courts, coût mensuel réel ;\n✔ certifications et analyses indépendantes = gages de sérieux ;\n✔ promesses miracles et formules « poussière de fée » = fuir ;\n✔ le pharmacien est votre meilleur conseiller gratuit.\n\n🏅 Badge à débloquer en validant le quiz : « Je choisis mes compléments »"]],
  q:[["Quel est le premier critère à vérifier sur une étiquette ?",["La forme du nutriment (elle détermine l'assimilation)","La couleur du flacon","La police d'écriture"],0,"Bisglycinate vs oxyde, D3 vs D2 : la forme change tout."],
     ["Qu'est-ce que le « fairy dusting » ?",["25 ingrédients sous-dosés : un soupçon de tout, une dose efficace de rien","Un label de qualité","Une vitamine"],0,"Une formule impressionnante sur le papier, inefficace dans la gélule."],
     ["Quel signal doit faire fuir immédiatement ?",["Une promesse de guérison ou de résultat miracle","Une analyse de laboratoire indépendante","Une composition détaillée"],0,"Un complément n'a légalement pas le droit de prétendre guérir une maladie."],
     ["Que garantissent les analyses par laboratoire indépendant ?",["Pureté, absence de métaux lourds et dosage réel","Le goût","La livraison rapide"],0,"Les bonnes marques les publient ou les fournissent sur demande."],
     ["Qui peut évaluer gratuitement un complément par rapport à VOS traitements ?",["Votre pharmacien","Un influenceur","Personne"],0,"Il connaît les interactions et peut trancher en 2 minutes."]]},
 {t:"Construire une stratégie de supplémentation personnalisée",mi:"Construisez votre stratégie : 📋 listez vos compléments actuels/envisagés, et pour chacun répondez : quel besoin identifié ? quel dosage sanguin à l'appui ? quelle durée ? comment je mesure l'effet ? Apportez le tout à votre médecin ou pharmacien.",p:[
  ["👋 Introduction","Vous connaissez maintenant les principaux compléments, leurs promesses et leurs limites. Dernière étape : transformer ces connaissances en STRATÉGIE personnelle — sobre, ciblée, encadrée.\nCar en supplémentation, le sur-mesure raisonné bat toujours l'accumulation.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ identifier les compléments réellement utiles POUR VOUS ;\n✅ éviter les associations inutiles ;\n✅ intégrer les compléments dans une démarche globale ;\n✅ savoir quand demander conseil."],
  ["🎯 Étape 1 : partir de VOTRE situation","La supplémentation s'individualise — jamais de copier-coller :\n🩸 vos ANALYSES d'abord (Module 8 !) : vitamine D basse ? B12 basse sous metformine ? ferritine effondrée ? Ce sont les VRAIS points d'appui ;\n🍽️ votre ASSIETTE ensuite : jamais de poisson gras → oméga-3 à discuter ; peu de légumes verts et oléagineux → magnésium à surveiller ;\n💊 vos TRAITEMENTS : metformine → B12 à suivre ; anticoagulants → prudence oméga-3 ; antidiabétiques → prudence berbérine/ALA/chrome ;\n🎯 vos SYMPTÔMES persistants (crampes, fatigue, fourmillements) — à explorer AVEC le médecin avant de supplémenter.\nRésultat : une liste COURTE (souvent 0 à 3 produits) de candidats justifiés — pas un placard entier.","m9c9b"],
  ["🧩 Étape 2 : sobre, séquencé, mesuré","Les règles d'une stratégie propre :\n1️⃣ UN produit à la fois (2-4 semaines d'écart) : sinon impossible d'attribuer effets et désagréments ;\n2️⃣ pas d'ASSOCIATIONS INUTILES : plusieurs produits « glycémie » ensemble (berbérine + chrome + cannelle…) = risques additionnés sans bénéfice démontré ; des doublons cachés existent aussi dans les multivitamines — lisez tout ;\n3️⃣ chaque produit a un OBJECTIF MESURABLE (dosage sanguin à recontrôler, glycémies, symptôme coté sur 10) et une ÉCHÉANCE (souvent 3 mois) ;\n4️⃣ à l'échéance : bénéfice mesurable → on continue en réévaluant ; rien → on ARRÊTE. Un complément « par habitude » n'a pas sa place ;\n5️⃣ tout est CONSIGNÉ (produit, dose, début, effet) et PARTAGÉ avec vos soignants.","m9c9c"],
  ["🌳 Étape 3 : la pyramide — et les bons réflexes de conseil","Gardez la hiérarchie en tête, comme une pyramide :\n🟩 LA BASE (non négociable) : alimentation, activité physique, sommeil, gestion du stress — 90 % des résultats viennent de là ;\n🟨 L'ÉTAGE SANTÉ : traitements prescrits et suivi médical ;\n🟧 LE SOMMET (la cerise) : les compléments CIBLÉS, qui optimisent une base déjà en place — jamais l'inverse.\nUn complément qui « compense » une base absente est de l'argent perdu ; un complément qui corrige un déficit documenté sur une base solide est un vrai levier.\n\n🩺 QUAND DEMANDER CONSEIL — systématiquement si : vous prenez un traitement (quel qu'il soit), vous êtes enceinte ou allaitez, vous avez une maladie rénale ou hépatique, un symptôme nouveau apparaît, ou un produit promet monts et merveilles. Médecin pour la stratégie, pharmacien pour les interactions : les deux sont vos alliés.\n\n💡 Astuce Keto-Essenciel : refaites cet exercice une fois par an, avec vos nouvelles analyses. Une stratégie de supplémentation est vivante : elle doit maigrir ou s'ajuster au fil de vos progrès — souvent, mieux vous allez, moins vous en avez besoin.","m9c9d"],
  ["📝 À retenir — et bravo pour ce module !","📝 À retenir :\n✔ partir de SA situation : analyses, assiette, traitements, symptômes ;\n✔ liste courte (0-3), un produit à la fois, objectif mesurable, échéance à 3 mois ;\n✔ pas d'associations « glycémie » multiples ni de doublons cachés ;\n✔ pyramide : base de vie → traitements → compléments ciblés en cerise ;\n✔ médecin et pharmacien : vos deux alliés systématiques.\n\n🎓 Dans ce Module 10, vous avez appris à : distinguer médicament et complément, connaître magnésium, oméga-3, vitamine D, chrome, berbérine, cannelle et acide alpha-lipoïque, choisir un produit de qualité et construire une stratégie personnalisée et raisonnée.\n\n🏅 Après ce chapitre, le Quiz final du module (20 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge 💊 « Utilisation raisonnée des compléments alimentaires » et la compétence : « Je sais évaluer, choisir et encadrer mes compléments avec discernement »."]],
  q:[["Sur quoi fonder sa stratégie de supplémentation ?",["Ses analyses, son assiette, ses traitements et ses symptômes","Les publicités","Ce que prend le voisin"],0,"Le sur-mesure raisonné bat toujours l'accumulation."],
     ["Pourquoi introduire un seul produit à la fois ?",["Pour pouvoir attribuer les effets et les désagréments","Pour dépenser moins vite","C'est inutile"],0,"2-4 semaines d'écart entre chaque introduction."],
     ["Que faire d'un complément sans bénéfice mesurable après 3 mois ?",["L'arrêter","Le continuer par habitude","En doubler la dose"],0,"Un complément « par habitude » n'a pas sa place."],
     ["Quelle est la place des compléments dans la pyramide de santé ?",["La cerise au sommet — après l'hygiène de vie et les traitements","La base","Ils remplacent tout le reste"],0,"90 % des résultats viennent de la base : alimentation, activité, sommeil, stress."],
     ["Faut-il associer plusieurs produits « glycémie » (berbérine + chrome + cannelle…) ?",["Non : risques additionnés sans bénéfice démontré","Oui, plus il y en a mieux c'est"],0,"Les associations inutiles sont l'erreur classique — sobriété et mesure."]]}
],fq:[
 ["Quelle est la différence entre un médicament et un complément alimentaire ?",["Le médicament doit prouver efficacité et sécurité avant sa mise sur le marché","Aucune différence","Le complément est plus contrôlé","Le médicament est naturel"],0,"Le complément est réglementé comme un aliment — moins de garanties."],
 ["« Naturel » signifie-t-il « sans danger » ?",["Non : interactions et surdosages existent","Oui, toujours"],0,"Certaines plantes interagissent avec des traitements courants."],
 ["Quand un complément est-il le plus légitime ?",["Pour corriger un déficit documenté par une analyse","Au cas où","Sur les conseils d'une publicité","Pour remplacer les repas"],0,"L'assiette d'abord, le dosage ensuite, la gélule enfin."],
 ["Pourquoi le magnésium concerne-t-il les personnes diabétiques ?",["La glycémie élevée augmente ses pertes urinaires et il participe à l'action de l'insuline","Il fait monter la glycémie","Aucun lien","Il remplace l'insuline"],0,"Réserves souvent plus basses en cas de diabète."],
 ["Quelle précaution majeure avec le magnésium en supplément ?",["Insuffisance rénale = avis médical obligatoire","Aucune","Le prendre avec un soda","L'éviter dans les aliments"],0,"Des reins qui filtrent mal peuvent le laisser s'accumuler."],
 ["L'ALA végétal (noix, lin) remplace-t-il les oméga-3 marins ?",["Non : conversion en EPA/DHA de quelques % seulement","Oui, totalement"],0,"Le poisson gras 2-3 fois/semaine reste l'objectif."],
 ["Quel est l'effet le mieux démontré des oméga-3 ?",["La baisse des triglycérides","La pousse des cheveux","La mémoire absolue","Le bronzage"],0,"Particulièrement pertinent sur le terrain métabolique."],
 ["Quelle précaution avec les oméga-3 à fortes doses ?",["Prudence avec les anticoagulants et avant une chirurgie","Aucune","Ne pas conduire","Éviter le sport"],0,"Ils fluidifient le sang : avis médical indispensable."],
 ["Pourquoi la carence en vitamine D est-elle fréquente en hiver ?",["Le soleil est trop bas d'octobre à avril pour la synthèse cutanée","Il pleut","On mange moins","Les jours sont longs"],0,"S'ajoutent l'âge, la vie en intérieur et le surpoids."],
 ["Pourquoi éviter les mégadoses de vitamine D en automédication ?",["Liposoluble, elle s'accumule : risque d'hypercalcémie","Elle ne fait rien","Elle coûte trop cher","Elle empêche de dormir"],0,"Plus n'est pas mieux — les intoxications existent."],
 ["Que montrent les études sur le chrome chez les non-carencés ?",["Un effet au mieux modeste et inconstant","Une guérison du diabète","Un danger mortel systématique","Un effet spectaculaire garanti"],0,"Ni mythe total, ni traitement."],
 ["Quel est le mécanisme phare proposé pour la berbérine ?",["L'activation de l'AMPK","Le blocage du fer","La production de mélatonine","Aucun"],0,"Proche de celui décrit pour la metformine — d'où son activité réelle."],
 ["Pourquoi la berbérine exige-t-elle un avis médical ?",["Risque d'hypoglycémie avec les antidiabétiques et interactions médicamenteuses nombreuses","Par formalité","Elle n'en exige pas","Parce qu'elle est chère"],0,"Elle inhibe des enzymes hépatiques qui métabolisent de nombreux médicaments."],
 ["Peut-on remplacer un traitement antidiabétique par la berbérine ?",["Non, jamais","Oui, librement"],0,"Un complément ne remplace jamais un traitement."],
 ["Quelle cannelle privilégier en usage quotidien ?",["La Ceylan, pauvre en coumarine","La Cassia à fortes doses","N'importe laquelle","Aucune n'est comestible"],0,"La coumarine de la Cassia peut peser sur le foie à doses répétées."],
 ["Dans quel domaine l'acide alpha-lipoïque a-t-il les meilleures données ?",["Les symptômes de la neuropathie diabétique","Le bronzage","La croissance","La vue perçante"],0,"Essais à 600 mg/j — l'équilibre glycémique restant le traitement de fond."],
 ["Quel critère d'étiquette détermine l'assimilation d'un nutriment ?",["Sa forme chimique (ex. : bisglycinate vs oxyde)","La couleur de la boîte","Le slogan","Le prix"],0,"La forme d'abord, la dose réelle ensuite, les excipients enfin."],
 ["Quel signal marketing doit faire fuir ?",["Une promesse de guérison miracle","Une analyse indépendante publiée","Une composition transparente","Un conseil de pharmacien"],0,"Un complément n'a pas le droit de prétendre guérir une maladie."],
 ["Combien de compléments une stratégie raisonnée compte-t-elle en général ?",["0 à 3, justifiés et mesurés","Une dizaine minimum","Le plus possible","Toujours zéro"],0,"Un produit à la fois, objectif mesurable, échéance à 3 mois."],
 ["Quelle est la place des compléments dans la santé ?",["La cerise sur une base solide : alimentation, activité, sommeil, stress, traitements","La base de tout","Un substitut aux repas","Un substitut aux traitements"],0,"90 % des résultats viennent de la base — les compléments optimisent, ils ne compensent pas."]
],bd:"💊 Utilisation raisonnée des compléments alimentaires",sk:["Distinguer médicament et complément","Évaluer magnésium, oméga-3 et vitamine D","Garder un regard critique (chrome, cannelle)","Encadrer les compléments actifs (berbérine, acide alpha-lipoïque)","Lire une étiquette et repérer la qualité","Déjouer les pièges du marketing","Construire une stratégie sobre, mesurée et suivie","Savoir quand consulter médecin ou pharmacien"]}'''

src = src[:i] + NEW + ',\n' + src[j+len(']},\n'):]
io.open(PATH,'w',encoding='utf-8').write(src)
print('OK: Module 10 = 10 chapitres + quiz final')
