#!/usr/bin/env python3
# Module 2 : refonte « Pourquoi le Keto ? » (5 chapitres au format complet + quiz final 10 q)
import io, sys
PATH='/app/keto.html'; src=io.open(PATH,encoding='utf-8').read()
START='{t:"Pourquoi le Keto ?",e:"🥑",ip:"m1",'
END=']},\n{t:"Bien manger"'
i=src.find(START); j=src.find(END,i)
if i<0 or j<0: print('ERREUR bornes M2',i,j); sys.exit(1)
if 'Je sais pourquoi le keto' in src: print('DÉJÀ APPLIQUÉ'); sys.exit(0)

NEW = r'''{t:"Pourquoi le Keto ?",e:"🥑",ip:"m1",d:"Comprendre pourquoi réduire les glucides change la donne : la logique, la cétose, les idées reçues, les preuves scientifiques — et les situations qui demandent un avis médical.",ch:[
 {t:"Pourquoi réduire les glucides ?",mi:"Faites l'inventaire d'une journée type : 🍞 listez tout ce que vous mangez habituellement en une journée et surlignez les sources de glucides (pain, pâtes, riz, sucre, jus, fruits…). Vous serez surpris du total — c'est le point de départ de votre transformation.",p:[
  ["👋 Introduction","Si le diabète de type 2 est une intolérance aux glucides… pourquoi continuer à en consommer autant ?\nC'est LA question fondatrice de toute l'approche Keto-Essenciel. Dans ce chapitre, nous posons la logique simple — presque évidente — qui explique pourquoi réduire les glucides change la donne.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre la logique « moins de glucides = moins de glucose » ;\n✅ situer les glucides cachés de l'alimentation moderne ;\n✅ comprendre pourquoi le pancréas a besoin de souffler ;\n✅ voir ce qui change concrètement dans votre corps."],
  ["🧩 La logique est simple","Le diabète de type 2 est une intolérance aux glucides : le corps ne sait plus les gérer correctement.\nLe raisonnement tient en une ligne :\n🍞 GLUCIDES → 🩸 GLUCOSE DANS LE SANG → ⚡ BESOIN D'INSULINE.\nRéduire fortement les glucides, c'est réduire DIRECTEMENT l'arrivée de glucose dans le sang :\n📉 moins de glucose → moins de pics de glycémie ;\n📉 moins de pics → moins de besoin en insuline ;\n😮‍💨 moins d'insuline → le pancréas SOUFFLE enfin ;\n🔑 et avec le temps, les cellules redeviennent progressivement plus SENSIBLES à l'insuline.\nC'est comme une allergie au pollen : la première mesure de bon sens, c'est de réduire l'exposition au pollen. Pour une intolérance aux glucides… c'est pareil.","m1c0b"],
  ["🥖 Le vrai visage de l'alimentation moderne","Savez-vous combien de glucides contient une journée « normale » ?\n🥐 petit-déjeuner : pain, confiture, jus d'orange ≈ 80-100 g ;\n🍝 déjeuner : pâtes ou riz + dessert ≈ 90-120 g ;\n🍪 goûter : biscuits, café sucré ≈ 30-40 g ;\n🍕 dîner : pizza ou pain + yaourt sucré ≈ 80-100 g.\nTOTAL : souvent 250 à 350 g de glucides par jour — soit l'équivalent de 60 à 85 morceaux de sucre à gérer quotidiennement pour un pancréas déjà fatigué !\nL'alimentation cétogène ramène ce total à environ 20-50 g par jour, issus principalement des légumes. Le corps passe alors des montagnes russes glycémiques… à un long fleuve tranquille.","m1c0c"],
  ["🔄 Ce qui change dans votre corps","Quand les glucides baissent durablement, une cascade positive s'enclenche :\n📅 JOURS 1-3 : le corps épuise ses réserves de glycogène (et relâche l'eau qui va avec — d'où la perte rapide du début, Module 7 !) ;\n📅 SEMAINE 1-2 : le corps bascule progressivement vers son carburant de secours : les GRAISSES (les vôtres !) — c'est la cétose, détaillée au chapitre suivant ;\n📅 SEMAINES 3-6 : les glycémies se stabilisent, l'énergie devient constante (fini les coups de pompe de 11 h et 16 h), la faim se calme ;\n📅 MOIS 2-3 : l'insuline baisse durablement, la graisse viscérale commence à fondre, les analyses s'améliorent.\n\n💡 Astuce Keto-Essenciel : vous n'avez rien à calculer — les menus de l'application sont déjà construits pour respecter cette cible de glucides. Votre seul travail : suivre le plan et observer les changements.","m1c0d"],
  ["📝 À retenir","📝 À retenir :\n✔ diabète de type 2 = intolérance aux glucides : réduire l'exposition est la mesure de bon sens ;\n✔ moins de glucides → moins de glucose → moins d'insuline → pancréas soulagé ;\n✔ l'alimentation moderne apporte 250-350 g de glucides/jour ; le keto en apporte 20-50 g ;\n✔ la cascade positive s'installe en quelques semaines : glycémie stable, énergie constante, faim calmée ;\n✔ les menus de l'app font les calculs pour vous.\n\n🏅 Badge à débloquer en validant le quiz : « J'ai compris la logique »"]],
  q:[["Pourquoi réduire les glucides en cas de diabète de type 2 ?",["Parce que le diabète de type 2 est une intolérance aux glucides : on réduit l'exposition","Pour le plaisir de se priver","Aucune raison"],0,"Moins de glucose entrant = moins de pics = moins d'insuline nécessaire."],
     ["Que se passe-t-il quand le besoin en insuline diminue ?",["Le pancréas souffle et les cellules redeviennent plus sensibles","Rien","Le corps s'arrête"],0,"C'est la cascade positive du keto."],
     ["Combien de glucides apporte une journée « moderne » typique ?",["250 à 350 g — l'équivalent de 60 à 85 morceaux de sucre","20 g","Zéro"],0,"Une charge énorme pour un pancréas déjà fatigué."],
     ["Quelle est la cible de glucides en alimentation cétogène ?",["Environ 20-50 g par jour, principalement issus des légumes","300 g par jour","Aucun glucide toléré"],0,"Les menus de l'app respectent cette cible automatiquement."],
     ["Quand la glycémie commence-t-elle à se stabiliser ?",["Généralement en 3 à 6 semaines","En une heure","Jamais"],0,"L'énergie devient constante et la faim se calme dans le même temps."]]},
 {t:"Qu'est-ce que la cétose ?",mi:"Repérez vos signaux de transition : 🔥 pendant votre première ou prochaine semaine keto, notez chaque jour votre énergie et votre faim sur 10 dans l'app. Vous verrez la bascule se dessiner — c'est votre corps qui change de carburant.",p:[
  ["👋 Introduction","« Cétose »… Le mot peut inquiéter. Il désigne pourtant un mécanisme parfaitement NATUREL que votre corps connaît depuis toujours — celui qui a permis à l'humanité de traverser les hivers et les périodes sans nourriture.\nComprendre la cétose, c'est comprendre pourquoi le keto fonctionne — et ne plus craindre le mot.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ expliquer ce qu'est la cétose nutritionnelle ;\n✅ distinguer cétose et acidocétose (rien à voir !) ;\n✅ traverser sereinement la période d'adaptation ;\n✅ reconnaître les signes de la bascule."],
  ["🔥 Le changement de carburant","Votre corps peut fonctionner avec DEUX carburants :\n⛽ LE GLUCOSE — carburant « rapide », issu des glucides : c'est le mode par défaut de l'alimentation moderne ;\n🕯️ LES GRAISSES ET LES CÉTONES — carburant « de fond » : quand les glucides se font rares, le foie transforme les graisses en CORPS CÉTONIQUES, un carburant propre et efficace que le cerveau, le cœur et les muscles adorent.\nLa CÉTOSE NUTRITIONNELLE, c'est simplement cet état où le corps brûle majoritairement des graisses — y compris les VÔTRES, celles stockées depuis des années.\nC'est un mécanisme de survie normal, utilisé par l'humanité à chaque hiver et chaque disette depuis des millénaires. Rien d'artificiel : vous rallumez simplement un moteur que l'abondance de sucre avait mis en veille.","m1c1b"],
  ["⚠️ Cétose ≠ acidocétose : ne confondez jamais","Deux mots proches, deux réalités OPPOSÉES :\n✅ LA CÉTOSE NUTRITIONNELLE — cétones modérées (0,5-3 mmol/L), glycémie normale, insuline présente qui régule tout : un état physiologique SÛR pour la grande majorité des gens ;\n🚨 L'ACIDOCÉTOSE DIABÉTIQUE — cétones très élevées (>10 mmol/L) + glycémie très haute + MANQUE D'INSULINE : une urgence médicale, qui concerne surtout le diabète de type 1 ou des situations particulières (dont certains traitements, comme les gliflozines — Module 11 !).\nLa différence clé : L'INSULINE. Tant qu'elle est présente et fonctionnelle, elle empêche les cétones de s'emballer — comme un thermostat.\n⚠️ Si vous êtes sous insuline ou gliflozine : l'avis de votre médecin est indispensable AVANT de démarrer — vous le savez déjà si vous suivez ce parcours dans l'ordre !","m1c1c"],
  ["🌡️ La période d'adaptation : la « grippe keto »","Entre le mode « sucre » et le mode « graisses », il y a une transition de 3 à 10 jours — parfois appelée « grippe keto » :\n😮‍💨 fatigue passagère, maux de tête, irritabilité, envies de sucre… Rien de grave : votre corps recrute ses nouvelles enzymes et élimine beaucoup d'eau et de sels.\nLES 3 PARADES QUI CHANGENT TOUT :\n💧 HYDRATATION généreuse (le corps élimine plus d'eau) ;\n🧂 SEL — le grand secret : un bouillon salé par jour prévient l'essentiel des symptômes (l'eau part avec le sodium !) ;\n😴 DOUCEUR : pas de sport intense la première semaine, couchez-vous tôt.\nLES SIGNES QUE LA BASCULE EST FAITE : faim qui se calme (les graisses rassasient !), énergie stable toute la journée, clarté mentale, parfois une haleine légèrement fruitée (transitoire).\n\n💡 Astuce Keto-Essenciel : préparez un grand bouillon de légumes salé dès le premier jour — votre meilleur allié de la semaine de transition.","m1c1d"],
  ["📝 À retenir","📝 À retenir :\n✔ la cétose = changement de carburant : le corps brûle les graisses (y compris les vôtres) ;\n✔ c'est un mécanisme naturel et ancestral, pas un état artificiel ;\n✔ cétose nutritionnelle ≠ acidocétose : l'insuline fait toute la différence ;\n✔ sous insuline ou gliflozine : avis médical AVANT de démarrer ;\n✔ transition de 3-10 jours : eau + sel + douceur = grippe keto évitée.\n\n🏅 Badge à débloquer en validant le quiz : « Je comprends la cétose »"]],
  q:[["Qu'est-ce que la cétose nutritionnelle ?",["Un état naturel où le corps brûle majoritairement des graisses transformées en cétones","Une maladie grave","Un état artificiel dangereux"],0,"Un mécanisme de survie que l'humanité utilise depuis des millénaires."],
     ["Quelle est la différence clé entre cétose et acidocétose ?",["L'insuline : présente et fonctionnelle, elle empêche les cétones de s'emballer","Aucune différence","La couleur des urines"],0,"Cétose = 0,5-3 mmol/L, état sûr ; acidocétose = urgence avec manque d'insuline."],
     ["Qui doit demander un avis médical AVANT de démarrer le keto ?",["Les personnes sous insuline ou gliflozine notamment","Personne","Uniquement les sportifs"],0,"Les traitements doivent parfois être adaptés — sécurité d'abord."],
     ["Quel est le grand secret contre la « grippe keto » ?",["Le sel (bouillon salé) + hydratation généreuse","Le sucre","Courir un marathon"],0,"Le corps élimine eau et sodium en début de cétose : compensez-les."],
     ["Quels signes montrent que la bascule est faite ?",["Faim calmée, énergie stable, clarté mentale","Fatigue permanente","Rien ne change"],0,"Les graisses rassasient durablement : c'est le mode « long fleuve tranquille »."]]},
 {t:"Les idées reçues",mi:"Jouez au détective : 🕵️ repérez cette semaine UNE idée reçue sur le gras ou le keto (dans une conversation, un magazine, une pub). Notez-la et écrivez en une phrase ce que vous savez maintenant qui la contredit. Votre esprit critique est votre meilleur outil santé.",p:[
  ["👋 Introduction","« Le gras bouche les artères », « le cerveau a besoin de sucre », « le keto abîme les reins »…\nCes phrases, vous les entendrez — de proches bien intentionnés, parfois même de professionnels. Ce chapitre démonte une à une les idées reçues les plus courantes, preuves à l'appui, pour que vous puissiez avancer serein et informé.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ répondre aux 6 idées reçues les plus fréquentes ;\n✅ comprendre d'où vient la peur du gras ;\n✅ distinguer les vraies nuances des faux dangers ;\n✅ dialoguer sans conflit avec les sceptiques."],
  ["🧈 « Le gras est dangereux » : l'histoire d'un malentendu","D'où vient la peur du gras ? Des années 1950-70 : des études imparfaites ont accusé les graisses de causer les maladies cardiaques. Résultat : 40 ans de produits « allégés »… compensés par du SUCRE. Et pendant ces 40 ans, obésité et diabète ont EXPLOSÉ.\nCe que dit la science moderne :\n✔ les graisses naturelles (olive, avocat, poissons gras, œufs, beurre avec modération) ne sont pas l'ennemi — les grandes méta-analyses n'ont pas confirmé le lien redouté ;\n⚠️ les VRAIS accusés : les graisses TRANS industrielles (margarines hydrogénées, fritures industrielles) et le combo explosif SUCRE + GRAISSE des produits ultra-transformés ;\n🥑 en keto, on mange des graisses de QUALITÉ, dans un contexte pauvre en glucides — un contexte métabolique complètement différent de celui des études d'époque.","m1c2b"],
  ["🧠 « Le cerveau a besoin de sucre » — et autres classiques","❌ « LE CERVEAU A BESOIN DE 130 g DE SUCRE PAR JOUR » — le cerveau a besoin de GLUCOSE, pas de sucre ALIMENTAIRE : le foie sait en fabriquer exactement ce qu'il faut (néoglucogenèse) à partir des protéines. Et en cétose, le cerveau carbure aux cétones avec bonheur — beaucoup rapportent même une clarté mentale accrue ;\n❌ « LE KETO ABÎME LES REINS » — confusion avec les régimes hyperprotéinés : le keto est riche en GRAISSES et modéré en protéines. Chez les personnes aux reins sains, aucune atteinte démontrée (reins fragiles : suivi médical, Module 8) ;\n❌ « ON MANQUE FORCÉMENT DE VITAMINES » — une assiette keto bien construite (légumes verts à volonté, œufs, poissons, abats, oléagineux) est plus dense en nutriments que l'assiette moderne pain-pâtes ;\n❌ « C'EST UN RÉGIME À LA MODE » — utilisé en médecine depuis 1921 (épilepsie) et étudié dans le diabète depuis des décennies.","m1c2c"],
  ["🗣️ Répondre aux sceptiques — sans conflit","Vous rencontrerez des sceptiques — voici comment gérer :\n😊 PAS DE PROSÉLYTISME : votre transformation parlera d'elle-même (rappelez-vous : c'est votre assiette qui convainc, pas vos discours) ;\n📊 VOS RÉSULTATS SONT VOS ARGUMENTS : « mon HbA1c est passée de 7,8 à 6,9 et mon médecin est ravi » clôt poliment la plupart des débats ;\n🩺 APPUYEZ-VOUS SUR VOTRE SUIVI MÉDICAL : « je fais ça avec mon médecin, mes analyses sont surveillées » rassure les proches inquiets — et c'est la vérité ;\n🤝 ACCUEILLEZ LES INQUIÉTUDES : derrière « tu vas te boucher les artères » il y a souvent « je m'inquiète pour toi ». Répondez à l'amour, pas à l'argument ;\n📚 et restez humble : la science évolue, les nuances existent (chapitre 5 !) — c'est justement ce qui vous distingue des dogmatiques.\n\n💡 Astuce Keto-Essenciel : la meilleure réponse aux sceptiques reste une invitation à dîner keto — régal garanti, préjugés dissous.","m1c2d"],
  ["📝 À retenir","📝 À retenir :\n✔ la peur du gras vient d'études imparfaites des années 50-70 — l'ère du « light » a nourri l'épidémie de diabète ;\n✔ les vrais accusés : graisses trans industrielles et combo sucre+graisse ultra-transformé ;\n✔ le cerveau fabrique son glucose et adore les cétones ;\n✔ keto ≠ hyperprotéiné : les reins sains ne craignent rien (reins fragiles : suivi médical) ;\n✔ face aux sceptiques : résultats, suivi médical et bienveillance — pas de débats stériles.\n\n🏅 Badge à débloquer en validant le quiz : « Je démonte les idées reçues »"]],
  q:[["D'où vient la peur du gras ?",["D'études imparfaites des années 1950-70, suivies de 40 ans de produits allégés compensés au sucre","D'une preuve scientifique définitive","De nulle part"],0,"Pendant l'ère du « light », obésité et diabète ont explosé."],
     ["Le cerveau a-t-il besoin de sucre alimentaire ?",["Non : le foie fabrique le glucose nécessaire, et le cerveau carbure très bien aux cétones","Oui, 130 g de bonbons par jour","Le cerveau ne consomme rien"],0,"C'est la néoglucogenèse — beaucoup rapportent même une clarté mentale accrue."],
     ["Le keto est-il un régime hyperprotéiné ?",["Non : il est riche en graisses et modéré en protéines","Oui, exactement pareil"],0,"D'où la confusion sur les reins — infondée chez les personnes aux reins sains."],
     ["Quels sont les VRAIS accusés côté graisses ?",["Les graisses trans industrielles et le combo sucre+graisse ultra-transformé","L'huile d'olive et l'avocat","Les œufs uniquement"],0,"Les graisses naturelles de qualité ne sont pas l'ennemi."],
     ["Quelle est la meilleure réponse aux sceptiques ?",["Vos résultats + votre suivi médical + de la bienveillance","Un débat enflammé de 3 heures","Les ignorer méchamment"],0,"Derrière l'inquiétude il y a souvent de l'affection : répondez-y."]]},
 {t:"Les bénéfices scientifiquement observés",mi:"Créez votre tableau de bord des bénéfices : 📊 notez aujourd'hui dans l'app vos valeurs de départ (HbA1c, poids, tour de taille, énergie sur 10). Dans 3 mois, comparez avec ce chapitre sous les yeux — vous mesurerez VOS bénéfices, pas ceux des études.",p:[
  ["👋 Introduction","Au-delà de la logique et des témoignages : que disent les ÉTUDES sur l'alimentation cétogène et pauvre en glucides dans le diabète de type 2 ?\nBeaucoup de choses — et de solides. Ce chapitre fait le tour des bénéfices scientifiquement observés, sans exagération ni promesse magique.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ connaître les bénéfices démontrés sur la glycémie ;\n✅ comprendre les effets sur le poids et les traitements ;\n✅ situer les effets cardiovasculaires et métaboliques ;\n✅ garder un regard honnête sur les limites des études."],
  ["🩸 Glycémie, HbA1c, traitements : les résultats phares","Les essais cliniques sur l'alimentation pauvre en glucides dans le diabète de type 2 montrent de façon répétée :\n📉 BAISSE DE L'HbA1c — souvent de 0,5 à 1,5 point en quelques mois, comparable ou supérieure à certains médicaments ;\n💊 RÉDUCTION DES TRAITEMENTS — dans plusieurs études (notamment les suivis de Virta Health sur 2 ans), une majorité de participants ont pu réduire ou arrêter certains médicaments, TOUJOURS sous supervision médicale ;\n🌟 RÉMISSIONS — une proportion significative atteint une HbA1c < 6,5 % sans médicament (hors metformine) — la rémission vue au Module 11 ;\n📊 GLYCÉMIES STABLES — moins de variabilité, moins d'hypoglycémies quand les traitements sont bien adaptés.\nCes résultats sont suffisamment solides pour que plusieurs sociétés savantes (dont l'American Diabetes Association) reconnaissent officiellement l'alimentation pauvre en glucides comme une option valide dans le diabète de type 2.","m1c3b"],
  ["⚖️ Poids, satiété, foie : la cascade des bénéfices","Au-delà de la glycémie, les études observent :\n⚖️ PERTE DE POIDS — souvent supérieure aux régimes pauvres en graisses à 6-12 mois, avec un avantage clé : la SATIÉTÉ. Graisses et protéines rassasient : on mange moins SANS compter ni lutter ;\n🫁 FOIE — la stéatose (« foie gras ») régresse souvent rapidement : moins de glucides = moins de fabrication de graisse hépatique (Module 8) ;\n📏 GRAISSE VISCÉRALE — c'est elle qui fond en priorité, d'où l'amélioration du tour de taille et de la sensibilité à l'insuline ;\n🔥 TRIGLYCÉRIDES — baisse souvent spectaculaire (−30 à −50 %) ;\n💚 HDL (le « bon cholestérol ») — remonte fréquemment ;\n🩺 TENSION ARTÉRIELLE — amélioration fréquente (perte de poids + moins d'insuline = moins de rétention de sel).","m1c3c"],
  ["🔬 Le regard honnête : nuances et limites","Rester crédible, c'est aussi connaître les nuances :\n📊 le LDL-cholestérol peut augmenter chez certaines personnes — c'est variable et cela se SURVEILLE (bilan lipidique régulier, dialogue avec le médecin — Module 8) ;\n⏳ beaucoup d'études durent 6-24 mois : les données à 10 ans sont encore rares — d'où l'importance de VOTRE suivi personnel ;\n🧍 l'adhésion est LE facteur clé : le meilleur régime est celui qu'on TIENT — et c'est là que la satiété du keto est un atout majeur ;\n🥦 la QUALITÉ compte : un keto de vraie nourriture (légumes, poissons, œufs, huile d'olive) n'a rien à voir avec un « dirty keto » de charcuterie industrielle ;\n🩺 et le message constant : ces bénéfices s'obtiennent AVEC un suivi médical, surtout sous traitement.\nAu final : une option scientifiquement solide, pas une religion — testez-la, mesurez VOS résultats, ajustez avec votre médecin.\n\n💡 Astuce Keto-Essenciel : vos propres courbes (HbA1c, poids, taille) dans l'app sont VOTRE étude scientifique personnelle — la seule qui compte vraiment pour vous.","m1c3d"],
  ["📝 À retenir","📝 À retenir :\n✔ HbA1c : baisse de 0,5 à 1,5 point souvent observée ; rémissions possibles ;\n✔ traitements souvent réduits — toujours sous supervision médicale ;\n✔ poids, foie, triglycérides, HDL, tension : la cascade de bénéfices est large ;\n✔ nuances honnêtes : LDL à surveiller, données très long terme encore rares ;\n✔ le facteur clé du succès : l'adhésion — et la satiété du keto y aide puissamment.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais les preuves »"]],
  q:[["Quelle baisse d'HbA1c les études observent-elles souvent ?",["0,5 à 1,5 point en quelques mois","5 points en une semaine","Aucune"],0,"Comparable ou supérieure à certains médicaments."],
     ["Que montrent les études sur les traitements ?",["Une majorité de participants peut souvent les réduire — sous supervision médicale","Il faut toujours en ajouter","Aucun changement possible"],0,"Notamment les suivis Virta Health sur 2 ans — jamais en solo."],
     ["Quel avantage clé explique la perte de poids en keto ?",["La satiété : graisses et protéines rassasient, on mange moins sans compter","La magie","La privation permanente"],0,"Le meilleur régime est celui qu'on tient — la satiété y aide."],
     ["Quel marqueur peut augmenter chez certains et doit être surveillé ?",["Le LDL-cholestérol","La taille des pieds","La vitamine C"],0,"Variable selon les personnes : bilan lipidique régulier et dialogue médecin."],
     ["Que reconnaissent plusieurs sociétés savantes dont l'ADA ?",["L'alimentation pauvre en glucides comme option valide dans le diabète de type 2","Que le sucre est indispensable","Rien"],0,"Une option scientifiquement solide — pas une religion."]]},
 {t:"Quand le keto n'est pas indiqué",mi:"Faites votre check-list de sécurité : ✅ relisez les situations de ce chapitre et vérifiez si l'une vous concerne (traitements hypoglycémiants, gliflozine, grossesse, maladie rénale…). Si oui : notez-le et prenez rendez-vous avec votre médecin AVANT d'aller plus loin. Sinon : feu vert, en route !",p:[
  ["👋 Introduction","L'honnêteté avant tout : l'alimentation cétogène ne convient pas à tout le monde, ni à toutes les situations.\nCe chapitre — peut-être le plus important du module — liste clairement les cas où le keto est déconseillé, et ceux où il exige un encadrement médical strict. Votre sécurité passe avant tout enthousiasme.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ identifier les contre-indications franches ;\n✅ reconnaître les situations à encadrement médical obligatoire ;\n✅ comprendre pourquoi les traitements doivent être adaptés ;\n✅ démarrer (ou pas) en toute sécurité."],
  ["🚫 Les contre-indications franches","Dans ces situations, le keto strict est DÉCONSEILLÉ (sauf avis spécialisé contraire) :\n👶 GROSSESSE ET ALLAITEMENT — les besoins sont particuliers : une alimentation simplement « moins sucrée et non transformée » est préférable au keto strict ;\n🧬 MALADIES MÉTABOLIQUES RARES — déficits enzymatiques du métabolisme des graisses (vous le sauriez : diagnostics précoces) ;\n🍽️ ANTÉCÉDENTS DE TROUBLES DU COMPORTEMENT ALIMENTAIRE — toute restriction structurée peut raviver le trouble : accompagnement spécialisé d'abord ;\n🫘 INSUFFISANCE RÉNALE AVANCÉE — l'alimentation se décide avec le néphrologue ;\n🧒 ENFANTS ET ADOLESCENTS — hors indication médicale précise (épilepsie), croissance oblige ;\n⚖️ INSUFFISANCE PONDÉRALE ou dénutrition.\nDans le doute : demandez. Un avis médical de 15 minutes vaut mieux que des mois d'incertitude.","m1c4b"],
  ["🩺 Les situations à encadrement médical OBLIGATOIRE","Ici, le keto est possible — mais JAMAIS sans votre médecin :\n💉 SOUS INSULINE — la réduction des glucides fait baisser la glycémie : sans adaptation des doses, risque d'HYPOGLYCÉMIE sévère. Le médecin ajuste AVANT et PENDANT la transition ;\n⚡ SOUS SULFAMIDES OU GLINIDES — même mécanisme, même exigence (Module 11) ;\n💧 SOUS GLIFLOZINES (SGLT2) — risque accru de cétoacidose euglycémique en keto strict : compatibilité à évaluer par le médecin ;\n🩺 DIABÈTE DE TYPE 1 — approche possible mais très spécialisée : uniquement avec une équipe expérimentée ;\n💊 AUTRES TRAITEMENTS SENSIBLES — antihypertenseurs (la tension baisse souvent en keto : doses à revoir), anticoagulants, lithium… : signalez votre changement d'alimentation ;\n🫀 maladies cardiaques, hépatiques ou rénales évolutives : feu vert médical d'abord.\nLA RÈGLE D'OR : tout traitement qui fait baisser la glycémie ou la tension devra probablement être ADAPTÉ — c'est un signe que ça marche, mais ça s'anticipe !","m1c4c"],
  ["✅ Bien démarrer en sécurité — votre feuille de route","VOTRE CHECK-LIST DE DÉMARRAGE :\n1️⃣ je vérifie les situations des pages précédentes — concerné ? → rendez-vous médical AVANT ;\n2️⃣ traité pour le diabète ou l'hypertension ? → j'informe mon médecin de mon projet et j'apporte ce parcours en consultation ;\n3️⃣ je fais (ou j'ai) un bilan sanguin de départ récent : HbA1c, lipides, reins, foie (Module 8) — ma photo de départ ;\n4️⃣ je surveille davantage ma glycémie pendant la transition si je suis traité ;\n5️⃣ je démarre progressivement avec les menus de l'app, eau + sel pour la transition (chapitre 2 !) ;\n6️⃣ tout signal inhabituel (malaises, hypos répétées) → médecin, sans attendre.\nEt si le keto strict n'est pas pour vous ? Une alimentation simplement PAUVRE EN GLUCIDES et non transformée apporte déjà d'immenses bénéfices — l'app propose des modes adaptés. Il n'y a pas UNE seule voie vers la santé.\n\n💡 Astuce Keto-Essenciel : imprimez ou montrez cette check-list à votre médecin — elle structure la discussion et montre votre sérieux. La suite du parcours (Module 3 : Bien manger) vous attend !","m1c4d"],
  ["📝 À retenir — et bravo pour ce module !","📝 À retenir :\n✔ contre-indications franches : grossesse, TCA, maladies métaboliques rares, insuffisance rénale avancée, enfants ;\n✔ encadrement médical OBLIGATOIRE : insuline, sulfamides, gliflozines, diabète de type 1 ;\n✔ traitements hypoglycémiants et antihypertenseurs : adaptation à anticiper avec le médecin ;\n✔ bilan de départ + surveillance renforcée pendant la transition ;\n✔ le keto strict n'est pas la seule voie : pauvre en glucides et non transformé, c'est déjà immense.\n\n🎓 Dans ce Module 2, vous avez appris : la logique de la réduction des glucides, la cétose et sa sécurité, les idées reçues démontées, les preuves scientifiques et les situations de prudence.\n\n🏅 Après ce chapitre, le Quiz final du module (10 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge 🥑 « Je sais pourquoi le keto » !"]],
  q:[["Dans quelle situation le keto strict est-il déconseillé ?",["Grossesse, troubles du comportement alimentaire, insuffisance rénale avancée notamment","Après 50 ans","Quand on aime les légumes"],0,"Dans le doute : un avis médical de 15 minutes vaut mieux que des mois d'incertitude."],
     ["Pourquoi l'encadrement médical est-il OBLIGATOIRE sous insuline ou sulfamides ?",["La baisse des glucides fait baisser la glycémie : sans adaptation des doses, risque d'hypoglycémie sévère","Pour la paperasse","Ce n'est pas obligatoire"],0,"Le médecin ajuste avant et pendant la transition."],
     ["Quel risque spécifique existe sous gliflozine en keto strict ?",["La cétoacidose euglycémique : compatibilité à évaluer par le médecin","Aucun","Des cheveux blancs"],0,"Les deux augmentent les cétones — le médecin tranche."],
     ["Que peut-il arriver à la tension artérielle en keto ?",["Elle baisse souvent : les antihypertenseurs peuvent devoir être adaptés","Elle explose toujours","Rien jamais"],0,"C'est un signe que ça marche — mais ça s'anticipe avec le médecin."],
     ["Le keto strict est-il la seule voie vers la santé ?",["Non : une alimentation pauvre en glucides et non transformée apporte déjà d'immenses bénéfices","Oui, c'est tout ou rien"],0,"L'app propose des modes adaptés — il n'y a pas une seule voie."]]}
],fq:[
 ["Pourquoi réduire les glucides dans le diabète de type 2 ?",["C'est une intolérance aux glucides : on réduit l'exposition au problème","Pour suivre la mode","Pour manger moins bon","Aucune raison"],0,"Moins de glucose → moins d'insuline → pancréas soulagé → sensibilité restaurée."],
 ["Combien de glucides apporte l'alimentation moderne typique, contre le keto ?",["250-350 g/jour contre 20-50 g/jour","Autant dans les deux cas","10 g contre 500 g","Personne ne sait"],0,"L'équivalent de 60-85 morceaux de sucre par jour pour un pancréas fatigué."],
 ["Qu'est-ce que la cétose nutritionnelle ?",["Un état naturel où le corps brûle des graisses transformées en cétones par le foie","Une urgence médicale","Un mythe","Une maladie rare"],0,"Le carburant de secours ancestral — cerveau, cœur et muscles l'adorent."],
 ["Qu'est-ce qui distingue la cétose de l'acidocétose ?",["L'insuline présente et fonctionnelle, qui empêche l'emballement des cétones","Rien du tout","La saison","L'âge"],0,"Cétose : 0,5-3 mmol/L, état sûr ; acidocétose : urgence avec manque d'insuline."],
 ["Comment éviter la « grippe keto » des premiers jours ?",["Hydratation généreuse + sel (bouillon) + douceur la première semaine","En mangeant plus de sucre","En courant un marathon","C'est impossible"],0,"L'eau part avec le sodium : compensez les deux."],
 ["Le cerveau a-t-il besoin de sucre alimentaire ?",["Non : le foie fabrique le glucose nécessaire et le cerveau carbure bien aux cétones","Oui, absolument","Le cerveau ne consomme rien","Uniquement le matin"],0,"Néoglucogenèse + cétones : le duo qui nourrit le cerveau sans bonbons."],
 ["Quels sont les vrais accusés côté graisses ?",["Les graisses trans industrielles et le combo sucre+graisse ultra-transformé","L'avocat et l'huile d'olive","Les poissons gras","Les œufs"],0,"Les graisses naturelles de qualité ne sont pas l'ennemi."],
 ["Quels bénéfices les études observent-elles avec le keto dans le diabète de type 2 ?",["Baisse d'HbA1c (0,5-1,5 pt), réduction fréquente des traitements, triglycérides en baisse","Aucun bénéfice","Uniquement de la fatigue","Une prise de poids"],0,"Reconnu comme option valide par plusieurs sociétés savantes dont l'ADA."],
 ["Quel marqueur surveiller car il peut augmenter chez certains ?",["Le LDL-cholestérol","La vitamine D","Le fer","Le magnésium"],0,"Variable selon les personnes : bilan lipidique régulier avec le médecin."],
 ["Qui doit impérativement consulter AVANT de démarrer le keto ?",["Les personnes sous insuline, sulfamides ou gliflozine, et les situations particulières (grossesse, reins…)","Personne","Uniquement les végétariens","Les gens pressés"],0,"Les traitements doivent être adaptés : sécurité avant enthousiasme."]
],bd:"🥑 Je sais pourquoi le keto",sk:["Expliquer la logique « moins de glucides = moins d'insuline »","Comprendre la cétose et la distinguer de l'acidocétose","Traverser la transition (eau + sel) sereinement","Démonter les idées reçues sur le gras et le keto","Connaître les bénéfices scientifiquement observés — et leurs nuances","Identifier les situations qui exigent un avis médical avant de démarrer"]}'''

src = src[:i] + NEW + ',\n' + src[j+len(']},\n'):]
io.open(PATH,'w',encoding='utf-8').write(src)
print('OK: Module 2 = 5 chapitres au format complet + quiz final 10 q')
