#!/usr/bin/env python3
# Module 6 : remplace ch.5 "Les étirements" par "Le stress", ajoute ch.6-10 + quiz final (fq/bd/sk)
import io, sys

PATH = '/app/keto.html'
src = io.open(PATH, encoding='utf-8').read()

OLD = r''' {t:"Les étirements",p:[
  ["Souplesse et récupération","Les étirements entretiennent la mobilité, diminuent les tensions et favorisent la récupération et la détente (utile aussi pour le stress — Module 9 !).\nLe meilleur moment : après l'effort ou le soir, quand les muscles sont chauds. Jamais d'étirement violent à froid."],
  ["La routine de 5 minutes","À faire chaque soir :\n• Nuque : inclinez doucement la tête de chaque côté, 20 s.\n• Épaules : roulez-les lentement 10 fois.\n• Dos : assis, tournez doucement le buste de chaque côté, 20 s.\n• Ischio-jambiers : debout, penchez-vous vers l'avant jambes légèrement fléchies, 30 s.\n• Respirez profondément pendant chaque étirement — cette routine prépare aussi un meilleur sommeil."]],
  q:[["Quel est le meilleur moment pour s'étirer ?",["À froid, brutalement","Après l'effort ou le soir, muscles chauds","Jamais"],1,"Muscles chauds + gestes doux = étirements efficaces et sans risque."],
     ["Que faut-il faire pendant un étirement ?",["Bloquer sa respiration","Respirer profondément","Sautiller"],1,"La respiration profonde amplifie la détente musculaire et nerveuse."]]}
]},'''

NEW = r''' {t:"Le stress : comprendre son impact et apprendre à le gérer",mi:"Aujourd'hui, offrez-vous une pause respiration : 🌬️ 5 minutes de respiration lente (inspirez 5 secondes, expirez 5 secondes), assis confortablement. Notez ensuite comment vous vous sentez. Bonus : identifiez votre principale source de stress de la journée et une petite action pour l'alléger.",p:[
  ["👋 Introduction","Le stress fait partie de la vie. Face à un imprévu, une contrariété ou une inquiétude, votre corps réagit : c'est un mécanisme normal et utile.\nMais lorsque le stress devient fréquent ou permanent, il peut peser sur votre bien-être… et sur votre glycémie.\nLa bonne nouvelle : il existe des outils simples, accessibles à tous, pour apprendre à mieux le gérer.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre l'impact du stress sur votre organisme et votre glycémie ;\n✅ reconnaître les signes d'un stress qui s'installe ;\n✅ utiliser des techniques simples pour retrouver votre calme."],
  ["🧠 Stress et glycémie : quel lien ?","Face au stress, votre organisme libère des hormones comme le cortisol et l'adrénaline. Leur rôle : préparer le corps à réagir, notamment en libérant du glucose dans le sang.\nPonctuel, ce mécanisme est sans conséquence. Mais un stress qui dure peut contribuer à maintenir une glycémie plus élevée et rendre son équilibre plus difficile.\nLe stress chronique peut aussi favoriser :\n🍫 le grignotage et les envies de sucre ;\n😴 un sommeil de moins bonne qualité ;\n📉 une baisse de motivation pour bouger et bien manger.\n\n🚨 Les signes à repérer : tensions musculaires (nuque, mâchoires), irritabilité, fatigue persistante, difficultés de concentration, troubles du sommeil. Les reconnaître est déjà un premier pas.","m5c4b"],
  ["🌬️ La respiration : votre outil n°1","La respiration lente est l'un des moyens les plus simples et les plus rapides d'apaiser le système nerveux.\nEssayez la respiration en rythme régulier :\n✔ installez-vous confortablement, dos droit ;\n✔ inspirez doucement par le nez pendant 5 secondes ;\n✔ expirez lentement pendant 5 secondes ;\n✔ continuez pendant 5 minutes.\nPratiquée quelques minutes, plusieurs fois par jour (par exemple matin, midi et soir), cette technique aide à relâcher la pression.\nElle est discrète : vous pouvez la pratiquer partout, même au bureau ou dans les transports.","m5c4c"],
  ["🌿 D'autres alliés anti-stress","Plusieurs habitudes contribuent à faire baisser la pression au quotidien :\n🚶 bouger régulièrement — l'activité physique est un excellent régulateur du stress ;\n😴 dormir suffisamment (voir le chapitre précédent) ;\n🌳 passer du temps dans la nature ;\n🤝 entretenir des liens sociaux et parler de ce que vous vivez ;\n🎨 garder du temps pour vos loisirs et ce qui vous fait du bien ;\n☕ limiter les excès de café et d'alcool.\n\n⚠️ Si le stress ou l'anxiété devient envahissant, perturbe durablement votre sommeil ou votre quotidien, parlez-en à votre médecin : un accompagnement adapté peut faire toute la différence.\n\n💡 Astuce Keto-Essenciel : programmez des micro-pauses. Deux ou trois fois par jour, arrêtez-vous 2 minutes : respirez lentement, détendez vos épaules et votre mâchoire, puis reprenez votre activité. Ces petites pauses répétées évitent au stress de s'accumuler.","m5c4d"],
  ["📝 À retenir","📝 À retenir :\n✔ le stress est une réaction normale, mais un stress qui dure peut peser sur la glycémie ;\n✔ tensions, irritabilité et sommeil perturbé sont des signaux à écouter ;\n✔ la respiration lente est un outil simple, discret et efficace ;\n✔ mouvement, sommeil, nature et liens sociaux sont vos alliés ;\n✔ n'hésitez pas à demander de l'aide si le stress devient envahissant.\n\n🏅 Badge à débloquer en validant le quiz : « Je gère mon stress »"]],
  q:[["Le stress peut-il influencer la glycémie ?",["Non","Oui, les hormones du stress peuvent la faire monter"],1,"Cortisol et adrénaline libèrent du glucose pour préparer le corps à réagir."],
     ["Quel est un signe fréquent de stress qui s'installe ?",["Tensions, irritabilité, sommeil perturbé","Une énergie parfaitement stable"],0,"Le stress qui dure laisse des traces : corps tendu, humeur et sommeil perturbés."],
     ["Quel outil simple aide à apaiser le stress ?",["La respiration lente et profonde","Boire plus de café","S'endormir devant les écrans"],0,"Quelques minutes de respiration lente suffisent à calmer le système nerveux."],
     ["Combien de temps de respiration lente est déjà utile ?",["Au moins une heure d'affilée","Quelques minutes, plusieurs fois par jour"],1,"5 minutes, deux à trois fois par jour : simple, discret, efficace."],
     ["Que faire si le stress devient envahissant ?",["Le garder pour soi","En parler à un professionnel de santé"],1,"Un accompagnement adapté peut faire toute la différence."]]},
 {t:"L'hydratation : un pilier souvent oublié",mi:"Aujourd'hui, gardez une bouteille ou une carafe d'eau à portée de main : 💧 buvez un verre d'eau au réveil, un verre avant chaque repas, et observez la couleur de vos urines en fin de journée (claires = bonne hydratation).",p:[
  ["👋 Introduction","On parle beaucoup d'alimentation et d'activité physique… et on oublie souvent l'essentiel : l'eau.\nVotre corps est composé d'environ 60 % d'eau. Elle participe à la digestion, au transport des nutriments, à l'élimination des déchets et à la régulation de la température.\nBien s'hydrater est un geste simple qui soutient votre énergie, votre concentration et l'équilibre de votre glycémie.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi l'hydratation est essentielle, surtout en cas de diabète ;\n✅ reconnaître les signes de déshydratation ;\n✅ adopter des réflexes simples pour boire suffisamment chaque jour."],
  ["💧 Pourquoi l'eau est-elle si importante ?","Une bonne hydratation contribue à :\n🩸 maintenir un bon volume sanguin et une circulation fluide ;\n🧠 soutenir la concentration et limiter la fatigue ;\n🍽️ faciliter la digestion et le transit ;\n🌡️ réguler la température du corps.\n\n🩺 En cas de diabète, l'hydratation mérite une attention particulière : lorsque la glycémie est élevée, l'organisme élimine davantage d'eau par les urines pour évacuer l'excès de glucose. Le risque de déshydratation est donc plus important.\nDe plus, au début d'une alimentation cétogène, le corps retient moins d'eau : les besoins peuvent augmenter.","m5c5b"],
  ["🚰 Reconnaître les signes de déshydratation","Les signaux les plus fréquents :\n💛 urines foncées et moins abondantes ;\n😴 fatigue inhabituelle ;\n🤕 maux de tête ;\n👄 bouche et lèvres sèches ;\n😵 sensations de vertige en se levant.\nLa soif elle-même est un signal tardif : lorsqu'elle apparaît, la déshydratation a souvent déjà commencé.\n⚠️ Avec l'âge, la sensation de soif diminue : les personnes de plus de 60 ans doivent être particulièrement attentives, ainsi qu'en période de chaleur, de fièvre ou d'activité physique.","m5c5c"],
  ["🥤 Les bons réflexes au quotidien","Pour la plupart des adultes, 1,5 à 2 litres d'eau par jour constituent une bonne référence (à adapter selon votre situation et l'avis de votre médecin, notamment en cas de problème cardiaque ou rénal).\nQuelques réflexes simples :\n✔ un verre d'eau au réveil ;\n✔ un verre avant chaque repas ;\n✔ une bouteille ou une carafe toujours visible ;\n✔ boire un peu plus en cas de chaleur ou d'activité physique.\nÀ privilégier : 💧 eau plate ou gazeuse, 🌿 infusions sans sucre, 🍵 thé léger, 🥣 bouillons.\nÀ limiter : 🥤 sodas et jus industriels (même « light », ils entretiennent l'attrait pour le goût sucré), 🍷 alcool qui favorise la déshydratation.\n\n💡 Astuce Keto-Essenciel : utilisez une bouteille graduée ou remplissez votre carafe le matin. Voir ce qu'il reste à boire dans la journée est le moyen le plus simple de ne pas oublier.","m5c5d"],
  ["📝 À retenir","📝 À retenir :\n✔ l'eau participe à presque toutes les fonctions de votre organisme ;\n✔ une glycémie élevée augmente les pertes en eau : l'hydratation est encore plus importante en cas de diabète ;\n✔ urines foncées, fatigue et maux de tête doivent faire penser à la déshydratation ;\n✔ buvez régulièrement, sans attendre la soif ;\n✔ l'eau et les infusions sans sucre sont vos meilleures alliées.\n\n🏅 Badge à débloquer en validant le quiz : « Je pense à bien m'hydrater »"]],
  q:[["Pourquoi l'hydratation est-elle particulièrement importante en cas de diabète ?",["Une glycémie élevée peut augmenter l'élimination d'eau par les urines","L'eau fait monter la glycémie"],0,"Pour évacuer l'excès de glucose, le corps élimine plus d'eau : le risque de déshydratation augmente."],
     ["Quel est un signe possible de déshydratation ?",["Urines foncées, fatigue, maux de tête, bouche sèche","Une grande énergie"],0,"Des urines claires sont au contraire un bon repère d'hydratation suffisante."],
     ["Quelle boisson privilégier au quotidien ?",["L'eau et les infusions sans sucre","Les sodas","Les jus de fruits industriels"],0,"L'eau reste la référence ; les infusions et bouillons complètent agréablement."],
     ["Faut-il attendre d'avoir soif pour boire ?",["Oui, toujours","Non, mieux vaut boire régulièrement : la soif est un signal tardif"],1,"Quand la soif apparaît, la déshydratation a souvent déjà commencé — surtout après 60 ans."],
     ["Quel réflexe simple aide à boire suffisamment ?",["Un verre d'eau à chaque repas et une bouteille à portée de main","Boire un litre d'un coup le soir"],0,"Répartir les apports tout au long de la journée est plus efficace et plus confortable."]]},
 {t:"Suivre ses progrès sans devenir obsédé",mi:"Choisissez votre jour de bilan hebdomadaire : 📅 notez ce jour-là votre poids, votre tour de taille et votre niveau d'énergie (sur 10) dans l'onglet Suivi. Un seul rendez-vous par semaine suffit.",p:[
  ["👋 Introduction","Suivre ses progrès est motivant… à condition de le faire intelligemment.\nSe peser tous les matins, vérifier sa glycémie avec anxiété ou se comparer aux autres : ces habitudes découragent plus qu'elles n'aident.\nDans ce chapitre, vous allez apprendre quels indicateurs suivre, à quel rythme, et surtout comment les interpréter avec sérénité.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ choisir les indicateurs les plus utiles pour vous ;\n✅ les mesurer au bon rythme ;\n✅ interpréter les résultats sans vous décourager."],
  ["📊 Les indicateurs qui comptent vraiment","Inutile de tout mesurer. Quelques repères bien choisis suffisent :\n⚖️ le poids — environ une fois par semaine, le même jour, dans les mêmes conditions (le matin, à jeun) ;\n📏 le tour de taille — un excellent reflet de la graisse abdominale, souvent plus parlant que la balance ;\n🩸 la glycémie — selon les recommandations de votre médecin (à jeun, avant les repas…) ;\n⚡ l'énergie, l'humeur et le sommeil — notez-les simplement sur 10 ;\n🚶 l'activité physique — nombre de pas ou minutes de mouvement dans la journée.\nCes indicateurs se complètent : ensemble, ils racontent votre progression bien mieux qu'un seul chiffre.","m5c6b"],
  ["📉 Interpréter sans se décourager","Quelques règles d'or pour garder le moral :\n✔ le poids fluctue naturellement d'un jour à l'autre (eau, digestion, hormones) — une variation de ±1 kg ne veut rien dire ;\n✔ ce qui compte, c'est la TENDANCE sur plusieurs semaines, pas la valeur d'un jour ;\n✔ un plateau est normal : le corps s'adapte et se recompose (si le tour de taille diminue, vous progressez encore) ;\n✔ une glycémie ponctuellement plus élevée n'est pas un échec : cherchez la cause (repas, stress, sommeil) et ajustez ;\n✔ ne vous comparez qu'à vous-même — chacun avance à son rythme.\nUn chiffre décevant n'est pas un verdict : c'est une information qui vous aide à ajuster.","m5c6c"],
  ["📔 Vos outils Keto-Essenciel","L'application est conçue pour vous simplifier le suivi :\n⚖️ l'onglet Suivi enregistre votre poids et trace votre courbe automatiquement ;\n🩸 en mode Diabète, le tableau de bord regroupe glycémies, traitement et habitudes de vie, avec un score quotidien ;\n📏 les mesures corporelles (tour de taille, hanches…) se notent en quelques secondes ;\n😊 humeur, sommeil et pas complètent le tableau.\nQuelques minutes par semaine suffisent pour voir vos progrès prendre forme.\n\n💡 Astuce Keto-Essenciel : choisissez UN jour de bilan fixe (par exemple le dimanche matin) et tenez-vous-y. Entre deux bilans, rangez la balance : vous vous libérez de la pression des fluctuations quotidiennes.","m5c6d"],
  ["📝 À retenir","⚠️ Les pièges à éviter :\n❌ se peser tous les jours et réagir à chaque variation ;\n❌ ne suivre que le poids en ignorant les autres progrès ;\n❌ se comparer aux autres ;\n❌ transformer le suivi en source d'anxiété.\n\n📝 À retenir :\n✔ quelques indicateurs bien choisis valent mieux que des mesures permanentes ;\n✔ la tendance sur plusieurs semaines compte plus que la valeur du jour ;\n✔ le tour de taille et l'énergie en disent souvent plus que la balance ;\n✔ le suivi est un outil au service de votre sérénité, pas l'inverse.\n\n🏅 Badge à débloquer en validant le quiz : « Je suis mes progrès avec sérénité »"]],
  q:[["À quelle fréquence est-il raisonnable de se peser ?",["Plusieurs fois par jour","Environ une fois par semaine, dans les mêmes conditions"],1,"Un rendez-vous hebdomadaire suffit : la balance quotidienne ne mesure que du bruit."],
     ["Que penser d'une variation de poids d'un jour à l'autre ?",["C'est un échec","C'est normal : eau, digestion et hormones font fluctuer le poids"],1,"±1 kg d'un jour à l'autre ne veut rien dire — regardez la tendance."],
     ["Quel indicateur reflète bien la graisse abdominale ?",["Le tour de taille","La pointure","La taille des mains"],0,"Le mètre ruban est souvent plus parlant que la balance."],
     ["Qu'est-ce qui compte le plus dans le suivi ?",["La valeur d'un seul jour","La tendance sur plusieurs semaines"],1,"C'est la direction générale qui raconte vos progrès."],
     ["Que faire si le poids stagne malgré vos efforts ?",["Tout arrêter","Regarder les autres progrès (tour de taille, énergie, glycémie) et ajuster en douceur"],1,"Un plateau est une adaptation normale — les autres indicateurs continuent souvent de s'améliorer."]]},
 {t:"Rester motivé et créer des habitudes durables",mi:"Choisissez UNE mini-habitude à installer cette semaine (2 minutes maximum) : 🚶 5 minutes de marche après le déjeuner, 💧 un verre d'eau au réveil, ou 🧘 3 respirations profondes avant chaque repas. Accrochez-la à une habitude existante et cochez chaque jour réussi.",p:[
  ["👋 Introduction","Vous avez sûrement déjà vécu cela : une motivation débordante au départ… qui s'essouffle au bout de quelques semaines.\nRassurez-vous : c'est parfaitement normal. La motivation est une émotion, et comme toute émotion, elle fluctue.\nLe secret des personnes qui réussissent sur la durée n'est pas une volonté hors du commun : ce sont des HABITUDES bien construites, qui fonctionnent même les jours sans motivation.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi la motivation fluctue ;\n✅ construire des habitudes qui tiennent dans le temps ;\n✅ rebondir après une interruption sans culpabiliser."],
  ["🔥 Pourquoi la motivation fluctue","La motivation dépend de votre énergie, de votre humeur, de votre sommeil, des événements de la vie… Elle est précieuse pour DÉMARRER, mais trop instable pour DURER.\nCompter uniquement sur la volonté, c'est comme espérer du soleil tous les jours : un jour ou l'autre, il pleut.\nLa solution : transformer vos bonnes résolutions en automatismes. Une habitude installée ne demande presque plus d'effort — comme se brosser les dents.\nC'est pour cela que les petits gestes répétés chaque jour battent toujours les grands projets abandonnés au bout d'un mois.","m5c7b"],
  ["🧱 La mécanique des habitudes","Une habitude repose sur trois éléments :\n1️⃣ un DÉCLENCHEUR — un moment ou un geste existant (après le déjeuner, en me levant…) ;\n2️⃣ une ACTION simple — la nouvelle habitude, en version facile ;\n3️⃣ une SATISFACTION — cocher un calendrier, noter son progrès, se féliciter.\nLes clés pour réussir :\n✔ commencez PETIT : 2 minutes suffisent au début (5 minutes de marche, 1 verre d'eau…) ;\n✔ accrochez la nouvelle habitude à une routine existante : « après mon café du matin, je bois un grand verre d'eau » ;\n✔ une seule nouvelle habitude à la fois ;\n✔ visez la régularité, pas la performance.","m5c7c"],
  ["🎯 Tenir sur la durée","Quelques stratégies qui font la différence :\n🏆 célébrez les petites victoires — chaque jour réussi compte ;\n📅 suivez vos jours réussis (calendrier, application) : voir la série grandir motive à la poursuivre ;\n🤝 parlez de vos objectifs à vos proches ou trouvez un partenaire de marche ;\n🔁 après une interruption (vacances, maladie, coup de mou), reprenez SIMPLEMENT, sans chercher à « rattraper » ;\n💬 remplacez « j'ai échoué » par « j'ai appris quelque chose sur ce qui me freine ».\nRappelez-vous : rater un jour n'efface pas vos progrès. C'est l'abandon complet qui fait reculer — jamais la pause.\n\n💡 Astuce Keto-Essenciel : la règle des 2 minutes. Si une habitude vous semble insurmontable aujourd'hui, faites-en seulement 2 minutes. L'essentiel n'est pas la durée : c'est de ne pas casser la chaîne.","m5c7d"],
  ["📝 À retenir","⚠️ Les pièges à éviter :\n❌ compter uniquement sur la volonté ;\n❌ vouloir tout changer d'un coup ;\n❌ viser la perfection ;\n❌ abandonner après une interruption.\n\n📝 À retenir :\n✔ la motivation fluctue : c'est normal, prévoyez-le ;\n✔ les habitudes battent la volonté sur la durée ;\n✔ commencez petit et accrochez chaque habitude à une routine existante ;\n✔ célébrez vos victoires et reprenez sans culpabilité après une pause.\n\n🏅 Badge à débloquer en validant le quiz : « Je construis des habitudes durables »"]],
  q:[["La motivation est-elle constante ?",["Oui","Non, elle fluctue naturellement — c'est normal"],1,"La motivation est une émotion : précieuse pour démarrer, trop instable pour durer."],
     ["Sur quoi repose une habitude durable ?",["La volonté seule","Un déclencheur, une action simple et une satisfaction"],1,"C'est la mécanique déclencheur → action → satisfaction qui crée l'automatisme."],
     ["Comment démarrer une nouvelle habitude ?",["Voir très grand dès le premier jour","Commencer petit (2 minutes) et l'accrocher à une routine existante"],1,"Petit + accroché à l'existant = l'habitude s'installe presque toute seule."],
     ["Que faire après quelques jours d'interruption ?",["Abandonner","Reprendre simplement, sans culpabilité"],1,"Une pause n'efface pas vos progrès — seul l'abandon complet fait reculer."],
     ["Qu'est-ce qui aide à tenir sur la durée ?",["Célébrer les petites victoires et s'entourer","Se critiquer sévèrement"],0,"Les encouragements — les vôtres et ceux de vos proches — nourrissent la régularité."]]},
 {t:"Les idées reçues sur le diabète, le sport et l'alimentation",mi:"Repensez à une idée reçue que vous avez longtemps crue sur le diabète, le sport ou l'alimentation. 🔍 Qu'en dit ce module ? Notez ce que vous savez maintenant et, au besoin, parlez-en à votre médecin lors de votre prochain rendez-vous.",p:[
  ["👋 Introduction","« Le diabète, c'est parce que tu manges trop de sucre. » « Le sport est dangereux pour toi. » « Le gras bouche les artères. »\nVous avez sans doute déjà entendu ces phrases. Entre les conseils de l'entourage, les publicités et les réseaux sociaux, difficile de démêler le vrai du faux.\nDans ce chapitre, nous allons déconstruire les idées reçues les plus fréquentes et vous donner des repères pour reconnaître une information fiable.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ identifier les principaux mythes sur le diabète, le sport et l'alimentation ;\n✅ comprendre ce qu'en dit la connaissance actuelle ;\n✅ reconnaître les sources d'information fiables."],
  ["🍬 Les mythes sur le diabète","❌ « Le diabète de type 2 vient uniquement du sucre. »\n✔ En réalité, c'est une maladie multifactorielle : hérédité, âge, sédentarité, poids, alimentation globale et stress jouent tous un rôle. Se sentir « coupable » n'aide pas — agir sur son mode de vie, oui.\n\n❌ « Diabète = plus jamais de plaisir à table. »\n✔ Faux : vous l'avez vu dans le module Cuisine, on peut se régaler en prenant soin de sa glycémie.\n\n❌ « Le diabète de type 2 ne peut jamais s'améliorer. »\n✔ L'alimentation, l'activité physique, le sommeil et la gestion du stress peuvent contribuer à améliorer l'équilibre glycémique, en lien avec votre équipe soignante. Chaque situation est unique, mais les progrès sont possibles.","m5c8b"],
  ["🏃 Les mythes sur le sport","❌ « Le sport est dangereux quand on est diabétique. »\n✔ Adaptée et progressive, l'activité physique est généralement bénéfique. Quelques précautions s'imposent (avis médical, surveillance en cas de traitement à risque d'hypoglycémie), mais l'inactivité est bien plus risquée que le mouvement.\n\n❌ « Il faut souffrir pour que ce soit efficace. »\n✔ Faux : la marche, le jardinage ou la danse comptent. La régularité bat l'intensité.\n\n❌ « À mon âge, c'est trop tard pour commencer. »\n✔ Il n'est JAMAIS trop tard : les bénéfices apparaissent à tout âge, même en commençant par 10 minutes par jour.","m5c8c"],
  ["🥑 Les mythes sur l'alimentation — et comment s'informer","❌ « Le gras est l'ennemi. »\n✔ Les graisses de qualité (olive, avocat, poissons gras, beurre…) sont utiles à l'organisme. Ce sont surtout les excès de sucres et de produits ultra-transformés qui posent problème.\n\n❌ « Un produit “sans sucre” est toujours un bon choix. »\n✔ Pas forcément : lisez la composition (glucides totaux, édulcorants, additifs). Un aliment brut reste souvent le meilleur choix.\n\n❌ « Il faut manger 5 à 6 fois par jour. »\n✔ Aucun rythme n'est universel : écoutez votre faim réelle.\n\n🔍 Reconnaître une information fiable :\n✔ elle cite des sources sérieuses (autorités de santé, professionnels) ;\n✔ elle ne promet PAS de résultats miracles ou immédiats ;\n✔ elle ne cherche pas d'abord à vous vendre un produit ;\n✔ en cas de doute, parlez-en à votre médecin ou pharmacien.\n\n💡 Astuce Keto-Essenciel : avant de partager ou d'appliquer un conseil santé vu sur les réseaux, posez-vous trois questions : Qui parle ? Que vend-il ? Quelles sont ses sources ?","m5c8d"],
  ["📝 À retenir","📝 À retenir :\n✔ le diabète de type 2 est multifactoriel — la culpabilité n'a pas sa place ;\n✔ l'activité physique adaptée est une alliée, pas un danger ;\n✔ les graisses de qualité ne sont pas l'ennemi ; les mentions marketing, si, parfois ;\n✔ méfiez-vous des promesses miracles et vérifiez les sources ;\n✔ votre équipe soignante reste votre meilleur repère.\n\n🏅 Badge à débloquer en validant le quiz : « Je m'informe avec discernement »"]],
  q:[["Le diabète de type 2 est-il causé uniquement par le sucre ?",["Oui","Non, c'est une maladie multifactorielle (hérédité, âge, mode de vie…)"],1,"Plusieurs facteurs se combinent — la culpabilité n'aide pas, les actions du quotidien oui."],
     ["Le sport est-il dangereux pour les personnes diabétiques ?",["Oui, toujours","Non : adapté et progressif, il est généralement bénéfique — demandez conseil à votre médecin"],1,"L'inactivité est bien plus risquée que le mouvement adapté."],
     ["Est-il trop tard pour commencer à bouger après 60 ans ?",["Oui","Non, il n'est jamais trop tard pour en tirer des bénéfices"],1,"Les bénéfices du mouvement apparaissent à tout âge, même en commençant petit."],
     ["Un produit « sans sucre » est-il toujours un bon choix ?",["Oui","Non, il faut lire la composition (glucides, édulcorants, additifs)"],1,"La mention marketing ne remplace pas la liste d'ingrédients."],
     ["Comment reconnaître une information santé fiable ?",["Elle promet des résultats miracles et rapides","Elle s'appuie sur des sources sérieuses et peut être confirmée par un professionnel de santé"],1,"Qui parle ? Que vend-il ? Quelles sources ? Trois questions qui démasquent presque tout."]]},
 {t:"Construire un mode de vie durable",mi:"Écrivez votre plan d'action : 🎯 choisissez 3 priorités pour les 3 prochains mois (ex. : marcher 20 minutes par jour, me coucher à heure régulière, faire 2 séances de renforcement par semaine). Affichez-les quelque part où vous les verrez chaque jour.",p:[
  ["👋 Introduction","Vous voici au terme de ce module. Mouvement, muscles, sommeil, stress, hydratation, suivi, habitudes, discernement… vous avez désormais toutes les pièces du puzzle.\nL'objectif de ce dernier chapitre : assembler ces pièces pour construire VOTRE mode de vie — celui qui vous ressemble et que vous pourrez tenir dans la durée.\nCar la vraie réussite n'est pas un changement spectaculaire de quelques semaines : c'est un équilibre durable, mois après mois.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ faire le bilan de vos apprentissages ;\n✅ construire un plan d'action simple et réaliste ;\n✅ maintenir vos progrès sur les mois à venir."],
  ["🧭 Le bilan de vos apprentissages","Prenez un instant pour mesurer le chemin parcouru. Dans ce module, vous avez appris :\n🚶 pourquoi chaque mouvement compte et comment bouger davantage ;\n💪 comment renforcer vos muscles, alliés de votre glycémie ;\n😴 comment un sommeil de qualité soutient votre santé ;\n🌬️ comment apaiser le stress avec des outils simples ;\n💧 pourquoi l'hydratation est un pilier à part entière ;\n📊 comment suivre vos progrès avec sérénité ;\n🧱 comment construire des habitudes qui durent ;\n🔍 comment déjouer les idées reçues.\nPour chaque thème, demandez-vous : où en suis-je aujourd'hui, sur 10 ? Vos réponses vous montrent naturellement vos priorités.","m5c9b"],
  ["📅 Construire votre plan d'action","Un bon plan d'action est SIMPLE. La méthode :\n1️⃣ choisissez 2 ou 3 priorités maximum (celles où vous avez le plus à gagner) ;\n2️⃣ transformez chaque priorité en action concrète et mesurable : « bouger plus » devient « marcher 20 minutes après le déjeuner, 5 jours sur 7 » ;\n3️⃣ ancrez chaque action dans votre semaine : quel jour ? quel moment ? après quelle routine existante ? ;\n4️⃣ anticipez les obstacles : que ferez-vous s'il pleut, si vous êtes fatigué, en déplacement ? Prévoyez un plan B (version 2 minutes !) ;\n5️⃣ prévoyez votre récompense : cocher le calendrier, constater vos progrès dans l'onglet Suivi.\nUn plan écrit a beaucoup plus de chances d'être suivi qu'une intention gardée en tête.","m5c9c"],
  ["🌱 Avancer sur les mois à venir","Votre plan n'est pas gravé dans le marbre : il vit avec vous.\n✔ chaque mois, faites un mini-bilan : qu'est-ce qui a fonctionné ? qu'est-ce qui doit être ajusté ? ;\n✔ quand une habitude est bien installée, ajoutez-en UNE nouvelle — pas avant ;\n✔ entourez-vous : proches, partenaires d'activité, et bien sûr votre équipe soignante, qui reste votre alliée pour adapter traitements et objectifs ;\n✔ acceptez les périodes creuses : elles font partie du chemin. L'important est toujours de reprendre ;\n✔ et surtout : célébrez vos progrès, même les plus discrets. Ils sont le signe que votre mode de vie change en profondeur.\n\n💡 Astuce Keto-Essenciel : notez la date d'aujourd'hui, puis dans 3 mois relisez votre plan d'action. Vous serez surpris du chemin parcouru — et vous saurez exactement quoi ajuster pour la suite.","m5c9d"],
  ["📝 À retenir — et bravo pour ce module !","📝 À retenir :\n✔ un mode de vie durable repose sur la régularité, pas la perfection ;\n✔ 2 ou 3 priorités bien choisies valent mieux que 10 résolutions ;\n✔ un plan écrit, ancré dans votre semaine, avec un plan B pour les obstacles ;\n✔ réévaluez chaque mois et avancez une habitude à la fois ;\n✔ votre équipe soignante et vos proches sont vos alliés dans la durée.\n\n🎓 Dans ce Module 6, vous avez appris à : bouger au quotidien, choisir votre activité, renforcer vos muscles, dormir mieux, gérer votre stress, bien vous hydrater, suivre vos progrès sereinement, construire des habitudes durables et déjouer les idées reçues.\n\n🏅 Après ce chapitre, le Quiz final du module (20 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge 🏃 « Mode de vie équilibré » et la compétence : « Je sais intégrer le mouvement, la récupération et de bonnes habitudes de vie dans mon quotidien »."]],
  q:[["Quelle est la clé d'un mode de vie durable ?",["La perfection permanente","La régularité et des habitudes adaptées à votre vie"],1,"C'est l'équilibre tenable mois après mois qui transforme la santé — pas les exploits de quelques semaines."],
     ["Combien de priorités choisir pour démarrer son plan d'action ?",["Une dizaine","Deux ou trois, bien choisies"],1,"Peu de priorités = de vrais progrès. Trop de résolutions = abandon assuré."],
     ["Que faire face à un obstacle prévu (pluie, fatigue, déplacement) ?",["Tout abandonner","Prévoir un plan B, par exemple la version 2 minutes de l'habitude"],1,"Anticiper les obstacles, c'est déjà les désamorcer."],
     ["À quelle fréquence réévaluer son plan d'action ?",["Jamais","Régulièrement, par exemple chaque mois"],1,"Un mini-bilan mensuel permet d'ajuster sans pression."],
     ["Qui peut vous accompagner dans la durée ?",["Personne","Votre équipe soignante, vos proches et vos outils de suivi"],1,"Bien entouré, on va plus loin — et plus sereinement."]]}
],fq:[
 ["Pourquoi l'activité physique est-elle bénéfique en cas de diabète de type 2 ?",["Elle aide les muscles à utiliser le glucose et améliore la sensibilité à l'insuline","Elle remplace les traitements","Elle n'a aucun effet","Elle fait monter la glycémie durablement"],0,"Les muscles au travail consomment du glucose : un vrai coup de pouce pour la glycémie."],
 ["Faut-il être sportif pour bénéficier du mouvement ?",["Oui","Non : marche, jardinage, escaliers, danse… chaque mouvement compte"],1,"Toute activité qui fait bouger le corps est bénéfique."],
 ["Quelle est la recommandation générale d'activité pour un adulte ?",["10 minutes par mois","Environ 150 minutes d'intensité modérée par semaine, réparties comme on veut","10 heures par jour"],1,"150 minutes par semaine — par exemple 30 minutes 5 jours sur 7, ou 3 × 10 minutes par jour."],
 ["À quelle fréquence le renforcement musculaire est-il conseillé ?",["Au moins deux fois par semaine","Une fois par an","Uniquement l'été"],0,"Deux séances hebdomadaires avec récupération entre les deux : la base idéale."],
 ["Quel matériel peut remplacer des haltères à la maison ?",["Des bouteilles d'eau","Un oreiller","Rien"],0,"Bouteilles d'eau, chaise, mur, bande élastique : votre salon suffit."],
 ["Combien d'heures de sommeil sont recommandées pour la plupart des adultes ?",["4 à 5 heures","7 à 9 heures","Plus de 11 heures"],1,"7 à 9 heures : la référence — durée ET qualité comptent."],
 ["Quelle habitude favorise l'endormissement ?",["Les écrans jusqu'au coucher","Une routine calme : lecture, respiration, horaires réguliers","Un café après le dîner"],1,"Une routine relaxante répétée prépare le cerveau au sommeil."],
 ["Que faire si les troubles du sommeil persistent ?",["Les ignorer","En parler à un professionnel de santé"],1,"Insomnie persistante ou ronflements avec pauses méritent une évaluation médicale."],
 ["Le stress peut-il influencer la glycémie ?",["Non, jamais","Oui, les hormones du stress peuvent la faire monter"],1,"Cortisol et adrénaline libèrent du glucose dans le sang."],
 ["Quel outil simple aide à apaiser le stress ?",["La respiration lente et profonde","Regarder plus d'écrans","Sauter des repas"],0,"Quelques minutes de respiration lente calment le système nerveux — partout, discrètement."],
 ["Quel est un signe possible de déshydratation ?",["Urines foncées, fatigue, maux de tête","Une énergie débordante","Un sommeil parfait"],0,"La soif est un signal tardif : surveillez plutôt ces signes."],
 ["Quelle boisson privilégier au quotidien ?",["Les sodas","L'eau et les infusions sans sucre","Les jus de fruits industriels"],1,"L'eau reste la référence, surtout quand la glycémie augmente les pertes hydriques."],
 ["À quelle fréquence est-il raisonnable de se peser ?",["Plusieurs fois par jour","Environ une fois par semaine, dans les mêmes conditions"],1,"Un rendez-vous hebdomadaire suffit : les fluctuations quotidiennes sont du bruit."],
 ["Quel indicateur reflète le mieux la graisse abdominale ?",["Le tour de taille","La pointure","La couleur des cheveux"],0,"Le mètre ruban en dit souvent plus que la balance."],
 ["Qu'est-ce qui compte le plus dans le suivi des progrès ?",["La valeur d'un seul jour","La tendance sur plusieurs semaines"],1,"C'est la direction générale qui raconte vos progrès."],
 ["Comment construire une habitude durable ?",["Commencer petit et l'accrocher à une routine existante","Tout changer d'un coup","Compter uniquement sur la volonté"],0,"Déclencheur → action simple → satisfaction : la mécanique qui crée l'automatisme."],
 ["Que faire après un écart ou une pause dans ses habitudes ?",["Tout abandonner","Reprendre simplement dès que possible, sans culpabilité"],1,"Une pause n'efface pas vos progrès — seul l'abandon complet fait reculer."],
 ["Le diabète de type 2 peut-il s'améliorer avec l'hygiène de vie ?",["Non, jamais","Oui : alimentation, activité, sommeil et gestion du stress peuvent y contribuer, en lien avec l'équipe soignante"],1,"Chaque situation est unique, mais les progrès sont possibles à tout âge."],
 ["Comment reconnaître une information santé fiable ?",["Elle promet des résultats miracles","Elle s'appuie sur des sources sérieuses et peut être confirmée par un professionnel de santé"],1,"Qui parle ? Que vend-il ? Quelles sources ? Trois questions qui démasquent presque tout."],
 ["Quelle est la clé d'un mode de vie durable ?",["La perfection permanente","La régularité et des habitudes adaptées à votre vie"],1,"L'équilibre tenable dans la durée bat toujours les changements spectaculaires éphémères."]
],bd:"🏃 Mode de vie équilibré",sk:["Intégrer le mouvement dans mon quotidien","Renforcer mes muscles à la maison","Prendre soin de mon sommeil","Gérer mon stress avec des outils simples","Maintenir une bonne hydratation","Suivre mes progrès avec sérénité","Construire des habitudes durables et déjouer les idées reçues"]},'''

if OLD not in src:
    print('ERREUR: bloc "Les étirements" introuvable'); sys.exit(1)
if src.count(OLD) != 1:
    print('ERREUR: bloc non unique'); sys.exit(1)
src = src.replace(OLD, NEW)
io.open(PATH, 'w', encoding='utf-8').write(src)
print('OK: Module 6 = 10 chapitres + quiz final')
