#!/usr/bin/env python3
# Module 7 : refonte complète "Comprendre et réussir sa perte de poids durable" (10 chapitres + quiz final)
import io, sys

PATH = '/app/keto.html'
src = io.open(PATH, encoding='utf-8').read()

START = '{t:"Perte de poids",e:"⚖️",d:"Comprendre son corps pour mincir durablement.",ch:['
END = ']},\n{t:"Comprendre ses analyses"'
i = src.find(START)
j = src.find(END, i)
if i < 0 or j < 0:
    print('ERREUR: bornes module 7 introuvables', i, j); sys.exit(1)

NEW = r'''{t:"Comprendre et réussir sa perte de poids durable",e:"⚖️",d:"Comprendre les mécanismes de la prise de poids, perdre durablement et éviter l'effet yo-yo.",ch:[
 {t:"Pourquoi grossit-on ?",mi:"Repensez à votre journée d'hier : 🔍 repérez les moments qui ont le plus sollicité votre insuline (grignotages, boissons sucrées, repas riches en glucides). Choisissez UN changement simple à appliquer dès aujourd'hui et notez-le.",p:[
  ["👋 Introduction","« Il suffit de manger moins et de bouger plus. » Si c'était si simple, personne ne serait en surpoids.\nLa prise de poids est un phénomène plus subtil : elle dépend de la balance énergétique, mais aussi — et surtout — des HORMONES qui décident si votre corps stocke ou déstocke.\nComprendre ces mécanismes, c'est cesser de culpabiliser et commencer à agir efficacement.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le principe de la balance énergétique et ses limites ;\n✅ connaître le rôle des hormones (insuline, leptine, ghréline) ;\n✅ comprendre pourquoi toutes les calories n'ont pas le même impact ;\n✅ identifier les principaux facteurs qui favorisent la prise de poids."],
  ["⚖️ La balance énergétique… et ses limites","Le principe de base : si vous absorbez plus d'énergie que vous n'en dépensez, le surplus est stocké.\nMais cette équation cache une réalité plus complexe :\n✔ vos dépenses ne sont pas fixes — le corps les ajuste selon ce que vous mangez et votre mode de vie ;\n✔ votre faim n'est pas un choix — elle est pilotée par des hormones ;\n✔ ce que vous mangez influence directement OÙ va l'énergie : vers les muscles… ou vers les réserves de graisse.\nAutrement dit : la qualité de l'alimentation compte autant que la quantité.","m6c0b"],
  ["🔑 Les hormones aux commandes","Trois hormones jouent un rôle central :\n🗝️ L'INSULINE — l'hormone du stockage. Tant qu'elle est élevée (repas glucidiques répétés, grignotage), le corps stocke et ne déstocke pas, même en mangeant « peu ». Réduire les glucides fait baisser l'insuline : le corps peut enfin puiser dans ses réserves.\n🍽️ La LEPTINE — l'hormone de la satiété, produite par les cellules graisseuses. Elle dit au cerveau « stop, réserves suffisantes ». Problème : en cas de surpoids installé, le cerveau peut y devenir résistant… et ne plus entendre le signal.\n😋 La GHRÉLINE — l'hormone de la faim, produite par l'estomac. Elle monte avant les repas et après une mauvaise nuit de sommeil.\nQuand ces trois messagères se dérèglent, la volonté seule ne suffit plus : il faut agir sur les causes.","m6c0c"],
  ["🍽️ Toutes les calories ne se valent pas","100 kcal de saumon et 100 kcal de soda n'ont pas le même destin :\n🐟 les protéines rassasient durablement, demandent de l'énergie pour être digérées et protègent les muscles ;\n🥤 les sucres rapides provoquent un pic d'insuline, favorisent le stockage… et donnent à nouveau faim 2 heures plus tard.\nC'est le fameux cercle vicieux : repas sucré → pic de glycémie → pic d'insuline → chute → fringale → nouveau grignotage.\n\n📌 Les principaux facteurs qui favorisent la prise de poids :\n🍭 excès de sucres et de produits ultra-transformés ;\n😴 manque de sommeil (la ghréline monte, la leptine baisse) ;\n⛈️ stress chronique (cortisol) ;\n🪑 sédentarité ;\n🧬 terrain génétique et âge — des facteurs qui se gèrent, mais ne se choisissent pas.\n\n💡 Astuce Keto-Essenciel : plutôt que de compter chaque calorie, concentrez-vous sur la STABILITÉ de votre glycémie : protéines à chaque repas, légumes, bonnes graisses, et le moins de grignotage possible. La satiété fera le reste.","m6c0d"],
  ["📝 À retenir","📝 À retenir :\n✔ on ne grossit pas seulement parce qu'on « mange trop » : on grossit parce que le corps STOCKE ;\n✔ l'insuline est le chef d'orchestre du stockage ;\n✔ leptine et ghréline pilotent votre faim et votre satiété ;\n✔ toutes les calories n'ont pas le même impact métabolique ;\n✔ sommeil, stress et sédentarité pèsent autant que l'assiette.\n\n🏅 Badge à débloquer en validant le quiz : « Je comprends mon corps »"]],
  q:[["Quelle hormone commande le stockage des graisses ?",["L'insuline","La mélatonine","L'adrénaline"],0,"Tant que l'insuline est haute, le corps stocke et ne déstocke pas."],
     ["Quel est le rôle de la leptine ?",["Signaler la satiété au cerveau","Faire monter la glycémie","Colorer les cheveux"],0,"Produite par les cellules graisseuses, elle dit au cerveau « réserves suffisantes »."],
     ["Quand la ghréline (hormone de la faim) augmente-t-elle ?",["Avant les repas et après une mauvaise nuit","Uniquement en été","Jamais"],0,"Le manque de sommeil fait monter la ghréline : la faim du lendemain n'est pas un hasard."],
     ["100 kcal de saumon et 100 kcal de soda ont-elles le même effet ?",["Oui, une calorie est une calorie","Non, leur impact hormonal et métabolique est très différent"],1,"Protéines = satiété durable ; sucres rapides = pic d'insuline, stockage et fringale."],
     ["Quel facteur favorise la prise de poids ?",["Le manque de sommeil et le stress chronique","Boire de l'eau","Marcher tous les jours"],0,"Sommeil court et stress dérèglent ghréline, leptine et cortisol."]]},
 {t:"La graisse viscérale : celle qu'il faut vraiment perdre",mi:"Aujourd'hui, mesurez votre tour de taille : 📏 au niveau du nombril, ventre relâché, sans serrer. Notez la valeur dans l'onglet Suivi (Mesures corporelles) — ce sera votre point de départ pour suivre la fonte de la graisse viscérale.",p:[
  ["👋 Introduction","Toutes les graisses du corps ne se ressemblent pas.\nCelle qui se voit — sous la peau — est la moins préoccupante. Celle qui se cache — autour des organes, dans le ventre — est la plus active… et la plus risquée pour la santé.\nBonne nouvelle : c'est aussi celle qui répond le mieux aux changements de mode de vie.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer graisse sous-cutanée et graisse viscérale ;\n✅ comprendre pourquoi la graisse abdominale augmente les risques métaboliques ;\n✅ savoir comment la réduire progressivement ;\n✅ utiliser le tour de taille comme indicateur de suivi."],
  ["🆚 Deux graisses très différentes","🧈 La graisse SOUS-CUTANÉE se loge sous la peau (cuisses, hanches, bras). C'est une réserve d'énergie relativement passive : inesthétique parfois, mais peu dangereuse.\n🫀 La graisse VISCÉRALE s'installe en profondeur, autour du foie, du pancréas et des intestins. Invisible de l'extérieur, elle peut être présente même chez des personnes d'apparence mince.\nC'est elle qui donne le ventre dur et bombé, et c'est elle qu'il faut vraiment cibler.","m6c1b"],
  ["⚠️ Pourquoi est-elle si problématique ?","La graisse viscérale n'est pas un simple stock : c'est un tissu ACTIF qui libère en continu des substances inflammatoires et des acides gras directement vers le foie.\nConséquences possibles :\n📉 aggravation de la résistance à l'insuline ;\n🩸 glycémie et triglycérides plus élevés ;\n❤️ risque cardiovasculaire augmenté ;\n🫁 foie gras (stéatose).\nC'est elle qui fait le lit du diabète de type 2 — et c'est pourquoi la réduire améliore souvent rapidement les marqueurs métaboliques.","m6c1c"],
  ["📏 La mesurer et la faire fondre","Le TOUR DE TAILLE est un bien meilleur indicateur que le poids seul : la balance ne fait pas la différence entre muscle, eau et graisse — le mètre ruban, si.\nRepères de vigilance : plus de 94 cm chez l'homme, plus de 80 cm chez la femme.\n📐 Mesurez chaque semaine, au niveau du nombril, ventre relâché, et notez la valeur dans l'onglet Suivi.\n\nComment la réduire progressivement :\n🥗 réduire sucres et produits ultra-transformés (l'insuline basse permet le déstockage) ;\n🚶 bouger chaque jour — la marche après les repas est particulièrement efficace ;\n💪 renforcer ses muscles (ils consomment le glucose) ;\n😴 dormir suffisamment et gérer le stress (le cortisol favorise la graisse abdominale).\nLa graisse viscérale est souvent la PREMIÈRE à fondre : les résultats se voient au ruban avant la balance.\n\n💡 Astuce Keto-Essenciel : prenez la mesure toujours dans les mêmes conditions (le matin, à jeun). Voir le chiffre baisser semaine après semaine est l'une des motivations les plus puissantes qui soient.","m6c1d"],
  ["📝 À retenir","📝 À retenir :\n✔ la graisse viscérale (autour des organes) est la plus risquée pour la santé ;\n✔ elle entretient l'inflammation et la résistance à l'insuline ;\n✔ le tour de taille la reflète mieux que le poids seul (repères : 94 cm homme / 80 cm femme) ;\n✔ alimentation, marche, muscle, sommeil : elle répond vite aux bonnes habitudes ;\n✔ mesurez une fois par semaine, toujours dans les mêmes conditions.\n\n🏅 Badge à débloquer en validant le quiz : « Je cible la bonne graisse »"]],
  q:[["Quelle graisse augmente le plus les risques métaboliques ?",["La graisse sous-cutanée","La graisse viscérale (autour des organes)","La graisse des bras"],1,"Active et inflammatoire, elle aggrave la résistance à l'insuline."],
     ["Pourquoi la graisse viscérale est-elle si problématique ?",["Elle libère des substances inflammatoires vers le foie","Elle est purement esthétique","Elle protège les organes du froid"],0,"C'est un tissu actif qui perturbe le métabolisme en continu."],
     ["Quel indicateur reflète le mieux la graisse abdominale ?",["Le tour de taille","Le poids seul","La pointure"],0,"Le mètre ruban distingue ce que la balance confond (muscle, eau, graisse)."],
     ["Quels sont les repères de vigilance du tour de taille ?",["Plus de 94 cm (homme) / 80 cm (femme)","Plus de 150 cm pour tous","Il n'y a aucun repère"],0,"Au-delà de ces valeurs, le risque métabolique augmente."],
     ["Comment réduire la graisse viscérale ?",["Moins de sucres, marche quotidienne, muscle, sommeil","Uniquement des crèmes amincissantes","En sautant le petit-déjeuner à vie"],0,"Elle répond remarquablement bien aux changements de mode de vie — et souvent en premier."]]},
 {t:"Comprendre son métabolisme",mi:"Aujourd'hui, boostez vos dépenses invisibles (NEAT) : 🪜 prenez les escaliers, 🚶 marchez pendant vos appels, ⏰ levez-vous 2 minutes toutes les heures. Comptez le nombre de fois où vous avez bougé « en plus » dans la journée.",p:[
  ["👋 Introduction","« Je ne perds pas de poids, j'ai un métabolisme lent. » Vrai frein ou fausse excuse ?\nLe métabolisme, c'est l'ensemble de l'énergie que votre corps dépense chaque jour — et il varie réellement d'une personne à l'autre.\nComprendre le vôtre, c'est arrêter de vous comparer et apprendre à travailler AVEC votre corps plutôt que contre lui.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre ce qu'est le métabolisme de base ;\n✅ connaître les facteurs qui influencent vos dépenses ;\n✅ comprendre pourquoi deux personnes ne maigrissent pas pareil ;\n✅ démêler le vrai du faux sur le « métabolisme lent »."],
  ["🔥 Le métabolisme de base","C'est l'énergie que votre corps consomme AU REPOS, juste pour fonctionner : faire battre le cœur, respirer, maintenir la température, faire travailler le cerveau…\nIl représente 60 à 70 % de vos dépenses quotidiennes — bien plus que le sport !\nLe reste se répartit entre :\n🍽️ la digestion (~10 %) — les protéines sont les plus « coûteuses » à digérer ;\n🏃 l'activité physique volontaire (sport) ;\n🚶 le NEAT : tous les mouvements du quotidien (marcher, jardiner, monter des escaliers, gigoter) — un levier énorme et sous-estimé.","m6c2b"],
  ["📊 Pourquoi deux personnes ne maigrissent pas pareil","Vos dépenses dépendent de facteurs que vous ne choisissez pas :\n💪 la masse musculaire — le muscle brûle des calories même au repos ;\n🎂 l'âge — le métabolisme diminue doucement, surtout si le muscle fond ;\n🚻 le sexe — la masse musculaire moyenne diffère ;\n🧬 la génétique et les hormones (thyroïde notamment) ;\n📜 l'historique de régimes — les restrictions répétées apprennent au corps à économiser.\nDeux personnes qui mangent pareil et bougent pareil ne perdront donc PAS au même rythme. Ce n'est ni une injustice ni un échec : c'est de la physiologie. La seule comparaison utile, c'est vous… avec vous-même.","m6c2c"],
  ["🐢 Le mythe du « métabolisme lent » — et comment protéger le vôtre","Un vrai ralentissement métabolique majeur (thyroïde…) existe mais se diagnostique médicalement : en cas de doute, parlez-en à votre médecin.\nEn revanche, un métabolisme qui S'ÉCONOMISE, c'est très fréquent — et souvent causé… par les régimes trop restrictifs : le corps se défend contre la famine en réduisant ses dépenses et en augmentant la faim. D'où l'effet yo-yo.\n\nComment protéger votre métabolisme :\n🥩 mangez suffisamment de protéines (elles préservent le muscle) ;\n💪 faites du renforcement musculaire — chaque kilo de muscle augmente vos dépenses au repos ;\n🍽️ ne descendez pas trop bas en calories trop longtemps : mangez à satiété des aliments de qualité ;\n😴 dormez 7 à 9 h — le métabolisme se régule la nuit ;\n🚶 augmentez votre NEAT : c'est le levier le plus facile à activer.\n\n💡 Astuce Keto-Essenciel : le NEAT peut représenter plusieurs centaines de kcal par jour d'écart entre deux personnes. Escaliers, marche pendant les appels, se lever chaque heure : des « miettes » qui, cumulées, font une vraie différence.","m6c2d"],
  ["📝 À retenir","📝 À retenir :\n✔ le métabolisme de base représente 60 à 70 % de vos dépenses ;\n✔ muscle, âge, sexe, génétique : chacun a son propre rythme ;\n✔ les régimes trop restrictifs apprennent au corps à économiser ;\n✔ protéines + renforcement musculaire + sommeil = métabolisme protégé ;\n✔ le NEAT (mouvements du quotidien) est un levier puissant et accessible.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais mon métabolisme »"]],
  q:[["Que représente le métabolisme de base ?",["L'énergie dépensée au repos pour faire fonctionner le corps","Uniquement les calories du sport","L'énergie des repas"],0,"Cœur, respiration, température, cerveau : 60 à 70 % de vos dépenses quotidiennes."],
     ["Qu'est-ce que le NEAT ?",["Tous les mouvements du quotidien hors sport (marche, escaliers, ménage…)","Un régime à la mode","Une hormone"],0,"Un levier énorme et sous-estimé : il peut représenter des centaines de kcal par jour."],
     ["Pourquoi deux personnes ne perdent-elles pas du poids de la même façon ?",["Parce que l'une triche forcément","Muscle, âge, sexe, génétique et historique de régimes diffèrent","C'est le hasard"],1,"C'est de la physiologie, pas une question de volonté."],
     ["Que provoquent les régimes très restrictifs sur le métabolisme ?",["Ils l'accélèrent durablement","Le corps s'économise : moins de dépenses, plus de faim"],1,"C'est le mécanisme central de l'effet yo-yo."],
     ["Qu'est-ce qui protège le métabolisme ?",["Les protéines, le muscle et le sommeil","Sauter des repas au hasard","Les sodas light"],0,"Le muscle brûle des calories même au repos : préservez-le."]]},
 {t:"Pourquoi la perte de poids ralentit : les plateaux",mi:"Si votre poids stagne, passez en revue la checklist des 5 leviers : 🔍 glucides cachés, 🧀 excès de laitages/oléagineux, 🍽️ grignotage, 🚶 mouvement quotidien, 😴 sommeil. Choisissez UN levier à activer cette semaine et notez-le.",p:[
  ["👋 Introduction","Les premières semaines, la balance descend régulièrement… puis un jour, plus rien. Pendant deux, trois semaines. Décourageant ? Seulement si on ne comprend pas ce qui se passe.\nLe plateau n'est pas une panne : c'est une phase NORMALE et prévisible de toute perte de poids.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi les plateaux sont normaux ;\n✅ connaître les mécanismes d'adaptation du corps ;\n✅ différencier un vrai plateau d'une simple fluctuation ;\n✅ appliquer les bonnes stratégies pour relancer la progression."],
  ["⚙️ Pourquoi le corps s'adapte","Votre corps est une machine à survivre : quand il perd du poids, il s'ajuste.\n📉 un corps plus léger dépense moins d'énergie pour bouger ;\n🔥 le métabolisme s'ajuste légèrement à la baisse ;\n💧 le corps se recompose : il arrive de perdre de la graisse en gagnant du muscle et de l'eau — la balance ne bouge pas, mais la silhouette change ;\n🍽️ les hormones de la faim remontent doucement pour défendre les réserves.\nLe plateau est donc le signe que votre corps… fonctionne normalement. La question n'est pas « pourquoi ça bloque ? » mais « comment relancer intelligemment ? ».","m6c3b"],
  ["🔍 Vrai plateau ou simple fluctuation ?","Avant de parler de plateau, vérifiez :\n📅 la durée — moins de 3-4 semaines de stagnation = fluctuation normale (eau, digestion, hormones, sel…) ;\n⚖️ les conditions de pesée — même jour, même heure, même tenue, à jeun ;\n📏 les AUTRES indicateurs — si le tour de taille diminue ou si les vêtements flottent, vous progressez encore : ce n'est PAS un plateau, c'est une recomposition ;\n🚺 chez les femmes, le cycle hormonal peut masquer une perte réelle pendant 1 à 2 semaines.\nUn vrai plateau = poids ET mensurations stables depuis plus de 3-4 semaines, malgré des habitudes inchangées.","m6c3c"],
  ["🛠️ Les stratégies anti-plateau","Si le plateau est confirmé, activez ces leviers un par un :\n1️⃣ traquez les glucides cachés : sauces, plats préparés, produits « keto » industriels ;\n2️⃣ modérez les aliments faciles à surconsommer : fromages, crème, oléagineux ;\n3️⃣ resserrez le rythme : 2-3 vrais repas, zéro grignotage — chaque prise alimentaire relance l'insuline ;\n4️⃣ bougez davantage : marche quotidienne + 2 séances de renforcement musculaire ;\n5️⃣ dormez ! Le manque de sommeil est un bloqueur de perte de poids majeur ;\n6️⃣ vérifiez le stress : le cortisol chronique freine le déstockage.\nSurtout : ne réduisez PAS drastiquement les calories — vous aggraveriez l'adaptation métabolique.\n\n💡 Astuce Keto-Essenciel : pendant un plateau, changez d'objectif : concentrez-vous 2 semaines sur un indicateur NON-balance (pas quotidiens, tour de taille, énergie). Le poids repartira souvent tout seul — et vous n'aurez pas perdu votre motivation en route.","m6c3d"],
  ["📝 À retenir","📝 À retenir :\n✔ le plateau est une adaptation normale, pas un échec ;\n✔ moins de 3-4 semaines de stagnation = simple fluctuation ;\n✔ si le tour de taille diminue, vous progressez encore ;\n✔ relancez avec les leviers : glucides cachés, rythme des repas, mouvement, sommeil ;\n✔ ne vous affamez jamais pour « forcer » — c'est contre-productif.\n\n🏅 Badge à débloquer en validant le quiz : « Je dépasse les plateaux »"]],
  q:[["Un plateau de poids signifie…",["Que tout est perdu","Une adaptation normale du corps","Qu'il faut manger plus de sucre"],1,"Le corps s'ajuste et se recompose : le plateau fait partie du voyage."],
     ["À partir de quand parle-t-on d'un vrai plateau ?",["24 heures sans perte","Plus de 3-4 semaines de stagnation (poids ET mensurations)","Une semaine"],1,"Avant cela, ce sont des fluctuations normales (eau, digestion, hormones)."],
     ["Le poids stagne mais le tour de taille diminue : que se passe-t-il ?",["Rien ne progresse","Une recomposition : vous perdez de la graisse en gagnant du muscle/de l'eau"],1,"La balance confond tout — le mètre ruban, non."],
     ["Quel levier aide à relancer la perte de poids ?",["Resserrer le rythme des repas et arrêter le grignotage","Grignoter davantage","Supprimer le sommeil"],0,"Moins de prises alimentaires = insuline plus basse = déstockage facilité."],
     ["Faut-il réduire drastiquement les calories pour casser un plateau ?",["Oui, s'affamer","Non : cela aggrave l'adaptation métabolique"],1,"Se restreindre trop fort apprend au corps à économiser encore plus."]]},
 {t:"Les hormones qui influencent votre poids",mi:"Identifiez votre « hormone point faible » : 😋 fringales fréquentes (insuline/ghréline) ? 🍽️ jamais rassasié (leptine) ? ⛈️ stress et ventre qui résiste (cortisol) ? Choisissez le conseil du chapitre correspondant et appliquez-le dès aujourd'hui.",p:[
  ["👋 Introduction","Vous l'avez découvert au chapitre 1 : votre poids n'est pas qu'une affaire de volonté, c'est une affaire d'HORMONES.\nDans ce chapitre, nous passons en revue les quatre messagères qui pilotent votre faim, votre satiété et votre stockage — et surtout, comment les remettre de votre côté.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle de l'insuline, de la leptine, de la ghréline et du cortisol ;\n✅ repérer les signes d'un déséquilibre ;\n✅ agir concrètement sur chacune d'elles."],
  ["🗝️ L'insuline : la clé du stockage","Son rôle : faire entrer le glucose dans les cellules… et commander le stockage des surplus.\nTant qu'elle est élevée, le déstockage est bloqué. Et elle monte à CHAQUE prise alimentaire glucidique — y compris les grignotages « légers ».\nSignes d'une insuline souvent haute : fringales 2 h après les repas, coups de pompe, ventre qui s'installe, envies de sucre le soir.\nComment l'apaiser :\n✔ réduire sucres et féculents raffinés ;\n✔ espacer les repas (le grignotage la relance sans cesse) ;\n✔ bouger après les repas (les muscles absorbent le glucose sans insuline) ;\n✔ privilégier protéines, légumes et bonnes graisses.","m6c4b"],
  ["🍽️ Leptine et ghréline : le duo faim-satiété","🛑 La LEPTINE (satiété) est produite par vos cellules graisseuses. Paradoxe : en cas de surpoids installé, il y a BEAUCOUP de leptine… mais le cerveau n'y répond plus (résistance à la leptine). Résultat : on a des réserves, mais toujours faim.\nPour restaurer la sensibilité : moins de produits ultra-transformés, moins d'inflammation, un bon sommeil, et de la patience — elle revient progressivement avec la perte de graisse.\n😋 La GHRÉLINE (faim) monte avant les repas… et explose après une nuit courte : une seule mauvaise nuit peut augmenter nettement la faim du lendemain, surtout pour les aliments riches et sucrés.\nPour la calmer : dormir 7-9 h, des repas riches en protéines (c'est le nutriment qui la freine le mieux), et des horaires de repas réguliers.","m6c4c"],
  ["⛈️ Le cortisol : l'hormone du stress qui fait stocker","Face au stress, le cortisol libère du glucose pour préparer le corps à réagir. Utile en cas de danger ponctuel… mais nos stress modernes sont permanents.\nUn cortisol chroniquement élevé :\n🍩 favorise le stockage abdominal (la fameuse graisse viscérale) ;\n🍫 augmente les envies d'aliments riches et sucrés ;\n😴 perturbe le sommeil — qui dérègle à son tour ghréline et leptine.\nComment agir : respiration lente quotidienne, marche dans la nature, sommeil protégé, limiter les excitants, et les outils du Module 6.\n\n💡 Astuce Keto-Essenciel : vos hormones travaillent en ÉQUIPE. Une seule habitude — dormir 7 à 9 heures — améliore à la fois la ghréline, la leptine, le cortisol ET la sensibilité à l'insuline. C'est le meilleur rapport effort/bénéfice de tout ce module.","m6c4d"],
  ["📝 À retenir","📝 À retenir :\n✔ l'insuline stocke : apaisez-la en réduisant sucres et grignotages ;\n✔ la leptine signale la satiété — le surpoids peut rendre le cerveau « sourd » à son message ;\n✔ la ghréline crée la faim — le manque de sommeil la fait exploser ;\n✔ le cortisol favorise le stockage abdominal ;\n✔ le sommeil est l'habitude qui améliore les quatre à la fois.\n\n🏅 Badge à débloquer en validant le quiz : « Je comprends mes hormones »"]],
  q:[["Quel est le rôle principal de l'insuline dans le poids ?",["Commander le stockage des surplus d'énergie","Créer la sensation de faim","Réguler la température"],0,"Tant qu'elle est élevée, le déstockage est bloqué."],
     ["Qu'est-ce que la résistance à la leptine ?",["Le cerveau ne répond plus au signal de satiété malgré des réserves importantes","Une allergie alimentaire","Un manque de leptine dans le sang"],0,"Beaucoup de leptine, mais un cerveau qui ne l'entend plus : on a toujours faim."],
     ["Que se passe-t-il après une nuit trop courte ?",["La ghréline (faim) augmente et la leptine (satiété) baisse","On a moins faim","Rien"],0,"Le manque de sommeil pousse vers les aliments riches et sucrés dès le lendemain."],
     ["Quel effet a un cortisol chroniquement élevé ?",["Il favorise le stockage abdominal et les envies de sucre","Il fait fondre la graisse viscérale","Il améliore le sommeil"],0,"Stress permanent = glucose libéré + stockage abdominal + fringales."],
     ["Quelle habitude améliore les quatre hormones à la fois ?",["Dormir 7 à 9 heures","Sauter le dîner tous les soirs","Boire plus de café"],0,"Le sommeil est le meilleur rapport effort/bénéfice de tout le module."]]},
 {t:"Les écarts alimentaires : comment les gérer sans culpabiliser",mi:"Préparez votre stratégie pour votre prochain repas de fête : 🍽️ mangez normalement avant, 🥩 repérez les plats compatibles (viandes, poissons, fromages, légumes), 💧 gardez l'eau gazeuse comme alliée, et surtout… profitez du moment sans culpabilité.",p:[
  ["👋 Introduction","Un anniversaire, un restaurant, un moment de fatigue… et voilà un repas qui s'éloigne de vos habitudes.\nEt après ? RIEN de grave. Un écart ne ruine pas des semaines d'efforts — c'est la façon dont vous RÉAGISSEZ à l'écart qui fait toute la différence.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi un écart ne ruine pas vos efforts ;\n✅ éviter les erreurs classiques après un repas plus riche ;\n✅ reprendre rapidement vos bonnes habitudes ;\n✅ miser sur la régularité plutôt que la perfection."],
  ["🎉 Un écart ne ruine pas vos efforts","Faisons le calcul : sur une semaine, vous prenez environ 21 repas. Un repas de fête = moins de 5 % de votre alimentation.\nCe qui détermine vos résultats, c'est ce que vous faites dans 95 % des cas — jamais l'exception.\nPhysiologiquement, après un repas riche : la glycémie monte, le corps stocke un peu, retient de l'eau (d'où le +1 kg du lendemain, essentiellement de l'EAU, pas de la graisse), puis tout rentre dans l'ordre en 24-48 h… si vous reprenez simplement vos habitudes.\nLa balance du lendemain d'un écart ne mesure pas votre échec : elle mesure du sel et de l'eau.","m6c5b"],
  ["❌ Les erreurs à éviter après un écart","1️⃣ CULPABILISER — la culpabilité est le vrai danger : elle pousse au « foutu pour foutu » et transforme UN écart en UNE semaine d'écarts.\n2️⃣ SE PUNIR — jeûne punitif, sport à outrance, restriction sévère : ces compensations extrêmes entretiennent le cercle restriction → craquage.\n3️⃣ REPORTER — « je reprendrai lundi » : chaque jour d'attente rend la reprise plus difficile.\n4️⃣ SE PESER en panique le lendemain — vous ne verrez que de l'eau, et votre moral n'a pas besoin de ça.\n\nLa règle des 3 R :\n1️⃣ ne pas Ruminer ;\n2️⃣ Reprendre le cap dès le repas SUIVANT (pas lundi prochain) ;\n3️⃣ Rebooster : une marche, un grand verre d'eau, un bon repas keto.","m6c5c"],
  ["🔄 Reprendre — et anticiper les prochaines occasions","Reprendre, concrètement : au repas suivant, composez une assiette normale (protéines + légumes + bonnes graisses), hydratez-vous, marchez un peu, couchez-vous à l'heure. C'est tout. Pas de compensation, pas de privation.\n\nAnticiper les occasions festives :\n✔ AVANT : mangez normalement dans la journée — arriver affamé garantit les excès ;\n✔ SUR PLACE : privilégiez viandes, poissons, fromages, légumes ; limitez pain et desserts ; l'eau gazeuse est votre alliée ;\n✔ APRÈS : reprenez simplement vos habitudes — et si vous suivez votre glycémie, elle vous racontera l'histoire sans drame.\nUn écart CHOISI et savouré (le dessert de votre grand-mère) vaut mieux qu'un écart subi et culpabilisé.\n\n💡 Astuce Keto-Essenciel : planifiez vos plaisirs. Un écart prévu et apprécié n'est plus un « craquage » : c'est une décision. Et une décision ne génère aucune culpabilité.","m6c5d"],
  ["📝 À retenir","📝 À retenir :\n✔ un repas sur 21 ne change rien : c'est la routine qui fait le résultat ;\n✔ le +1 kg du lendemain, c'est de l'eau — pas de la graisse ;\n✔ la culpabilité est plus dangereuse que l'écart lui-même ;\n✔ règle des 3 R : ne pas Ruminer, Reprendre au repas suivant, Rebooster ;\n✔ la régularité bat la perfection, toujours.\n\n🏅 Badge à débloquer en validant le quiz : « Je gère les écarts sans culpabilité »"]],
  q:[["Un repas de fête ruine-t-il une semaine d'efforts ?",["Oui, tout est perdu","Non : c'est ce que vous faites dans 95 % des cas qui compte"],1,"Un repas sur 21 : l'exception ne définit jamais le résultat."],
     ["Que représente surtout le +1 kg au lendemain d'un écart ?",["De la graisse installée","De l'eau et du sel, qui s'éliminent en 24-48 h"],1,"La rétention d'eau post-repas riche est temporaire et normale."],
     ["Quelle est la pire réaction après un écart ?",["Culpabiliser et enchaîner sur le mode « foutu pour foutu »","Reprendre ses habitudes au repas suivant"],0,"C'est la culpabilité qui transforme un écart en une semaine d'écarts."],
     ["Que dit la règle des 3 R ?",["Ne pas Ruminer, Reprendre au repas suivant, Rebooster","Râler, Recommencer, Regretter","Rien, Rien, Rien"],0,"Simple et efficace : le cap se reprend au repas suivant, pas « lundi »."],
     ["Avant un repas de fête, il vaut mieux…",["Arriver affamé","Manger normalement avant","Jeûner 3 jours"],1,"Arriver affamé garantit les excès : mangez normalement avant l'événement."]]},
 {t:"Les freins cachés à la perte de poids",mi:"Pendant 3 jours, tenez un mini-journal détective : 📔 notez chaque grignotage (quoi, quand, pourquoi) et chaque boisson autre que l'eau. Sans jugement — juste pour VOIR. Vous découvrirez probablement un frein dont vous n'aviez pas conscience.",p:[
  ["👋 Introduction","Vous mangez bien, vous bougez… et pourtant ça ne descend pas ?\nAvant de conclure que « rien ne marche », partez à la chasse aux FREINS CACHÉS : ces facteurs discrets qui sabotent la perte de poids sans qu'on s'en rende compte.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ identifier les 6 freins cachés les plus fréquents ;\n✅ repérer ceux qui vous concernent ;\n✅ agir sur chacun d'eux concrètement."],
  ["😴 Frein n°1 : le manque de sommeil — ⛈️ Frein n°2 : le stress chronique","😴 LE MANQUE DE SOMMEIL : dormir moins de 6-7 h dérègle la ghréline (faim ↑) et la leptine (satiété ↓), augmente les envies de sucre et freine le déstockage. Beaucoup de « plateaux inexpliqués » se résolvent… au lit.\n➡️ Action : visez 7-9 h, avec la routine du soir du Module 6.\n\n⛈️ LE STRESS CHRONIQUE : le cortisol libère du glucose, favorise la graisse abdominale et pousse au grignotage émotionnel. On ne mange plus par faim, mais pour se calmer.\n➡️ Action : respiration lente quotidienne, marche, micro-pauses. Et avant de grignoter, demandez-vous : « Ai-je faim… ou besoin de souffler ? »","m6c6b"],
  ["🪑 Frein n°3 : la sédentarité — 🍪 Frein n°4 : les grignotages inconscients","🪑 LA SÉDENTARITÉ : rester assis des heures met les muscles « en veille » — ils ne consomment presque plus de glucose, même si vous faites du sport le soir. Le sport ne compense pas 10 heures de chaise.\n➡️ Action : levez-vous 2-3 minutes chaque heure, marchez après les repas, augmentez votre NEAT.\n\n🍪 LES GRIGNOTAGES INCONSCIENTS : la poignée de fruits secs en passant, le carré de fromage en cuisinant, les restes des enfants… Ces bouchées « qui ne comptent pas » peuvent représenter des centaines de kcal par jour — et surtout, elles relancent l'insuline en continu.\n➡️ Action : la règle de l'assiette — tout ce qui se mange se met dans une assiette, assis. Le grignotage debout disparaît de lui-même.","m6c6c"],
  ["🥤 Frein n°5 : les boissons caloriques — 💊 Frein n°6 : certains traitements","🥤 LES BOISSONS CALORIQUES : jus de fruits (autant de sucre qu'un soda), alcool (calories + désinhibition + déstockage mis en pause), cafés gourmands, sirops… Les calories LIQUIDES ne rassasient pas : elles s'ajoutent, sans jamais couper la faim.\n➡️ Action : eau, eau gazeuse, infusions, thé, café nature. L'alcool en quantité modérée et occasionnelle.\n\n💊 CERTAINS TRAITEMENTS MÉDICAUX peuvent favoriser une prise de poids ou freiner la perte (certains antidiabétiques comme l'insuline ou les sulfamides, cortisone, certains antidépresseurs ou bêtabloquants…).\n➡️ Action : n'arrêtez ou ne modifiez JAMAIS un traitement seul. Parlez-en à votre médecin : des alternatives ou des ajustements existent parfois.\n\n💡 Astuce Keto-Essenciel : ne cherchez pas à corriger les 6 freins d'un coup. Identifiez LE frein principal (le journal de 3 jours vous le montrera) et travaillez-le pendant 2 semaines avant de passer au suivant.","m6c6d"],
  ["📝 À retenir","📝 À retenir :\n✔ sommeil court et stress chronique dérèglent les hormones du poids ;\n✔ le sport ne compense pas des journées entières assis ;\n✔ les grignotages « invisibles » relancent l'insuline en continu ;\n✔ les calories liquides s'ajoutent sans rassasier ;\n✔ certains traitements freinent la perte : parlez-en à votre médecin, sans jamais arrêter seul.\n\n🏅 Badge à débloquer en validant le quiz : « Je lève mes freins cachés »"]],
  q:[["Quel effet a le manque de sommeil sur le poids ?",["Aucun","Il augmente la faim (ghréline) et diminue la satiété (leptine)"],1,"Beaucoup de plateaux inexpliqués se résolvent… au lit."],
     ["Le sport du soir compense-t-il 10 heures assis dans la journée ?",["Oui, totalement","Non : les longues heures assises freinent le métabolisme malgré le sport"],1,"Levez-vous chaque heure et marchez après les repas : le NEAT compte autant."],
     ["Pourquoi les grignotages « qui ne comptent pas » posent-ils problème ?",["Ils relancent l'insuline en continu et s'accumulent","Ils n'ont aucun effet","Ils améliorent la satiété"],0,"La règle de l'assiette (tout se mange assis, dans une assiette) les fait disparaître."],
     ["Quel est le problème des calories liquides (jus, alcool, cafés gourmands) ?",["Elles ne rassasient pas et s'ajoutent au reste","Elles coupent la faim durablement","Elles n'existent pas"],0,"Un jus de fruits contient autant de sucre qu'un soda — sans la satiété d'un fruit entier."],
     ["Que faire si vous suspectez un traitement de freiner votre perte de poids ?",["L'arrêter immédiatement","En parler à votre médecin, sans jamais modifier le traitement seul"],1,"Des ajustements ou alternatives existent parfois — mais toujours avec le médecin."]]},
 {t:"Comment éviter l'effet yo-yo ?",mi:"Définissez votre zone de stabilité : ⚖️ votre poids cible ± 2 kg, et vos 3 habitudes non négociables (ex. : protéines à chaque repas, marche quotidienne, pesée hebdomadaire). Notez-les : c'est votre contrat de maintien.",p:[
  ["👋 Introduction","Perdre du poids, beaucoup y arrivent. Le GARDER, c'est là que tout se joue : la majorité des régimes classiques se soldent par une reprise — souvent avec des kilos en plus.\nCet effet yo-yo n'est pas une fatalité ni un manque de volonté : c'est la conséquence logique de méthodes trop brutales. Et il s'évite.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi les régimes très restrictifs échouent ;\n✅ stabiliser durablement votre poids ;\n✅ connaître les habitudes qui maintiennent les résultats ;\n✅ cultiver la patience nécessaire."],
  ["📉 Pourquoi les régimes restrictifs échouent","Le scénario classique : restriction sévère → perte rapide → puis…\n🔥 le métabolisme s'économise (le corps se défend contre la « famine ») ;\n😋 les hormones de la faim explosent — la ghréline monte, la leptine chute ;\n💪 une partie du poids perdu était du MUSCLE — donc moins de dépenses au repos ;\n🧠 la frustration s'accumule… jusqu'au craquage.\nRésultat : on reprend tout, souvent plus — et avec proportionnellement plus de graisse qu'avant. Chaque cycle rend le suivant plus difficile.\nLa leçon : la méthode qui vous fait perdre doit être une méthode que vous pouvez GARDER. Si vous ne vous imaginez pas vivre ainsi dans 2 ans, ce n'est pas la bonne méthode.","m6c7b"],
  ["⚖️ Stabiliser durablement","La stabilisation n'est pas un « retour à la normale » (l'ancienne normale vous a menée ici) : c'est une transition douce vers votre nouveau mode de vie.\n✔ ne changez RIEN brutalement : conservez la structure de vos repas (protéines + légumes + bonnes graisses) ;\n✔ réintroduisez d'éventuels aliments progressivement, UN à la fois, en observant votre corps (poids, énergie, fringales, glycémie) ;\n✔ gardez vos habitudes socles : mouvement quotidien, sommeil, gestion du stress ;\n✔ maintenez une surveillance LÉGÈRE : une pesée par semaine + le tour de taille par mois suffisent.\nLe muscle est votre assurance-stabilité : continuez le renforcement musculaire — il protège votre métabolisme.","m6c7c"],
  ["🕰️ Les habitudes du maintien — et la patience","Votre plan de maintien tient en peu de choses :\n1️⃣ une ZONE DE STABILITÉ : votre poids cible ± 2 kg. En dessous du seuil haut, tout va bien — inutile de réagir aux fluctuations ;\n2️⃣ un SIGNAL D'ALERTE : si le seuil haut est franchi 2 semaines de suite, réactivez simplement les fondamentaux (chapitre plateaux) pendant 2-3 semaines. Pas de panique, pas de régime : un simple resserrage ;\n3️⃣ vos 3 habitudes NON NÉGOCIABLES : celles que vous gardez quoi qu'il arrive (ex. : protéines à chaque repas, marche quotidienne, pesée hebdomadaire).\n\nEt la patience ? Elle est ESSENTIELLE : votre corps a besoin de plusieurs mois pour « accepter » son nouveau poids (la leptine et l'appétit se rééquilibrent progressivement). Plus vous tenez la stabilité longtemps, plus elle devient facile.\n\n💡 Astuce Keto-Essenciel : méfiez-vous de la « dérive des petites exceptions » — c'est rarement un gros craquage qui fait regrossir, mais l'accumulation discrète d'exceptions devenues quotidiennes. Votre pesée hebdomadaire est le garde-fou qui les détecte à temps.","m6c7d"],
  ["📝 À retenir","📝 À retenir :\n✔ les régimes brutaux programment la reprise (métabolisme freiné + faim accrue + muscle perdu) ;\n✔ la bonne méthode est celle que vous pouvez garder à vie ;\n✔ stabilisez en douceur : mêmes repères, réintroductions progressives ;\n✔ zone de stabilité ± 2 kg + 3 habitudes non négociables + pesée hebdo ;\n✔ la patience est votre alliée : la stabilité devient plus facile avec le temps.\n\n🏅 Badge à débloquer en validant le quiz : « J'évite l'effet yo-yo »"]],
  q:[["Pourquoi les régimes très restrictifs provoquent-ils l'effet yo-yo ?",["Le métabolisme ralentit et la faim augmente","Ils marchent trop bien","La balance se casse"],0,"Le corps se défend contre la famine : moins de dépenses, plus de faim → reprise."],
     ["Quel est le problème de perdre du muscle pendant un régime ?",["Aucun","Moins de muscle = moins de dépenses au repos = reprise facilitée"],1,"Le muscle est votre assurance-stabilité : protéines + renforcement le préservent."],
     ["Comment réintroduire d'éventuels aliments après la perte de poids ?",["Tout d'un coup dès l'objectif atteint","Progressivement, un aliment à la fois, en observant son corps"],1,"La stabilisation est une transition douce, pas un « retour à l'ancienne normale »."],
     ["Qu'est-ce qu'une zone de stabilité ?",["Le poids cible ± 2 kg, avec un signal d'alerte si le seuil haut est franchi durablement","Un poids exact au gramme près","Une salle de sport"],0,"Elle évite de réagir aux fluctuations tout en détectant les vraies dérives à temps."],
     ["Qu'est-ce qui fait le plus souvent regrossir ?",["Un gros craquage isolé","L'accumulation discrète de petites exceptions devenues quotidiennes"],1,"La pesée hebdomadaire est le garde-fou qui détecte la dérive à temps."]]},
 {t:"Les vrais indicateurs de réussite",mi:"Créez votre tableau de bord personnel : choisissez 3 indicateurs NON-balance et faites le point de départ aujourd'hui — 📏 tour de taille, 📸 photo de face/profil (même tenue, même lumière), ⚡ énergie sur 10. Rendez-vous dans un mois pour comparer.",p:[
  ["👋 Introduction","Combien de personnes progressent magnifiquement… et se découragent à cause d'un chiffre sur la balance ?\nLe poids n'est qu'UN indicateur parmi d'autres — et souvent le moins fiable à court terme. Dans ce chapitre, vous allez construire un tableau de bord qui raconte VRAIMENT votre transformation.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi la balance ne raconte pas toute l'histoire ;\n✅ utiliser le tour de taille, les mensurations et les photos d'évolution ;\n✅ suivre votre énergie, votre condition physique et votre bien-être ;\n✅ composer votre propre tableau de bord de réussite."],
  ["⚖️ Pourquoi la balance ne dit pas tout","Le chiffre de la balance mélange TOUT : graisse, muscle, eau, contenu digestif.\nExemples concrets :\n💧 un repas salé la veille = +1 kg d'eau le lendemain ;\n💪 2 mois de renforcement musculaire = -3 kg de graisse et +2 kg de muscle → la balance n'affiche que -1 kg… alors que la silhouette est transformée ;\n🚺 le cycle hormonal peut masquer une perte réelle pendant 1 à 2 semaines.\nSe fier à la balance seule, c'est juger un film sur une seule image. Elle reste utile — mais UNE fois par semaine, et jamais seule.","m6c8b"],
  ["📏 Le corps qui change : taille, mensurations, photos","📏 LE TOUR DE TAILLE : votre indicateur n°1 (vous le savez depuis le chapitre 2). Une mesure par semaine, mêmes conditions.\n📐 LES MENSURATIONS : hanches, cuisses, poitrine, bras — une fois par mois. La graisse part rarement d'où on voudrait en premier : les mensurations révèlent les progrès que la taille de vêtement ne montre pas encore.\n📸 LES PHOTOS D'ÉVOLUTION : une photo de face et de profil, une fois par mois, même tenue, même endroit, même lumière. On ne SE voit pas changer au quotidien — la comparaison à 3 mois d'écart est souvent spectaculaire, et c'est l'antidote parfait au découragement.\n👖 LE TEST DU VÊTEMENT : ce jean qui ferme à nouveau en dit plus que 3 pesées.","m6c8c"],
  ["⚡ Les indicateurs de vie : énergie, forme, bien-être","Votre transformation ne se mesure pas qu'en centimètres :\n⚡ L'ÉNERGIE — fini le coup de pompe de 15 h ? Notez votre énergie sur 10 chaque semaine ;\n🏃 LA CONDITION PHYSIQUE — monter les escaliers sans essoufflement, marcher plus vite, porter les courses facilement : des victoires concrètes (les tests physiques de l'onglet Muscu vous donnent des mesures objectives) ;\n😴 LE SOMMEIL — plus profond, plus réparateur ;\n😊 LE BIEN-ÊTRE GÉNÉRAL — humeur plus stable, moins de fringales, meilleure concentration, confiance retrouvée ;\n🩸 et pour les personnes diabétiques : la GLYCÉMIE qui s'améliore est peut-être le plus beau des indicateurs.\n\n💡 Astuce Keto-Essenciel : composez VOTRE tableau de bord — 1 mesure corporelle (tour de taille), 1 photo mensuelle, 1 indicateur de vie (énergie /10). Trois données suffisent : au-delà, le suivi devient une corvée.","m6c8d"],
  ["📝 À retenir","📝 À retenir :\n✔ la balance mélange graisse, muscle et eau : elle ne raconte pas tout ;\n✔ tour de taille hebdomadaire + mensurations et photo mensuelles = la vraie histoire ;\n✔ énergie, condition physique, sommeil et bien-être comptent autant que les centimètres ;\n✔ le test du vêtement ne ment jamais ;\n✔ 3 indicateurs bien choisis suffisent.\n\n🏅 Badge à débloquer en validant le quiz : « Je mesure ma vraie réussite »"]],
  q:[["Pourquoi la balance ne raconte-t-elle pas toute l'histoire ?",["Elle mélange graisse, muscle, eau et contenu digestif","Elle est toujours cassée","Elle raconte tout, justement"],0,"Perdre 3 kg de graisse en gagnant 2 kg de muscle n'affiche que -1 kg… pour une silhouette transformée."],
     ["À quelle fréquence prendre ses photos d'évolution ?",["Tous les jours","Une fois par mois, même tenue, même lumière","Jamais"],1,"On ne se voit pas changer au quotidien — la comparaison mensuelle, si."],
     ["Que révèlent les mensurations (hanches, cuisses, bras) ?",["Des progrès que la balance et la taille de vêtement ne montrent pas encore","Rien d'utile","La météo"],0,"La graisse part rarement d'où on voudrait en premier : mesurez plusieurs zones."],
     ["Quels indicateurs de vie témoignent de la transformation ?",["Énergie, condition physique, sommeil, bien-être","Uniquement le poids","La couleur des ongles"],0,"Monter les escaliers sans essoufflement en dit long — bien plus qu'une pesée."],
     ["Combien d'indicateurs suffisent pour un bon tableau de bord ?",["Une vingtaine, mesurés chaque jour","Environ 3, bien choisis (mesure, photo, énergie)"],1,"Au-delà, le suivi devient une corvée — et une source d'obsession."]]},
 {t:"Réussir sa transformation durable",mi:"Écrivez votre plan de maintien : 🎯 vos 3 habitudes non négociables, ⚖️ votre zone de stabilité (poids ± 2 kg), et 🛡️ votre action de resserrage si le seuil est franchi 2 semaines de suite. Affichez-le et relisez-le dans 3 mois.",p:[
  ["👋 Introduction","Vous voici au terme de ce module — et surtout au DÉBUT de votre nouvelle vie.\nVous savez désormais pourquoi on grossit, comment fondre la bonne graisse, comment déjouer plateaux, hormones et freins cachés, et comment éviter le yo-yo.\nCe dernier chapitre assemble tout : votre bilan, vos habitudes, votre plan de maintien et votre stratégie anti-rechute.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ faire le bilan de votre parcours ;\n✅ identifier vos nouvelles habitudes ;\n✅ construire votre plan de maintien ;\n✅ prévenir les rechutes et continuer à progresser."],
  ["🧭 Le bilan de votre parcours","Prenez un moment pour regarder le chemin parcouru — pas seulement les kilos :\n📉 qu'est-ce qui a changé sur la balance ET au mètre ruban ?\n⚡ et votre énergie ? votre sommeil ? vos fringales ? votre glycémie ?\n🧠 qu'avez-vous APPRIS sur votre corps (vos freins, vos déclencheurs, vos leviers efficaces) ?\n🏆 de quoi êtes-vous le plus fier ?\n\nIdentifiez maintenant vos NOUVELLES HABITUDES — celles qui sont devenues presque automatiques : protéines à chaque repas ? marche quotidienne ? pesée hebdomadaire ? nuits protégées ? Ce sont ELLES, votre vraie transformation. Les kilos perdus n'en sont que la conséquence.","m6c9b"],
  ["📅 Votre plan de maintien","Un plan de maintien tient sur une page :\n1️⃣ MES 3 HABITUDES NON NÉGOCIABLES — celles que vous gardez quoi qu'il arrive, en vacances comme en semaine chargée ;\n2️⃣ MA ZONE DE STABILITÉ — poids cible ± 2 kg, vérifiée par UNE pesée hebdomadaire + le tour de taille mensuel ;\n3️⃣ MON SIGNAL D'ALERTE — seuil haut franchi 2 semaines de suite → j'active mon plan de resserrage ;\n4️⃣ MON PLAN DE RESSERRAGE — 2-3 semaines de fondamentaux renforcés : zéro grignotage, glucides cachés traqués, marche quotidienne, sommeil prioritaire. Pas de régime, pas de panique : un simple réglage ;\n5️⃣ MES PLAISIRS PLANIFIÉS — les écarts choisis qui rendent le mode de vie tenable.\nÉcrivez-le noir sur blanc : un plan écrit survit aux baisses de motivation.","m6c9c"],
  ["🛡️ Prévenir les rechutes — et continuer à progresser","Les rechutes suivent presque toujours le même scénario : une période difficile (stress, deuil, surcharge) → les habitudes glissent → « je m'y remets bientôt » → des mois passent.\nVos protections :\n🚨 repérez vos situations à risque À L'AVANCE (périodes de stress, vacances longues, changements de vie) et prévoyez la version MINIMALE de vos habitudes (la règle des 2 minutes du Module 6) ;\n📆 gardez le rendez-vous hebdomadaire avec vous-même (pesée + tour de taille) MÊME quand ça dérive — surtout quand ça dérive : c'est lui qui empêche les -2 kg de devenir +8 ;\n🤝 restez entouré : proches, équipe soignante, et votre app Keto-Essenciel ;\n🌱 et continuez à progresser : un nouvel objectif de forme (les tests physiques de l'onglet Muscu), une nouvelle recette chaque semaine, un défi de pas quotidien… La progression entretient la motivation bien mieux que le maintien seul.\n\n💡 Astuce Keto-Essenciel : notez la date d'aujourd'hui et relisez votre plan de maintien dans 3 mois. Ajustez-le : un plan vivant est un plan qui dure.","m6c9d"],
  ["📝 À retenir — et bravo pour ce module !","📝 À retenir :\n✔ votre vraie transformation, ce sont vos habitudes — pas seulement les kilos ;\n✔ un plan de maintien tient sur une page : 3 habitudes, une zone de stabilité, un signal d'alerte, un plan de resserrage ;\n✔ anticipez les périodes à risque avec la version minimale de vos habitudes ;\n✔ le rendez-vous hebdomadaire est votre meilleur garde-fou anti-rechute ;\n✔ continuez à progresser : c'est le meilleur carburant de la motivation.\n\n🎓 Dans ce Module 7, vous avez appris à : comprendre pourquoi on grossit, cibler la graisse viscérale, connaître votre métabolisme, dépasser les plateaux, apprivoiser vos hormones, gérer les écarts sans culpabilité, lever les freins cachés, éviter l'effet yo-yo, mesurer votre vraie réussite et construire votre transformation durable.\n\n🏅 Après ce chapitre, le Quiz final du module (20 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge ⚖️ « Maîtrise de la perte de poids durable » et la compétence : « Je comprends les mécanismes de mon poids et je sais le stabiliser durablement »."]],
  q:[["Quelle est votre vraie transformation ?",["Uniquement les kilos perdus","Les habitudes devenues automatiques — les kilos n'en sont que la conséquence"],1,"Les habitudes restent quand la motivation passe : ce sont elles, le résultat."],
     ["Que contient un bon plan de maintien ?",["3 habitudes non négociables, une zone de stabilité, un signal d'alerte et un plan de resserrage","Un régime strict permanent","Rien d'écrit"],0,"Une page suffit — mais une page ÉCRITE."],
     ["Comment prévenir les rechutes lors des périodes difficiles ?",["Tout suspendre en attendant des jours meilleurs","Prévoir à l'avance la version minimale de ses habitudes"],1,"La règle des 2 minutes maintient le fil — c'est l'abandon complet qui fait reculer."],
     ["Pourquoi garder la pesée hebdomadaire même quand ça dérive ?",["Pour se punir","C'est le garde-fou qui empêche +2 kg de devenir +8 kg"],1,"Le rendez-vous hebdomadaire détecte la dérive tôt, quand elle est facile à corriger."],
     ["Quel est le meilleur carburant de la motivation au long cours ?",["Continuer à progresser (nouveaux objectifs de forme, défis)","Ne plus jamais rien changer","La culpabilité"],0,"La progression entretient la motivation bien mieux que le maintien seul."]]}
],fq:[
 ["On grossit principalement parce que…",["Le corps stocke, sous le contrôle d'hormones comme l'insuline","On manque de volonté","On boit trop d'eau","On dort trop"],0,"Le stockage est un mécanisme hormonal — pas une question de caractère."],
 ["Quelle hormone commande le stockage des graisses ?",["L'insuline","La mélatonine","L'adrénaline","La vitamine D"],0,"Tant que l'insuline est haute, le déstockage est bloqué."],
 ["Quel est le rôle de la leptine ?",["Signaler la satiété au cerveau","Créer la faim","Stocker le fer","Faire dormir"],0,"En cas de surpoids installé, le cerveau peut devenir résistant à son message."],
 ["Quand la ghréline (hormone de la faim) augmente-t-elle ?",["Avant les repas et après une nuit trop courte","Uniquement le week-end","Jamais","Après une sieste"],0,"Une nuit courte fait exploser la faim du lendemain — surtout pour le sucré."],
 ["Toutes les calories ont-elles le même impact métabolique ?",["Oui, strictement","Non : protéines, sucres et graisses n'ont pas le même effet hormonal"],1,"100 kcal de saumon et 100 kcal de soda n'ont pas le même destin."],
 ["Quelle graisse augmente le plus les risques métaboliques ?",["La graisse viscérale (autour des organes)","La graisse sous-cutanée","La graisse des bras","Aucune"],0,"Active et inflammatoire, elle aggrave la résistance à l'insuline."],
 ["Quels sont les repères de vigilance du tour de taille ?",["94 cm (homme) / 80 cm (femme)","150 cm pour tous","50 cm pour tous","Aucun repère n'existe"],0,"Le mètre ruban reflète la graisse abdominale mieux que la balance."],
 ["Que représente le métabolisme de base ?",["60 à 70 % des dépenses quotidiennes","Moins de 5 %","Uniquement le sport","Les calories des boissons"],0,"L'énergie du corps au repos : cœur, respiration, température, cerveau."],
 ["Qu'est-ce que le NEAT ?",["Les mouvements du quotidien hors sport (marche, escaliers, ménage…)","Un complément alimentaire","Une hormone du stress","Un régime"],0,"Un levier de dépense énorme, accessible à tous, chaque jour."],
 ["Un plateau de moins de 3-4 semaines est…",["Un échec définitif","Le plus souvent une fluctuation normale (eau, hormones, recomposition)"],1,"Avant 3-4 semaines de stagnation complète, pas d'inquiétude."],
 ["Le poids stagne mais le tour de taille diminue : que se passe-t-il ?",["Rien","Une recomposition : la graisse fond pendant que muscle/eau compensent sur la balance"],1,"C'est un progrès réel que la balance ne sait pas montrer."],
 ["Faut-il s'affamer pour casser un plateau ?",["Oui","Non : la restriction sévère aggrave l'adaptation métabolique"],1,"Relancez plutôt : glucides cachés, rythme des repas, mouvement, sommeil."],
 ["Que représente surtout le +1 kg au lendemain d'un repas de fête ?",["De la graisse installée","De l'eau et du sel, éliminés en 24-48 h"],1,"La rétention d'eau post-repas riche est temporaire et normale."],
 ["Quelle est la meilleure réaction après un écart ?",["Culpabiliser et compenser par un jeûne punitif","Reprendre simplement ses habitudes dès le repas suivant"],1,"Règle des 3 R : ne pas Ruminer, Reprendre, Rebooster."],
 ["Quel est le problème des calories liquides (jus, alcool, cafés gourmands) ?",["Elles ne rassasient pas et s'ajoutent au reste","Elles coupent la faim","Elles font maigrir","Elles n'existent pas"],0,"Un jus contient autant de sucre qu'un soda — sans la satiété du fruit entier."],
 ["Que faire si un traitement médical semble freiner votre perte de poids ?",["L'arrêter seul immédiatement","En parler à votre médecin sans jamais modifier le traitement vous-même"],1,"Des ajustements existent parfois — toujours avec un professionnel."],
 ["Pourquoi les régimes très restrictifs provoquent-ils l'effet yo-yo ?",["Métabolisme freiné, faim accrue, muscle perdu, frustration","Ils sont trop efficaces","À cause de la météo","Ils ne le provoquent pas"],0,"Le corps se défend contre la famine : la reprise est programmée."],
 ["Qu'est-ce qu'une zone de stabilité ?",["Le poids cible ± 2 kg, surveillé par une pesée hebdomadaire","Un poids exact au gramme près","Une pièce de la maison","Un régime"],0,"Elle évite de réagir aux fluctuations tout en détectant les vraies dérives."],
 ["Pourquoi la balance seule est-elle un mauvais juge ?",["Elle mélange graisse, muscle, eau et contenu digestif","Elle est trop précise","Elle ne ment jamais","Elle mesure la taille"],0,"Tour de taille, photos et énergie racontent la vraie histoire."],
 ["Quelle est la clé d'une transformation durable ?",["Des habitudes tenables, un plan de maintien écrit et de la patience","La perfection permanente","Un régime différent chaque mois","La chance"],0,"La méthode qui vous fait perdre doit être celle que vous pouvez garder à vie."]
],bd:"⚖️ Maîtrise de la perte de poids durable",sk:["Comprendre les mécanismes de la prise de poids","Cibler la graisse viscérale","Protéger mon métabolisme","Dépasser les plateaux sans paniquer","Apprivoiser mes hormones (insuline, leptine, ghréline, cortisol)","Gérer les écarts sans culpabilité","Lever les freins cachés","Stabiliser mon poids sans effet yo-yo"]}'''

src = src[:i] + NEW + ',\n' + src[j+len(']},\n'):]
io.open(PATH, 'w', encoding='utf-8').write(src)
print('OK: Module 7 = 10 chapitres + quiz final')
