#!/usr/bin/env python3
# Module 1 : refonte « Comprendre son diabète » (10 chapitres + quiz final 20 q)
import io, sys
PATH='/app/keto.html'; src=io.open(PATH,encoding='utf-8').read()
START='{t:"Comprendre son diabète",e:"🧠",ip:"m0",'
END=']},\n{t:"Pourquoi le Keto ?"'
i=src.find(START); j=src.find(END,i)
if i<0 or j<0: print('ERREUR bornes M1',i,j); sys.exit(1)
if 'Devenir acteur de sa santé",mi' in src: print('DÉJÀ APPLIQUÉ'); sys.exit(0)

NEW = r'''{t:"Comprendre son diabète",e:"🩸",ip:"m0",d:"Comprendre ce qu'est le diabète, pourquoi il apparaît, comment il agit dans l'organisme et quelles solutions existent pour mieux vivre avec. Les bases indispensables pour tout le parcours.",ch:[
 {t:"Qu'est-ce que le diabète ?",mi:"Observez-vous : 🩸 si vous avez un lecteur, notez votre glycémie à jeun ce matin. Sinon, retrouvez votre dernière valeur sur une prise de sang. Situez-la : normale (< 1,10 g/L), pré-diabète (1,10-1,25) ou diabète (≥ 1,26). C'est votre point de départ.",p:[
  ["👋 Introduction","Avant de vouloir améliorer son diabète, il faut le comprendre. Et bonne nouvelle : c'est plus simple qu'il n'y paraît !\nCommençons par la base : qu'est-ce que le glucose, à quoi sert l'insuline, et que se passe-t-il exactement quand on devient diabétique ?\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre ce qu'est le glucose et pourquoi le corps en a besoin ;\n✅ comprendre le rôle de l'insuline ;\n✅ savoir ce qu'est une glycémie normale ;\n✅ comprendre ce qui se dérègle dans le diabète."],
  ["🍬 Le glucose : le carburant du corps","Le GLUCOSE est un sucre simple : c'est le carburant principal de vos cellules — un peu comme l'essence d'une voiture.\nD'où vient-il ? Principalement de votre alimentation : le pain, les pâtes, le riz, les fruits, le sucre… tous les glucides sont transformés en glucose lors de la digestion, puis passent dans le SANG.\nPourquoi le corps en a besoin ? Toutes vos cellules — muscles, cerveau, organes — l'utilisent pour produire de l'énergie. Sans carburant, pas de mouvement, pas de pensée, pas de vie.\nMais attention : le glucose doit rester dans une fourchette précise dans le sang. Trop peu = malaise (hypoglycémie) ; trop = dangereux à long terme (hyperglycémie). Votre corps possède un régulateur automatique très précis pour cela… et c'est là qu'entre en scène une hormone clé.","m0c1b"],
  ["🔑 L'insuline : la clé qui ouvre les cellules","L'INSULINE est une hormone fabriquée par le PANCRÉAS. C'est LA vedette de toute cette histoire.\nSon rôle ? Elle agit comme une CLÉ : quand le glucose arrive dans le sang après un repas, l'insuline se fixe sur les cellules et leur « ouvre la porte » pour laisser entrer le glucose. Le sucre quitte alors le sang pour nourrir les cellules.\nRésultat : la glycémie (taux de sucre dans le sang) redescend et reste stable.\nImaginez : le glucose, ce sont des voyageurs ; les cellules, des maisons aux portes verrouillées ; l'insuline, le trousseau de clés qui ouvre les portes. Sans clé, les voyageurs restent bloqués dehors — dans le sang. Retenez bien cette image : elle explique TOUT le diabète.","m0c1c"],
  ["📊 Une glycémie normale — et le dérèglement","CHEZ UNE PERSONNE NON DIABÉTIQUE, la mécanique est parfaitement huilée :\n🍽️ après un repas, la glycémie monte un peu ;\n🔑 le pancréas libère l'insuline nécessaire ;\n📉 le glucose entre dans les cellules, la glycémie redescend en 1-2 h ;\n🎯 à jeun, elle reste entre 0,70 et 1,10 g/L.\n\nDANS LE DIABÈTE, ce système se dérègle, de deux façons possibles :\n1️⃣ le pancréas ne fabrique plus assez d'insuline (plus assez de clés) ;\n2️⃣ OU les clés fonctionnent mal : les cellules « résistent » à l'insuline (les serrures sont grippées) — c'est le cas le plus fréquent.\nDans les deux cas, le glucose ne peut plus entrer correctement dans les cellules : il S'ACCUMULE dans le sang. La glycémie reste durablement élevée : c'est le diabète.","m0c1d"],
  ["📝 À retenir","📝 À retenir :\n✔ le glucose est le carburant des cellules, issu surtout des glucides alimentaires ;\n✔ l'insuline (fabriquée par le pancréas) est la « clé » qui fait entrer le glucose dans les cellules ;\n✔ une glycémie normale à jeun est comprise entre 0,70 et 1,10 g/L ;\n✔ dans le diabète, soit il manque d'insuline, soit les cellules y résistent ;\n✔ résultat : le glucose s'accumule dans le sang.\n\n🏅 Badge à débloquer en validant le quiz : « Je comprends le mécanisme »"]],
  q:[["Qu'est-ce que le glucose ?",["Le carburant principal des cellules, issu surtout des glucides","Une hormone","Un muscle"],0,"Il vient de l'alimentation et nourrit toutes vos cellules."],
     ["Quel est le rôle de l'insuline ?",["Une clé qui fait entrer le glucose dans les cellules","Fabriquer du sucre","Digérer les graisses"],0,"Fabriquée par le pancréas, elle ouvre la « porte » des cellules."],
     ["Quelle est une glycémie normale à jeun ?",["Entre 0,70 et 1,10 g/L","Entre 3 et 5 g/L","Zéro"],0,"Au-delà de 1,26 g/L à jeun (à deux reprises), on parle de diabète."],
     ["Que se passe-t-il dans le diabète ?",["Le glucose s'accumule dans le sang (manque d'insuline ou résistance)","Le sang disparaît","Rien"],0,"Soit il manque d'insuline, soit les cellules y résistent."],
     ["Quel organe fabrique l'insuline ?",["Le pancréas","Le foie","Les poumons"],0,"C'est la vedette de toute l'histoire du diabète."]]},
 {t:"Les différents types de diabète",mi:"Clarifiez votre situation : 🔎 savez-vous précisément de quel type de diabète vous relevez (le plus souvent type 2) ? Si vous avez un doute, notez la question pour votre médecin. Comprendre SON type, c'est comprendre son traitement.",p:[
  ["👋 Introduction","On dit « le diabète » comme s'il n'y en avait qu'un. En réalité, il existe plusieurs formes très différentes, avec des causes et des prises en charge distinctes.\nSavoir de quel type on relève est essentiel — cela change tout dans la compréhension et le traitement.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer les diabètes de type 1 et de type 2 ;\n✅ connaître le diabète gestationnel ;\n✅ situer les formes plus rares ;\n✅ comprendre les grandes différences entre elles."],
  ["1️⃣ Le diabète de type 1 : le pancréas défaillant","Le DIABÈTE DE TYPE 1 concerne environ 10 % des personnes diabétiques.\n🧬 sa cause : une maladie AUTO-IMMUNE — le système immunitaire détruit par erreur les cellules du pancréas qui fabriquent l'insuline. Le corps ne produit alors PLUS DU TOUT d'insuline ;\n👶 il apparaît souvent jeune (enfance, adolescence, jeune adulte), parfois brutalement ;\n💉 son traitement : l'insuline est VITALE et indispensable à vie (pas de choix possible : sans clé, aucune porte ne s'ouvre) ;\n⚠️ il n'est PAS lié au mode de vie ou à l'alimentation — une personne mince et sportive peut en être atteinte.\nCe n'est PAS le diabète que cible principalement cette application (même si les principes d'alimentation saine profitent à tous, l'insuline y reste indispensable).","m0c2b"],
  ["2️⃣ Le diabète de type 2 : le plus fréquent","Le DIABÈTE DE TYPE 2 représente environ 90 % des cas — c'est très probablement le vôtre, et le cœur de cette application.\n🔧 sa cause : les cellules deviennent RÉSISTANTES à l'insuline (les serrures se grippent, chapitre 3). Le pancréas produit d'abord PLUS d'insuline pour compenser… puis s'épuise progressivement ;\n📈 il s'installe LENTEMENT, souvent sans symptôme pendant des années — d'où l'importance du dépistage ;\n🎯 les leviers : contrairement au type 1, le mode de vie a un impact MAJEUR — alimentation, activité, poids, sommeil peuvent considérablement l'améliorer (c'est toute la promesse de ce parcours !) ;\n💊 les traitements viennent en complément, adaptés par le médecin.\nBonne nouvelle centrale : le diabète de type 2 se PILOTE. Vous n'êtes pas spectateur.","m0c2c"],
  ["3️⃣ Diabète gestationnel et formes plus rares","LE DIABÈTE GESTATIONNEL :\n🤰 il apparaît pendant la GROSSESSE, chez des femmes qui n'étaient pas diabétiques avant ;\n🔄 il disparaît le plus souvent après l'accouchement, MAIS il augmente le risque de développer un diabète de type 2 plus tard : un suivi ultérieur est important ;\n🩺 il se surveille et se traite pendant la grossesse (alimentation, parfois insuline) pour protéger la mère et l'enfant.\n\nLES FORMES PLUS RARES :\n🧬 diabètes MODY (origine génétique, familiale) ;\n💊 diabètes secondaires (à une maladie du pancréas, à certains médicaments comme les corticoïdes…) ;\n🔬 diabète de type 1 lent (LADA), à mi-chemin.\nCes formes nécessitent un diagnostic précis par le médecin — mais elles restent minoritaires.","m0c2d"],
  ["📝 À retenir","📝 À retenir :\n✔ diabète de type 1 (~10 %) : auto-immun, aucune insuline produite, insuline vitale à vie, non lié au mode de vie ;\n✔ diabète de type 2 (~90 %) : résistance à l'insuline, fortement influencé par le mode de vie — c'est le cœur de ce parcours ;\n✔ diabète gestationnel : pendant la grossesse, souvent transitoire mais à surveiller après ;\n✔ formes rares (MODY, LADA, secondaires) : diagnostic médical précis ;\n✔ connaître SON type, c'est comprendre son traitement.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais les types de diabète »"]],
  q:[["Quelle est la cause du diabète de type 1 ?",["Une maladie auto-immune : le corps ne produit plus d'insuline","Trop de sucre mangé","Le manque de sport"],0,"L'insuline y est vitale et indispensable à vie."],
     ["Quel type représente environ 90 % des cas ?",["Le diabète de type 2","Le diabète de type 1","Le diabète gestationnel"],0,"Il est fortement influencé par le mode de vie — c'est le cœur de ce parcours."],
     ["Qu'est-ce qui caractérise le diabète de type 2 ?",["Une résistance des cellules à l'insuline","Une absence totale d'insuline dès la naissance","Un excès de vitamines"],0,"Le pancréas compense d'abord, puis s'épuise."],
     ["Le diabète gestationnel…",["Apparaît pendant la grossesse et disparaît souvent après, mais augmente le risque futur de type 2","Est définitif","Touche les hommes"],0,"Un suivi ultérieur reste important."],
     ["Le mode de vie a-t-il un impact majeur sur le diabète de type 2 ?",["Oui, considérable : alimentation, activité, poids, sommeil","Non, aucun","Uniquement le sommeil"],0,"C'est toute la promesse de ce parcours : vous n'êtes pas spectateur."]]},
 {t:"Comprendre l'insuline et l'insulinorésistance",mi:"Testez votre compréhension : 🔑 expliquez à voix haute (ou à un proche) l'image de la clé et de la serrure grippée. Si vous savez l'expliquer simplement, vous avez compris le mécanisme central du diabète de type 2 — la clé de tout le reste !",p:[
  ["👋 Introduction","L'insulinorésistance : voilà LE mot central du diabète de type 2. Si vous ne deviez retenir qu'un mécanisme de tout ce module, ce serait celui-ci.\nComprenons ensemble pourquoi l'insuline devient moins efficace, et pourquoi cela conduit au diabète.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ rappeler le rôle de l'insuline ;\n✅ comprendre l'insulinorésistance ;\n✅ comprendre l'hyperinsulinémie ;\n✅ relier tout cela à l'apparition du diabète de type 2."],
  ["🔑 Rappel : l'insuline, la clé","Rappelons l'image essentielle (chapitre 1) :\n🔑 l'insuline est la CLÉ qui ouvre les cellules pour y faire entrer le glucose ;\n🚪 les cellules sont des maisons aux portes verrouillées ;\n🍬 le glucose attend dans le sang de pouvoir entrer.\nQuand tout va bien : la clé tourne, la porte s'ouvre, le glucose entre, la glycémie reste stable.\nL'insuline a aussi un autre rôle important : c'est l'hormone du STOCKAGE. Quand elle est élevée, elle ordonne au corps de STOCKER l'énergie sous forme de graisse — et empêche de la brûler. Retenez ce point : il expliquera beaucoup de choses sur le poids (Module 7) !","m0c3b"],
  ["🔧 L'insulinorésistance : les serrures se grippent","Voici le cœur du diabète de type 2.\nAvec le temps — sous l'effet d'un excès de glucides, de graisse abdominale, de sédentarité, de stress — les cellules deviennent PROGRESSIVEMENT SOURDES au message de l'insuline. Les serrures se GRIPPENT.\nLa clé (l'insuline) est bien là, mais elle a de plus en plus de mal à ouvrir les portes. Le glucose peine à entrer et commence à s'accumuler dans le sang.\nC'est ça, l'INSULINORÉSISTANCE : les cellules RÉSISTENT à l'action de l'insuline.\nAu début, ce phénomène est silencieux : la glycémie reste encore normale, car le pancréas compense. Mais en coulisses, la machine force déjà.","m0c3c"],
  ["📈 L'hyperinsulinémie : le cercle vicieux","Face à des serrures grippées, que fait le pancréas ? Il FORCE : il produit de PLUS EN PLUS d'insuline pour parvenir à ouvrir les portes malgré la résistance.\nRésultat : un taux d'insuline très élevé dans le sang — c'est l'HYPERINSULINÉMIE.\nEt c'est un CERCLE VICIEUX :\n🔁 plus d'insuline → plus de stockage de graisse → plus de graisse abdominale → PLUS de résistance → encore plus d'insuline…\n⏳ pendant des années, la glycémie peut rester à peu près normale (le pancréas tient bon en surrégime), mais l'hyperinsulinémie fait déjà des dégâts silencieux ;\n💥 puis un jour, le pancréas s'ÉPUISE : il ne parvient plus à compenser. La glycémie grimpe : le diabète de type 2 devient visible sur la prise de sang.\nCe qu'il faut comprendre : le diabète de type 2 ne commence PAS le jour du diagnostic — il mijotait depuis 5, 10, parfois 15 ans. Et la clé pour l'inverser, c'est de BRISER ce cercle vicieux : moins de glucides → moins d'insuline → serrures qui se dégrippent.","m0c3d"],
  ["📝 À retenir","📝 À retenir :\n✔ l'insuline est la clé qui ouvre les cellules — et l'hormone du stockage des graisses ;\n✔ insulinorésistance = les cellules deviennent sourdes à l'insuline (serrures grippées) ;\n✔ le pancréas compense en produisant plus d'insuline : c'est l'hyperinsulinémie ;\n✔ cercle vicieux : plus d'insuline → plus de graisse → plus de résistance ;\n✔ briser ce cercle (moins de glucides) est la clé pour améliorer le diabète de type 2.\n\n🏅 Badge à débloquer en validant le quiz : « Je maîtrise l'insulinorésistance »"]],
  q:[["Qu'est-ce que l'insulinorésistance ?",["Les cellules deviennent sourdes au message de l'insuline (serrures grippées)","Une absence d'insuline","Un excès de vitamines"],0,"C'est le mécanisme central du diabète de type 2."],
     ["Quel autre rôle joue l'insuline en plus d'ouvrir les cellules ?",["C'est l'hormone du stockage des graisses","Elle digère les protéines","Elle fabrique du glucose"],0,"Quand elle est élevée, elle fait stocker et empêche de brûler les graisses."],
     ["Qu'est-ce que l'hyperinsulinémie ?",["Un taux d'insuline très élevé, car le pancréas force pour compenser","Un manque d'insuline","Une glycémie basse"],0,"Elle précède souvent de plusieurs années le diabète visible."],
     ["Pourquoi parle-t-on de cercle vicieux ?",["Plus d'insuline → plus de graisse → plus de résistance → encore plus d'insuline","Parce que c'est irréversible","Il n'y a pas de cercle vicieux"],0,"Le briser (moins de glucides) est la clé de l'amélioration."],
     ["Le diabète de type 2 commence-t-il le jour du diagnostic ?",["Non : il mijotait souvent depuis 5 à 15 ans","Oui, ce jour précis","Il n'y a pas de diagnostic"],0,"L'hyperinsulinémie fait des dégâts silencieux bien avant."]]},
 {t:"Pourquoi la glycémie augmente-t-elle ?",mi:"Menez l'enquête sur VOS glycémies : 🔍 pendant quelques jours, notez ce qui précède vos glycémies élevées — un repas riche en glucides ? une nuit courte ? une journée stressante ? Vous identifierez VOS facteurs personnels, bien au-delà de la seule alimentation.",p:[
  ["👋 Introduction","« C'est le sucre. » Voilà ce qu'on croit souvent. La réalité est bien plus riche : de NOMBREUX facteurs font monter la glycémie — et en connaître la liste vous donne autant de leviers d'action.\nCe chapitre est une vraie boîte à outils.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre le rôle de l'alimentation et du foie ;\n✅ identifier l'influence des hormones, du stress et du sommeil ;\n✅ comprendre l'effet de la sédentarité ;\n✅ savoir que maladies et infections comptent aussi."],
  ["🍽️ L'alimentation et le foie","L'ALIMENTATION — le facteur le plus connu :\nles GLUCIDES (pain, pâtes, riz, sucre, jus, sodas…) sont transformés en glucose et font monter la glycémie. Plus le glucide est raffiné et rapide, plus la montée est brutale. C'est le levier n°1 de ce parcours.\n\n🫁 LE FOIE — le facteur méconnu, pourtant crucial :\nvotre foie est une réserve de sucre. Il en FABRIQUE et en LIBÈRE en permanence, surtout la NUIT et le matin, pour maintenir la glycémie. C'est pourquoi on peut avoir une glycémie élevée le matin… sans avoir rien mangé ! Chez le diabétique, ce foie est souvent « déréglé » et libère trop de glucose.\nComprendre cela évite bien des incompréhensions : non, une glycémie matinale élevée ne signifie pas forcément « j'ai triché hier soir ».","m0c4b"],
  ["😰 Hormones, stress et sommeil","🔥 LE STRESS — un puissant facteur souvent ignoré :\nen situation de stress, le corps libère du CORTISOL et de l'ADRÉNALINE, des hormones qui ORDONNENT au foie de libérer du glucose (pour « fuir ou combattre »). Résultat : un stress intense ou chronique FAIT MONTER la glycémie, même sans manger. Un entretien tendu, un souci familial, une contrariété… peuvent se lire sur le lecteur.\n\n😴 LE MANQUE DE SOMMEIL — un facteur sous-estimé :\nune seule nuit trop courte augmente l'insulinorésistance dès le lendemain ! Le manque de sommeil dérègle les hormones de la faim (plus de fringales sucrées) et augmente le cortisol. Bien dormir est un véritable traitement (Module 9).\n\n🔄 D'autres hormones (règles, ménopause, thyroïde…) peuvent aussi influencer la glycémie.","m0c4c"],
  ["🛋️ Sédentarité, maladies et infections","🛋️ LA SÉDENTARITÉ :\nles muscles sont de GROS consommateurs de glucose — et surtout, ils peuvent le capter SANS insuline pendant l'effort ! À l'inverse, rester assis toute la journée prive le corps de ce « canal de sortie » naturel du glucose. Moins on bouge, plus la glycémie a tendance à stagner haut. Même une marche de 15 minutes après le repas fait une vraie différence (Module 6).\n\n🤒 LES MALADIES ET INFECTIONS :\nune infection (grippe, angine, infection urinaire…), une inflammation ou une douleur intense font grimper la glycémie — le corps est en état de stress interne et libère des hormones hyperglycémiantes. C'est pourquoi les glycémies se dérèglent souvent lors d'une maladie : ce n'est pas votre faute, c'est physiologique. En cas de maladie sous traitement, suivez les consignes de votre médecin (certains traitements doivent être ajustés).\n\n💡 Astuce Keto-Essenciel : la glycémie est une PHOTO de nombreux facteurs, pas seulement de votre dernière assiette. Cette vision d'ensemble vous libère de la culpabilité et multiplie vos leviers d'action.","m0c4d"],
  ["📝 À retenir","📝 À retenir :\n✔ les glucides alimentaires font monter la glycémie : levier n°1 ;\n✔ le foie fabrique et libère du glucose, surtout la nuit et le matin ;\n✔ le stress (cortisol, adrénaline) fait monter la glycémie sans manger ;\n✔ le manque de sommeil augmente l'insulinorésistance dès le lendemain ;\n✔ la sédentarité prive le corps du « canal de sortie » musculaire ; maladies et infections font aussi grimper la glycémie.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais les facteurs »"]],
  q:[["Le foie peut-il faire monter la glycémie ?",["Oui : il fabrique et libère du glucose, surtout la nuit et le matin","Non, jamais","Uniquement s'il est malade"],0,"D'où une glycémie matinale parfois élevée sans avoir mangé."],
     ["Le stress influence-t-il la glycémie ?",["Oui : cortisol et adrénaline ordonnent au foie de libérer du glucose","Non","Seulement en vacances"],0,"Un stress intense peut faire monter la glycémie sans repas."],
     ["Quel est l'effet d'une nuit trop courte ?",["Elle augmente l'insulinorésistance dès le lendemain","Elle n'a aucun effet","Elle guérit le diabète"],0,"Le manque de sommeil dérègle aussi les hormones de la faim."],
     ["Pourquoi bouger aide-t-il la glycémie ?",["Les muscles captent le glucose, même sans insuline, pendant l'effort","Ça ne change rien","Cela augmente le sucre"],0,"Une marche de 15 min après le repas fait une vraie différence."],
     ["Une infection peut-elle dérégler la glycémie ?",["Oui : le corps libère des hormones hyperglycémiantes","Non","Seulement les enfants"],0,"Ce n'est pas votre faute, c'est physiologique — suivez votre médecin."]]},
 {t:"Les symptômes du diabète",mi:"Faites votre auto-observation : 👀 relisez les symptômes de ce chapitre et cochez mentalement ceux que vous avez déjà ressentis. Si vous reconnaissez des signes d'hyper ou d'hypo, notez-les pour votre médecin — et retenez surtout les signaux d'alerte à ne jamais ignorer.",p:[
  ["👋 Introduction","Le diabète est parfois surnommé « le tueur silencieux » : il peut évoluer des années sans le moindre symptôme. Mais il envoie aussi des signaux — encore faut-il savoir les reconnaître.\nCe chapitre vous apprend à écouter votre corps, sans tomber dans l'inquiétude excessive.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ reconnaître les signes fréquents du diabète ;\n✅ repérer les symptômes discrets ;\n✅ distinguer hyperglycémie et hypoglycémie ;\n✅ savoir quand consulter rapidement."],
  ["💧 Les signes fréquents — et les discrets","LES SIGNES CLASSIQUES d'une glycémie durablement élevée :\n🚰 SOIF intense et permanente ;\n🚽 ENVIE D'URINER souvent, y compris la nuit (le corps évacue le sucre en trop dans les urines, en emportant de l'eau) ;\n😴 FATIGUE inhabituelle (le glucose n'entre pas dans les cellules : elles manquent de carburant) ;\n📉 parfois PERTE DE POIDS inexpliquée.\n\nLES SIGNES PLUS DISCRETS, souvent négligés :\n👁️ vision floue passagère ;\n🩹 plaies ou infections qui cicatrisent LENTEMENT ;\n🍄 infections répétées (mycoses, infections urinaires) ;\n🐜 fourmillements ou picotements dans les pieds et les mains ;\n😤 irritabilité, difficultés de concentration.\n⚠️ IMPORTANT : dans le diabète de type 2, ces signes sont souvent ABSENTS ou très légers pendant des années — d'où l'importance capitale du DÉPISTAGE par prise de sang, même quand on se sent bien.","m0c5b"],
  ["⬆️⬇️ Hyperglycémie et hypoglycémie","Deux situations opposées à savoir distinguer :\n\n⬆️ L'HYPERGLYCÉMIE (glycémie trop HAUTE) :\nsoif, urines fréquentes, fatigue, vision floue, bouche sèche, maux de tête. Elle s'installe généralement progressivement. Très élevée et prolongée, elle peut mener à des complications (chapitre 7) et, dans les cas graves, à un malaise nécessitant une prise en charge.\n\n⬇️ L'HYPOGLYCÉMIE (glycémie trop BASSE, < 0,70 g/L) :\ntremblements, sueurs froides, palpitations, faim brutale, vertiges, confusion. Elle survient RAPIDEMENT.\n⚠️ Point crucial : l'hypoglycémie concerne surtout les personnes SOUS TRAITEMENT (insuline, sulfamides). Sans ces traitements, elle est rare. Nous y consacrons un chapitre entier au Module 11 (avec la « règle des 15 »).\nRetenez la nuance : l'hyper monte lentement et se voit sur le long terme ; l'hypo chute vite et demande une réaction immédiate.","m0c5c"],
  ["🚨 Quand consulter rapidement","La plupart du temps, le diabète se gère avec un suivi régulier tranquille. Mais certains signaux imposent de consulter SANS TARDER :\n📞 CONSULTATION RAPIDE (médecin, dans la journée ou sous 48 h) :\n• soif et urines très intenses d'apparition récente ;\n• fatigue majeure et amaigrissement rapide inexpliqué ;\n• glycémies très élevées et persistantes sur votre lecteur ;\n• infection qui traîne ou plaie qui ne cicatrise pas ;\n\n🆘 URGENCE (15 / SAMU) :\n• signes d'hypoglycémie sévère avec confusion ou perte de connaissance ;\n• nausées, vomissements, douleurs abdominales, respiration rapide (surtout sous gliflozine — Module 11) ;\n• somnolence anormale, difficulté à réveiller la personne.\n\nEt bien sûr, pour toute question ou doute : votre médecin est là. Il vaut toujours mieux poser une question « pour rien » que de laisser traîner.\n\n💡 Astuce Keto-Essenciel : notez vos symptômes inhabituels dans le Suivi de l'app avec leur date — un précieux repère pour vos consultations.","m0c5d"],
  ["📝 À retenir","📝 À retenir :\n✔ signes fréquents : soif, urines abondantes, fatigue, parfois perte de poids ;\n✔ signes discrets : vision floue, cicatrisation lente, infections répétées, fourmillements ;\n✔ dans le type 2, les symptômes sont souvent absents des années : le dépistage est capital ;\n✔ hyperglycémie = installation lente ; hypoglycémie = chute rapide (surtout sous traitement) ;\n✔ certains signaux imposent une consultation rapide, voire le 15.\n\n🏅 Badge à débloquer en validant le quiz : « Je reconnais les symptômes »"]],
  q:[["Quels sont les signes fréquents d'une glycémie élevée ?",["Soif intense, urines fréquentes, fatigue","Une grande forme","Aucun signe possible"],0,"Le corps évacue le sucre dans les urines en emportant de l'eau."],
     ["Pourquoi le dépistage est-il capital dans le diabète de type 2 ?",["Car les symptômes sont souvent absents pendant des années","Parce qu'il n'existe pas de test","Ce n'est pas capital"],0,"On peut être diabétique en se sentant parfaitement bien."],
     ["Comment évolue une hyperglycémie ?",["Progressivement, sur le long terme","En quelques secondes","Elle n'évolue pas"],0,"L'hypoglycémie, elle, chute rapidement."],
     ["Qui est surtout concerné par l'hypoglycémie ?",["Les personnes sous traitement (insuline, sulfamides)","Tout le monde également","Personne"],0,"Sans ces traitements, l'hypo est rare — voir la règle des 15 au Module 11."],
     ["Quand appeler le 15 ?",["Confusion/perte de connaissance, vomissements avec respiration rapide, somnolence anormale","Pour une légère fatigue","Jamais"],0,"Mieux vaut une question « pour rien » que laisser traîner un vrai signal."]]},
 {t:"Les facteurs de risque",mi:"Faites votre bilan personnel : 📋 parmi les facteurs de ce chapitre, identifiez ceux qui vous concernent. Séparez-les en deux colonnes : « je ne peux pas les changer » (âge, hérédité) et « je peux agir dessus » (poids, activité, sommeil…). Concentrez votre énergie sur la seconde colonne !",p:[
  ["👋 Introduction","Pourquoi certaines personnes développent-elles un diabète de type 2 et d'autres non ?\nConnaître les facteurs de risque a deux vertus : comprendre ce qui vous est arrivé (sans culpabilité !) et surtout identifier les leviers sur lesquels vous POUVEZ agir.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ distinguer facteurs modifiables et non modifiables ;\n✅ comprendre le rôle central de la graisse abdominale ;\n✅ situer l'influence du sommeil et du stress ;\n✅ concentrer vos efforts là où ils comptent."],
  ["🧬 Les facteurs qu'on ne choisit pas","Certains facteurs échappent à notre contrôle — les connaître aide à comprendre, pas à culpabiliser :\n👪 L'HÉRÉDITÉ — avoir un parent, frère ou sœur diabétique augmente nettement le risque. Il y a une prédisposition génétique réelle ;\n🎂 L'ÂGE — le risque augmente avec les années (surtout après 45 ans), car l'insulinorésistance tend à s'installer avec le temps ;\n🌍 L'ORIGINE — certaines populations sont statistiquement plus à risque ;\n🤰 des ANTÉCÉDENTS de diabète gestationnel ou d'un gros bébé à la naissance.\n⚠️ Point essentiel : avoir ces facteurs ne signifie PAS que le diabète est une fatalité ! La génétique « charge le pistolet », mais c'est souvent le mode de vie qui « appuie sur la détente ». Et sur le mode de vie, vous avez un pouvoir immense.","m0c6b"],
  ["⚖️ Les facteurs sur lesquels vous pouvez agir","Voici la bonne nouvelle — les leviers puissants ET modifiables :\n📏 LA GRAISSE ABDOMINALE — LE facteur clé : la graisse VISCÉRALE (autour des organes, dans le ventre) est très inflammatoire et provoque directement l'insulinorésistance. C'est le tour de taille, plus que le poids total, qui compte (Module 7). Bonne nouvelle : c'est souvent la première graisse à fondre !\n⚖️ LE SURPOIDS — un excès de poids augmente le risque, surtout s'il est abdominal ;\n🛋️ LE MANQUE D'ACTIVITÉ PHYSIQUE — moins de muscles sollicités = plus d'insulinorésistance ;\n🍔 LES HABITUDES ALIMENTAIRES — excès de glucides raffinés, de sucres, de produits ultra-transformés, de boissons sucrées.\nChacun de ces facteurs est une PORTE DE SORTIE : agir dessus, c'est réduire le risque et améliorer un diabète déjà installé.","m0c6c"],
  ["😴 Sommeil, stress : les facteurs oubliés","Deux facteurs modifiables trop souvent négligés :\n😴 LE SOMMEIL — dormir mal ou trop peu (moins de 6 h, apnées du sommeil non traitées) augmente l'insulinorésistance et les fringales sucrées. L'apnée du sommeil, en particulier, est fortement liée au diabète de type 2 : si vous ronflez fort et êtes fatigué au réveil, parlez-en à votre médecin ;\n😰 LE STRESS CHRONIQUE — un stress permanent maintient le cortisol élevé, ce qui augmente la glycémie et favorise le stockage de graisse abdominale (retour du cercle vicieux !).\n\nCes deux facteurs sont abordés en profondeur au Module 9. Retenez pour l'instant qu'ils sont de VRAIS leviers, au même titre que l'alimentation.\n\n💡 Astuce Keto-Essenciel : ne vous découragez jamais devant les facteurs non modifiables. Un seul chiffre compte : sur la plupart des facteurs qui font la différence — ventre, alimentation, activité, sommeil, stress — vous avez le pouvoir d'agir. Ce parcours est fait pour ça.","m0c6d"],
  ["📝 À retenir","📝 À retenir :\n✔ facteurs non modifiables : hérédité, âge, origine, antécédents — ils expliquent, ils ne condamnent pas ;\n✔ la graisse abdominale (viscérale) est LE facteur clé et modifiable ;\n✔ surpoids, sédentarité, habitudes alimentaires : des leviers puissants ;\n✔ sommeil et stress chronique sont de vrais facteurs de risque, souvent oubliés ;\n✔ la génétique charge le pistolet, le mode de vie appuie (ou non) sur la détente.\n\n🏅 Badge à débloquer en validant le quiz : « Je connais mes facteurs de risque »"]],
  q:[["La graisse abdominale est-elle un facteur clé ?",["Oui : la graisse viscérale provoque directement l'insulinorésistance","Non, elle est inoffensive","Seulement chez les sportifs"],0,"C'est le tour de taille, plus que le poids total, qui compte."],
     ["L'hérédité rend-elle le diabète inévitable ?",["Non : elle charge le pistolet, mais le mode de vie appuie (ou non) sur la détente","Oui, c'est une fatalité absolue","L'hérédité n'existe pas"],0,"Sur le mode de vie, vous avez un pouvoir immense."],
     ["Quel facteur modifiable est souvent oublié ?",["Le sommeil (dont l'apnée du sommeil)","La couleur des yeux","La taille des mains"],0,"L'apnée du sommeil est fortement liée au diabète de type 2."],
     ["Où concentrer ses efforts ?",["Sur les facteurs modifiables : ventre, alimentation, activité, sommeil, stress","Sur son âge","Sur son hérédité"],0,"C'est là que se joue la vraie différence."],
     ["Le stress chronique est-il un facteur de risque ?",["Oui : il maintient le cortisol élevé et favorise la graisse abdominale","Non","Seulement le week-end"],0,"Retour du cercle vicieux — abordé en profondeur au Module 9."]]},
 {t:"Les complications : pourquoi agir tôt ?",mi:"Transformez la peur en action : 💪 plutôt que de vous inquiéter des complications, choisissez UN examen de dépistage à vérifier cette semaine (fond d'œil, bilan rénal, examen des pieds). Le dépistage précoce est votre meilleure protection — et il est entre vos mains.",p:[
  ["👋 Introduction","Ce chapitre parle des complications du diabète — non pas pour faire peur, mais pour MOTIVER. Car le message central est plein d'espoir : ces complications ne sont PAS inévitables, et une bonne prise en charge les évite largement.\nComprendre l'enjeu, c'est comprendre pourquoi chaque effort compte.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi une glycémie élevée est nocive à long terme ;\n✅ connaître les principaux organes concernés ;\n✅ comprendre l'intérêt du dépistage précoce ;\n✅ voir pourquoi une bonne prise en charge protège."],
  ["🩸 Pourquoi le sucre en excès abîme","Pourquoi une glycémie durablement élevée pose-t-elle problème ?\nLe glucose en excès dans le sang se comporte comme un liquide « collant et corrosif » : il s'accroche aux protéines des vaisseaux sanguins et les abîme LENTEMENT, année après année. On appelle ça la « glycation » — imaginez du caramel qui encrasse une tuyauterie.\nComme les vaisseaux sanguins irriguent TOUT le corps, les dégâts touchent en priorité les organes riches en petits vaisseaux fragiles : les yeux, les reins, les nerfs. Puis les gros vaisseaux : cœur et artères.\n⚠️ Le point crucial : ces dégâts sont SILENCIEUX et PROGRESSIFS. On ne sent rien pendant des années — c'est précisément ce qui les rend dangereux. Quand les symptômes apparaissent, les dégâts sont déjà avancés. D'où l'importance de dépister AVANT.","m0c7b"],
  ["👁️ Les organes concernés","Les principales complications d'un diabète mal contrôlé sur le long terme :\n👁️ LES YEUX (rétinopathie) — les petits vaisseaux de la rétine s'abîment ; non dépistée, c'est une cause majeure de baisse de vue. Un fond d'œil annuel la détecte des années avant tout symptôme ;\n🫘 LES REINS (néphropathie) — ils filtrent le sang ; abîmés, ils filtrent mal. Le dépistage précoce (albuminurie) permet d'agir tôt (Module 8) ;\n🦶 LES NERFS (neuropathie) — fourmillements, perte de sensibilité, surtout aux pieds. Une blessure non ressentie peut s'aggraver : d'où l'examen régulier des pieds ;\n❤️ LE CŒUR ET LES VAISSEAUX — le diabète augmente le risque d'infarctus et d'AVC. C'est la complication la plus importante à prévenir.\nCes complications ont un point commun : elles se dépistent et se PRÉVIENNENT.","m0c7c"],
  ["🛡️ La bonne nouvelle : agir tôt protège","Voici le message le plus important de ce chapitre :\n✅ les grandes études le prouvent : bien contrôler sa glycémie (et sa tension, et ses lipides) RÉDUIT MASSIVEMENT le risque de complications — souvent de moitié ou plus ;\n✅ plus on agit TÔT, plus la protection est grande : chaque année de glycémie mieux contrôlée compte ;\n✅ le dépistage régulier (fond d'œil, reins, pieds, cœur — calendrier détaillé au Module 12) permet de détecter et traiter les problèmes à un stade où ils sont encore parfaitement gérables ;\n✅ et surtout : les complications graves surviennent principalement chez les personnes NON suivies ou dont le diabète reste très déséquilibré des années durant.\nAutrement dit : vous êtes en train, en suivant ce parcours, de faire exactement ce qui protège. Chaque repas mieux composé, chaque marche, chaque consultation est une brique de votre protection.\n\n💡 Astuce Keto-Essenciel : ne voyez pas ce chapitre comme une menace, mais comme votre MOTIVATION profonde. Vous n'agissez pas « contre » le diabète — vous agissez POUR vos yeux, vos reins, vos pieds, votre cœur.","m0c7d"],
  ["📝 À retenir","📝 À retenir :\n✔ le glucose en excès abîme lentement et silencieusement les vaisseaux (glycation) ;\n✔ organes concernés : yeux, reins, nerfs, cœur et vaisseaux ;\n✔ les dégâts sont indolores des années : le dépistage précoce est capital ;\n✔ bien contrôler glycémie, tension et lipides réduit massivement les risques ;\n✔ agir tôt protège — vous le faites déjà en suivant ce parcours.\n\n🏅 Badge à débloquer en validant le quiz : « Je sais pourquoi agir tôt »"]],
  q:[["Pourquoi une glycémie durablement élevée est-elle nocive ?",["Le glucose en excès abîme lentement les vaisseaux sanguins (glycation)","Elle ne l'est pas","Elle abîme uniquement les cheveux"],0,"Comme du caramel qui encrasse une tuyauterie, sur des années."],
     ["Quels organes sont concernés en priorité ?",["Yeux, reins, nerfs, cœur et vaisseaux","Les ongles uniquement","Aucun"],0,"Ce sont les organes riches en petits vaisseaux fragiles."],
     ["Pourquoi ces complications sont-elles dangereuses ?",["Elles sont silencieuses et progressives pendant des années","Elles font très mal immédiatement","Elles sont sans gravité"],0,"Quand les symptômes apparaissent, les dégâts sont déjà avancés : dépister avant."],
     ["Bien contrôler sa glycémie tôt permet-il de réduire les risques ?",["Oui, massivement — souvent de moitié ou plus","Non, aucun effet","Uniquement après 80 ans"],0,"Chaque année de glycémie mieux contrôlée compte."],
     ["Chez qui surviennent surtout les complications graves ?",["Chez les personnes non suivies ou au diabète longtemps déséquilibré","Chez tout le monde de façon égale","Chez les personnes suivies"],0,"En suivant ce parcours, vous faites exactement ce qui protège."]]},
 {t:"Peut-on améliorer son diabète ?",mi:"Choisissez votre premier levier : 🌱 parmi alimentation, activité, sommeil et gestion du stress, lequel vous semble le plus accessible à améliorer cette semaine ? Choisissez-en UN seul et engagez-vous sur un tout petit changement concret. C'est ainsi que tout commence.",p:[
  ["👋 Introduction","La question que tout le monde se pose : peut-on vraiment AMÉLIORER son diabète de type 2 ? La réponse, appuyée par la science, est un OUI franc et motivant.\nCe chapitre est le cœur optimiste de tout le parcours : découvrez tous vos leviers d'action.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ comprendre pourquoi l'hygiène de vie change la donne ;\n✅ connaître vos quatre grands leviers ;\n✅ situer la place des traitements ;\n✅ comprendre l'importance du suivi médical."],
  ["🌟 Oui, le diabète de type 2 se pilote","Le diabète de type 2 n'est PAS une maladie figée qui ne peut qu'empirer. C'est une maladie DYNAMIQUE, qui répond fortement à vos actions.\nPourquoi ? Parce que son mécanisme central — l'insulinorésistance — est largement RÉVERSIBLE :\n🔄 moins de glucides → moins d'insuline → serrures qui se dégrippent progressivement ;\n📉 perte de graisse abdominale → moins d'inflammation → cellules plus sensibles ;\n💪 plus de muscle actif → plus de glucose consommé.\nLes études le confirment : de nombreuses personnes améliorent nettement leur HbA1c, réduisent leurs traitements, et certaines atteignent la RÉMISSION (HbA1c normale sans médicament — Module 11), surtout quand le diabète est récent et la perte de poids importante.\nLe mot d'ordre : vous avez un réel POUVOIR sur votre diabète.","m0c8b"],
  ["🌿 Vos quatre grands leviers","Quatre piliers d'hygiène de vie, qui se renforcent mutuellement :\n🥗 L'ALIMENTATION — le levier n°1 : réduire les glucides, privilégier vraie nourriture, légumes, protéines et bonnes graisses. C'est l'objet des Modules 2 à 5 ;\n🏃 L'ACTIVITÉ PHYSIQUE — les muscles captent le glucose et améliorent la sensibilité à l'insuline. Pas besoin de marathon : la marche et un peu de renforcement suffisent (Module 6) ;\n😴 LE SOMMEIL — bien dormir restaure la sensibilité à l'insuline et calme les fringales (Module 9) ;\n😌 LA GESTION DU STRESS — réduire le cortisol chronique stabilise la glycémie (Module 9).\nCes quatre leviers agissent en SYNERGIE : améliorer l'un facilite les autres. Nul besoin de tout faire parfaitement d'un coup — chaque levier activé, même partiellement, améliore déjà la situation.","m0c8c"],
  ["💊 Traitements et suivi : les alliés","L'hygiène de vie est la base, mais elle ne s'oppose pas aux traitements — au contraire :\n💊 LES TRAITEMENTS PRESCRITS sont des alliés précieux, adaptés à votre situation par votre médecin (tout le Module 11 leur est consacré). Le duo hygiène de vie + traitement donne les meilleurs résultats ;\n⚠️ RÈGLE D'OR : on ne modifie JAMAIS un traitement seul. Si votre hygiène de vie améliore vos glycémies (bravo !), c'est votre MÉDECIN qui ajustera les doses — parfois à la baisse, ce qui est un beau signe de progrès ;\n🩺 LE SUIVI MÉDICAL RÉGULIER est indispensable : il mesure vos progrès, dépiste les complications, ajuste la prise en charge (Module 12). Vous et votre médecin formez une ÉQUIPE : vous pilotez l'hygiène de vie, il pilote le traitement et le dépistage.\n\n💡 Astuce Keto-Essenciel : le plus grand ennemi n'est pas le diabète, c'est l'INACTION. Vous venez de faire le contraire : vous vous informez et vous agissez. Le simple fait d'être ici, à lire ce chapitre, prouve que vous êtes déjà acteur de votre santé.","m0c8d"],
  ["📝 À retenir","📝 À retenir :\n✔ le diabète de type 2 est dynamique et largement améliorable : l'insulinorésistance est réversible ;\n✔ quatre leviers en synergie : alimentation, activité physique, sommeil, gestion du stress ;\n✔ les traitements sont des alliés — jamais modifiés sans le médecin ;\n✔ hygiène de vie + traitement + suivi = la meilleure combinaison ;\n✔ vous et votre médecin formez une équipe : chacun son rôle.\n\n🏅 Badge à débloquer en validant le quiz : « Je peux agir sur mon diabète »"]],
  q:[["Peut-on améliorer un diabète de type 2 ?",["Oui : l'insulinorésistance est largement réversible","Non, jamais","Uniquement avec la chirurgie"],0,"De nombreuses personnes améliorent leur HbA1c et réduisent leurs traitements."],
     ["Quel est le levier n°1 de l'hygiène de vie ?",["L'alimentation","Regarder la télévision","Rien"],0,"Réduire les glucides, privilégier la vraie nourriture — Modules 2 à 5."],
     ["Comment agissent les quatre leviers ?",["En synergie : améliorer l'un facilite les autres","Ils se gênent mutuellement","Ils sont inutiles"],0,"Alimentation, activité, sommeil, gestion du stress."],
     ["Peut-on modifier son traitement seul si les glycémies s'améliorent ?",["Non, jamais : c'est le médecin qui ajuste les doses","Oui, tout de suite","On arrête tout"],0,"Une baisse des doses par le médecin est un beau signe de progrès."],
     ["Quel est le plus grand ennemi face au diabète ?",["L'inaction","Le médecin","Les légumes"],0,"En vous informant et en agissant, vous faites déjà le contraire."]]},
 {t:"Les idées reçues sur le diabète",mi:"Débusquez une croyance : 🕵️ repérez cette semaine UNE idée reçue sur le diabète (entendue autour de vous, lue quelque part, ou que VOUS croyiez vraie). Notez-la et écrivez la réalité en une phrase. Corriger une croyance fausse peut débloquer un vrai progrès.",p:[
  ["👋 Introduction","Le diabète est entouré de croyances tenaces — certaines inoffensives, d'autres carrément nuisibles quand elles empêchent d'agir correctement.\nFaisons le ménage dans les idées reçues les plus fréquentes, avec bienveillance et clarté.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ corriger les croyances les plus répandues ;\n✅ comprendre pourquoi elles sont fausses ;\n✅ éviter les pièges qu'elles entraînent ;\n✅ raisonner sur des faits, pas sur des mythes."],
  ["❌ « C'est le sucre » et « plus de fruits »","❌ « LE DIABÈTE EST UNIQUEMENT CAUSÉ PAR LE SUCRE » — FAUX et réducteur : le diabète de type 2 résulte d'un ENSEMBLE de facteurs (insulinorésistance, graisse abdominale, hérédité, sédentarité, sommeil, stress…). Le sucre y contribue, mais tous les glucides comptent (pain, pâtes, riz aussi), ainsi que le mode de vie global. Manger du sucre ne « donne » pas mécaniquement le diabète, et l'éviter seul ne suffit pas ;\n\n❌ « JE NE PEUX PLUS MANGER DE FRUITS » — NUANCE : tous les fruits ne se valent pas. Les fruits rouges (fraises, framboises, myrtilles) sont pauvres en sucre et parfaits ; les fruits très sucrés (banane mûre, raisin, mangue) et les JUS de fruits (pur sucre liquide !) sont à limiter. On ne bannit pas les fruits, on les CHOISIT (Module 3).","m0c9b"],
  ["❌ « Fatalité » et « traitement = liberté totale »","❌ « LE DIABÈTE EST UNE FATALITÉ, ON NE PEUT RIEN FAIRE » — ARCHI-FAUX, et c'est l'idée la plus nuisible de toutes ! Comme vu au chapitre 8, le diabète de type 2 répond fortement à l'hygiène de vie. Croire à la fatalité, c'est baisser les bras avant d'avoir essayé — alors que le pouvoir d'agir est réel ;\n\n❌ « SI JE PRENDS UN TRAITEMENT, JE PEUX MANGER CE QUE JE VEUX » — DANGEREUX : le traitement aide, mais ne « répare » pas les dégâts d'une mauvaise alimentation. Continuer à mal manger sous prétexte qu'on est traité, c'est laisser la maladie progresser en coulisses, augmenter les doses, et exposer aux complications. Le traitement est un partenaire de l'hygiène de vie, pas un permis de tout manger.","m0c9c"],
  ["❌ « Uniquement les personnes en surpoids » — et autres","❌ « LE DIABÈTE CONCERNE UNIQUEMENT LES PERSONNES EN SURPOIDS » — FAUX : si le surpoids (surtout abdominal) est un facteur majeur, on peut être diabétique en étant mince — notamment avec une prédisposition génétique ou de la graisse viscérale « cachée » (le fameux « TOFI » : mince dehors, gras dedans). À l'inverse, beaucoup de personnes en surpoids ne sont pas diabétiques ;\n\nD'AUTRES CROYANCES FRÉQUENTES :\n❌ « le diabète, ce n'est pas grave » → il l'est s'il n'est pas pris en charge (chapitre 7) ;\n❌ « les édulcorants sont dangereux / le miel est meilleur que le sucre » → nuances au Module bonus ;\n❌ « le diabète est contagieux » → absolument pas ;\n❌ « une fois diagnostiqué, ça ne peut qu'empirer » → faux, la rémission existe.\n\n💡 Astuce Keto-Essenciel : chaque idée reçue corrigée est un obstacle en moins sur votre chemin. Le savoir juste est un traitement à part entière.","m0c9d"],
  ["📝 À retenir","📝 À retenir :\n✔ le diabète n'est pas causé « que par le sucre » : c'est un ensemble de facteurs ;\n✔ on ne bannit pas les fruits, on les choisit (rouges oui, jus non) ;\n✔ le diabète n'est PAS une fatalité : l'idée la plus nuisible de toutes ;\n✔ un traitement n'est pas un permis de tout manger : il complète l'hygiène de vie ;\n✔ on peut être diabétique en étant mince ; le savoir juste est un traitement.\n\n🏅 Badge à débloquer en validant le quiz : « Je démêle le vrai du faux »"]],
  q:[["Le diabète est-il uniquement causé par le sucre ?",["Non : c'est un ensemble de facteurs (insulinorésistance, graisse abdominale, hérédité, mode de vie…)","Oui, uniquement","Il n'a aucune cause"],0,"Tous les glucides comptent, ainsi que le mode de vie global."],
     ["Faut-il bannir tous les fruits ?",["Non : on les choisit (fruits rouges oui, jus et fruits très sucrés à limiter)","Oui, tous interdits","On peut tout manger sans limite"],0,"Les jus de fruits sont du sucre liquide — à éviter."],
     ["Le diabète de type 2 est-il une fatalité ?",["Non : il répond fortement à l'hygiène de vie","Oui, on ne peut rien faire","Personne ne sait"],0,"C'est l'idée reçue la plus nuisible de toutes."],
     ["Prendre un traitement permet-il de manger n'importe quoi ?",["Non : le traitement complète l'hygiène de vie, il ne répare pas une mauvaise alimentation","Oui, c'est un permis de tout manger","Le traitement suffit à tout"],0,"Mal manger sous traitement laisse la maladie progresser en coulisses."],
     ["Peut-on être diabétique en étant mince ?",["Oui, notamment avec une prédisposition ou de la graisse viscérale cachée","Non, jamais","Uniquement les enfants"],0,"Le surpoids est un facteur majeur, mais pas le seul."]]},
 {t:"Devenir acteur de sa santé",mi:"Posez votre première pierre : 🌱 en repensant à tout ce module, écrivez UNE phrase qui résume ce que vous avez compris de plus important, et UNE première habitude que vous décidez de mettre en place dès cette semaine. Vous venez de passer de spectateur à acteur.",p:[
  ["👋 Introduction","Vous voilà au terme de ce premier module — et à un tournant. Vous ne subissez plus le diabète : vous le COMPRENEZ. Et comprendre, c'est déjà commencer à agir.\nCe dernier chapitre fait le bilan et vous prépare à la suite du parcours.\n\n⏱ Temps de lecture : 5 minutes.\n\n🎯 À la fin de ce chapitre, vous serez capable de :\n✅ faire le bilan de vos nouvelles connaissances ;\n✅ comprendre que chaque petit changement compte ;\n✅ adopter une attitude positive ;\n✅ poser vos premières habitudes et aborder la suite."],
  ["🎓 Le bilan de ce que vous savez maintenant","Regardez le chemin parcouru en un seul module ! Vous savez désormais :\n✅ ce qu'est le glucose, l'insuline, et comment fonctionne une glycémie ;\n✅ les différents types de diabète et pourquoi le vôtre (type 2) est particulièrement modifiable ;\n✅ le mécanisme central : l'insulinorésistance et le cercle vicieux de l'hyperinsulinémie ;\n✅ tous les facteurs qui font monter la glycémie — bien au-delà du seul sucre ;\n✅ les symptômes, les facteurs de risque, les complications et pourquoi agir tôt ;\n✅ que le diabète de type 2 s'AMÉLIORE, et comment ;\n✅ le vrai du faux parmi les idées reçues.\nCes bases changent tout : vous pouvez maintenant comprendre POURQUOI chaque conseil des prochains modules fonctionne. Vous n'appliquerez pas des recettes à l'aveugle — vous agirez en connaissance de cause.","m0c10b"],
  ["🌱 Chaque petit changement compte","Le piège classique : vouloir tout changer d'un coup, se décourager, tout abandonner. La vérité est à l'opposé :\n🐜 les PETITS changements RÉPÉTÉS battent toujours les grandes révolutions éphémères. Une marche de 15 minutes après le déjeuner, une boisson sucrée remplacée par de l'eau, un légume ajouté à l'assiette : ces gestes minuscules, tenus dans la durée, transforment un diabète ;\n📈 les progrès s'ADDITIONNENT : chaque bonne glycémie est une victoire, chaque habitude installée facilite la suivante ;\n😌 l'ATTITUDE POSITIVE est un vrai levier : voir le diabète comme un signal d'alarme utile (« mon corps me demande de prendre soin de moi ») plutôt que comme une punition change toute la dynamique ;\n🚫 et zéro culpabilité : un écart, une glycémie élevée, une semaine difficile ne sont pas des échecs — juste des informations. On reprend, tout simplement.","m0c10c"],
  ["🚀 Vos premières habitudes — et la suite","Vous n'avez pas besoin d'attendre la fin du parcours pour commencer. Voici trois premières habitudes SIMPLES, à choisir selon vous :\n1️⃣ BOUGER un peu après les repas — même 10-15 minutes de marche ;\n2️⃣ REMPLACER les boissons sucrées (sodas, jus) par de l'eau, thé ou café non sucrés ;\n3️⃣ OBSERVER — commencer à noter dans l'app une donnée simple (poids, une glycémie, votre énergie).\nUne seule à la fois suffit pour démarrer !\n\n🧭 ET LA SUITE DU PARCOURS :\n🥑 Module 2 : pourquoi le keto fonctionne ;\n🥦 Modules 3-5 : bien manger, vos menus, cuisiner ;\n🏃 Module 6 : bouger et récupérer ;\n⚖️😌🩺📈 Modules 7 à 12 : perte de poids, analyses, stress/sommeil, compléments, traitements, suivi ;\n🎁 Module bonus : gérer toutes les situations de la vie.\nVous avez les fondations. Construisons la suite, ensemble, à votre rythme.\n\n💡 Astuce Keto-Essenciel : le simple fait d'avoir terminé ce module vous place déjà parmi les personnes qui prennent leur santé en main. Bravo — et en route pour le Module 2 !","m0c10d"],
  ["📝 À retenir — et bravo pour ce module !","📝 À retenir :\n✔ vous comprenez maintenant les bases : glucose, insuline, insulinorésistance, facteurs, complications ;\n✔ le diabète de type 2 s'améliore — vous avez un réel pouvoir d'action ;\n✔ les petits changements répétés battent les grandes révolutions éphémères ;\n✔ attitude positive et zéro culpabilité : les écarts sont des informations, pas des échecs ;\n✔ commencez par UNE habitude simple dès cette semaine.\n\n🎓 Dans ce Module 1, vous avez appris : ce qu'est le diabète, ses types, l'insulinorésistance, les causes de l'hyperglycémie, les symptômes, les facteurs de risque, les complications, les moyens d'agir, les idées reçues et l'art de devenir acteur de sa santé.\n\n🏅 Après ce chapitre, le Quiz final du module (20 questions, validation à 80 %) vous attend en bas de la page du module : réussissez-le pour décrocher le badge 🩸 « Je comprends mon diabète » !"]],
  q:[["Quelle stratégie de changement fonctionne le mieux ?",["Les petits changements répétés dans la durée","Tout changer d'un coup puis abandonner","Ne rien changer"],0,"Les gestes minuscules tenus dans le temps transforment un diabète."],
     ["Comment considérer un écart ou une glycémie élevée ?",["Comme une information, pas un échec — on reprend simplement","Comme une catastrophe","Comme une raison d'abandonner"],0,"Zéro culpabilité : c'est la clé pour durer."],
     ["Par quoi commencer dès cette semaine ?",["Une seule habitude simple (marche, eau à la place des sodas, observer une donnée)","Quinze changements à la fois","Rien avant la fin du parcours"],0,"Une seule à la fois suffit pour démarrer."],
     ["Que vous apportent les bases apprises dans ce module ?",["Comprendre POURQUOI chaque conseil des prochains modules fonctionne","Rien d'utile","Uniquement de la théorie"],0,"Vous agirez en connaissance de cause, pas à l'aveugle."],
     ["Quelle attitude adopter face au diabète ?",["Positive : un signal utile pour prendre soin de soi","Fataliste","Indifférente"],0,"L'attitude positive est un vrai levier de réussite."]]}
],fq:[
 ["Qu'est-ce que le glucose ?",["Le carburant principal des cellules, issu surtout des glucides","Une hormone du pancréas","Un type de muscle","Une vitamine"],0,"Il vient de l'alimentation et nourrit toutes vos cellules."],
 ["Quel est le rôle de l'insuline ?",["Une clé qui fait entrer le glucose dans les cellules","Fabriquer du sucre","Éliminer l'eau","Digérer les fibres"],0,"Fabriquée par le pancréas — et c'est aussi l'hormone du stockage des graisses."],
 ["Quelle est une glycémie normale à jeun ?",["Entre 0,70 et 1,10 g/L","Entre 3 et 5 g/L","Toujours zéro","Plus de 2 g/L"],0,"Diabète : ≥ 1,26 g/L à jeun à deux reprises."],
 ["Quel type de diabète représente ~90 % des cas ?",["Le type 2","Le type 1","Le gestationnel","Le MODY"],0,"Fortement influencé par le mode de vie — le cœur de ce parcours."],
 ["Qu'est-ce qui caractérise le diabète de type 1 ?",["Une maladie auto-immune : plus d'insuline produite, insuline vitale","Une résistance à l'insuline","Un excès de sport","Trop de fruits"],0,"Il n'est pas lié au mode de vie et apparaît souvent jeune."],
 ["Qu'est-ce que l'insulinorésistance ?",["Les cellules deviennent sourdes à l'insuline (serrures grippées)","Une absence totale d'insuline","Un excès de vitamines","Une glycémie basse"],0,"C'est le mécanisme central du diabète de type 2."],
 ["Qu'est-ce que l'hyperinsulinémie ?",["Un taux d'insuline très élevé car le pancréas force pour compenser","Un manque d'insuline","Une hypoglycémie","Un excès de glucose uniquement"],0,"Elle précède souvent de plusieurs années le diabète visible."],
 ["Le foie peut-il faire monter la glycémie ?",["Oui : il libère du glucose, surtout la nuit et le matin","Non, jamais","Uniquement après le sport","Le foie ne stocke rien"],0,"D'où une glycémie matinale parfois élevée sans avoir mangé."],
 ["Le stress influence-t-il la glycémie ?",["Oui : cortisol et adrénaline font libérer du glucose","Non","Seulement chez les enfants","Uniquement la nuit"],0,"Un stress intense peut faire monter la glycémie sans repas."],
 ["Quel est l'effet d'une nuit trop courte sur le diabète ?",["Elle augmente l'insulinorésistance dès le lendemain","Aucun effet","Elle guérit le diabète","Elle baisse la glycémie"],0,"Le manque de sommeil dérègle aussi les hormones de la faim."],
 ["Quels sont des signes fréquents d'hyperglycémie ?",["Soif intense, urines fréquentes, fatigue","Une grande énergie","Des cheveux plus longs","Rien du tout"],0,"Le corps évacue le sucre dans les urines en emportant de l'eau."],
 ["Qui est surtout concerné par l'hypoglycémie ?",["Les personnes sous insuline ou sulfamides","Tout le monde également","Personne","Les sportifs uniquement"],0,"Sans ces traitements, l'hypo est rare (règle des 15 au Module 11)."],
 ["Quel est LE facteur de risque clé et modifiable ?",["La graisse abdominale (viscérale)","La couleur des yeux","La taille des mains","La pointure"],0,"C'est le tour de taille, plus que le poids total, qui compte."],
 ["L'hérédité rend-elle le diabète inévitable ?",["Non : elle charge le pistolet, le mode de vie appuie ou non sur la détente","Oui, c'est une fatalité","L'hérédité n'existe pas","Elle protège du diabète"],0,"Sur le mode de vie, vous avez un pouvoir immense."],
 ["Pourquoi une glycémie durablement élevée est-elle nocive ?",["Le glucose en excès abîme lentement les vaisseaux (glycation)","Elle ne l'est pas","Elle abîme seulement les cheveux","Elle renforce les vaisseaux"],0,"Yeux, reins, nerfs, cœur : les organes riches en petits vaisseaux d'abord."],
 ["Pourquoi les complications sont-elles dangereuses ?",["Elles sont silencieuses et progressives : le dépistage précoce est capital","Elles font mal tout de suite","Elles sont bénignes","Elles n'existent pas"],0,"Bien contrôler tôt réduit massivement les risques."],
 ["Peut-on améliorer un diabète de type 2 ?",["Oui : l'insulinorésistance est largement réversible","Non, jamais","Uniquement par chirurgie","Seulement avec des médicaments"],0,"La rémission est même possible, surtout si le diabète est récent."],
 ["Peut-on modifier son traitement seul si les glycémies s'améliorent ?",["Non : seul le médecin ajuste les doses","Oui, immédiatement","On arrête tout d'un coup","On double les doses"],0,"Une baisse des doses par le médecin est un beau signe de progrès."],
 ["Prendre un traitement permet-il de manger n'importe quoi ?",["Non : il complète l'hygiène de vie, il ne répare pas une mauvaise alimentation","Oui, c'est un permis","Le traitement suffit à tout","On peut tout manger sans limite"],0,"Mal manger sous traitement laisse la maladie progresser en coulisses."],
 ["Quelle est la meilleure stratégie de changement ?",["Les petits changements répétés dans la durée","Tout bouleverser d'un coup","Ne rien changer","Attendre un miracle"],0,"Chaque petit geste tenu dans le temps transforme un diabète — sans culpabilité."]
],bd:"🩸 Je comprends mon diabète",sk:["Comprendre glucose, insuline et glycémie","Distinguer les différents types de diabète","Maîtriser l'insulinorésistance et l'hyperinsulinémie","Identifier tous les facteurs qui font monter la glycémie","Reconnaître symptômes, facteurs de risque et complications","Savoir que le diabète de type 2 s'améliore — et comment","Démêler le vrai du faux et devenir acteur de sa santé"]}'''

src = src[:i] + NEW + ',\n' + src[j+len(']},\n'):]
io.open(PATH,'w',encoding='utf-8').write(src)
print('OK: Module 1 = 10 chapitres + quiz final 20 q')
